### PR TITLE
Get-DbaAvailabilityGroup blown up and cleaned up

### LINKED ISSUE #978: Get-DBAAvailabilityGroup - Primary AG member returns as 'Unknown'
### Is this a *feature* OR *bug*:

Bug

### System Details

- Operating system name and version: Server 2012 R2 Core
- Output from `$PSVersionTable`: 

Name                           Value
----                           -----
PSVersion                      4.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   6.3.9600.17400
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.2

```
Evaluate $PSVersionTable in PowerShell and paste the output here
```

- Output of dbatools version:
ModuleType Version    Name
---------- -------    ----
Script     0.8.903    dbatools
``` 
Evaluate (Get-Module dbatools -ListAvailable).Version and paste output here
```

- SQL Server version for source/target
2016 Enterprise

### Steps to Reproduce

Run:

Get-DbaAvailabilityGroup -SqlServer sql-prd-c01

against cluster from either a primary or secondary sync member

### Action Results

AvailabilityGroup : AG-APP-PRD
ReplicaName       : SQL-PRD-V05
Role              : Unknown
SyncState         : Unknown
AvailabilityMode  : SynchronousCommit
FailoverMode      : Automatic

AvailabilityGroup : AG-APP-PRD
ReplicaName       : SQL-PRD-V06
Role              : Secondary
SyncState         : Synchronized
AvailabilityMode  : SynchronousCommit
FailoverMode      : Automatic

AvailabilityGroup : AG-InformationSystemsInternal
ReplicaName       : SQL-PRD-V05
Role              : Unknown
SyncState         : Unknown
AvailabilityMode  : SynchronousCommit
FailoverMode      : Automatic

AvailabilityGroup : AG-InformationSystemsInternal
ReplicaName       : SQL-PRD-V06
Role              : Secondary
SyncState         : Synchronized
AvailabilityMode  : SynchronousCommit
FailoverMode      : Automatic

AvailabilityGroup : AG-Intramaps
ReplicaName       : SQL-PRD-V05
Role              : Unknown
SyncState         : Unknown
AvailabilityMode  : SynchronousCommit
FailoverMode      : Automatic

AvailabilityGroup : AG-Intramaps
ReplicaName       : SQL-PRD-V06
Role              : Secondary
SyncState         : Synchronized
AvailabilityMode  : SynchronousCommit
FailoverMode      : Automatic

AvailabilityGroup : AG-Sharepoint
ReplicaName       : SQL-PRD-V05
Role              : Unknown
SyncState         : Unknown
AvailabilityMode  : SynchronousCommit
FailoverMode      : Automatic

AvailabilityGroup : AG-Sharepoint
ReplicaName       : SQL-PRD-V06
Role              : Secondary
SyncState         : Synchronized
AvailabilityMode  : SynchronousCommit
FailoverMode      : Automatic

AvailabilityGroup : AG-SSISDB
ReplicaName       : SQL-PRD-V05
Role              : Unknown
SyncState         : Unknown
AvailabilityMode  : SynchronousCommit
FailoverMode      : Automatic

AvailabilityGroup : AG-SSISDB
ReplicaName       : SQL-PRD-V06
Role              : Secondary
SyncState         : Synchronized
AvailabilityMode  : SynchronousCommit
FailoverMode      : Automatic

### Expected Results

I would expect the PRIMARY member to be listed, instead it is only listed as 'Unknown'. I do recall this working at some point though, I cannot see where this is failing.

### Attached Logs or any exception errors

- Use of Start-Transcript can help collection of console output and exceptions
- Certain commands will generate an exception log that you can find in following directory: `dir $env:USERPROFILE\Documents\dbatools-exceptions.txt`

**None of these return any errors or exceptions.**

### PR DESCRIPTION
**Pull request by wsmelton**
Fixes #978 

Changes proposed in this pull request:
 - Cleaned this command up by rewriting it for the most part. 💣 
 - Cleaned up help and removed unwanted parameters
 - Cleaned up output to be full AG object for SMO, but only have default set of properties output
 - Adjusted logic to determine primary replica based on SMO properties (this needs to be tested to verify it works on 2012 up to 2016 property BEFORE IT IS MERGED)

Has been tested on minimum requirements:
- [ ]  Powershell 3
- [ ]  SQL Server 2012

Has been tested on maximum requirements:
- [ ]  SQL Server 2016
- [ ]  Windows Server 2012 R2

Tests for tester:
- [ ] `Get-DbaAvailabilityGroup -SqlInstance Server1`
- [ ] `Get-DbaAvailabilityGroup -SqlInstance Server1 -IsPrimary`
- [ ] `Get-DbaAvailabilityGroup - SqlInstance Server1 -AvailabilityGroup AG1`

Verify output and no errors.

### CODE REVIEW

**Comment by wsmelton** [comment]
The changes to this command will lead to two additional commands being built: `Get-DbaAgReplica` and `Get-DbaAgDatabase` each outputting only their associated SMO object as this command now does.

**Comment by potatoqualitee** [comment]
BOOOM 💣 , awesome changes! A few more are needed, though. Lemme go do a review real quick

**Comment by potatoqualitee** [comment]
Actually, NM, it was all stuff that you removed 💯 

Would any of these be useful to the user? 

IsDistributedAvailabilityGroup
LocalReplicaRole
PrimaryReplicaServerName
AvailabilityReplicas
AvailabilityDatabases
DatabaseReplicaStates
AvailabilityGroupListeners

I myself would like AvailabilityDatabases. You can do a `Databases = AvailabilityDatabases - join ','` to make it prettier, but it's super cool that those are full on SMO objects. I'd probably like the AvailabilityGroupListeners as well.

**Comment by potatoqualitee** [comment]
added two columns - modify as desired

**Pull request merged**
