### PR TITLE
Dotsource optin

### PR DESCRIPTION
**Pull request by FriedrichWeinmann**
Features # 

Changes proposed in this pull request:
 - Allows opting into dotsourcing the dbatools files

Three ways to do it:
 - Set `$dbatools_dotsourcemodule` to `$true`
 - Set `"HKLM:\SOFTWARE\Microsoft\WindowsPowerShell\dbatools\System"`, property: `DoDotSOurce` type: `DWORD` to `1`
 - Set `"HKCU:\SOFTWARE\Microsoft\WindowsPowerShell\dbatools\System"`, property: `DoDotSOurce` type: `DWORD` to `1`

### CODE REVIEW

**Comment by potatoqualitee** [comment]
:wizard: Nice work, man. @wsmelton is gone' like that

**Comment by FriedrichWeinmann** [comment]
Fallback is back in

**Comment by potatoqualitee** [comment]
thanks, @FriedrichWeinmann  - hey @gbargsley, I don't know why you're up, but this one is ready to test. Fred left the instructions up there. I'll be up in about 5 hours and can merge.

**Comment by gbargsley** [comment]
@FriedrichWeinmann  Where do you set the first option listed in your test instructions?

**Comment by potatoqualitee** [comment]
hey @gbargsley - it would just be `$dbatools_dotsourcemodule = $true` from the console, I believe

**Comment by potatoqualitee** [comment]
this will be fun, ill try it too

**Comment by potatoqualitee** [comment]
interrrrrresting, there isn't nearly as much time increase as I expected 🤔 

3.9 to 4.6

(It used to be 2.5 before we added all those new shiny SMOs, but I'll take it)

**Comment by potatoqualitee** [comment]
Now 4.2 - that doesn't seem right

**Comment by gbargsley** [comment]
Ok and for my lack of knowledge what will this accomplish and what should I look for?

**Comment by potatoqualitee** [comment]
I was looking for slower loading times (because dotsourcing is far more expensive) but I wasn't finding them, exactly. 

So just measure-command { ipmo dbatools } see how long it takes true vs false. 

Can you try the registry keys? I didn't.

**Comment by potatoqualitee** [comment]
I mean, I tested it. I'm just shocked at how fast it was using dot sourcing.

**Comment by wsmelton** [comment]
I've gotten to many emails on these GitHub updates :shock-and-awe:

I'll test this and get block post up on how to use it. 

@gbargsley this was needed specifically around letting folks debug the module. 

_Sent from my Samsung SM-G900V using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Pull request merged**
