### PR TITLE
Get-DbaBackupHistory, speedup

### PR DESCRIPTION
**Pull request by niphlod**
## Type of Change

 - [ ] Bug fix (non-breaking change, fixes #<enter issue number>)
 - [ ] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
Speedup. Issuing a query for each group with a bit of latency between the PS console and the targeted server was slow(ish). Hopefully passing from FileList being `System.Data.DataRow` to  `Selected.System.Data.DataRow` doesn't break stuff.

Additionally a bit of revamping and ScriptAnalyzer checks pass all.

PS: "beware of the dogs"... this function was alredy manually signed off for Messaging, but had `Write-Verbose` in it ....

### Approach
Issue one query only for grouped results.

### Screenshots
new
```
Measure-Command { Get-DbaBackupInformation ......  }
Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 5
Milliseconds      : 182
Ticks             : 51823527
TotalDays         : 5,99809340277778E-05
TotalHours        : 0,00143954241666667
TotalMinutes      : 0,086372545
TotalSeconds      : 5,1823527
TotalMilliseconds : 5182,3527
```
old
```
Measure-Command { Get-DbaBackupInformation ......  }
Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 18
Milliseconds      : 387
Ticks             : 183871308
TotalDays         : 0,000212814013888889
TotalHours        : 0,00510753633333333
TotalMinutes      : 0,30645218
TotalSeconds      : 18,3871308
TotalMilliseconds : 18387,1308
```

### CODE REVIEW

**Comment by potatoqualitee** [comment]
wow nice, thank you!

**Comment by potatoqualitee** [comment]
The code LGTM and all checks pass, does anyone need to approve?

**Comment by Stuart-Moore** [comment]
I approve :+1: or do you want something more formal ;)

**Comment by potatoqualitee** [comment]
perfect 🌮 !

**Pull request merged**
