### PR TITLE
Test coverage for Invoke-DbaDatabaseShrink

### PR DESCRIPTION
**Pull request by dgmyrs**
## Type of Change

 - [ ] Bug fix (non-breaking change, fixes #<enter issue number>)
 - [ ] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [x] Adding code coverage to existing functionality
 - [x] Pester test is included
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
 
To provide basic test coverage to Invoke-DbaDatabaseShrink

### Approach

Test creates a database with a small data and log file, and then tests a few shrink methods.

### CODE REVIEW

**Comment by Stuart-Moore** [comment]
Nice tests :+1:
But, would it be easier to prebuild a db with empty space, and then add the backups to https://github.com/sqlcollaborative/appveyor-lab and just restore them each time?

**Comment by dgmyrs** [comment]
Ha! Absolutely, it would have been easier, had I been aware of that option before writing the tests :).  Right now, this should work, but to further test things like the difference b/w TruncateOnly and Truncate, backup/restores will probably be about the only way to go.  I'll have to dig around in the code to see how that's all done.

**Comment by potatoqualitee** [comment]
hey @dgmyrs - can you check why this isnt working? Perhaps change the instance or do it a slightly different way? sometimes appveyor is 🍑

**Comment by dgmyrs** [comment]
@potatoqualitee I believe the new commit should resolve it, but I don't have 2008R2 to test against, so can't say for certain until appveyor runs the test again.

**Comment by dgmyrs** [comment]
@potatoqualitee, finally got this running under 2008R2, and looks to be passing now.

**Comment by potatoqualitee** [comment]
Looookin great! Thanks so much 🌮 🌯 🍕

**Pull request merged**
