### PR TITLE
CIM for DiskAlignment

### PR DESCRIPTION
**Pull request by ctrlbold**
Can someone who knows something about CIM fix this? It's almost fixed.

### CODE REVIEW

**Comment by PowerDBAKlaas** [comment]
this function too has almost all code wrapped in a nested function in BEGIN{}
I just struggled with that in Get-DbaDiskspace
I think it creates problems with passing the necessary parameters,
like $cimsession, which is created in PROCESS{}, but is it handed over to the nested function?

**Comment by FriedrichWeinmann** [comment]
Yeah, I'm currently working on it. Will remove all scope boundary violations and change some other things around.

**Comment by FriedrichWeinmann** [comment]
And that should do it, please test the overhauled Test-DbaDiskAlignment

**Comment by ctrlbold** [comment]
Thanks, @FriedrichWeinmann !

**Pull request merged**
