### PR TITLE
Restore from snapshot  - cleaned up db loop

### PR DESCRIPTION
**Pull request by potatoqualitee**
for @niphlod - dont merge yet

### CODE REVIEW

**Comment by niphlod** [comment]
unfortunately still 1 minute spent before hitting line 132. The real monster - at least here - is line 99. Probably because no props are selected, it goes around and enums all the things. 
Commenting out line 99 and searching/replacing `$allDbs` with `$server.Databases` closes the deal.
Still slower than a tailored select but is more "SMOish".

**Comment by niphlod** [comment]
scratch that. was testing passing a connect-dbainstance as sqlinstance. 
when passed a string as sqlinstance, even that mod results in no improvements.

**Comment by potatoqualitee** [comment]
i cannot find a smoish fix and would be happy for you to fix it with your spruced select 👍

**Comment by niphlod** [comment]
Okay!
PS: is there a place to shout out for SMO lovers that we have a problem?

Il mer 28 mar 2018, 10:25 Chrissy LeMaire <notifications@github.com> ha
scritto:

**Pull request closed without merging**
