### PR TITLE
Replace -Detailed in Get-DbaTcpPort (#2217)

### PR DESCRIPTION
**Pull request by joshcorr**
## Type of Change

 - [x] Bug fix (non-breaking change, fixes #2217 #3350 )
 - [ ] New feature (non-breaking change, adds functionality)
 - [x] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [x] Pester test is included
 - [ ] Nunit test is included
 - [x] Documentation
 - [ ] Build system
 

### Purpose
Refactor Get-DbaTcpPort to not use `-Detailed` parameter
Add new descriptive parameter called `-AllTcpPort` to replace `-Detailed`
Include Test for cmdlet where one had not previously existed

### Approach
Tried to completely refactor the cmdlet, but realized it was being used by `Test-DbaConnection` in it's default form. Came up with a more suited parameter name to replace `-Detailed` (although I am completely up to changing it if it doesn't fit). `Select-DefaultView` returns the same properties regardless of if this new switch is used or not. 

### Commands to test
Get-DbaTcpPort -SqlInstance sqltestbed
Get-DbaTcpPort -SqlInstance sqltestbed -AllTcpPort

### Screenshots
Using Default Form
tcp1

Piping to Select *
tcp2

### CODE REVIEW

**Comment by potatoqualitee** [comment]
Thanks so much! And thank you for the new test! The test failures are unrelated (appveyor died)

Unfortunately, the help was formatted back to the old style and our updated notes were reverted as well. Please resubmit with properly formatted help and I'll be happy to merge 👍

**Comment by potatoqualitee** [comment]
As for the name, yours is clearer, but it doesn't sound right. Maybe it needs to be plural? Perhaps the detailed output should just be included by default?

**Comment by potatoqualitee** [comment]
This command was written when we were using Detailed a lot. Since then, we decided on the other way. Showing a lot by default and `-Simple` for simplified output. Perhaps we should go that way.

**Comment by joshcorr** [comment]
Okay, Indents are fixed. Should be clearer to review the changes now. Sorry about that.

I was thinking plural (`-AllTcpPorts`) makes more sense, but was trying to stick with the parameter guide of singular. I considered having the fuctionality flipped, but didn't want to make that decision by myself. I only know of one internal dependency that would need to change as well.

**Comment by potatoqualitee** [comment]
Looks good, thank you. I understand about the singular vs plural for sure. What I've done in other commands is `-Exclude Databases` so i get to have both 😅  I say go for `-Simple`, what you say, @wsmelton ?

**Comment by potatoqualitee** [comment]
okay this is super strange - it keeps failing on the same tests. @joshcorr - can you try creating a new branch and copying your changes into there. I'm a bit confused as to what's going on.

**Comment by joshcorr** [comment]
Okay will do. I will close this PR and open a new one.

**Pull request closed without merging**
