### PR TITLE
Fix math for higher seed values and negative incremental values. Issue #2017

### PR DESCRIPTION
**Pull request by mvillegascuellar**
Fix math for higher seed values and negative incremental values. Fixes issue #2017

### CODE REVIEW

**Comment by potatoqualitee** [comment]
Oh, excellent! We've needed this one. Thank you 💃 

@wsmelton or @jpomfret would you have time to create a very simple Test for Test-DbaIdentityUsage in another PR?

**Comment by jpomfret** [comment]
I can take a look at creating a test today for it

**Comment by potatoqualitee** [comment]
Thanks so much! I think a tinyint will be nice for showing percentages above 1 😂  

My lab is filllled with 0-1%

**Comment by jpomfret** [comment]
PR for Pester Tests
https://github.com/sqlcollaborative/dbatools/pull/2108

**Comment by potatoqualitee** [comment]
Thanks, ya'll! let's see how this goes

**Comment by potatoqualitee** [comment]
Will come back to celebrate once the test passes!

**Pull request merged**
