### PR TITLE
Fixing Max Memory

### LINKED ISSUE #1927: Test-DbaMaxMemory error
### General Troubleshooting steps

- [ x] Verified running latest release of dbatools?
- [x ] Verified errors are not related to permissions?
- [x ] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - Operating System (Name|Version): 
Win 10 Pro
 - PowerShell Version: 
PSVersion                      5.1.14393.1480
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.1480
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
 - SQL Server (Edition|Version): 
SQL 2014 SP2

## Steps to Reproduce

 - [ ] Attach any screenshots (if possible/allowed)
 - [ ] Attach logs generated by dbatools (`Get-DbatoolsLog`)
 - [ x] Attach output from PowerShell console (if possible/allowed)
[Test-DbaMaxMemory Error.txt](https://github.com/sqlcollaborative/dbatools/files/1183759/Test-DbaMaxMemory.Error.txt)

### PR DESCRIPTION
**Pull request by potatoqualitee**
Fixes #1927

### CODE REVIEW

**Comment by gbargsley** [comment]
I started my testing with the Test-DbaMaxMemory and do not get the ComputeName, InstanceName or SqlInstance returned now.
image

**Comment by wsmelton** [comment]
@gbargsley what does `Get-DbaMaxMemory` return for those instances in your environment?

**Comment by gbargsley** [comment]
@wsmelton  The new version or old?

**Comment by gbargsley** [comment]
Here is before and after.

image

**Comment by wsmelton** [comment]
From a new PowerShell window with the module as associated to this PR.

I pulled this PR down to my environment and it works as expected.

**Comment by gbargsley** [comment]
Ran the Test, Get and Set.  Test and Get work with multiple instances passed.  Set does set, but CurrentMaxValue is blank.  Should that not show what it was set to?  If I do a Get after the Set it has the new value set.

image

**Comment by potatoqualitee** [comment]
yeah its failing the tests too, thank you both, will fix

**Comment by potatoqualitee** [comment]
fixed and passed!

**Pull request merged**
