### PR TITLE
Watch-DbaDbLogin: Enable pipeline input and ensure CMS can be used

### LINKED ISSUE #7143: Watch-DBALogin - Add the ability to target a single SQL instance
### Summary of new feature

Add the ability to target a single SQL instance or enumerate a PS object of SQL instances through this command. Flesh out the documentation on this command.

### Proposed technical details (if applicable)

Instead of forcing a text file to be used or a CMS server add the ability to explicitly point to a single SQLInstance or input object of SQLInstances. If this isn't possible or unnecessary then clarify the documentation a bit 

### Latest version of dbatools as of writing

1.0.139

### PR DESCRIPTION
**Pull request by lancasteradam**
Watch-DbaDbLogin: Enable pipeline input and ensure CMS can be used

## Type of Change

 - [x] Bug fix (non-breaking change, fixes # )
 - [x] New feature (non-breaking change, adds functionality, fixes #7143 )
 - [ ] Breaking change (effects multiple commands or functionality, fixes # )
 - [x] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [x] Adding code coverage to existing functionality
 - [x] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Nunit test is included
 - [x] Documentation
 - [ ] Build system
 

### Purpose
1. Enable pipeline input to address the request in #7143 
2. Minor fix for the CMS use case to ensure that the server name is passed in correctly.

### Approach

1. Added a new param for the pipeline input so that the caller can pass in pre-connected instances. This also addresses the issue of those separate instances having different credentials.
2. When the connection is being made to the server represented by the RegisteredServer it now uses $instance.ServerName so that it can connect successfully.
3. Added new integration tests for the CMS and Pipeline use cases.

### Commands to test

See the new integration tests.

### CODE REVIEW

**Comment by potatoqualitee** [comment]
Can you tell me more about the SkipLocalTest? Did I miss that implementation or is it new to this commit, @lancasteradam ?

**Comment by lancasteradam** [comment]
It's a low-tech way to exclude tests if they are not likely to work in the AppVeyor environment. If there is another preferred approach for excluding tests I'm happy to update the code.

**Comment by jpomfret** [comment]
@potatoqualitee or @wsmelton - I feel like there was a way to exclude tests from running on appveyor, but currently can't track it down...

**Comment by wsmelton** [comment]
@potatoqualitee it was used in other tests that got merged last week. #7183 

Considering it requires a user to physically go into the tests to manipulate it, it needs to be removed and implemented through our manual tests scripts that @niphlod created.

@jpomfret as it pertains to this one we don't generally tests 3rd party commands in a test suite so this one can get added to this list:

https://github.com/sqlcollaborative/dbatools/blob/9d7db5fe4d1762a4c773fadff3d8e4e5fb63aace/tests/pester.groups.ps1#L23-L28

**Comment by jpomfret** [comment]
Alright I've added that to the skip list in development and updated this branch with those changes. 

@lancasteradam - can you remove the skiplocal logic from yours and then we should be good here. Thanks!

https://github.com/sqlcollaborative/dbatools/blob/a7e603817e36c69d76fe7bdc28299afb543880ec/tests/pester.groups.ps1#L66-L69

**Comment by lancasteradam** [comment]
Yes, will do. Thank you @jpomfret.

**Review by jpomfret — APPROVED** [review]
Thanks! Looks great 😄

**Pull request merged**
