### PR TITLE
Get-DbaSpDatabase

### PR DESCRIPTION
**Pull request by potatoqualitee**
This is something I've needed a bunch of times, also will be useful for AutoSPAg

### CODE REVIEW

**Comment by potatoqualitee** [comment]
I cannot get a compressed backup of this database to restore, so I used a dacpac instead. Not sure what's up - I even backed up / restored different/old SharePoint_Config dbs. This works but takes 15 seconds. I've asked stuart to take a look.

**Comment by wsmelton** [comment]
Are going to start adding in commands for different products that may be hosted on SQL Server?

**Comment by potatoqualitee** [comment]
we can potentially with justification, but sharepoint is the reason dbatools exists, i'm a huge user of it and when mixed with ags, this will be another magic feature people lose their minds over.

**Comment by potatoqualitee** [comment]
all tests finally pass 👍

**Comment by potatoqualitee** [comment]
my only issue is that..is this the best name? Would Get-DbaDbSharePoint be better?

**Comment by wsmelton** [comment]
Product name should be full, because "sp" is short for stored procedure with SQL Server world.

**Comment by potatoqualitee** [comment]
i dig, ty, will rename

**Pull request merged**
