### PR TITLE
Support for SSRS2017 in *-DbaService functions

### LINKED ISSUE #3349: Get-DbaSqlService (now Get-DbaService), SSRS 2017, No ComputerManagement Namespace
### General Troubleshooting steps

- [x] Verified running the latest release of dbatools?
- [x] Verified errors are not related to permissions?
- [x] Can duplicate in new/clean PowerShell session (clean = `powershell -NoProfile`)?

### Version Information
 - Operating System (Name|Version): Windows Server 2012 R2, Windows Server 2016
 - PowerShell Version: 5.1.14409.1005
 - SQL Server (Edition|Version): SSRS 2017 Enterprise, October 2017 release

## Steps to Reproduce

 - [ ] Attach any screenshots (if possible/allowed)
 - [ ] Attach logs generated by dbatools (`Get-DbatoolsLog`)
 - [x] Attach output from PowerShell console (if possible/allowed)

"WARNING: [Get-DbaSqlService][15:08:35] No ComputerManagement Namespace on [servername]. Please note that this function is available from SQL 2005 up."

## Feature Request

If possible, would like to be able to successfully use Get-DbaSqlService (now Get-DbaService) against a target which has only SSRS 2017 installed (no other SQL Server components installed).

### Problem to solve
Get-DbaSqlService (now Get-DbaService) doesn't currently work against a target which hosts only stand-alone SSRS 2017.

### Additional information

Perhaps the needed WMI provider or namespace is not created when SSRS 2017 is installed stand-alone on a server on which no other SQL Server components have been installed?

### LINKED ISSUE #4391: Restart-DbaService with Type Engine gets an error
Restart-DbaService -ComputerName<computer> -InstanceName <instance> -Type Engine

Gets this error
Get-RunspaceData : Runspace timed out at 30.0497279 seconds for the object:
ComputerName : ISD40153
ServiceName  : MSSQL$SQL2016
ServiceType  : Engine
InstanceName : SQL2016
DisplayName  : SQL Server (SQL2016)
StartName    : NT Service\MSSQL$SQL2016
State        : Running
StartMode    : Automatic
```
At C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.450\allcommands.ps1:97150 char:13
+             Get-RunspaceData -wait
+             ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-RunspaceData
```

### LINKED ISSUE #4410: Fix PSUsePSCredentialType
### Summary of new feature

There are 3 incidents of cmdlets breaking the PSUsePSCredentialType script analyzer rule, which could be impacting cmdlet use as well as our BOH. 

```
ScriptName            Line Extent
----------            ---- ------
Find-DbaInstance.ps1   539 [object]$Credential
Get-DbaWindowsLog.ps1  256 [object]...
New-DbaAgentProxy.ps1  105 [parameter(Mandatory)]...
````

This rule indicates that if the parameter `$Credential` is being used then is needs to use the `[PSCredential]` type and not `[string]` or `[object]`
See [PSUsePSCredentialType.md](https://github.com/PowerShell/PSScriptAnalyzer/blob/development/RuleDocumentation/UsePSCredentialType.md) for more details

### Proposed technical details (if applicable)

Change the instances in these three cmdlets to use `[PSCredential]`

### PR DESCRIPTION
**Pull request by nvarscar**
## Type of Change

 - [x] Bug fix (non-breaking change, fixes #4410, fixes #3349, maybe fixes #4391 )
 - [x] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [x] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
1. To add support for SSRS2017 which now lives in an individual namespace.
2. To improve UX with Start/Stop services: less vague output messages, more details

### Approach
1. All the reporting services are now being extracted from the reporting services namespace `root\Microsoft\SQLServer\ReportServer`. This is handled by a function Get-DbaReportingService. The function is made internal for now, but it can be later converted into a public function if a need arises (probably not, `Get-DbaService -Type SSRS` pretty much turns into a call to this function. No reason to expose it).
Unfortunately, this adds an overhead of yet another WMI query incorporated into the Get- command, but only when Type is not specified.
Returned reporting service objects have a different subset of properties, but Add-Member ensures the user gets the same experience across all the service types.
2. Had to make a few changes on how the internal functions work to improve the way the output is presented and to support SSRS2017 services.

### Commands to test
I have no 2017 instances and I would love to have people with access to SSRS2017 to test this branch. Examples:
```
Get-DbaService -ComputerName server -Type SSRS
Get-DbaService -ComputerName server #should return all the stuff including SSRS
Get-DbaService -ComputerName server -Instance RS_SSRS #new default instance name for SSRS
Get-DbaService -ComputerName server -ServiceName SQLServerReportingServices #new service name
```

### Screenshots
image
image

### Learning
`root\Microsoft\SQLServer\ReportServer` seems to be quite nice and returns a whole bunch of SSRS properties, most of which are read-only though:
image

### CODE REVIEW

**Comment by Zhunya** [comment]
Nothing working for me

image

```powershell
[19:26:12][754,88 ms] C:\Users\> Get-DbaService -ComputerName srv-sql-report1 -Type SSRS
WARNING: [19:30:36][Get-DbaService] No Sql Services found on srv-sql-report1.veles-capital.org

[19:31:20][15 ms] C:\Users\> (get-module dbatools).Path
E:\GitHub\dbatools-nvarscar-ssrs2017\dbatools.psm1
```

**Comment by nvarscar** [comment]
@Zhunya that's something one more person was encountering and I wonder what could've gone wrong.
The message that you see is no longer in the code, it has been replaced with a new message 'No services found in relevant namespaces...' check old line 255 and how it was replaced. I just realized, that apparently, that's where allcommands.ps1 kicks in and takes over the control :D make sure to create a folder .git in the module folder to load it using function files, not the allcommands file.
@wsuhoey could you check this new version too ensuring that it loads properly without using allcommands.ps1?

**Comment by potatoqualitee** [comment]
checks passed, got approval from Oleg 👍

**Comment by nvarscar** [comment]
Ugh, I mentioned a wrong issue in here, it should've been #4420 , which is also resolved by this PR.

**Pull request merged**
