### PR TITLE
Fidete sed verificate

### LINKED ISSUE #4861: 'Backup-DbaDatabase -Type LOG -Verify`
### Before submitting a bug report:

- [X] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [X] Verified this bug is not already reported in an issue
- [X] Verified errors are not related to permissions
- [X] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

## Steps to Reproduce

```powershell
Backup-DbaDatabase -SqlInstance SQLServer1 -Database DB1 -Verify -Type Log -Verbose
```
## Expected Behavior

Run RESTORE VERIFYONLY against a file, not a full restore.
If you go with full look for FULL/DIFF backup. Maybe implement a switch for full restore test.

## Actual Behavior

```powershell
VERBOSE: [10:02:31][Backup-DbaDatabase] Setting Default timestampformat
VERBOSE: [10:02:31][Backup-DbaDatabase] No backupfolder passed in, setting it to instance default
VERBOSE: [10:02:32][Backup-DbaDatabase] 1 database to backup
VERBOSE: [10:02:32][Backup-DbaDatabase] Backup database [DB1]
VERBOSE: [10:02:32][Backup-DbaDatabase] Creating log backup
VERBOSE: [10:02:32][Backup-DbaDatabase] Building file name
VERBOSE: [10:02:32][Backup-DbaDatabase] Setting filename - 201812211002
VERBOSE: [10:02:32][Backup-DbaDatabase] Building backup path
VERBOSE: [10:02:32][Backup-DbaDatabase] Devices added
VERBOSE: Performing the operation "Backing up DB1 to C:\Program Files\Microsoft SQL
Server\MSSQL14.MSSQLSERVER\MSSQL\Backup\DB1_201812211002.trn" on target "srv-vc".
VERBOSE: [10:02:32][Read-DbaTransactionLog] Limiting results to 1 rows
VERBOSE: [10:02:32][Read-DbaTransactionLog] Please be aware that ignoring the recommended limits may impact on the
performance of the SQL Server database and the calling system
VERBOSE: [10:02:32][Read-DbaTransactionLog] Starting Log retrieval
VERBOSE: [10:02:32][Convert-DbaLSN] Hexadecimal LSN passed in, converting to numeric
VERBOSE: [10:02:34][Get-DbaBackupHistory] Processing DB1
VERBOSE: [10:02:34][Get-DbaBackupHistory] Executing sql query.
VERBOSE: [10:02:34][Get-DbaBackupHistory] Processing as grouped output.
VERBOSE: [10:02:34][Get-DbaBackupHistory] 1 result-groups found.
VERBOSE: [10:02:34][Get-DbaBackupHistory] Processing DB1
VERBOSE: [10:02:34][Get-DbaBackupHistory] Executing sql query.
VERBOSE: [10:02:34][Get-DbaBackupHistory] Processing as grouped output.
VERBOSE: [10:02:34][Get-DbaBackupHistory] 0 result-groups found.
VERBOSE: [10:02:34][Get-DbaBackupHistory] No Diff found
VERBOSE: [10:02:34][Get-DbaBackupHistory] Executing sql query.
VERBOSE: [10:02:34][Get-DbaBackupHistory] Processing as grouped output.
VERBOSE: [10:02:34][Get-DbaBackupHistory] 4 result-groups found.
VERBOSE: [10:02:34][Restore-DbaDatabase] Changing statement timeout to infinity
VERBOSE: [10:02:34][Restore-DbaDatabase] ParameterSet  = Restore
VERBOSE: [10:02:34][Restore-DbaDatabase] Trust Database Backup History Set
VERBOSE: [10:02:34][Restore-DbaDatabase] Processing DatabaseName - DbaVerifyOnly
VERBOSE: [10:02:35][Format-DbaBackupInformation] Starting
VERBOSE: [10:02:35][Format-DbaBackupInformation] String passed in for DB rename
VERBOSE: [10:02:35][Format-DbaBackupInformation] New DbName (String) = DbaVerifyOnly
VERBOSE: [10:02:36][Format-DbaBackupInformation]  1 PhysicalName = C:\Program Files\Microsoft SQL
Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\DB1-2018-11-15sa.mdf
VERBOSE: [10:02:37][Format-DbaBackupInformation] PhysicalName = C:\Program Files\Microsoft SQL
Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\DbaVerifyOnlyDB1-2018-11-15sa.mdf
VERBOSE: [10:02:37][Format-DbaBackupInformation]  1 PhysicalName = C:\Program Files\Microsoft SQL
Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\DB1-2018-11-15sa.ldf
VERBOSE: [10:02:37][Format-DbaBackupInformation] PhysicalName = C:\Program Files\Microsoft SQL
Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\DbaVerifyOnlyDB1-2018-11-15sa.ldf
VERBOSE: [10:02:37][Select-DbaBackupInformation] Filtering by DatabaseName
WARNING: [10:02:37][Select-DbaBackupInformation] Fullname property not found. This could mean that a full backup could
not be found or the command must be re-run with the -Continue switch.
VERBOSE: [10:02:37][Restore-DbaDatabase] VerifyOnly = True
VERBOSE: [10:02:37][Restore-DbaDatabase]  passed testing
VERBOSE: [10:02:37][Restore-DbaDatabase] Passing in to restore
WARNING: [10:02:37][Backup-DbaDatabase] Backup Failed | Cannot index into a null array.
```

### PR DESCRIPTION
**Pull request by Stuart-Moore**
## Type of Change

 - [x] Bug fix (non-breaking change, fixes #4861)
 - [ ] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
Backup -Verify now works with Diffs and log backups

### Approach
Fix chain tests

### CODE REVIEW

**Comment by potatoqualitee** [comment]
will wait for review by @Zhunya !

**Comment by Zhunya** [comment]
Error still there

```powershell
PS C:\Users\sqladmin> Backup-DbaDatabase -SqlInstance srv-vc -Database DB1 -Verify -Type Log

WARNING: [17:47:57][Select-DbaBackupInformation] Fullname property not found. This could mean that a full backup could not be found or the command must be re-run with the -Continue switch.
WARNING: [17:47:58][Backup-DbaDatabase] Backup Failed | Cannot index into a null array.
```
```powershell
PS C:\Users\sqladmin> Backup-DbaDatabase -SqlInstance srv-vc -Database DB1 -Verify -Type Log -Verbose
VERBOSE: [17:50:36][Backup-DbaDatabase] Setting Default timestampformat
VERBOSE: [17:50:37][Backup-DbaDatabase] No backupfolder passed in, setting it to instance default
VERBOSE: [17:50:39][Backup-DbaDatabase] 1 database to backup
VERBOSE: [17:50:39][Backup-DbaDatabase] Backup database [DB1]
VERBOSE: [17:50:39][Backup-DbaDatabase] Creating log backup
VERBOSE: [17:50:39][Backup-DbaDatabase] Building file name
VERBOSE: [17:50:39][Backup-DbaDatabase] Setting filename - 201812211750
VERBOSE: [17:50:39][Backup-DbaDatabase] Building backup path
VERBOSE: [17:50:39][Backup-DbaDatabase] Devices added
VERBOSE: Performing the operation "Backing up DB1 to C:\Program Files\Microsoft SQLServer\MSSQL14.MSSQLSERVER\MSSQL\Backup\DB1_201812211750.trn" on target "srv-vc".
VERBOSE: [17:50:39][Read-DbaTransactionLog] Limiting results to 1 rows
VERBOSE: [17:50:39][Read-DbaTransactionLog] Please be aware that ignoring the recommended limits may impact on the performance of the SQL Server database and the calling system
VERBOSE: [17:50:39][Read-DbaTransactionLog] Starting Log retrieval
VERBOSE: [17:50:39][Convert-DbaLSN] Hexadecimal LSN passed in, converting to numeric
VERBOSE: [17:50:40][Get-DbaBackupHistory] Processing DB1
VERBOSE: [17:50:40][Get-DbaBackupHistory] Executing sql query.
VERBOSE: [17:50:40][Get-DbaBackupHistory] Processing as grouped output.
VERBOSE: [17:50:40][Get-DbaBackupHistory] 1 result-groups found.
VERBOSE: [17:50:40][Get-DbaBackupHistory] Processing DB1
VERBOSE: [17:50:40][Get-DbaBackupHistory] Executing sql query.
VERBOSE: [17:50:40][Get-DbaBackupHistory] Processing as grouped output.
VERBOSE: [17:50:40][Get-DbaBackupHistory] 0 result-groups found.
VERBOSE: [17:50:40][Get-DbaBackupHistory] No Diff found
VERBOSE: [17:50:40][Get-DbaBackupHistory] Executing sql query.
VERBOSE: [17:50:40][Get-DbaBackupHistory] Processing as grouped output.
VERBOSE: [17:50:40][Get-DbaBackupHistory] 7 result-groups found.
VERBOSE: [17:50:41][Restore-DbaDatabase] Changing statement timeout to infinity
VERBOSE: [17:50:41][Restore-DbaDatabase] ParameterSet  = Restore
VERBOSE: [17:50:41][Restore-DbaDatabase] Trust Database Backup History Set
VERBOSE: [17:50:41][Restore-DbaDatabase] Processing DatabaseName - DbaVerifyOnly
VERBOSE: [17:50:41][Format-DbaBackupInformation] Starting
VERBOSE: [17:50:41][Format-DbaBackupInformation] String passed in for DB rename
VERBOSE: [17:50:41][Format-DbaBackupInformation] New DbName (String) = DbaVerifyOnly
VERBOSE: [17:50:41][Format-DbaBackupInformation]  1 PhysicalName = C:\Program Files\Microsoft SQLServer\MSSQL14.MSSQLSERVER\MSSQL\DATA\DB1-2018-11-15sa.mdf
VERBOSE: [17:50:41][Format-DbaBackupInformation] PhysicalName = C:\Program Files\Microsoft SQLServer\MSSQL14.MSSQLSERVER\MSSQL\DATA\DbaVerifyOnlyDB1-2018-11-15sa.mdf
VERBOSE: [17:50:41][Format-DbaBackupInformation]  1 PhysicalName = C:\Program Files\Microsoft SQLServer\MSSQL14.MSSQLSERVER\MSSQL\DATA\DB1-2018-11-15sa.ldf
VERBOSE: [17:50:41][Format-DbaBackupInformation] PhysicalName = C:\Program Files\Microsoft SQLServer\MSSQL14.MSSQLSERVER\MSSQL\DATA\DbaVerifyOnlyDB1-2018-11-15sa.ldf
VERBOSE: [17:50:41][Select-DbaBackupInformation] Filtering by DatabaseName
WARNING: [17:50:41][Select-DbaBackupInformation] Fullname property not found. This could mean that a full backup could not be found or the command must be re-run with the -Continue switch.
VERBOSE: [17:50:41][Restore-DbaDatabase] VerifyOnly = True
VERBOSE: [17:50:42][Restore-DbaDatabase]  passed testing
VERBOSE: [17:50:42][Restore-DbaDatabase] Passing in to restore
WARNING: [17:50:42][Backup-DbaDatabase] Backup Failed | Cannot index into a null array.
```

**Comment by Stuart-Moore** [comment]
Works fine here:
image
```
C:\github\dbatools [FideteSedVerificate ≡]> $b = Backup-DbaDatabase -SqlInstance localhost\sql2016 -database stripetest -Type diff  -Verify
-verbose
VERBOSE: [16:14:33][Backup-DbaDatabase] Setting Default timestampformat
VERBOSE: [16:14:33][Backup-DbaDatabase] No backupfolder passed in, setting it to instance default
VERBOSE: [16:14:33][Backup-DbaDatabase] 1 database to backup
VERBOSE: [16:14:33][Backup-DbaDatabase] Backup database [StripeTest]
VERBOSE: [16:14:33][Backup-DbaDatabase] Creating differential backup
VERBOSE: [16:14:33][Backup-DbaDatabase] Building file name
VERBOSE: [16:14:33][Backup-DbaDatabase] Setting filename - 201812221614
VERBOSE: [16:14:33][Backup-DbaDatabase] Building backup path
VERBOSE: [16:14:33][Backup-DbaDatabase] Devices added
VERBOSE: Performing the operation "Backing up StripeTest to C:\Program Files\Microsoft SQL
Server\MSSQL13.SQL2016\MSSQL\Backup\StripeTest_201812221614.bak" on target "localhost\sql2016".
VERBOSE: [16:14:33][Read-DbaTransactionLog] Limiting results to 1 rows
VERBOSE: [16:14:33][Read-DbaTransactionLog] Please be aware that ignoring the recommended limits may impact on the performance of the SQL
Server database and the calling system
VERBOSE: [16:14:33][Read-DbaTransactionLog] Starting Log retrieval
VERBOSE: [16:14:34][Convert-DbaLSN] Hexadecimal LSN passed in, converting to numeric
VERBOSE: [16:14:34][Get-DbaBackupHistory] Processing StripeTest
VERBOSE: [16:14:34][Get-DbaBackupHistory] Executing sql query.
VERBOSE: [16:14:34][Get-DbaBackupHistory] Processing as grouped output.
VERBOSE: [16:14:34][Get-DbaBackupHistory] 1 result-groups found.
VERBOSE: [16:14:34][Get-DbaBackupHistory] Processing StripeTest
VERBOSE: [16:14:34][Get-DbaBackupHistory] Executing sql query.
VERBOSE: [16:14:34][Get-DbaBackupHistory] Processing as grouped output.
VERBOSE: [16:14:34][Get-DbaBackupHistory] 1 result-groups found.
VERBOSE: [16:14:34][Get-DbaBackupHistory] Valid Differential backup
VERBOSE: [16:14:34][Get-DbaBackupHistory] Executing sql query.
VERBOSE: [16:14:34][Get-DbaBackupHistory] Processing as grouped output.
VERBOSE: [16:14:34][Get-DbaBackupHistory] 19 result-groups found.
VERBOSE: [16:14:34][Restore-DbaDatabase] Changing statement timeout to infinity
VERBOSE: [16:14:34][Restore-DbaDatabase] ParameterSet  = Restore
VERBOSE: [16:14:34][Restore-DbaDatabase] Trust Database Backup History Set
VERBOSE: [16:14:34][Restore-DbaDatabase] Processing DatabaseName - DbaVerifyOnly
VERBOSE: [16:14:34][Format-DbaBackupInformation] Starting
VERBOSE: [16:14:34][Format-DbaBackupInformation] String passed in for DB rename
VERBOSE: [16:14:34][Format-DbaBackupInformation] New DbName (String) = DbaVerifyOnly
VERBOSE: [16:14:34][Format-DbaBackupInformation]  1 PhysicalName = C:\Program Files\Microsoft SQL
Server\MSSQL13.SQL2016\MSSQL\DATA\StripeTestrestoretimestripe.mdf
VERBOSE: [16:14:34][Format-DbaBackupInformation] PhysicalName = C:\Program Files\Microsoft SQL
Server\MSSQL13.SQL2016\MSSQL\DATA\DbaVerifyOnlyStripeTestrestoretimestripe.mdf
VERBOSE: [16:14:34][Format-DbaBackupInformation]  1 PhysicalName = C:\Program Files\Microsoft SQL
Server\MSSQL13.SQL2016\MSSQL\DATA\StripeTestrestoretimestripe_log.LDF
VERBOSE: [16:14:34][Format-DbaBackupInformation] PhysicalName = C:\Program Files\Microsoft SQL
Server\MSSQL13.SQL2016\MSSQL\DATA\DbaVerifyOnlyStripeTestrestoretimestripe_log.LDF
VERBOSE: [16:14:34][Restore-DbaDatabase] VerifyOnly = True
VERBOSE: [16:14:34][Test-DbaBackupInformation] Testing restore for DbaVerifyOnly
VERBOSE: [16:14:34][Test-DbaBackupInformation] VerifyOnly = True
VERBOSE: [16:14:34][Test-DbaBackupInformation] Marking DbaVerifyOnly as verified
VERBOSE: [16:14:34][Restore-DbaDatabase] DbaVerifyOnly passed testing
VERBOSE: [16:14:34][Restore-DbaDatabase] Passing in to restore
VERBOSE: [16:14:34][Invoke-DbaAdvancedRestore] Performing restore action
VERBOSE: [16:14:34][Invoke-DbaAdvancedRestore] VerifyOnly restore
VERBOSE: [16:14:34][Invoke-DbaAdvancedRestore] VerifyOnly restore Succeeded
VERBOSE: [16:14:34][Invoke-DbaAdvancedRestore] Succeeded, Closing Server connection
C:\github\dbatools [FideteSedVerificate ≡]> $b.Verified
True
C:\github\dbatools [FideteSedVerificate ≡]>
```
Anyone else fancy being the tie breaker?

**Comment by Stuart-Moore** [comment]
Added pester tests (Backup-DbaDatabase.Tests.ps1 L179-198) to check for verification , they pass locally and on appveyor.

**Comment by potatoqualitee** [comment]
i shall break this tie! brb

**Comment by potatoqualitee** [comment]
works well for me! 
image

**Comment by potatoqualitee** [comment]
Thank you both so much 🙇

**Pull request merged**
