### PR TITLE
Get-DbaHelpIndex - break out Statistics from Index column in output

### LINKED ISSUE #2819: Get-DbaHelpIndex, add column to account for index and stats separately
### Problem to solve
The output for Get-DbaHelpIndex does not include the index name or the statistics name. It would be helpful to have the index name and statistics name included in the output. Also please consider changing the name of the output column ObjectName to be TableName.

### Additional information

There is an input parameter also named ObjectName, but it is always a table. Would TableName for the input parameter be more clear?

Thanks,
Matthew

### PR DESCRIPTION
**Pull request by jpomfret**
## Type of Change

 - [X] Bug fix (non-breaking change, fixes #<enter issue number>)
 - [ ] New feature (non-breaking change, adds functionality)
 - [X] Breaking change (effects multiple commands or functionality)
 - [X] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
 
Fix #2819 to add Statistics column. 

### Approach

Adds column to output for Statistics.
I need some help testing the function against 2005 boxes. I'm not sure the code is currently working but I don't have a 2005 instance to test against currently.

### Screenshots

image

### CODE REVIEW

**Comment by potatoqualitee** [comment]
aww yis, thank you jess!

**Comment by jpomfret** [comment]
@potatoqualitee not sure what's wrong with the encoding, I changed it to UTF-8 and repushed. Also I need help making this change for the 2005 code... will take me a little while to get a 2005 instance here to test against.

**Comment by potatoqualitee** [comment]
it passed, another test failed - appveyoru has been a bit rough lately. 

is it ready to merge now or do you need time for 2005?

**Comment by jpomfret** [comment]
If you merge it won't work on 2005 I don't think... however I'm not sure it's currently working on 2005 either. I got errors just trying to run the query.

**Comment by potatoqualitee** [comment]
it does not! going to merge and add a minimum connection var 🎉 
image

Thank you so much, @jpomfret !

**Pull request merged**
