### PR TITLE
Repair-DbaInstanceName / Test-DbaInstanceName - Added more verbose and debug output and fix user problem

### LINKED ISSUE #7332: [Bug] Repair-DbaInstanceName does not work in SQL 2019

### PR DESCRIPTION
**Pull request by andreasjordan**
## Type of Change

 - [x] Bug fix (non-breaking change, fixes #7332)
 - [ ] New feature (non-breaking change, adds functionality, fixes # )
 - [ ] Breaking change (effects multiple commands or functionality, fixes # )
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system

It adds more verbose and debug output to help to understand the situation at the user.
It also renames some variables to better reflect the values they store.
And it does not rely on $server.ComputerName but $server.NetName as depending on the used code path in Connect-DbaInstance, the ComputerName property might be in full qualified format.

I ordered the properties in the output object to reflect our standards.
I added the property NewServerName that is based on $server.NetName.
I removed the Select-DefaultView as I think that all properties should be displayed by default.

I updated Repair-DbaInstanceName as well and changed some variable names.
I also used the new property NewServerName from Test-DbaInstanceName.

image

### CODE REVIEW

**Comment by andreasjordan** [comment]
I ordered the properties in the output object to reflect our standards.
I added the property NewServerName that is based on $server.NetName.
I removed the Select-DefaultView as I think that all properties should be displayed by default.

**Comment by andreasjordan** [comment]
Now I updated Repair-DbaInstanceName as well and changed some variable names.
I also used the new property NewServerName from Test-DbaInstanceName.

**Comment by andreasjordan** [comment]
Verified by user, see issue for details.

**Review by niphlod — APPROVED** [review]

**Comment by potatoqualitee** [comment]
🔥 🚒

**Pull request merged**
