### PR TITLE
Save-DbaCommunitySoftware - Add code to download WhoIsActive

### LINKED ISSUE #7884: Install-DbaWhoIsActive - Use Save-DbaCommunitySoftware to download latest version?
### Summarize Functionality

Do we want to use Save-DbaCommunitySoftware to download the lastest version of sp_WhoIsActive?

At the moment, we use Save-DbaCommunitySoftware for:
* MaintenanceSolution: SQL Server Maintenance Solution created by Ola Hallengren (https://ola.hallengren.com)
* FirstResponderKit: First Responder Kit created by Brent Ozar (http://FirstResponderKit.org)
* DarlingData: Erik Darling's stored procedures (https://www.erikdarlingdata.com)

Currently, Install-DbaWhoIsActive searches for the last release and downloads that. With Save-DbaCommunitySoftware we would just get the current master branch (as there is no dev branch).

### Is there a command that is similiar or close to what you are looking for?

No

### Technical Details

_No response_

### PR DESCRIPTION
**Pull request by andreasjordan**
## Type of Change

 - [ ] Bug fix (non-breaking change, fixes # )
 - [x] New feature (non-breaking change, adds functionality, fixes #7884 )
 - [ ] Breaking change (effects multiple commands or functionality, fixes # )
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1`)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Unit test is included
 - [ ] Documentation
 - [ ] Build system

### Purpose
Align all the code that downloads software from GitHub.

### Approach
Save WhoIsActive like we save some other software as well to reduce code.

### CODE REVIEW

**Comment by amachanic** [comment]
> * Is 'WhoIsActive' ok as the name of the software? The other software this command can download is called 'MaintenanceSolution', 'FirstResponderKit', 'DarlingData', 'SQLWATCH'

Yes, that's fine.


> * The documentation uses "* WhoIsActive: Adam Machanic's comprehensive activity monitoring stored procedure sp_WhoIsActive (https://github.com/amachanic/sp_whoisactive)" in the list of supported software. Is that ok or would your like some other text?

Works for me!


> * Should the user be able to download the software from the current master branch? Or will you shortly publish a new version with the recent changes?

I've been releasing periodically using the GitHub "Create Release" feature. Is that something you can use? The master branch may contain changes that are more sort of "beta" in nature.


> So if you plan to change the filename it would be nice to give us the new name (or a rule to find the correct name) ahead of time to update the command.

I think that will happen sometime. Will certainly let you know.

**Comment by potatoqualitee** [comment]
Thank you both 🙇🏼  The code looks good to me, let me know when you're ready @andreasjordan !

**Comment by andreasjordan** [comment]
Code is ready, can be merged.

**Comment by potatoqualitee** [comment]
excellent, thanks again!

**Comment by amachanic** [comment]
@andreasjordan I have just published a new sp_whoisactive release candidate, which includes the new file name that we'll be going to. (sp_WhoIsActive.sql). The plan is to maintain both file names for a little while -- probably a few months -- and then flip over to the new one. I think this should give you and others time to migrate. Let me know if you have any questions or concerns!

**Comment by andreasjordan** [comment]
Thanks to the information, opened #7944 for that and will take.

**Pull request merged**
