### PR TITLE
Connect-DbaInstance - New parameter AccessToken

### LINKED ISSUE #7271: [Bug]Connect-DbaInstance can't connect to Azure SQL or SQL MI
### Report
We are working on the migration to that fancy fluffy stuff up in the sky.  As of now, we have a mixed bag of SQL: SQL Server (on prem & VM), Azure SQL, & SQL MI.  Now that we have Azure SQL & MI, I need to be able to connect holistically, regardless of what my SQL type is!  I figured, based on the documentation in `Connect-DbaInstance` that I could do it, but unfortunately I was getting a bunch of errors!  What are these errors you speak of?  Well I am so happy you read this far and are interested for more!!!!  Below I have the various errors and scripts that I used.  I worked with @wsuhoey & @andreasjordan  in the dbatools channel in Slack for this too.

I did figure out a workaround for this (answered below too!)

#### Host used

- [x] powershell.exe
- [x] ISE
- [x] VS Code
- [ ] Other (please specify)

#### Errors Received

**Method 1**
```powershell
Connect-DbaInstance -SqlInstance $instance -Verbose -Database 'master' -Tenant $ConnectedAz -SqlCredential $cred -AuthenticationType 'AD Universal with MFA Support'
```
**Yielded**
`Response status code does not indicate success: 400 (Bad Request).`

**Full error message with -DEBUG**
```powershell
$connectedInstance = Connect-DbaInstance -SqlInstance $instance -Verbose -Database 'master' -Tenant $ConnectedAz -SqlCredential $cred -AuthenticationType 'AD Universal with MFA Support' -Debug
DEBUG: 2275 | [11:46:42][Connect-DbaInstance] Starting process block
DEBUG: 2277 | [11:46:42][Connect-DbaInstance] Starting loop for 'aaaaa.bbbbb.database.windows.net': ComputerName = 'aaaaa.bbbbb.database.windows.net', InstanceName = 'MSSQLSERVER', IsLocalHost = 'False', Type = 'Default'
DEBUG: 2646 | [11:46:42][Connect-DbaInstance] We are about to connect to Azure
DEBUG: 2682 | [11:46:42][Connect-DbaInstance] We have a Tenant and build the connect string
VERBOSE: [11:46:42][Connect-DbaInstance] Creating renewable token
DEBUG: 2717 | [11:46:42][Connect-DbaInstance] Creating renewable token
VERBOSE: The source code was already compiled and loaded.
VERBOSE: [11:46:42][Connect-DbaInstance] Connecting to Data Source=TCP:aaaaa.bbbbb.database.windows.net,1433;Initial Catalog=master;Persist Security Info=True;MultipleActiveResultSets=False;Connect Timeout=30;Encrypt=True;TrustServerCertificate=False;Application Name="dbatools PowerShell module - dbatools.io"
DEBUG: 2725 | [11:46:42][Connect-DbaInstance] Connecting to Data Source=TCP:aaaaa.bbbbb.database.windows.net,1433;Initial Catalog=master;Persist Security Info=True;MultipleActiveResultSets=False;Connect Timeout=30;Encrypt=True;TrustServerCertificate=False;Application Name="dbatools PowerShell module - dbatools.io"
VERBOSE: [11:46:42][Connect-DbaInstance] Connecting to Azure: aaaaa.bbbbb.database.windows.net
DEBUG: 2737 | [11:46:42][Connect-DbaInstance] Connecting to Azure: aaaaa.bbbbb.database.windows.net
DEBUG: [11:46:43][Connect-DbaInstance] Failure | Response status code does not indicate success: 400 (Bad Request).
```

**Method 2**
Using the new method of `Connect-DbaInstance` I get this (example 17 from the documentation page)
```powershell
Set-DbatoolsConfig -FullName sql.connection.experimental -Value $true
Connect-DbaInstance -SqlInstance $instance -SqlCredential $Cred
```
**Yielded**
`Cannot open server "MFCGD.COM" requested by the login.  The login failed.`

**Full error message with -DEBUG**
```powershell
Set-DbatoolsConfig -FullName sql.connection.experimental -Value $true
Connect-DbaInstance -SqlInstance $instance -SqlCredential $Cred -Debug
DEBUG: 2275 | [12:02:50][Connect-DbaInstance] Starting process block
DEBUG: 2277 | [12:02:50][Connect-DbaInstance] Starting loop for 'aaaaa.bbbbb.database.windows.net': ComputerName = 'aaaaa.bbbbb.database.windows.net', InstanceName = 'MSSQLSERVER', IsLocalHost = 'False', Type = 'Default'
DEBUG: 2282 | [12:02:50][Connect-DbaInstance] sql.connection.experimental is used
DEBUG: 2305 | [12:02:50][Connect-DbaInstance] String is passed in, will build server object from instance object and other parameters, do some checks and then return the server object
DEBUG: 2187 | [12:02:50][Test-Azure] Test for Azure is positive
DEBUG: 2367 | [12:02:50][Connect-DbaInstance] authentication method is 'azure ad'
DEBUG: 2399 | [12:02:50][Connect-DbaInstance] ApplicationName will be set to 'dbatools PowerShell module - dbatools.io'
DEBUG: 2421 | [12:02:50][Connect-DbaInstance] Authentication will be set to 'ActiveDirectoryPassword'
DEBUG: 2436 | [12:02:50][Connect-DbaInstance] ConnectionTimeout will be set to '15'
DEBUG: 2466 | [12:02:50][Connect-DbaInstance] PacketSize will be set to '4096'
DEBUG: 2485 | [12:02:50][Connect-DbaInstance] Pooled will be set to 'True'
DEBUG: 2494 | [12:02:50][Connect-DbaInstance] SecurePassword will be set
DEBUG: 2521 | [12:02:50][Connect-DbaInstance] UserName will be set to 'USER1@MFCGD.COM'
DEBUG: 2543 | [12:02:51][Connect-DbaInstance] TrueLogin is ''
DEBUG: 2566 | [12:02:51][Connect-DbaInstance] The masked server.ConnectionContext.ConnectionString is Data Source=aaaaa.bbbbb.database.windows.net;User ID=USER1@MFCGD.COM;Password=********;MultipleActiveResultSets=False;Encrypt=False;TrustServerCertificate=False;Packet Size=4096;Application Name="dbatools PowerShell module - dbatools.ioUSER1@MFCGD.COM;Password=********;MultipleActiveResultSets=False;Encrypt=False;TrustServerCertificate=False;Packet Size=4096;Application Name="dbatools PowerShell module - dbatools.io"
DEBUG: 2570 | [12:02:51][Connect-DbaInstance] We connect to the instance with server.ConnectionContext.SqlConnectionObject.Open()
DEBUG: [12:02:51][Connect-DbaInstance] Failure | Cannot open server "MFCGD.COM" requested by the login.  The login failed.
Confirm
Continue with this operation?
[Y] Yes [A] Yes to All [H] Halt Command [S] Suspend [?] Help (default is "Yes"): A
ConnectionError: C:\Users\CADBAMSQL04\Documents\PowerShell\Modules\dbatools\1.0.145\allcommands.ps1:88170:9
 Line |
88170 |          throw $records[0]
      |          ~~~~~~~~~~~~~~~~~
      | Cannot open server "MFCGD.COM" requested by the login.  The login failed.
```

#### Steps to Reproduce

**Method 1**
```powershell
$Cred = Get-Credential
$ConnectedAz = Connect-AzAccount -Credential $Cred
$instance = "aaaaaaaaaaa.bbbbbbbbb.database.windows.net"
$connectedInstance = Connect-DbaInstance -SqlInstance $instance -Verbose -AuthenticationType 'AD Universal with MFA Support' -Database 'master' -SqlCredential $Cred -Tenant $ConnectedAz
```

**Method 2**
Using the new method of `Connect-DbaInstance` I get this (example 17 from the documentation page)
```powershell
$Cred = Get-Credential
$ConnectedAz = Connect-AzAccount -Credential $Cred
$instance = "aaaaaaaaaaa.bbbbbbbbb.database.windows.net"

Set-DbatoolsConfig -FullName sql.connection.experimental -Value $true
Connect-DbaInstance -SqlInstance $instance -SqlCredential $Cred
```

#### Workaround

it would seem that dbatools doesn't yet support Azure SQL with Integrated Azure Active Directory ?  well to get around this, I had to go outside of dbatools and use the classic `SqlServer` module's `Invoke-SqlCmd`

Found in [Example 11: Connect to Azure SQL Database (or Managed Instance) using an Access Token
](https://docs.microsoft.com/en-us/powershell/module/sqlserver/invoke-sqlcmd?view=sqlserver-ps#example-11--connect-to-azure-sql-database--or-managed-instance--using-an-access-token)

```powershell
$Cred = New-Object System.Management.Automation.PSCredential -ArgumentList ($credid, $credpass)
$ConnectedAz = Connect-AzAccount -Credential $Cred -WarningAction SilentlyContinue
$token = (Get-AzAccessToken -ResourceUrl https://database.windows.net).Token
$instance = "aaaaa.bbbbb.database.windows.net"
Invoke-Sqlcmd -ServerInstance $instance -Database master -query "select [name] from [sys].[databases]" -AccessToken $token
name
----
master
tempdb
```

#### Expected Behavior

to connect

#### Actual Behavior

it didn't connect

### Environmental information

🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
Please provide the output of the below script

```powershell
PowerShell Version        : 7.1.3
dbatools latest installed : 1.0.145
Culture of OS             : en-US
```

#### SQL Server:

```sql
Microsoft SQL Azure (RTM) - 12.0.2000.8   Feb 20 2021 17:51:58   Copyright (C) 2019 Microsoft Corporation 
```

```sql
us_english
```

### PR DESCRIPTION
**Pull request by andreasjordan**
## Type of Change
 - [ ] Bug fix (non-breaking change, fixes # )
 - [x] New feature (non-breaking change, adds functionality, fixes #7271 )
 - [ ] Breaking change (effects multiple commands or functionality, fixes # )
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 
### Purpose
Be able to connect to Azure with an AccessToken

### Approach
Get AccessToken outside of dbatools and pass it to Connect-DbaInstance as a string.
Inside we build a System.Data.SqlClient.SqlConnection and assign the AccessToken there.

### Commands to test
See new example

### Screenshots
image

### CODE REVIEW

**Comment by andreasjordan** [comment]
Yes, help is still missing for the new parameter - will add that later today or tomorrow.

**Comment by andreasjordan** [comment]
Parameter help is added. Failing test seems not related to the change, can anyone restart test?

**Comment by andreasjordan** [comment]
See positive test:
https://github.com/sqlcollaborative/dbatools/issues/7271#issuecomment-841843778

**Review by niphlod — APPROVED** [review]

**Comment by potatoqualitee** [comment]
AWESOME!

**Comment by potatoqualitee** [comment]
Thank you, ive been wanting this for years but had issues implementing it.

**Comment by cmuncan** [comment]
so glad this finally came to fruition!  we are making a serious shift to SQL MI and I really don't want to lose the functionality of dbatools.

**Pull request merged**
