### PR TITLE
Test Redesign to pre-v2

### PR DESCRIPTION
**Pull request by FriedrichWeinmann**
Changes how the entire test suite works.
Primarily centralized all imports to avoid Import-Module/Export-Module conflicts.

### CODE REVIEW

**Comment by FriedrichWeinmann** [comment]
Note, this brings a few issues, which I'll address as the tests fail:
 - Help for internal functions is tested. That should be done anyway, but some of them don't have any.
 - Disabled all Script Analyzer Rule exclusions from the tests. Should not be disabled globally but on a per-file basis

Will see what fails and address as I go

**Comment by potatoqualitee** [comment]
@SQLDBAWithABeard and @niphlod - says you recently edited these files. Can you please confirm that you understand what's going on going forward? 

Thank you!

**Comment by potatoqualitee** [comment]
Thanks @niphlod - I'll be updating the tests so they don't fail. And start SqlServer and pass out that info so that ppl can make real tests 👍

**Comment by niphlod** [comment]
@cl to make sure sql server(s) are ready you can borrow this snippet
https://github.com/niphlod/pydal/blob/master/appveyor.yml#L37

Il 18 mag 2017 12:51, "Chrissy LeMaire" <notifications@github.com> ha
scritto:

**Comment by potatoqualitee** [comment]
Cool thank you! I'll add that

**Comment by SQLDBAWithABeard** [comment]
Yes, is time the tests moved from the initial get the script analyser run to a more concrete method

**Comment by potatoqualitee** [comment]
@SQLDBAWithABeard !! Look i wrote my first tests and theyr'e awesome! they perform actual restores from the appveyor-lab repo!!

image

image

**Comment by SQLDBAWithABeard** [comment]
So cool, next you need to learn mocking and remove the warning from the output but check it is called and I would use -ea silentlycontinue to avoid the "sea of red"

**Comment by potatoqualitee** [comment]
can you take a look at this [test](https://github.com/sqlcollaborative/dbatools/blob/testresolutions/tests/Restore-DbaDatabase.Tests.ps1) and tell me if it stayed within scope? i wanted it to be thorough but ended up sorta testing other commands, too.

**Comment by SQLDBAWithABeard** [comment]
I see an error in your test - look at these two tests below using output from restore-dbdatabase

First one passes - second one doesnt

PS Presentations:\TUGAIT 2017 - Pester> Describe "one test" {
    It "Should pass" {
        ($results.Restorecomplete -contains $False) | should be $False
    }
        It "Should pass but wont" {
        $results.Restorecomplete | should be $true
    }
}


Describing one test
  [+] Should pass 97ms
  [-] Should pass but wont 37ms
    Expected: {True}
    But was:  {True True True True True True True True True True True True True True True True True True True True True True True Tr
ue True True True True True True True True True True True True True True True True True True True True True True True True True True
 True True True True True True True}
    at <ScriptBlock>, : line 6
    6:         $results.Restorecomplete | should be $true

**Comment by potatoqualitee** [comment]
What's strange is that it depends on the version of PowerShell 👎 @gbargsley had the same problem you do, but it works perfectly on my version. How can i say "Shoudl not contain $false" i think i tried that and it scuked

**Comment by SQLDBAWithABeard** [comment]
But the scope i fine for the integration test

**Comment by SQLDBAWithABeard** [comment]
You can do it like I showed above 

It "Should pass" {
($results.Restorecomplete -contains $False) | should be $False
}

Pester contains only works for file contents so you have to use PowerShell contains and test for true or false

Good eh :-)

**Comment by potatoqualitee** [comment]
i like that! thank you!!!!

**Pull request merged**
