### PR TITLE
Fix the casting and alter error

### PR DESCRIPTION
**Pull request by sanderstad**

### CODE REVIEW

**Comment by sanderstad** [comment]
Results after fix:
image

**Comment by gbargsley** [comment]
Here is a before and after run.  What should I see different?

image

**Comment by sanderstad** [comment]
The force parameter should now remove existing job steps. 
There were some other errors that I fixed in the first commit of the PR

**Comment by potatoqualitee** [comment]
@gbargsley - tearin it up! Thanks so much, man. And thank you, @sanderstad for the quick fix! 🏆 🏆

**Pull request merged**
