### PR TITLE
PR - Set dba agent alert new

### PR DESCRIPTION
**Pull request by gbargsley**
New command.

### CODE REVIEW

**Comment by gbargsley** [comment]
Not sure what to set my tabs and spaces to get the test to past.

**Comment by niphlod** [comment]
easy peasy ...

image


line 90

image


line 166

image

**Comment by gbargsley** [comment]
Thanks, my VS Code showed them as tabs.  I took them out.  Lets see how this goes.

**Comment by potatoqualitee** [comment]
hey garry - would you be able to add a test for this command? 🤗

**Comment by potatoqualitee** [comment]
whaatup!

**Pull request merged**
