### PR TITLE
New-DbaDbSequence - Don't use Test-Bound with defaults

### PR DESCRIPTION
**Pull request by andreasjordan**
## Type of Change

 - [x] Bug fix (non-breaking change, fixes # )
 - [ ] New feature (non-breaking change, adds functionality, fixes # )
 - [ ] Breaking change (effects multiple commands or functionality, fixes # )
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 
StartWith was not set when not explicitly set by parameter.

### CODE REVIEW

**Comment by andreasjordan** [comment]
I don't have an idea why these two tests fail...

**Comment by andreasjordan** [comment]
Open issue: The command returns just the plain SMO, all the other commands add ComputerName, InstanceName and SqlInstance and have a default view. That should be added here as well. 
@lancasteradam : If you like, you can just close this pull request and open your own with all the necessary changes.

**Comment by wsmelton** [comment]
The test fails because you are outputting the created object and not the object from the database. You cannot output `$newSequence` it has to output the sequence object found in the database (after it is created), that is how the test is written.

**Comment by andreasjordan** [comment]
Test still fails and I don't have any idea. Can you please have a look @wsmelton - thanks.

**Comment by lancasteradam** [comment]
The integration tests for min and max need these small changes shown below. This is because of the bugfix being made in this PR for the StartWith param in New-DbaDbSequence.ps1.

New-DbaDbSequence.Tests.ps1

Line 109:
`$sequence = New-DbaDbSequence -SqlInstance $instance2 -Database $newDbName -Name "Sequence_$($randomForMinValues)" -Schema "Schema_$random" -MinValue $minValue -StartWith $minValue`

and line 118:
`$maxValues = @(10000, 100000)`

For the New-DbaDbSequence.ps1 return object and default view this code could potentially be used:

```
$newSequence = $db | Get-DbaDbSequence -Name $newSequence.Name -Schema $newSequence.Schema
                    
Add-Member -Force -InputObject $newSequence -MemberType NoteProperty -Name ComputerName -value $db.Parent.ComputerName
Add-Member -Force -InputObject $newSequence -MemberType NoteProperty -Name InstanceName -value $db.Parent.ServiceName
Add-Member -Force -InputObject $newSequence -MemberType NoteProperty -Name SqlInstance -value $db.Parent.DomainInstanceName

Select-DefaultView -InputObject $newSequence -Property ComputerName, InstanceName, SqlInstance, Name, Schema, DataType, StartValue, IncrementValue, MinValue, MaxValue, CacheSize, IsCycleEnabled
```

**Comment by andreasjordan** [comment]
Hi Adam, thanks for the hint, that changes to the test helped. Now only unrelated test fail.
The Add-Member and Select-DefaultView is not needed, that is already handled by the Get-DbaDbSequence - that is why we use the Get- to get the object.

**Comment by potatoqualitee** [comment]
Thank you both! Re-running tests now 👍🏼

**Comment by potatoqualitee** [comment]
All tests pass, merging! 😊

**Pull request merged**
