### PR TITLE
DbaInstanceParameter - Added support for SqlConnection

### PR DESCRIPTION
**Pull request by FriedrichWeinmann**
## Type of Change

 - [ ] Bug fix (non-breaking change, fixes #<enter issue number>)
 - [x] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [x] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 
### Changes

 - Added support for `System.Data.SqlClient.SqlConnection` as an input type. Connection will be reused.
 - Computer names which end with `.WORKGROUP` should have that suffix removed, as it impedes DNS resolution and prevented the machine from being recognized as localhost
 - Updated `Connect-SqlInstance` to reflect this change
 - Updated `Connect-DbaInstance` to reflect this change
 - Added `-SqlConnectionOnly` parameter to `Connect-DbaInstance`, causing the command to only return a connection object, without the full SMO server functionality

### CODE REVIEW

**Comment by potatoqualitee** [comment]
sorry, @FriedrichWeinmann there are strange failures that we didnt see before

**Comment by potatoqualitee** [comment]
It may not be an issue with yours (shouldnt be - it may be the new commit made to the appveyor lab repo, ill look)

**Comment by potatoqualitee** [comment]
merging because the failure is because the appveyor repo changed

**Comment by Stuart-Moore** [comment]
That commit should have just been 8 backup files. So shouldn't affect too
much.

If it is those move them into their own folder as it's probably just an
unfiltered gci or something

**Comment by potatoqualitee** [comment]
yep, got it taken care of, thank you

**Pull request merged**
