### PR TITLE
Added 2016 SP1 CU2

### PR DESCRIPTION
**Pull request by niphlod**
adds a ref to the latest CU available for 2016 SP1

### CODE REVIEW

**Comment by ClaudioESSilva** [comment]
@niphlod can we also add SQL Server 2012 SP3 CU8 to the list? 
https://support.microsoft.com/en-us/help/4013104/cumulative-update-8-for-sql-server-2012-sp3
Thanks!

**Comment by niphlod** [comment]
yes, we can!

**Comment by niphlod** [comment]
btw, I'm subscribed to the [tiger feed](https://blogs.msdn.microsoft.com/sqlreleaseservices/feed/) and probably they forgot to put those as "publish to rss", because relative articles are on the blog but not on the feed ...... come on!

**Comment by ctrlbold** [comment]
thanks much! will get this one out asap.

**Pull request merged**
