### PR TITLE
New/Set-DbaAgentSchedule - Fix usage of FrequencyInterval for daily interval

### LINKED ISSUE #7508: New/Set-DbaAgentSchedule - can't set FrequencyType to Daily and a recurrence interval of X day(s)
Via SSMS you can set a schedule with a FrequencyType of Daily and an a recurrence of X day(s).
If I try to set this via the New/Set-DbaAgentSchedule cmdlet, it always uses 1 day of recurrence for Daily.

Example:
New-DbaAgentSchedule -SqlInstance INSTANCENAME -Job 'JOBNAME' -Schedule 'SCHEDNAME' -FrequencyType Daily -FrequencyInterval 5 -StartTime 131313 -Force

Result should be: Occurs every 5 day(s) at 13:13:13. Schedule will be used starting on 7/07/2021.

### PR DESCRIPTION
**Pull request by andreasjordan**
## Type of Change

 - [x] Bug fix (non-breaking change, fixes #7508 )
 - [ ] New feature (non-breaking change, adds functionality, fixes # )
 - [ ] Breaking change (effects multiple commands or functionality, fixes # )
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1`)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Unit test is included
 - [ ] Documentation
 - [ ] Build system

### CODE REVIEW

**Comment by andreasjordan** [comment]
More work has to be done, see issue...

**Comment by potatoqualitee** [comment]
@andreasjordan - ive made the required changes (maybe? I copy/pasted from your comments). Hopefully that helps

**Comment by andreasjordan** [comment]
Thanks, @potatoqualitee . Maybe removing the numbers from the tab completion? Does not make sense to me to have them there.

**Comment by potatoqualitee** [comment]
I don't think it hurts and it gives people an idea of what is generally available

**Comment by andreasjordan** [comment]
Ok. Will have a look at the code again and align the tests and messages - and then open the PR for review.

**Comment by andreasjordan** [comment]
For -FrequencyType, New- accepts `'Once', 'OneTime', 'Daily', 'Weekly', 'Monthly', 'MonthlyRelative', 'AgentStart', 'AutoStart', 'IdleComputer', 'OnIdle'`, Set accepts `1, "Once", 4, "Daily", 8, "Weekly", 16, "Monthly", 32, "MonthlyRelative", 64, "AgentStart", 128, "IdleComputer"`.

I would like to take the one from New- to Set-, so not alowing the numbers anymore. Yes, would be a breaking change. What do you think?

**Comment by andreasjordan** [comment]
What PowerShell foo is `if (!$FrequencyType -or $FrequencyType) {` (line 175 of New-)? Isn't this totally useless?

**Comment by potatoqualitee** [comment]
Can we auto-convert for people instead of doing a breaking change? I'm unsure about that PS foo. It does not make sense to me since it's basically `$true` eh?

**Comment by andreasjordan** [comment]
The strings are converted to numbers because we need these. Then I leave the numbers but remove them from documentation.

**Comment by potatoqualitee** [comment]
This code makes sense to me and I think sander is busy

**Pull request merged**
