### PR TITLE
Restorework

### PR DESCRIPTION
**Pull request by Stuart-Moore**
New functionality - Moving Restore code to a modular format 

Changes proposed in this pull request:
 - Wrapper cmdlet Restore-SQLBackup
 - Which wraps around modules:
 * Get-DirectoryRestoreFiles
* Get-OlaRestoreFiles
* Get-FilteredRestoreFiles

More to follow as we need them

How to test this code: 
- [x] Grab some backups and try to restore them.
- [ ] 

Has been tested on minimum requirements:
- [x]  Powershell 3
- [x]  Windows 7
- [ ]  SQL Server 2000

Has been tested on maximum requirements:
- [ ]  SQL Server vNext
- [ ]  Windows 10
- [ ]  Azure Database

Tests for tester:
- [ ] Working/useful help content, including link to command on dbatools web site
- [ ] All examples work as advertised
- [x] Does not contain template content
- [x] Does not contain excessive/unnecessary amounts of comments
- [x] Works remotely
- [x] Works locally
- [ ] Works on lower versions or throws error specifying version not supported
- [x] Works with named instances
- [x] Works with clustered instances
- [ ] Handles offline/read only databases
- [ ] Supports multiple servers (at the command line or piped from Get-SqlRegisteredServerName)
- [ ] No un-handled errors which stop the command working with multiple servers

### CODE REVIEW

**Comment by dansqldba** [comment]
Hi @Stuart-Moore, I've assigned this to you because you appear to be pulling from your own fork into a dedicated branch in the dbatools repo.

**Comment by ctrlbold** [comment]
hey @Stuart-Moore, unfortunately, this PR has too many files in it. I tried to change the base to development but that didn't reduce the number. In addition, no changes can be made to the psd1 in any PR.

Also, internal files can be named with a generic convention (Get-Whatever) but exported files must be named Verb-DbaNoun.

**Comment by Stuart-Moore** [comment]
Morning @ctrlbold,
 How many files in a PR work? dropping the export from psd1 will drop by one, as will removing the Import-CSV code that's snuck it, but will still leave 9. I can do 2 PRs for the internal and external parts, so that'd be 8 and 1, Does that work for you?

I'll do the rename  as well.

**Comment by ctrlbold** [comment]
There's no max, really, but they must all be related and easy to test. It seems perhaps that the branch wasn't synced prior to the PR -- which was probably allowed because it's to a new branch. We dont allow non-synced PRs to Dev.

These two must be removed: 
functions/CsvSqlimport.ps1 <--- that one should be in its own PR if it wasnt already.
functions/Read-DbaBackupHeader.ps1 <-- that includes my changes that I made

And then this one has to follow PowerShell's naming convention
functions/Restore-DbaSqlBackup.ps1

The rest are great! Thanks so much. I can't wait to get into these.

**Comment by Stuart-Moore** [comment]
Will remerge after those changes.

I'm also making a changer to functions/Read-DbaBackupHeader.ps1 as I need to return the filename in the return object to make it easier to push into Restore-DBFromFilteredArray. 
vNext will also be returning position as well, so that'll be another change.

Restore-DBABackup.ps1 OK?

**Comment by ctrlbold** [comment]
Ah, ok, my bad! Yes, that one's good. I had to change string to object in another one of mine, I want to reexamine a bunch of our commands for opportunities to use objects instead of strings. I think it'll help with our pipeline programming.

**Comment by Stuart-Moore** [comment]
Yes, objects will make life a lot easier to keep common elements. ATM the Get-*RestoreFiles cmdlets are returning fileinfo objects, but if we end up with get-AzureBlocRestoreFiles then it's strings, so be good to be able to pipe all through the same process after that.

I'll start writing a blogpost for next tuesday now. Will do the functionality and then leave it till Monday night to say if it's dev/prod atm.

**Pull request merged**
