### PR TITLE
Adjust New-DbaAgentSchedule Parameter validation sets

### LINKED ISSUE #1570: New-DbaAgentSchedule - FrequencyType parameter showing numbers
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [ ] *feature* 
- [ x] *bug*:

When I try to create a new Agent Schedule, the parameter "FrequecyType" autocompletes numbers (1,128,16,32,4,64,8) and then the real Descriptive frequencies. I think numbers should be avoided for clarity of the command.

### PR DESCRIPTION
**Pull request by wsmelton**
Fixes #1570 

Changes proposed in this pull request:
 - Formatted command
 - Cleaned up help and corrected a few misspellings
 - Cleaned up param block, added validation sets that appeared to have been missed
 - Removed validation sets with numbers, only strings.
 - Cleaned up some of the warning messages to be a bit more clear in less words
 - Cleaned up use of Stop-Function, removed adding the exception message to the Message parameter as that is handled by Stop-Function when you pass the error record.
 - Also changed `-InnerErrorRecord` to just `-ErrorRecord` as that parameter was updated.

I only changed logic in the BEGIN block, but because I formatted the whole document it will appear I made many more changes than I really did.

### CODE REVIEW

**Comment by potatoqualitee** [comment]
hey @sanderstad - can you please take a look and approve?

**Comment by wsmelton** [comment]
On use of `-not $var` or `!$var` I'm not sure what our decision was on the style guide. @potatoqualitee  ?

**Comment by potatoqualitee** [comment]
Style guide left it open, but later discussions proved -not to be more reliable.

**Comment by potatoqualitee** [comment]
@sanderstad please approve when youve got time

**Pull request merged**
