### PR TITLE
 Get-DbaDatabaseFile compat fix

### PR DESCRIPTION
**Pull request by phantomflash47**
## Type of Change

 - [x] Bug fix (non-breaking change, fixes #<enter issue number>) - no issue number; reported on Slack
 - [ ] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
Fix:  Get-DbaDatabaseFile fails if database compatibility level differs "too much" from the SQL instance version -- enough so that different SQL code is required. This script uses 3 code variations:  SQL >=2008, 2005, and <2005. That has not changed; what is changed is how the script decides which variant to use.
Note: Only the single file Get-DbaDatabaseFile is affected. There are some other files here that are generated by Visual Studio, which I did not realize would show up on GitHub.

### Approach
Vary SQL code with DB compatibility level, not instance version
As part of the edits, moved invariant statements containing large amounts of SQL code outside the main loop, both for efficiency and program readability.

### Commands to test
Any of the examples in the help, if the DB compatibility level differs enough from the instance version.

### Learning
The error message returned by the original script was not very descriptive. It was necessary to dig deeper into the error details to discover the problem was an SQL syntax error. Then, only by examining the script's source code could it be determined that the wrong version of SQL was being used (in this case, SQL 2005 code directed at a database with only an SQL 2000 compatibility level, although running on a 2005 server instance).
Interesting note:  The new code needs Test-DbaDatabaseCompatibility, but that script was nonfunctional due to an unrelated bug. That was fixed by another party on Friday, 11/3.

### CODE REVIEW

**Comment by potatoqualitee** [comment]
Thanks so much, @phantomflash47 ! I'll test and merge 💯

**Comment by potatoqualitee** [comment]
actually, there are excess files. I'll have @FriedrichWeinmann take a look because it looks like library files.

**Comment by FriedrichWeinmann** [comment]
Heya, thanks for notifying me on that one @potatoqualitee 

Thank you for the effort on improving Get-DbaDatabaseFile @phantomflash47 , much appreciated.
However, as Chrissy noted, some additional file got accidentally mixed in. Artifacts from your using an older version of Visual Studio to peek at the library, I assume. Would you mind removing the following files from your PR?
```
bin/projects/dbatools/dbatools.v12.suo
dbatools.pssproj.user
dbatools.sln
```
I would also recommend installing Visual Studio 2017. The community edition is free and totally legal to use on free open source projects such as dbatools.

**Comment by potatoqualitee** [comment]
Thank you Fred! Phantom, I believe you can remove the files by just deleting them then committing the delete. If that is not the case and you continue to encounter issues, we can ask @ConstantineK for help 🌻

**Comment by potatoqualitee** [comment]
merging to phantom branch then cleaning up!

**Comment by phantomflash47** [comment]
Hi, I was not able to keep going on this without having to leave work yesterday, and being diverted to work on some other things for a while.

> However, as Chrissy noted, some additional file got accidentally mixed in.

Yes, that's why I told you about those extra files while filling out the information form at the top (under "Purpose"). I only discovered at the last minute they were there, and I didn't have time to deal with them before I had to leave for home.

> Artifacts from your using an older version of Visual Studio to peek at the library, I assume. 

Yes, I told you they were from Visual Studio. I did a lot more than "peek" with it; that's how I did the development. We all use VS 2013 here, so I figured might as well use it for PowerShell too, and also try out its Git integration feature (which took a while to figure out). Everyone has to use the same version of VS or else projects edited by one person may not be editable by someone else. (When editing certain older projects I've had to update them -- sometimes with a lot of manual effort.) At some point I'm sure we'll all move forward, but I'm pretty new here so I don't know how and when it's done. As recently as last year, in my previous job, I was using a "lite" version of VS 2010, and I'm still getting used to some of the things in 2013.

Ordinarily we track most of those VS files in our code management system (if they are lost some things can quit working), so I included them in my local Git repository. However I didn't intend on including them in the pull request to GitHub. I've never worked with Git or GitHub before, but I thought I could just specify the one file to go to GitHub. But GitHub didn't seem to ask me which files to include, as VS does when committing to the local repository.

So here's my (first) question:  Is that possible with GitHub, to simply omit some changed files, that exist in Git locally, from being included in a pull request?

P.S. I saw comments regarding branch and title that I don't understand. While feeling my way along, figuring out how to get all this to work together, I did see a pulldown menu for branches, but it didn't include Sqlcollaborative/development. So I chose development, which **was** in the list. (I was careful to change it from master, which your documentation says not to use.) I specified the title of the patch as "Fix to vary SQL code with DB compatibility level, not instance version."

**Comment by potatoqualitee** [comment]
hey @phantomflash47 - with regards to the branch, you did the PR properly 💯  I just created a new branch to merge your changes so that I could do the deleting for you. 

Ultimately, what you'd want to do is add those files to .gitignore (in my client, i right click, click ignore and it creates the .gitignore entry for me, then I create a PR for the modifications)

Your code has been merged and is now in 0.9.89 👍

**Comment by wsmelton** [comment]
Actually it would be good to just have our ignore file updated to ignore those as well. Since we have that project in the repo.

**Pull request merged**
