### PR TITLE
Backup-DbaDatabase: Switching from break/continue to Stop-Function

### LINKED ISSUE #3784: Backup-DbaDatabase disrupts script execution if server is not available
### Before submitting a bug report:

- [x] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [x] Verified this bug is not already reported in an issue
- [x] Verified errors are not related to permissions
- [x] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

## Steps to Reproduce
```powershell
& {
  Backup-DbaDatabase -SqlInstance 'localhost,12345' -Database nonexisting -backupfilename '\\myfilename\bak.bak'
  Write-Host "This will never appear on screen"
}
```

## Expected Behavior
Return a warning and the Write-Host output.

```
WARNING: [Backup-DbaDatabase][15:05:35] Cannot connect to localhost,12345
This will never appear on screen
```

## Actual Behavior
Any code after the Backup-DbaDatabase call is ignored, probably because the procedure exits the execution prematurely.
```
WARNING: [Backup-DbaDatabase][15:05:35] Cannot connect to localhost,12345
```

## Additional info
`-EnableException` switch never returns any errors, which is probably a related bug.

$Error[0] contains proper connection error exception:
```
PSMessageDetails      :
Exception             : System.Management.Automation.RuntimeException: Can't connect to localhost,12345: System.ComponentModel.Win32Exception
                        (0x80004005): The remote computer refused the network connection
TargetObject          : Can't connect to localhost,12345: System.ComponentModel.Win32Exception (0x80004005): The remote computer refused the network
                        connection
CategoryInfo          : OperationStopped: (Can't connect t...ork connection :String) [], RuntimeException
FullyQualifiedErrorId : Can't connect to localhost,12345: System.ComponentModel.Win32Exception (0x80004005): The remote computer refused the network
                        connection
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Connect-SqlInstance, <No file>: line 213
                        at Backup-DbaDatabase<Begin>, <No file>: line 180
                        at <ScriptBlock>, <No file>: line 2
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}
```

## Resolution:
Replace lines 183-184 of Backup-DbaDatabase with 
```
Stop-Function -Message "Cannot connect to $SqlInstance"
```
instead of Write-Message; **continue** <- probably the reason of the behavior - there is no loop to exit from at that point.
Will submit a PR shortly.

## Environmental data

 - PowerShell: 
PSVersion                      5.1.15063.1088
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.1088
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### PR DESCRIPTION
**Pull request by nvarscar**
## Type of Change

 - [x] Bug fix (non-breaking change, fixes #3784)
 - [ ] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
Fixing improper error handling that disrupts script execution

### Approach
Replacing break/continue with Stop-Function

### Commands to test
```
& {
  Backup-DbaDatabase -SqlInstance 'localhost,12345' -Database nonexisting -backupfilename '\\myfilename\bak.bak'
  Write-Host "This will now appear on screen"
}
```

### CODE REVIEW

**Comment by nvarscar** [comment]
oh. right. `return`. I forgot how to powershell.
`-Continue` are all there though.

**Comment by nvarscar** [comment]
I maybe overthinking this, but is it needed at all to pass all the `-EnableException $EnableException` into `Stop-Function`? Or they will be implicitly used from the parent function due to having the same variable name? If so, I'll add that too.

**Comment by potatoqualitee** [comment]
you do not need to pass it, it's inherited 👍  I'm so sorry I didn't notice your Continues! Please do use -Continue or it'll stop too soon if you pass in multiples. For instance, if you pass in 3 servers and cant access the first, it wont attempt the second or third.

**Comment by nvarscar** [comment]
I made sure that all the loops are covered by Continue (and non-loops are not). Codecov is throwing a tantrum because of the Azure tests. Do you guys need more negative testing on this? I can add something while I'm at it.

**Comment by potatoqualitee** [comment]
@nvarscar - no, it often throws a tantrum, even if you have a PR that's 100% tests. We ignore it for now ;) Thank you for your contribution! Other tests pass, will merge.

**Pull request merged**
