### PR TITLE
Test-DbaDbCompression fixes issue with non default schema

### LINKED ISSUE #4099: Test-DbaDbCompression - PercentScan and PercentUpdate fields are always NULL
PercentScan and PercentUpdate fields are always NULL resulting in incorrect recommendations for Compression Type. 

## Steps to Reproduce
 test-dbadbcompression SQLInstanceName | Out-GridView

## Expected Behavior
Expect to see numeric percentage values for PercentScan and PercentUpdate fields

## Actual Behavior
Always see NULL values for PercentScan and PercentUpdate fields

## Fix required
Issue is with the following statement, the join on "OBJECT_ID(tmp.TableName) = i.[object_id]" will never work as OBJECT_ID needs to be supplied SchemaName.TableName to work. I would suggest adding an object_id column to the temp table, testdbacompression, and then joining on the object_id fileds instead as shown below....

UPDATE ##testdbacompression
SET  [PercentScan] = i.range_scan_count * 100.0 / NULLIF((i.range_scan_count + i.leaf_insert_count + i.leaf_delete_count + i.leaf_update_count + i.leaf_page_merge_count + i.singleton_lookup_count), 0)
    ,[PercentUpdate] = i.leaf_update_count * 100.0 / NULLIF((i.range_scan_count + i.leaf_insert_count + i.leaf_delete_count + i.leaf_update_count + i.leaf_page_merge_count + i.singleton_lookup_count), 0)
FROM sys.dm_db_index_operational_stats(db_id(), NULL, NULL, NULL) i
INNER JOIN ##testdbacompression tmp ON OBJECT_ID(tmp.TableName) = i.[object_id]
    AND tmp.IndexID = i.index_id;

should be changed to this.....

UPDATE ##testdbacompression
SET  [PercentScan] = i.range_scan_count * 100.0 / NULLIF((i.range_scan_count + i.leaf_insert_count + i.leaf_delete_count + i.leaf_update_count + i.leaf_page_merge_count + i.singleton_lookup_count), 0)
    ,[PercentUpdate] = i.leaf_update_count * 100.0 / NULLIF((i.range_scan_count + i.leaf_insert_count + i.leaf_delete_count + i.leaf_update_count + i.leaf_page_merge_count + i.singleton_lookup_count), 0)
FROM sys.dm_db_index_operational_stats(db_id(), NULL, NULL, NULL) i
INNER JOIN ##testdbacompression tmp ON tmp.ObjectID = i.[object_id]
    AND tmp.IndexID = i.index_id;

## Environmental data
 - PowerShell: 

Name                           Value
----                           -----
PSVersion                      5.1.14409.1012
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1012
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

 - - SQL Server: 
Microsoft SQL Server 2016 (SP1-CU7-GDR) (KB4057119) - 13.0.4466.4 (X64)   Dec 22 2017 11:25:00   Copyright (c) Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2012 R2 Standard 6.3 <X64> (Build 9600: )

### PR DESCRIPTION
**Pull request by jpomfret**
## Type of Change

 - [X] Bug fix (non-breaking change, fixes #4099 #3698 )
 - [ ] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [X] Pester test is included
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
- #4099 - bad join to get index usage for objects not in dbo schema, fixed this.  Also changed logic so PercentScan and PercentUpdate return 0 instead of NULLs if there is no usage.  Added pester test to ensure this is the case.
- #3698 - Moved the logic out of the main SQL statement, now the version is determined in PowerShell and only valid SQL for that version is executed.

### CODE REVIEW

**Comment by potatoqualitee** [comment]
i'll fix the indents issue brb

**Comment by jpomfret** [comment]
haha @potatoqualitee I didn't see that...  I pushed one with them fixed, sorry if that caused a conflict 😃

**Comment by potatoqualitee** [comment]
np! mm something is up? can you check out the tabs? got another failure

**Comment by jpomfret** [comment]
sure will...

**Comment by potatoqualitee** [comment]
ty! 🙇

**Comment by potatoqualitee** [comment]
yay sorry, it was that the test hand't run yet

**Pull request merged**
