### PR TITLE
Speedup Copy-DbaDatabase

### PR DESCRIPTION
**Pull request by alevyinroc**
## Type of Change

 - [ ] Bug fix (non-breaking change, fixes #<enter issue number>)
 - [X] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
On instances with large numbers of databases, the call to `$destServer.databases.refresh()` can take a long time but only the new database needs to be refreshed (for comparison against properties of the source DB)

### Approach
Replaced refreshing all databases on the instance with getting a reference to just the new database that was restored.

On my test instance with 300+ databases, this was approx. a 10% speed improvement.

### Commands to test
`Copy-DbaDatabase`

### CODE REVIEW

**Comment by potatoqualitee** [comment]
excellent, thank you so much, Andy!

**Comment by wsmelton** [comment]
Just noting that the test did not actually run on your commit @alevyinroc . Appveyor seems to have 🐩 out.

I'm curious to know if you tested this against your larger instance and what the time difference really is?

`Get-DbaDatabase` does good bit more than just doing `$destServer.Databases[$currentDB].Refresh()`

**Comment by alevyinroc** [comment]
@wsmelton I didn't have an opportunity to test it against the big one on Friday but I will give it a shot in the next couple days.

**Comment by alevyinroc** [comment]
@wsmelton on my big instance, I got 4 minutes with the new version and 7:50 with the original. Th database I copied is about 230MB.

**Pull request merged**
