### PR TITLE
Install-DbaInstance

### PR DESCRIPTION
**Pull request by potatoqualitee**
putting this back on my radar

### CODE REVIEW

**Comment by potatoqualitee** [comment]
hey @nvarscar, any additional info i can give you?

```powershell
12.83 s] C:\WINDOWS\system32> Install-DbaInstance -ComputerName sql2017 -InstanceName twitch -Version 2017 -Path D:\ -Credential base\twitch -Verbose
VERBOSE: [02:17:36][Resolve-DbaNetworkName] Resolving sql2017 using .NET.Dns GetHostEntry
VERBOSE: [02:17:36][Resolve-DbaNetworkName] Resolving 10.0.1.172 using .NET.Dns GetHostByAddress
VERBOSE: [02:17:36][Get-DbaCmObject] Configuration loaded | Cache disabled: False
VERBOSE: [02:17:36][Get-DbaCmObject] [sql2017] Retrieving Management Information
VERBOSE: [02:17:36][Get-DbaCmObject] [sql2017] Accessing computer using Cim over WinRM
VERBOSE: [02:17:36][Get-DbaCmObject] [sql2017] Accessing computer using Cim over WinRM - Success
VERBOSE: [02:17:36][Resolve-DbaNetworkName] Resolving sql2017.base.local using .NET.Dns GetHostEntry
VERBOSE: [02:17:36][Get-DbaCmObject] Configuration loaded | Cache disabled: False
VERBOSE: [02:17:36][Get-DbaCmObject] [sql2017.base.local] Retrieving Management Information
VERBOSE: [02:17:36][Get-DbaCmObject] [sql2017.base.local] Accessing computer using Cim over WinRM
VERBOSE: [02:17:36][Get-DbaCmObject] [sql2017.base.local] Accessing computer using Cim over WinRM - Success
VERBOSE: [02:17:36][Install-DbaInstance] Attempting to configure CredSSP for remote connections
VERBOSE: [02:17:36][Initialize-CredSSP] Configuring remote host to use CredSSP
VERBOSE: [02:17:36][Install-DbaInstance] Looking for installation files in D:\ on remote machine sql2017.base.local
VERBOSE: [02:17:36][Get-DbaCmObject] Configuration loaded | Cache disabled: False
VERBOSE: [02:17:36][Get-DbaCmObject] [sql2017.base.local] Retrieving Management Information
VERBOSE: [02:17:36][Get-DbaCmObject] [sql2017.base.local] Accessing computer using Cim over WinRM
VERBOSE: [02:17:37][Get-DbaCmObject] [sql2017.base.local] Accessing computer using Cim over WinRM - Success
VERBOSE: [02:17:37][Write-IniFile] Writing Ini file to C:\Users\ctrlb.BASE\AppData\Local\Temp\Configuration_sql2017.base.local_2017.ini

Confirm
Are you sure you want to perform this action?
Performing the operation "Install 2017 from D:\setup.exe" on target "sql2017.base.local".
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"): y
VERBOSE: [02:17:40][Install-DbaInstance] Copying C:\Users\ctrlb.BASE\AppData\Local\Temp\Configuration_sql2017.base.local_2017.ini to remote machine into
C:\Users\twitch\AppData\Local\Temp\
VERBOSE: [02:17:40][Install-DbaInstance] Setup starting from D:\setup.exe
VERBOSE: [02:17:40][Invoke-Program] Starting process [D:\setup.exe] with arguments [/IACCEPTSQLSERVERLICENSETERMS
/CONFIGURATIONFILE="C:\Users\ctrlb.BASE\AppData\Local\Temp\Configuration_sql2017.base.local_2017.ini"] on sql2017.base.local through Credssp protocol
VERBOSE: [02:17:42][Get-DbaCmObject] Configuration loaded | Cache disabled: False
VERBOSE: [02:17:42][Get-DbaCmObject] [sql2017.base.local] Retrieving Management Information
VERBOSE: [02:17:42][Get-DbaCmObject] [sql2017.base.local] Accessing computer using Cim over WinRM
VERBOSE: [02:17:42][Get-DbaCmObject] [sql2017.base.local] Accessing computer using Cim over WinRM - Success


ComputerName : sql2017.base.local
InstanceName : twitch
Version      : 2017
Port         :
Successful   : True
Restarted    : False
Installer    : D:\setup.exe
ExitCode     : 0
Notes        : {}



[8.59 s] C:\WINDOWS\system32>
```

**Comment by potatoqualitee** [comment]
here are the logs 🙇 

[install.zip](https://github.com/sqlcollaborative/dbatools/files/2948976/install.zip)

**Comment by nvarscar** [comment]
From what I see, setup.exe returned exitcode 0 immediately. Are there any logs in C:\Program Files\Microsoft SQL Server\140\Setup Bootstrap\Log\summary.txt or in the latest details.txt one lever deeper? 
I wonder, what it didn't like and why did it return a success exit code.

**Comment by potatoqualitee** [comment]
this is the only thing ive got, hope it helps

[Detail_LandingPage.txt](https://github.com/sqlcollaborative/dbatools/files/2950150/Detail_LandingPage.txt)

**Comment by potatoqualitee** [comment]
[Summary.txt](https://github.com/sqlcollaborative/dbatools/files/2950152/Summary.txt)

summary hasnt been modified since 2018 :/ 

Note that this windows server has an isntance installed already and i am installing an additional one.

**Comment by potatoqualitee** [comment]
yay looks like the config file does not exist. is it possible it' looking on workstationx and executing on sql2017?

**Comment by nvarscar** [comment]
Yeah, for some reason it doesn’t see the config, perhaps the copy failed? Or maybe it was two different users and config ended up in a different profile? I’ll double check the code to see what could’ve gone wrong. And thanks for testing!

**Comment by nvarscar** [comment]
Found the issue, will test today and release along with multi-threading improvements

**Comment by potatoqualitee** [comment]
Yessssssssssssssss!

**Comment by potatoqualitee** [comment]
aw man, i tagged the wrong one

**Comment by nvarscar** [comment]
okay, if this one doesn't fail, we should be golden 🥇 
- added Invoke-DbaAdvancedInstall function to support parallelism
- fixed configuration file paths when calling the setup
- added progressbars

**Comment by potatoqualitee** [comment]
that'd bee amaaazing, lemme do a couple things here then ill test

**Comment by nvarscar** [comment]
oh yeah. I forgot to remove the configuration.ini templates - will do that right away. We don't need them anymore, configs are dynamic now.

**Comment by potatoqualitee** [comment]
Niceee!

**Comment by potatoqualitee** [comment]
fiya! 

image


image


going to merge this bad boy when the tests pass 🍌  💃  🍌  💃 !

thank you so very much

**Comment by nvarscar** [comment]
Noice 🤞 just in case, there are 2 functions to add to the psd1, not one.

**Comment by potatoqualitee** [comment]
pass due to other formatted file, thanks much!

**Comment by potatoqualitee** [comment]
got em

**Pull request merged**
