### PR TITLE
Dismount-DbaDatabase, my bad

### PR DESCRIPTION
**Pull request by niphlod**
too much globals will kill you

### CODE REVIEW

**Comment by potatoqualitee** [comment]
merci :bowtie:  I'll let the test finish then merge

**Comment by niphlod** [comment]
wait, a complete ran did not happen yet

**Comment by niphlod** [comment]
groan.

**Comment by niphlod** [comment]
@potatoqualitee : please merge so tests can resume. I need to investigate but I don't wanna crop all the queued tests

**Comment by potatoqualitee** [comment]
weird af

**Comment by potatoqualitee** [comment]
thanks bud!

**Pull request merged**
