### PR TITLE
Adding changes to eliminate duplicate named instances

### LINKED ISSUE #6003: Get-DbaService may return duplicate results when multiple SSRS instances exist
### Environmental information

```
#### PowerShell version:
Name                           Value                                                                                                                                                                  
----                           -----                                                                                                                                                                  
PSVersion                      5.1.14409.1018                                                                                                                                                         
PSEdition                      Desktop                                                                                                                                                                
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                
BuildVersion                   10.0.14409.1018                                                                                                                                                        
CLRVersion                     4.0.30319.42000                                                                                                                                                        
WSManStackVersion              3.0                                                                                                                                                                    
PSRemotingProtocolVersion      2.3                                                                                                                                                                    
SerializationVersion           1.1.0.1                                                                                                                                                                

#### dbatools Module version:
Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.38\dbatools.psd1
Version : 1.0.38
```

```powershell
PS C:\Windows\system32> Get-Culture
LCID             Name             DisplayName                                                                                                                                                         
----             ----             -----------                                                                                                                                                         
1033             en-US            English (United States) 
```

#### SQL Server: 

```sql
Microsoft SQL Server Reporting Services 
© 2016 Microsoft 
Version 13.0.4446.0 
```

#### Host used

- [x] powershell.exe
- [x] ISE
- [ ] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [x] Still buggy in powershell.exe

#### Errors Received

```
PSMessageDetails      : 
Exception             : System.Management.Automation.MethodInvocationException: Exception calling "QueryCimRMInstance" with "4" argument(s): "WinRM 
                        cannot process the request. The following error with errorcode 0x80090322 occurred while using Kerberos authentication: An 
                        unknown security error occurred.  
                         Possible causes are:
                          -The user name or password specified are invalid.
                          -Kerberos is used when no authentication method and no user name are specified.
                          -Kerberos accepts domain user names, but not local user names.
                          -The Service Principal Name (SPN) for the remote computer name and port does not exist.
                          -The client and remote computers are in different domains and there is no trust between the two domains.
                         After checking for the above issues, try the following:
                          -Check the Event Viewer for events related to authentication.
                          -Change the authentication method; add the destination computer to the WinRM TrustedHosts configuration setting or use 
                        HTTPS transport.
                         Note that computers in the TrustedHosts list might not be authenticated.
                           -For more information about WinRM configuration, run the following command: winrm help config." ---> 
                        Microsoft.Management.Infrastructure.CimException: WinRM cannot process the request. The following error with errorcode 
                        0x80090322 occurred while using Kerberos authentication: An unknown security error occurred.  
                         Possible causes are:
                          -The user name or password specified are invalid.
                          -Kerberos is used when no authentication method and no user name are specified.
                          -Kerberos accepts domain user names, but not local user names.
                          -The Service Principal Name (SPN) for the remote computer name and port does not exist.
                          -The client and remote computers are in different domains and there is no trust between the two domains.
                         After checking for the above issues, try the following:
                          -Check the Event Viewer for events related to authentication.
                          -Change the authentication method; add the destination computer to the WinRM TrustedHosts configuration setting or use 
                        HTTPS transport.
                         Note that computers in the TrustedHosts list might not be authenticated.
                           -For more information about WinRM configuration, run the following command: winrm help config.
                           at Microsoft.Management.Infrastructure.Internal.Operations.CimSyncEnumeratorBase`1.MoveNext()
                           at Sqlcollaborative.Dbatools.Connection.ManagementConnection.QueryCimRMInstance(PSCredential Credential, String Query, 
                        String Dialect, String Namespace) in 
                        D:\Code\Github\dbatools\bin\projects\dbatools\dbatools\Connection\ManagementConnection.cs:line 907
                           at CallSite.Target(Closure , CallSite , Object , Object , String , String , String )
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception 
                        exception)
                           at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
TargetObject          : 
CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
FullyQualifiedErrorId : CimException
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Get-DbaCmObject<Process>, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.38\allcommands.ps1: line 20031
                        at Get-DbaReportingService<Process>, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.38\allcommands.ps1: line 74388
                        at Get-DbaService<Process>, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.38\allcommands.ps1: line 33322
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}
```

#### Steps to Reproduce

When MyServer exists as a server with multiple instances of SSRS 2016:
```
Get-DbaService -ComputerName MyServer
```

#### Expected Behavior

Expected behavior is a result set containing one record per SSRS instance on the server.

#### Actual Behavior

Actual behavior is a result set containing multiple records per SSRS instance on the server.  The number of duplicates may be influenced by the instance count.  For example, if three instances of SSRS are installed, the result set may contain three copies of each instance service record, as shown in example below.
```powershell
PS C:\Users\MyUserName> Get-DbaService -ComputerName MyServer -Verbose | ft

VERBOSE: [07:43:55][Resolve-DbaNetworkName] Resolving MyServer using .NET.Dns GetHostEntry
VERBOSE: [07:43:56][Resolve-DbaNetworkName] Resolving x.x.x.x using .NET.Dns GetHostByAddress
VERBOSE: [07:43:56][Get-DbaCmObject] Configuration loaded | Cache disabled: False
VERBOSE: [07:43:56][Get-DbaCmObject] [MyServer] Retrieving Management Information
VERBOSE: [07:43:56][Get-DbaCmObject] [MyServer] Accessing computer using Cim over WinRM
VERBOSE: [07:43:56][Get-DbaCmObject] [MyServer] Accessing computer using Cim over WinRM - Success
VERBOSE: [07:43:56][Resolve-DbaNetworkName] Resolving MyServer.MyDomain using .NET.Dns GetHostEntry
VERBOSE: [07:43:56][Get-DbaService] Getting SQL Reporting Server services on MyServer.MyDomain
VERBOSE: [07:43:56][Get-DbaReportingService] Getting Reporting Server namespace on MyServer.MyDomain
VERBOSE: [07:43:56][Get-DbaCmObject] Configuration loaded | Cache disabled: False
VERBOSE: [07:43:56][Get-DbaCmObject] [MyServer.MyDomain] Retrieving Management Information
VERBOSE: [07:43:56][Get-DbaCmObject] [MyServer.MyDomain] Accessing computer using Cim over DCOM
VERBOSE: [07:43:56][Get-DbaCmObject] [MyServer.MyDomain] Accessing computer using Cim over DCOM - Success
VERBOSE: [07:43:56][Get-DbaReportingService] Getting version from the namespace RS_MYAPPDEV on MyServer.MyDomain.
VERBOSE: [07:43:56][Get-DbaCmObject] Configuration loaded | Cache disabled: False
VERBOSE: [07:43:56][Get-DbaCmObject] [MyServer.MyDomain] Retrieving Management Information
VERBOSE: [07:43:56][Get-DbaCmObject] [MyServer.MyDomain] Accessing computer using Cim over DCOM
VERBOSE: [07:43:56][Get-DbaCmObject] [MyServer.MyDomain] Accessing computer using Cim over DCOM - Success
VERBOSE: [07:43:56][Get-DbaCmObject] Configuration loaded | Cache disabled: False
VERBOSE: [07:43:56][Get-DbaCmObject] [MyServer.MyDomain] Retrieving Management Information
VERBOSE: [07:43:56][Get-DbaCmObject] [MyServer.MyDomain] Accessing computer using Cim over DCOM
VERBOSE: [07:43:56][Get-DbaCmObject] [MyServer.MyDomain] Accessing computer using Cim over DCOM - Success
VERBOSE: [07:43:56][Get-DbaCmObject] Configuration loaded | Cache disabled: False
VERBOSE: [07:43:56][Get-DbaCmObject] [MyServer.MyDomain] Retrieving Management Information
VERBOSE: [07:43:56][Get-DbaCmObject] [MyServer.MyDomain] Accessing computer using Cim over DCOM
VERBOSE: [07:43:56][Get-DbaCmObject] [MyServer.MyDomain] Accessing computer using Cim over DCOM - Success
VERBOSE: [07:43:56][Get-DbaCmObject] Configuration loaded | Cache disabled: False
VERBOSE: [07:43:56][Get-DbaCmObject] [MyServer.MyDomain] Retrieving Management Information
VERBOSE: [07:43:56][Get-DbaCmObject] [MyServer.MyDomain] Accessing computer using Cim over DCOM
VERBOSE: [07:43:56][Get-DbaCmObject] [MyServer.MyDomain] Accessing computer using Cim over DCOM - Success
VERBOSE: [07:43:56][Get-DbaCmObject] Configuration loaded | Cache disabled: False
VERBOSE: [07:43:56][Get-DbaCmObject] [MyServer.MyDomain] Retrieving Management Information
VERBOSE: [07:43:56][Get-DbaCmObject] [MyServer.MyDomain] Accessing computer using Cim over DCOM
VERBOSE: [07:43:56][Get-DbaCmObject] [MyServer.MyDomain] Accessing computer using Cim over DCOM - Success
VERBOSE: [07:43:56][Get-DbaReportingService] Getting version from the namespace RS_MSSQLSERVER on MyServer.MyDomain.
VERBOSE: [07:43:56][Get-DbaCmObject] Configuration loaded | Cache disabled: False
VERBOSE: [07:43:57][Get-DbaCmObject] [MyServer.MyDomain] Retrieving Management Information
VERBOSE: [07:43:57][Get-DbaCmObject] [MyServer.MyDomain] Accessing computer using Cim over DCOM
VERBOSE: [07:43:57][Get-DbaCmObject] [MyServer.MyDomain] Accessing computer using Cim over DCOM - Success
VERBOSE: [07:43:57][Get-DbaCmObject] Configuration loaded | Cache disabled: False
VERBOSE: [07:43:57][Get-DbaCmObject] [MyServer.MyDomain] Retrieving Management Information
VERBOSE: [07:43:57][Get-DbaCmObject] [MyServer.MyDomain] Accessing computer using Cim over DCOM
VERBOSE: [07:43:57][Get-DbaCmObject] [MyServer.MyDomain] Accessing computer using Cim over DCOM - Success
VERBOSE: [07:43:57][Get-DbaCmObject] Configuration loaded | Cache disabled: False
VERBOSE: [07:43:57][Get-DbaCmObject] [MyServer.MyDomain] Retrieving Management Information
VERBOSE: [07:43:57][Get-DbaCmObject] [MyServer.MyDomain] Accessing computer using Cim over DCOM
VERBOSE: [07:43:57][Get-DbaCmObject] [MyServer.MyDomain] Accessing computer using Cim over DCOM - Success
VERBOSE: [07:43:57][Get-DbaCmObject] Configuration loaded | Cache disabled: False
VERBOSE: [07:43:57][Get-DbaCmObject] [MyServer.MyDomain] Retrieving Management Information
VERBOSE: [07:43:57][Get-DbaCmObject] [MyServer.MyDomain] Accessing computer using Cim over DCOM
VERBOSE: [07:43:57][Get-DbaCmObject] [MyServer.MyDomain] Accessing computer using Cim over DCOM - Success
VERBOSE: [07:43:57][Get-DbaCmObject] Configuration loaded | Cache disabled: False
VERBOSE: [07:43:57][Get-DbaCmObject] [MyServer.MyDomain] Retrieving Management Information
VERBOSE: [07:43:57][Get-DbaCmObject] [MyServer.MyDomain] Accessing computer using Cim over DCOM
VERBOSE: [07:43:57][Get-DbaCmObject] [MyServer.MyDomain] Accessing computer using Cim over DCOM - Success
VERBOSE: [07:43:57][Get-DbaReportingService] Getting version from the namespace RS_MYAPPTST on MyServer.MyDomain.
VERBOSE: [07:43:57][Get-DbaCmObject] Configuration loaded | Cache disabled: False
VERBOSE: [07:43:57][Get-DbaCmObject] [MyServer.MyDomain] Retrieving Management Information
VERBOSE: [07:43:57][Get-DbaCmObject] [MyServer.MyDomain] Accessing computer using Cim over DCOM
VERBOSE: [07:43:57][Get-DbaCmObject] [MyServer.MyDomain] Accessing computer using Cim over DCOM - Success
VERBOSE: [07:43:57][Get-DbaCmObject] Configuration loaded | Cache disabled: False
VERBOSE: [07:43:57][Get-DbaCmObject] [MyServer.MyDomain] Retrieving Management Information
VERBOSE: [07:43:57][Get-DbaCmObject] [MyServer.MyDomain] Accessing computer using Cim over DCOM
VERBOSE: [07:43:57][Get-DbaCmObject] [MyServer.MyDomain] Accessing computer using Cim over DCOM - Success
VERBOSE: [07:43:57][Get-DbaCmObject] Configuration loaded | Cache disabled: False
VERBOSE: [07:43:57][Get-DbaCmObject] [MyServer.MyDomain] Retrieving Management Information
VERBOSE: [07:43:57][Get-DbaCmObject] [MyServer.MyDomain] Accessing computer using Cim over DCOM
VERBOSE: [07:43:58][Get-DbaCmObject] [MyServer.MyDomain] Accessing computer using Cim over DCOM - Success
VERBOSE: [07:43:58][Get-DbaCmObject] Configuration loaded | Cache disabled: False
VERBOSE: [07:43:58][Get-DbaCmObject] [MyServer.MyDomain] Retrieving Management Information
VERBOSE: [07:43:58][Get-DbaCmObject] [MyServer.MyDomain] Accessing computer using Cim over DCOM
VERBOSE: [07:43:58][Get-DbaCmObject] [MyServer.MyDomain] Accessing computer using Cim over DCOM - Success
VERBOSE: [07:43:58][Get-DbaCmObject] Configuration loaded | Cache disabled: False
VERBOSE: [07:43:58][Get-DbaCmObject] [MyServer.MyDomain] Retrieving Management Information
VERBOSE: [07:43:58][Get-DbaCmObject] [MyServer.MyDomain] Accessing computer using Cim over DCOM
VERBOSE: [07:43:58][Get-DbaCmObject] [MyServer.MyDomain] Accessing computer using Cim over DCOM - Success
VERBOSE: [07:43:58][Get-DbaService] Getting SQL Server namespace on MyServer.MyDomain
VERBOSE: [07:43:58][Get-DbaCmObject] Configuration loaded | Cache disabled: False
VERBOSE: [07:43:58][Get-DbaCmObject] [MyServer.MyDomain] Retrieving Management Information
VERBOSE: [07:43:58][Get-DbaCmObject] [MyServer.MyDomain] Accessing computer using Cim over DCOM
VERBOSE: [07:43:58][Get-DbaCmObject] [MyServer.MyDomain] Accessing computer using Cim over DCOM - Success
VERBOSE: [07:43:58][Get-DbaService] Getting Cim class SqlService in Namespace ComputerManagement13 on MyServer.MyDomain.
VERBOSE: [07:43:58][Get-DbaCmObject] Configuration loaded | Cache disabled: False
VERBOSE: [07:43:58][Get-DbaCmObject] [MyServer.MyDomain] Retrieving Management Information
VERBOSE: [07:43:58][Get-DbaCmObject] [MyServer.MyDomain] Accessing computer using Cim over DCOM
VERBOSE: [07:43:58][Get-DbaCmObject] [MyServer.MyDomain] Accessing computer using Cim over DCOM - Success


ComputerName ServiceName           ServiceType InstanceName DisplayName                                 StartName               State   StartMode
------------ -----------           ----------- ------------ -----------                                 ---------               -----   ---------
MyServer     ReportServer          SSRS        MSSQLSERVER  SQL Server Reporting Services (MSSQLSERVER) MyDomain\SQLSSRSMyServer Running Automatic
MyServer     ReportServer$MYAPPDEV SSRS        MYAPPDEV     SQL Server Reporting Services (MYAPPDEV)    MyDomain\SQLSSRSMYAPPDEV Running Automatic
MyServer     ReportServer$MYAPPTST SSRS        MYAPPTST     SQL Server Reporting Services (MYAPPTST)    MyDomain\SQLSSRSMYAPPTST Running Automatic
MyServer     ReportServer          SSRS        MSSQLSERVER  SQL Server Reporting Services (MSSQLSERVER) MyDomain\SQLSSRSMyServer Running Automatic
MyServer     ReportServer$MYAPPDEV SSRS        MYAPPDEV     SQL Server Reporting Services (MYAPPDEV)    MyDomain\SQLSSRSMYAPPDEV Running Automatic
MyServer     ReportServer$MYAPPTST SSRS        MYAPPTST     SQL Server Reporting Services (MYAPPTST)    MyDomain\SQLSSRSMYAPPTST Running Automatic
MyServer     ReportServer          SSRS        MSSQLSERVER  SQL Server Reporting Services (MSSQLSERVER) MyDomain\SQLSSRSMyServer Running Automatic
MyServer     ReportServer$MYAPPDEV SSRS        MYAPPDEV     SQL Server Reporting Services (MYAPPDEV)    MyDomain\SQLSSRSMYAPPDEV Running Automatic
MyServer     ReportServer$MYAPPTST SSRS        MYAPPTST     SQL Server Reporting Services (MYAPPTST)    MyDomain\SQLSSRSMYAPPTST Running Automatic

```

### PR DESCRIPTION
**Pull request by sqllensman**
## Type of Change

 - [X] Bug fix (non-breaking change, fixes #6003)
 - [ ] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
Fixes issue in internal function Get-DbaReportingService that can result in duplicate results when more than one instance of SSRS is present on a machine

### Approach
The namespaces used to obtain Reporting Service information seem to have a bug and can return information for all instances even when called for particular instance
Added a Server level array to test and exclude duplicate information

### Commands to test
Get-DbaService 
Get-DbaReportingService (internal function called by Get-DbaService

### CODE REVIEW

**Comment by potatoqualitee** [comment]
Thanks so much Patrick! can you include some screenshots? I dont have the enviornment to test

**Comment by sqllensman** [comment]
Results of current code for Server with 2 instances of SSRS

Version-1 0 39

**Comment by potatoqualitee** [comment]
looks fab, thank you! 💯

**Comment by sqllensman** [comment]
Results of revised code

FixedVersion

**Pull request merged**
