### PR TITLE
Adjust column reference in Get-DbaDatabaseFile and Invoke-DbaBalanceDataFiles

### LINKED ISSUE #3233: xp_fixeddrives does not return the same output in french vs English SQL server installation
When xp_fixeddrives is used, we need to take the second column instead of using the column names. Column name 'MB free' is 'Mo disponible' in French.

I found xp_fixeddrives to be used in 2 files in the module. I want to fix them to refer to the second column instead of using 'MB free'

### General Troubleshooting steps

- [x] Verified running the latest release of dbatools?
- [x] Verified errors are not related to permissions?
- [x] Can duplicate in new/clean PowerShell session (clean = `powershell -NoProfile`)?

### Version Information
 - Operating System (Name|Version): 
 - PowerShell Version: 
 - SQL Server (Edition|Version): 

## Steps to Reproduce

 - [ ] Attach any screenshots (if possible/allowed)
 - [ ] Attach logs generated by dbatools (`Get-DbatoolsLog`)
 - [ ] Attach output from PowerShell console (if possible/allowed)

### Problem to solve
Select-Object : Property "MB Free" cannot be found.

### PR DESCRIPTION
**Pull request by pollusb**
## Type of Change

 - [x] Bug fix (non-breaking change, fixes #3233)
 - [ ] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
xp_fixeddrives return a different column name in French version os SQL Server. So running these 2 command would return an error:
- Get-DbaDatabaseFile
- Invoke-DbaBalanceDataFiles

### Approach
Instead of refering to 'MB free' it refers to the name of the second column of xp_fixeddrives result.

### Commands to test
The error will only apear when in non-english version of SQL Server.

### Screenshots
Might be able to provide them tomorrow

### CODE REVIEW

**Comment by wsmelton** [comment]
Looks like your changes are causing the test for the invoke command to fail.

**Comment by pollusb** [comment]
I don't know what to say. I reverted the change on Invoke-DbaBalanceDataFiles and now checks are fines. But what I did should work. I changed one line with 3 lines below. Result is the same : as shown in variable $diskFreeSpace. OK, we also have 2 new variables with my code but this shouldn't break the test? How can I debug further? I need to start the test locally?

image

**Comment by potatoqualitee** [comment]
I'd agree, in theory it should be working. Let me see what happens when I run your code against my local

**Comment by wsmelton** [comment]
There are extra files in this PR now did you modify all of those?

**Comment by wsmelton** [comment]
It is failing because of this section in `Invoke-DbaBalanceDataFiles`

```powershell
                        if ($d.SizeMB -gt $freeSpace.FreeMB) {
                            # Set the success flag
                            $success = $false

                            Stop-Function -Message "The available space may not be sufficient to continue the process. Please use -Force to try anyway." -Target $instance -Continue
                            return
```

So it is associated with the command itself actually not performing the task properly on the database in Appveyor. It works successful on my local instance.

**Comment by potatoqualitee** [comment]
he didn't, those were from other PRs - im never really sure why github does this sometimes. @pollusb - can you sync with the latest dev branch, see if it removes those extra files, svp?

**Comment by pollusb** [comment]
Hi Chrissy, what is the git command to sync ?


*Livre "apprendre
<https://books.google.ca/books?id=zr_ZMgEACAAJ&dq=Apprendre+%C3%A0+donner&hl=fr&sa=X&redir_esc=y>"
à donner (moi-même)*
-------------------------------------------------------
*Pollus Brodeur*
SQL Server Expert
www.pollusbrodeur.com
514.803.4824

2018-02-17 5:56 GMT-05:00 Chrissy LeMaire <notifications@github.com>:

**Comment by potatoqualitee** [comment]
I only know how to do it in GitHub Desktop :( - @wsmelton or @ConstantineK can you guys help a fella out?

**Comment by pollusb** [comment]
I use both GitHub and git. So please tell me how in github

Le 17 févr. 2018 09:12, "Chrissy LeMaire" <notifications@github.com> a
écrit :

**Comment by ConstantineK** [comment]
I updated his local dev but we still have a merge conflict, going to pull from the other side and see what's up.

**Comment by ConstantineK** [comment]
Merge works, probably just waiting for the appveyor stuff to finish before it checks again. 

```
mac-n-chease:pollus ck$ git clone git@github.com:sqlcollaborative/dbatools.git
Cloning into 'dbatools'...
remote: Counting objects: 45025, done.
remote: Compressing objects: 100% (49/49), done.
remote: Total 45025 (delta 39), reused 57 (delta 31), pack-reused 44945
Receiving objects: 100% (45025/45025), 70.46 MiB | 1.05 MiB/s, done.
Resolving deltas: 100% (32837/32837), done.
mac-n-chease:pollus ck$ cd dbatools
mac-n-chease:dbatools ck$ git checkout development
Branch development set up to track remote branch development from origin.
Switched to a new branch 'development'
mac-n-chease:dbatools ck$ git checkout -b pollusb-development 
Switched to a new branch 'pollusb-development'
mac-n-chease:dbatools ck$ git pull https://github.com/pollusb/dbatools.git development
remote: Counting objects: 27, done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 27 (delta 20), reused 23 (delta 16), pack-reused 0
Unpacking objects: 100% (27/27), done.
From https://github.com/pollusb/dbatools
 * branch              development -> FETCH_HEAD
Updating 8741290d..57db0b39
Fast-forward
 functions/Get-DbaDatabaseFile.ps1        | 3 ++-
 functions/Invoke-DbaBalanceDataFiles.ps1 | 5 ++++-
 2 files changed, 6 insertions(+), 2 deletions(-)
mac-n-chease:dbatools ck$ git merge --no-ff pollusb-development
Already up-to-date.
mac-n-chease:dbatools ck$ git status
On branch pollusb-development
nothing to commit, working tree clean
```

**Comment by ConstantineK** [comment]
Ah, may just need a reviewer, going to head to dinner!

**Comment by pollusb** [comment]
Thanks @ConstantineK for the magic ;)
@potatoqualitee, Test is still failing when I uncomment the 3 lines. Do you want me to not change this file?

**Comment by potatoqualitee** [comment]
YAY you guys are frikken awesome! Thank you @pollusb , @wsmelton and @ConstantineK 💯

**Comment by pollusb** [comment]
Thanks. This experience makes me realize that I need to learn more about Git, Pester and magic

**Comment by potatoqualitee** [comment]
LOL, I'll never aim for git magic. It's dark dark stuff, man.

**Pull request merged**
