### PR TITLE
Find-DbaOrphanedFile, tests gentlyfication

### PR DESCRIPTION
**Pull request by niphlod**
## Type of Change

 - [ ] Bug fix (non-breaking change, fixes #<enter issue number>)
 - [ ] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [X] Pester test is included

----

(do Orphaned)

### CODE REVIEW

**Comment by niphlod** [comment]
I think we broke appveyor for a while ghghgh . Sadly turning down the amount of tests output leaves a little bit of a problem when trying to debug.

**Comment by potatoqualitee** [comment]
this one passed 💯 Can i merge?

**Comment by niphlod** [comment]
yeah, I'm pretty sure there is something going on with appveyor. a few hour ago everything was smoother.

**Comment by potatoqualitee** [comment]
Genuinely, I find some nights are better than others!

**Pull request merged**
