### PR TITLE
Addressing various submitted issues

### PR DESCRIPTION
**Pull request by wsmelton**
## Type of Change

 - [x] Bug fix
 - [x] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
Fixing various items to try and clean up some of our issues.

### Get-DbaDbCompatibility (breaking change)

#5919

`Get-DbaDbCompatibility` previously output the `Compatibility` property as a string (e.g. `Version140`). This PR adds a property, `Level`, to have the integer value be available.

### Get-DbaTcpPort

#5929

This command included a call to `Invoke-ManagedComputerCommand` but was passing a `$Credential` variable that the command never accepted as a parameter. So I updated the command to now accept that object.

In turn this fixes an issue `Test-DbaConnection` has because we were not passing in the actual Credential to `Get-DbaTcpPort`. I updated that call to now pass the Credential properly.

### Output messages

#5945
#5905

The other two items are just simply output messages.

### CODE REVIEW

**Comment by potatoqualitee** [comment]
Thanks so much!! 

Tests for Get-DbaDbCompatibility need to be updated - they are currently failing, which is great becuase it means they work ;)

Should we add an extra field for CompatabilityVersion or some other name instead? The reason it used VersionXX is because thats how SMO outputs it.

**Comment by wsmelton** [comment]
The error I believe is on the context calling for master and it is from deadlock. I had this happen running it locally one time, but any other time the test runs fine.

**Comment by wsmelton** [comment]
This is failing due to an issue with Appveyor, the test runs finally locally now. I cannot make it issue any error in the last context block with the last adjustment.

I also just caught we need to add an artifact to Appveyor to output the `$error` object contents. The log file we capture won't include errors that Pester hits, so those exceptions are never visible.

**Comment by wsmelton** [comment]
Oh well.

**Comment by potatoqualitee** [comment]
aw why? i was looking forward to this one

**Comment by wsmelton** [comment]
I'll be reworking it but should have kept my own standard of not including so much in one PR 😬

**Comment by potatoqualitee** [comment]
haha K 🏆 !!

**Pull request closed without merging**
