### PR TITLE
Get-DbaFile Test - makes test universal

### PR DESCRIPTION
**Pull request by potatoqualitee**

### CODE REVIEW

**Comment by jpomfret** [comment]
Looks good to me, tested against a couple of instances

image

**Comment by potatoqualitee** [comment]
omg appveyor is totally lying, im gonna have to do some more tests this is weird

**Comment by niphlod** [comment]
@potatoqualitee : you create "dbatoolsci_getfile$random" ... search for that file mask only (rather than dbatoolsci), probably other tests leave something behind.

**Comment by potatoqualitee** [comment]
i did - in this case, it was returning some files instead of true/false. i guess it's evaluated differently for som reason? i see why but wished it'da failed locally

**Pull request merged**
