### PR TITLE
Move-DbaDatabaseFile - Documentation changes for review

### PR DESCRIPTION
**Pull request by ConstantineK**
Ran through the comments and documentation, changed a bunch of grammar and phrasing to shorten and hopefully simplify some of the explanations. Altered -InputFile fundamentally because I think the explanation may have been copy pasted and not changed. Changed capitalization and period use to be more consistent.

### CODE REVIEW

**Comment by ConstantineK** [comment]
This is a PR on top of @ClaudioESSilva's submission, I believe we would either need to do a few commits on top of this to finish up.

**Comment by dansqldba** [comment]
@ClaudioESSilva this appears to be a PR for merging into your development branch, suggest you take responsibility for merging it.

**Comment by ctrlbold** [comment]
hey @ClaudioESSilva how's this coming?

**Comment by ClaudioESSilva** [comment]
I will try to do something this week but I can't promise :weary: 
As soon as I can contine on this I shout!

**Comment by ctrlbold** [comment]
np i did it ;)

**Pull request merged**
