### PR TITLE
DbaInstanceParameter - Added Support for Azure Instances

### PR DESCRIPTION
**Pull request by FriedrichWeinmann**
## Type of Change

 - [x] Bug fix (non-breaking change, fixes #<enter issue number>)
 - [ ] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 
### Changes
 - Fixed: SMO Server Instances of Azure SQL Instances can now be understood and passed through by the `[DbaInstance]` parameter class

### CODE REVIEW

**Comment by potatoqualitee** [comment]
unfortunately, both tests failed :(

**Comment by wsmelton** [comment]
Curious how are they not already?
image

The above was with 0.9.152 version.

I don't see much difference with this PR version:
image

**Comment by FriedrichWeinmann** [comment]
Dang it, I'll look into it.
@wsmelton : Strings work just fine. Try running `Connect-DbaInstance` and using the resulting server object to connect.

**Comment by wsmelton** [comment]
Works for me:

image

image

**Comment by wsmelton** [comment]
With Azure SQL you won't be able to access much of anything at the server-level with SMO (e.g. `$server.Logins`, etc) it is just not supported.

**Comment by FriedrichWeinmann** [comment]
And now that you have the `$server` object, try this:
`[DbaInstance]$server`

**Comment by wsmelton** [comment]
Ah, ok see your point. However, you will never be able to get instance level information from that `$server` object with Azure SQL...it is just not supported. 

The properties like InstanceName, ComptuerNamePhysicalNetBIOS or NetName will not have any value. Actually, not much of anything is populated on that top level server object in SMO when you hit an Azure SQL instance.

**Comment by FriedrichWeinmann** [comment]
Oh, that's totally fine with me. My priority is to have it accept the connection object, so pure SQL connections can be reused, rather than always opening a new one.

The parameter class only requires me to get a computer name (a dns resolveable name, which you need to connect anyway), and that's good enough for me. `Connect-SqlInstance` will ignore it all anyway if it's a live connection.

**Comment by potatoqualitee** [comment]
thanks fred! 💯

**Pull request merged**
