### PR TITLE
Invoke-SqlCmd2 fix for UNC path and other style/grammar/spelling

### LINKED ISSUE #2192: Invoke-SqlCmd2 fails with UNC path
## Bug Report

Executing Invoke-SqlCmd2 and providing an UNC based InputFile results in the error described below.  The reason for this is error is that [Line 295](https://github.com/sqlcollaborative/dbatools/blob/master/functions/Invoke-SqlCmd2.ps1#L295) of the script obtains the 'path' property returned from Resolve-Path, however for UNC paths, the path value contains provider information.  Using the ProviderPath property would resolve the UNC path issue without regressing existing functionality.

### General Troubleshooting steps

- [X] Verified running latest release of dbatools? 0.9.39
- [X] Verified errors are not related to permissions? Yes
- [X] Can duplicate in new/fresh PowerShell.exe session? Yes

### Version Information
 - Operating System (Name|Version): Windows Server 2016 Standard Version 1607 OS Build 14393.1593
 - PowerShell Version: 5.1.14393.1532
 - SQL Server (Edition|Version): Microsoft SQL Server 2016 (SP1-CU3) (KB4019916) - 13.0.4435.0 (X64) 

## Steps to Reproduce

 - [X] Attach any screenshots (if possible/allowed)
 - [ ] Attach logs generated by dbatools (`Get-DbatoolsLog`)
 - [X] Attach output from PowerShell console (if possible/allowed)

```
PS C:\> Invoke-Sqlcmd2 -ServerInstance "localhost" -InputFile "\\localhost\scripts\test.sql"
Exception calling "ReadAllText" with "1" argument(s): "The given path's format is not supported."
At line:299 char:13
+             $Query =  [System.IO.File]::ReadAllText("$filePath")
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : NotSupportedException
 
Exception calling "Fill" with "1" argument(s): "ExecuteReader: CommandText property has not been initialized"
At line:454 char:17
+                 [void]$da.fill($ds)
+                 ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : InvalidOperationException
```

## Feature Request

Ability to run scripts from a UNC share

### Problem to solve
Unable to run scripts from UNC share

### Additional information
```
PS C:\> $filePath = $(Resolve-Path "\\localhost\scripts\test.sql")

PS C:\> $filePath.Path
Microsoft.PowerShell.Core\FileSystem::\\localhost\scripts\test.sql

PS C:\> $filePath.ProviderPath
\\localhost\scripts\test.sql

PS C:\> $filePath = $(Resolve-Path "Y:\test.sql")

PS C:\> $filePath.Path
Y:\test.sql

PS C:\> $filePath.ProviderPath
Y:\test.sql

PS C:\> y:

PS Y:\> $filePath = $(Resolve-Path "./test.sql")

PS Y:\> $filePath.Path
Y:\test.sql

PS Y:\> $filePath.ProviderPath
Y:\test.sql
```

### PR DESCRIPTION
**Pull request by alevyinroc**
## Type of Change
 - [X] Bug fix (non-breaking change, fixes #<enter issue number>)
 - [ ] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Pester test is included
 - [X] Spelling, grammar & other cleanup in Help and other text content

### Purpose
 
To clean up grammar, style, spelling and other issues related to comment-based help and other text in functions.

Fix #2192 to allow for successful access to UNC paths

### CODE REVIEW

**Comment by wsmelton** [comment]
One point is this is not one of our commands. It is included but is maintained in a seperate repo.

Unless @potatoqualitee has changed her mind on how we keep this one.

**Comment by alevyinroc** [comment]
I think the function came over to this repo as a one-time copy because it seemed useful, but the original isn't really getting much maintenance either. I filed a PR over there back in January and it looked like there might be some discussion about what direction to go, but it didn't go far. See https://github.com/sqlcollaborative/Invoke-SqlCmd2/pull/7#issuecomment-274111028

**Comment by wsmelton** [comment]
I can't catch what you changed to fix the UNC path issue with all the other changes made?

**Comment by alevyinroc** [comment]
@wsmelton that change is on line 303. https://github.com/sqlcollaborative/dbatools/pull/2197/files#diff-f69d8083f0ef6ebfab68afb58a1170bfR303

However, I want to put this PR on hold for a bit as there's conversation in the Invoke-SQLCmd2 repo (spurred by this one) now about how to handle this function. We might end up making all changes over there and then just manually copying the function over to this repo as needed.

More to come when I can catch up on discussions.

**Comment by potatoqualitee** [comment]
Yeah, andy, make it there and I'll copy it over once it's merged. That way, non dbatools ppl can still benefit.

**Comment by alevyinroc** [comment]
Will do, @potatoqualitee . Hopefully my other PR can get merged in too.

**Comment by potatoqualitee** [comment]
I'll do that one too 👍

**Comment by potatoqualitee** [comment]
Will close this one so it can be merged at invoke-sqlcmd2 then ill copy over. I'll also add a simple test. If you'd like to add on to it, @alevyinroc or anyone - please do.

**Comment by alevyinroc** [comment]
I'll move the work over to invoke-sqlcmd2's repo and get everything synced up later this week

**Pull request closed without merging**
