### PR TITLE
Include a sample for retoring a single database from a bak file and rename physical and logical files.

### PR DESCRIPTION
**Pull request by Splaxi**
## Type of Change

 - [ ] Bug fix (non-breaking change, fixes #<enter issue number>)
 - [ ] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] Nunit test is included
 - [X] Documentation
 - [ ] Build system

### Purpose
 
Update example to include a simple use case for restoring a database with a new name and having the physical files and logical filenames updated.

### CODE REVIEW

**Comment by potatoqualitee** [comment]
Thanks motz :) for future reference, you just have to update your branch and it'll update here 💯

**Comment by Splaxi** [comment]
Still learning...

So even after I create an PR, and update my repo, it will reflect into the current PR?

**Comment by potatoqualitee** [comment]
yep! so convenient

**Comment by potatoqualitee** [comment]
all files edited in that branch  will be updated in this PR. so you'd basically want to make a branch per PR

**Comment by potatoqualitee** [comment]
thanks so much, added! checks failed because i ran out of azure credits

**Pull request merged**
