### PR TITLE
Startup procs

### PR DESCRIPTION
**Pull request by sqllensman**
## Type of Change

 - [ ] Bug fix (non-breaking change, fixes #<enter issue number>)
 - [X] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [X] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
Change #5265 added new command Copy-DbaStartupProcedure
This adds the matching Get-DbaStartupProcedure and Set-DbaStartupProcedure commands to provide complete coverage.

### Commands to test
Get-DbaStartupProcedure 
Set-DbaStartupProcedure

### CODE REVIEW

**Comment by wsmelton** [comment]
I'm not sure I see a reason to have the get command, `Get-DbaDbStoredProcedure` outputs the SMO object which allows you to script out the given procedure. This one will not being that it is just an enumerator.

**Comment by wsmelton** [comment]
I would rather see a Enable/Disable function instead of a Set...makes it more clear to users and more discover-able.

**Comment by sqllensman** [comment]
Happy to modify to use Enable / Disable as this would match the TraceFlag commands.

The Get procedure can be modified to return same output as Get-DbaStoredProcedure.

However once we go down this route should I also modify to allow the Get procedure to be piped to Disable procedure?

**Comment by sqllensman** [comment]
Also if Set function is to be split into multiple functions would it make sense to move code that parses an object name into Schema and Name into an internal function rather than maintaining multiple copies?

**Comment by potatoqualitee** [comment]
> I would rather see a Enable/Disable function instead of a Set
Agreed

> However once we go down this route should I also modify to allow the Get procedure to be piped to Disable procedure?
Awesome, yes please!

> The Get procedure can be modified to return same output as Get-DbaStoredProcedure
Agreed, that'd help simplify your code, too 👍 

Thanks so much!

**Comment by sqllensman** [comment]
Please close this pull request and I will submit a new request with expanded scope.

**Comment by potatoqualitee** [comment]
looking forward to it, @sqllensman

**Pull request closed without merging**
