### PR TITLE
Stop-Function  - more informative messages

### PR DESCRIPTION
**Pull request by potatoqualitee**
way more informative error messages

@FriedrichWeinmann - i know you weren't a fan of this approach, and admittedly it's hacky, but it really seems to work. 

image

I'd like to ensure this or an equivalent stays when the new messaging system is in place 🏹

### CODE REVIEW

**Comment by potatoqualitee** [comment]
It's so useful! 😍 

This last commit took a slightly different approach by adding an internal function /cc @FriedrichWeinmann 

image

**Comment by FriedrichWeinmann** [comment]
Btw, don't worry about the new message system breaking this: The mechanism is already in place!

**Comment by wsmelton** [comment]
So on command where we pass in the 3 or 4 deep inner exception to stop function this won't duplicate or will it wipe that out?

**Comment by potatoqualitee** [comment]
@wsmelton - this only looks at $errorrecord and not $exception so i dont think it'll impact it? nevertheless, the "finally" part of this command defaults to what it's been this whole time

**Pull request merged**
