### PR TITLE
New-DbaDatabaseSnapshot, fixes #1388

### LINKED ISSUE #1388: Name parameter New-DbaDatabaseSnapshot should be name of snapshot and not suffix
## Is this:

- [ ] *feature* 
- [X] *bug*:

## Steps to Reproduce

1. Run Command:
```powershell
New-DbaDatabaseSnapshot -SqlInstance server -Database Northwind -Name Northwind_dbss
```
3. Received snapshot named "NorthwindNorthwind_dbss"

## Expected Results
1. Run Command:
```powershell
New-DbaDatabaseSnapshot -SqlInstance server -Database Northwind -Name Northwind_dbss
```
3. Receive snapshot named "Northwind_dbss"

As it is called "Name" it should be the exact name of the snapshot being created. If a user wants to append the something to the name of the snapshot a parameter like "Suffix" or "Append" should be provided.

### PR DESCRIPTION
**Pull request by niphlod**
Fixes #1388

Changes proposed in this pull request:
 - introduced Name and NameSuffix
 - removed dependecy on remove-dbasqldatabase

Additionally removed remove-dbasqldatabase dependency from restore-dbadatabasefromsnapshot and remove-dbadatabasesnapshot

### CODE REVIEW

**Comment by potatoqualitee** [comment]
hey @niphlod - why did you remove the dependency on Remove-DbaDatabase? It helps drop the hell out of a database - yours may fail if users are still connected.

**Comment by niphlod** [comment]
Remove-dbadatabase is too tight to get-dbadatabase and the restore cmdlets.
It's crearly not meant to be used with snaps (database preselection,
general internals SMO methods not doing the right thing, tsql fallback
incompatible with snaps, etc).
Snap cmdlets were plainly not working anymore, erroring out.
 Instead of cross-adapting Remove-dbadatabase to work with snapshots
too(and maybe breaking other cmdlets that rely on it), until proper CI is
up, this is a first fix, which make snap cmdlets work again.
I'll eventually introduce internals to be able to drop snaps even with
stubborn transactions in a later release.

Il 12 giu 2017 7:01 PM, "Chrissy LeMaire" <notifications@github.com> ha
scritto:

**Comment by niphlod** [comment]
hey @potatoqualitee , this is now in the right shape. There's no best method than the one implemented in the latest commit to continue with the restore process. Design question though: should we kill transactions only when -Force is passed ? One *could* need to be "gentle" if there are open transactions and abort the removal/restore process.

**Comment by potatoqualitee** [comment]
good point. yeah, i'd say so. can you add?

**Comment by niphlod** [comment]
@potatoqualitee will do in 6 hours.

**Comment by niphlod** [comment]
done

**Comment by potatoqualitee** [comment]
:dancing_monkey:

**Comment by potatoqualitee** [comment]
thanks @niphlod  👯

**Pull request merged**
