### PR TITLE
Set-DbaAgentJob - Added parameter test

### LINKED ISSUE #6847: [Bug] Set-DbaAgentJob - error setting `OperatorEmail` w/o `EmailLevel`
### Environmental information

```powershell
PowerShell Version        : 5.1.19041.1
dbatools latest installed : 1.0.119
Culture of OS             : ru-RU
```

#### SQL Server:

```sql
Microsoft SQL Server 2016 (SP2-CU12) (KB4536648) - 13.0.5698.0 (X64)
                Feb 15 2020 01:47:30
                Copyright (c) Microsoft Corporation
                Standard Edition (64-bit) on Windows Server 2012 R2 Standard 6.3 <X64> (Build 9600: ) (Hypervisor)
```

```sql
us_english
```

### Report

Cannot set operator e-mail on a job w/o specifying notification level

#### Host used

- [ ] powershell.exe
- [ ] ISE
- [X] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [X] Still buggy in powershell.exe

#### Errors Received

```powershell
WARNING: [18:41:57][Set-DbaAgentJob] Something went wrong changing the job | The specified '@notify_level_email' is invalid (valid values are: 1, 2, 3).
```

#### Steps to Reproduce

```powershell
Get-DbaAgentJob -SqlInstance srv-sql-vm04 -Category 'SomeCategory' | Where-Object {$_.OperatorToEmail -eq ''} | Set-DbaAgentJob -EmailOperator 'OperatorEmail'
```

#### Expected Behavior

Set notification level to similar as in SSMS `onError`

#### Actual Behavior

Warning received, operator not set.

### PR DESCRIPTION
**Pull request by andreasjordan**
## Type of Change

 - [x] Bug fix (non-breaking change, fixes #6847 )
 - [ ] New feature (non-breaking change, adds functionality, fixes # )
 - [ ] Breaking change (effects multiple commands or functionality, fixes # )
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 
For all three possible types (e-mail, net send, page) now both operator and level have to be set, otherwise a warning is thrown and the command returns.

Also corrected some comments.

image

### CODE REVIEW

**Comment by potatoqualitee** [comment]
Unsure what's going on, but the changes seem to impact other AgentJob commands which causes failures :/

**Comment by andreasjordan** [comment]
Ok, I'll have a closer look.

**Comment by andreasjordan** [comment]
Ok, fixed it. Failed test seem unrelated.

**Review by niphlod — APPROVED** [review]

**Comment by potatoqualitee** [comment]
parrrty!

**Pull request merged**
