### PR TITLE
Address issue with use of module in Azure Automation

### LINKED ISSUE #5835: Importing dbatools module into Azure Automation Account
Has anyone managed to import dbatools module into Azure Automation Account? I tried to do it in several ways, but every time the installation fails:

- different versions checked from 1.0.0 to the latest 1.0.9
- from portal using Automation Accounts -> Automation modules -> Browse Gallery
- from portal using Automation Accounts -> Automation modules -> import from file

Every time I got:

> Error importing the module dbatools. Import failed with the following error: Orchestrator.Shared.AsyncModuleImport.ModuleImportException: An error occurred during module validation. When importing the module to an internal PowerShell session, it was not able to be loaded by PowerShell. There is likely an issue with the contents of the module that results in PowerShell's not being able to load it. Please verify that the module imports successfully in a local PowerShell session, correct any issues, and then try importing again.

As you can see the error message doesn't tell much (and obviously I am able to import it locally), thus I wonder if anyone managed to go over it somehow.

### PR DESCRIPTION
**Pull request by wsmelton**
## Type of Change

 - [x] Bug fix (non-breaking change, fixes #5835  )
 - [ ] New feature (non-breaking change, adds functionality, fixes # )
 - [ ] Breaking change (effects multiple commands or functionality, fixes # )
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
Importing the module into Azure Automation account gives a generic message:

> Error importing the module dbatools. Import failed with the following error: Orchestrator.Shared.AsyncModuleImport.ModuleImportException: An error occurred during module validation. When importing the module to an internal PowerShell session, it was not able to be loaded by PowerShell. There is likely an issue with the contents of the module that results in PowerShell's not being able to load it. Please verify that the module imports successfully in a local PowerShell session, correct any issues, and then try importing again. 

The reason this would work on most machines is because the DLLs noted are in a vanilla install of Windows where SQL Server tools have been installed. These are part of the C runtime library that is installed with VS, SSMS, and various other tools/software. I checked the sqlserver module and they include these two files. It simply requires they exists in the same directory as the BatchParser dll as it has some dependencies on this for backward compatibility.

### Approach
The process in Azure Automation for importing a module basically takes the module and tries to import it using the Azure Sandbox environment. This is the same environment you get (basically) when you are running a PowerShell Runbook. The following code was used for two runbooks. First runbook pulled development branch code, and the second one pulled the branch of this PR:

```powershell
$name = "dbatools"
$branch = "fix-azureautomation"
$url = "https://github.com/wsmelton/dbatools/archive/$($branch).zip"
$OutFile = Join-Path "$env:TEMP" -ChildPath 'dbatools.zip'
Invoke-WebRequest $url -OutFile $OutFile -UseBasicParsing -Verbose
# Get-Item $OutFile

Expand-Archive $outfile -destinationpath "$env:temp" -ErrorAction Stop
# Get-ChildItem "$env:temp\dbatools-$($branch)"
try {
    Import-Module "$env:TEMP\dbatools-$($branch)\dbatools.psd1" -Verbose -ErrorAction Stop
} catch {
    "caught exception"
    $e = $_.Exception
    while ($e -ne $null) {
        $e | fl * -force | out-string
        $e = $e.InnerException
    }
}

try {
    Get-DbaComputerSystem
} catch {
    "caught exception"
    $e = $_.Exception
    while ($e -ne $null) {
        $e | fl * -force | out-string
        $e = $e.InnerException
    }
}
```

### Screenshots
Development branch receives these errors when trying to import the module on the Azure sandbox server:
image

This PR branch receives no errors, the command called in the runbook spits out warnings but I was not expecting it to run successful anyway:
image

The fact this spits out at all though shows the module imported:
image

### CODE REVIEW

**Comment by potatoqualitee** [comment]
sweet as heck!!! how did you figure this out?

**Comment by wsmelton** [comment]
Various comments on forums and post on using SMO on C# projects.

**Comment by NowinskiK** [comment]
I guess that the issue hasn't been published yet? I tried to import `dbatools` module to Azure Automation and it fails with following message:  
> Error importing the module dbatools. Import failed with the following error: System.FormatException: Index (zero based) must be greater than or equal to zero and less than the size of the argument list.

**Comment by wsmelton** [comment]
This was published 6 months ago.

Please create a new issue if you are having issues.

**Pull request merged**
