### PR TITLE
Added filter of system files added in SQL 2019 install

### PR DESCRIPTION
**Pull request by gbargsley**
## Type of Change

 - [X] Bug fix (non-breaking change, fixes # )
 - [ ] New feature (non-breaking change, adds functionality, fixes # )
 - [ ] Breaking change (effects multiple commands or functionality, fixes # )
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
 
With the SQL 2019 installation the following four files are now being dropped in the DATA folder by default.

model_msdbdata.mdf
model_msdblog.ldf
model_replicatedmaster.ldf
model_replicatedmaster.mdf

The current version of the function identifies these as orphaned because they are not hosted by SQL Server, but I believe they are there for AG replication of system files or for some other SQL related feature.  I would not recommend displaying these as orphaned as deleting them might break the SQL 2019 instance.

### Approach

Added them as system files which then removes them from the output of the function.

### Commands to test

run Find-DbaOrphanedFiles against a SQL 2019 instance 

### Screenshots

Before: (ver 0.1.100)
image

After fix from PR:
image

### CODE REVIEW

**Comment by wsmelton** [comment]
This needs an issue to know the background of those files and how you determined SQL Server 2019 installation is putting them there on the server.

**Comment by gbargsley** [comment]
#6396

**Comment by gbargsley** [comment]
Yes on multiple boxes.  I cannot find it in any MS docs, but it seems related to a feature.

**Comment by potatoqualitee** [comment]
Interesting! I was able to find some docs, though it wasn't explicitly about the system dbs, just talks about them in passing

https://docs.microsoft.com/en-us/sql/big-data-cluster/deployment-high-availability?view=sql-server-ver15

Thanks much, great work, merging 💯

**Comment by wsmelton** [comment]
So an additional change is required then to also add `containedag_master` and `containedag_msdb` as documented in that link.

**Pull request merged**
