### PR TITLE
Get-DbaBackupHistory, fix for same-named databases

### PR DESCRIPTION
**Pull request by niphlod**
## Type of Change

 - [x] Bug fix (non-breaking change, fixes #<enter issue number>)
 - [ ] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 
### Purpose
Getting correct last backups in a recurring scenario when database with the same name get dropped and recreated. We continue to trust LSNs, which ultimately is what makes a restore possible.

### Approach
I slapped in the most annoying comment ever, because we revisited bits and pieces of the logic over and over without finding a proper fix (till now). 
Long story short (still long), LSNs are ordered correctly always. The whole point of LSNs is to be comparable and sortable to build a chain. Opposed to most of the scripts out there, we don't rely on backup_finish_date (even if that's what SMO does) because msdb holds dates with the timezone of the server. DST happens rarely, but they happen everywhere. That's why we go for last_lsn being "truthful" always. A small hiccup in this scenario happens when msdb holds the history for a database that has been backed up with the same name. LSNs are guaranteed to be ordered for the same database, but when you drop and recreate a database with the same name it's not the same database. 
database_guid, on the other end, changes. For the same database_guid, last_lsn is ordered correctly. So, to circumvent the hiccup, before trusting last_lsn, we filter out the history seeking the database that has the database_guid which has the last backup_finish_date (which translates to selecting the history that is relative to the last database backed up on the server with the same name).  

Short story: we trust last_lsn whenever possible. When it's not possible we filter out those rows whose database_guid has the oldest backup_finish_date. We don't go for backup_finish_date for DST. We don't go for backup_set_id because there's no explicit documentation stating that is ordered the same as LSNs.

### CODE REVIEW

**Comment by potatoqualitee** [comment]
haha enjoyed the comment. thank you for the fix. I'll let @Stuart-Moore take a look and merge /cc @Zhunya

**Comment by niphlod** [comment]
@Zhunya : went and added the same filtering in the subquery that is applied in the outer

@cviorel : added a fix for your finding and a regr test, thanks for the catch

**Comment by niphlod** [comment]
okay, could replicate. Working on a fix right now

**Comment by potatoqualitee** [comment]
yay all passes!

**Comment by niphlod** [comment]
yup. was due to backup concluding in the same second. seems that "second" is the default precision for msdb backupset-ty data.

**Comment by potatoqualitee** [comment]
is that a 👍 to merge?

**Comment by niphlod** [comment]
@Stuart-Moore approved when I discussed the main gist of the idea, @Zhunya notes have been incorporated and @cviorel fix is in. 
Tests pass, so I think we're good.

**Comment by potatoqualitee** [comment]
yessssssss!

**Pull request merged**
