### PR TITLE
Get-/Set-DbaTcpPort - Rewriting the commands and using Get-/Set-DbaNetworkConfiguration

### PR DESCRIPTION
**Pull request by andreasjordan**
Just a draft with first ideas.
There have been issues with the commands, so this is also a bugfix.

## Type of Change

 - [ ] Bug fix (non-breaking change, fixes # )
 - [ ] New feature (non-breaking change, adds functionality, fixes # )
 - [ ] Breaking change (effects multiple commands or functionality, fixes # )
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system

### CODE REVIEW

**Comment by potatoqualitee** [comment]
Tests pass but Set has no integration tests :/ Would you be so kind as to write at least one that ensure the command works as expected?

**Comment by andreasjordan** [comment]
How are the instances in AppVayor configured? Can I change the port without affecting other tests?
If they are on static port, I could just change that and then change it back.
If they are on dynamic port, I could change to static and then back to dynamic with Set-DbaNetworkConfiguration.

**Comment by andreasjordan** [comment]
I can just change the configuration without restarting the service or also restarting the service. What should the test do?

**Comment by niphlod** [comment]
the service_restarts env should be the best option here, as it runs pretty destructive tests already.
instances are configured using these scripts \tests\appveyor.SQL2017.ps1,\tests\appveyor.SQL2016.ps1

**Comment by potatoqualitee** [comment]
Fantastic! Thank you.

**Pull request merged**
