### PR TITLE
Fix examples4

### PR DESCRIPTION
**Pull request by sqllensman**
## Type of Change

 - [X] Bug fix (non-breaking change, fixes #<enter issue number>)
 - [ ] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] Nunit test is included
 - [X] Documentation
 - [ ] Build system
 

### Purpose
Contains minor changes to fix issues in examples 
Details below

Export-DbaDiagnosticQuery
	Removed unused reference to Notes field
	
Export-DbaExecutionPlan
	Added Compulsory Path Parameter
	Removed redundant code doing unnecessary cast of SinceLastExecution and SinceCreation
	Fixed cast of dates to "yyyy-MM-dd HH:mm:ss" Format
	Updated Examples to use Pipeline
	
Export-DbaUser
	Changed Parameter FilePath to Path, FilePath retained as Alias
	
Export-DbaXESessionTemplate
	Updated incorrect Examples
	
Find-DbaAgentJob
	Updated Examples to fix typos

Find-DbaUnusedIndex
	Updated examples to fix typos
	Changed Parameter FilePath to Path, FilePath retained as Alias
	
Get-DbaAgentJob
	Updated Examples to fix typos
	
Get-DbaAgentJobStep
	Updated Examples to fix typos

Get-DbaBackupHistory
	Updated Examples to fix typos 
	
Get-DbaBackupInformation
	Put examples together and fixed minor typos
	
Get-DbaClientAlias
	Updated CBH which was simple a copy of New-DbaClientAlias 
	Removed unused reference to $Pscmdlet.ShouldProcess
	
Get-DbaExecutionPlan
	Removed redundant code doing unnecessary cast of SinceLastExecution and SinceCreation
	Fixed cast of dates to "yyyy-MM-dd HH:mm:ss" Format

### CODE REVIEW

**Comment by potatoqualitee** [comment]
so good and necessary, especially since we'll soon be moving to the new docs system, ty ty ty

**Comment by sqllensman** [comment]
The 5th example had the tag .EXAMPLEa instead of .EXAMPLE. 
How do I update Pull Request

**Comment by potatoqualitee** [comment]
Just commit your changes and it'll automatically update the PR. I'll resolve the conflict after 👍

**Comment by potatoqualitee** [comment]
I'll do it real quick so i can merge 🎈

**Comment by potatoqualitee** [comment]
excellent, k - just gotta wait for the tests to pass and we'll be set 🎉

**Pull request merged**
