### PR TITLE
Add 2019 versions to build ref

### PR DESCRIPTION
**Pull request by jpomfret**
## Type of Change

 - [ ] Bug fix (non-breaking change, fixes #<enter issue number>)
 - [X] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
Adding the 2019 builds - discussed in #6059

### CODE REVIEW

**Comment by wsmelton** [comment]
Need to update the date at the top of the file.

**Comment by wsmelton** [comment]
The only ones to be added will be the release candidates. You can just match how the ones for 2017 are structured.

The CTPs can be removed as we don't support or need to worry about those.

**Comment by jpomfret** [comment]
@wsmelton is it formatted correctly now? I think the test failures would be expected since we don't have an RTM yet? Should I try and change those?

**Comment by wsmelton** [comment]
We must not have added the RCs for SQL Server 2017 until the RTM was released. I would rather not change the test because they are there to ensure we have the proper structure and we just have not built in dealing with RC releases. 

We can likely just hold off adding them for now.

**Comment by potatoqualitee** [comment]
I'd like to get the RC's in and want to help Jess get her demo to look good 💅 . Can @niphlod help modify the tests?

**Comment by wsmelton** [comment]
RCs are added and included in the build index. But we do not add them until there is an RTM, unless we want to make up what the RTM version may or may not be and have it published as that.

**Comment by jpomfret** [comment]
Could we exclude 2019 versions from the tests until RTM comes out? Then when that's added we could remove that exclusion? If we opened an issue to track it?

https://github.com/sqlcollaborative/dbatools/blob/8c28ffd8d98f3bb0b59393a7b6423083a659a336/tests/Get-DbaBuildReference.Tests.ps1#L97

**Comment by wsmelton** [comment]
I'm working on the test now. The way RCs are released changed a bit with 2019 and to be accurate with the information we put out publicly requires the test validate the information a bit.

**Comment by jpomfret** [comment]
Sounds good! Thank you, I appreciate it!

**Comment by wsmelton** [comment]
Done. PR #6071 submitted.

**Pull request closed without merging**
