### PR TITLE
Fixes broken class and error on re-import

### PR DESCRIPTION
**Pull request by FriedrichWeinmann**
## Type of Change
 - [x] Bug fix (non-breaking change, fixes #<enter issue number>)
 - [ ] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Pester test is included

### Purpose
 - Fixes wrong typename causing errors and fail
 - Suppresses errors on re-import

### CODE REVIEW

**Comment by DavidSingletonTN** [comment]
The change on line 36 to switch to the extension to the Database class is correct.

I am curious about the additions to ignore (and not display) errors on these Update-TypeData calls.

**Comment by potatoqualitee** [comment]
@FriedrichWeinmann - can i merge once tests have passed?

**Comment by potatoqualitee** [comment]
Also thank you for solving and doing so, so quickly 🙇

**Comment by FriedrichWeinmann** [comment]
Sure and can merge.
@DavidSingletonTN  the ignores are for re-importing the module. This script is run on each import and will cause duplicates on each subsequent intervals.
Whether those properly work the first time around is tested by testing commands that use them. I also have adding dedicated tests for them themselves on my todo list. It's a long list and I'm busy with work so I only fix things that are actively broken and queue the rest for later consideration. (I expect that to get better in the coming weeks)

**Comment by DavidSingletonTN** [comment]
That makes sense @FriedrichWeinmann.  I noticed the extra errors with the other extensions on subsequent  imports.

Thank you again for the quick fix.

**Pull request merged**
