### PR TITLE
Find-DbaInstance - Parsing user SPNSs

### PR DESCRIPTION
**Pull request by cfradenburg**
## Type of Change

 - [ ] Bug fix (non-breaking change, fixes # )
 - [X] New feature (non-breaking change, adds functionality, fixes # )
 - [ ] Breaking change (effects multiple commands or functionality, fixes # )
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
Have Find-DbaInstance use service account SPNs to find servers

### Approach
Remove the filter for computer objects and parse the host name out of the SPN if the property doesn't exist. 

### Commands to test
Find-DbaInstance -DiscoveryType DomainSPN

### CODE REVIEW

**Comment by potatoqualitee** [comment]
oh la la!

**Comment by potatoqualitee** [comment]
hey @cfradenburg - is this working? will you be ready for  PR soon?

**Comment by cfradenburg** [comment]
It works good in my environment but I'm aware that there may be nuances with SPNs.  When I was talking with @wsmelton on Slack about my thoughts he recommended putting it in as a draft to make sure Fred (I think @FriedrichWeinmann) got a chance to look at it to make sure I'm not inadvertently breaking anything.  He said Fred is busy so it may take a few days so I didn't think anything of it sitting for a bit.

**Comment by potatoqualitee** [comment]
No problem, thanks. I'll ping Fred. I took a look and it looks sound to me but I am not detail oriented 😅

**Pull request merged**
