### PR TITLE
appeyor to appveyor

### PR DESCRIPTION
**Pull request by potatoqualitee**

### CODE REVIEW

**Comment by niphlod** [comment]
if appveyor approves changing its own reference, I will comply.

**Comment by potatoqualitee** [comment]
this was our own variable, its not `$env:appveyor`

**Comment by niphlod** [comment]
I know but being a reference only in tests, and tests are ran on appveyor, it's cheking for itself and doesn't need my inspection, just my pure love.

**Comment by potatoqualitee** [comment]
LOL I heard it loves you too 💞

**Pull request merged**
