### PR TITLE
Get-DbaWaitStatistic Tests

### PR DESCRIPTION
**Pull request by awickham10**
## Type of Change

 - [ ] Bug fix (non-breaking change, fixes #<enter issue number>)
 - [ ] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [x] Pester test is included
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
 
Improving test coverage for Get-DbaWaitStatistic.

### Approach

Three additional tests added.

### Commands to test

N/A

### Screenshots

N/A

### Learning

N/A

### CODE REVIEW

**Comment by potatoqualitee** [comment]
Heyyyy!! Awesome and welcome to the repo, @awickham10! Tests are especially appreciated and loved, thank you so much, here is a taco 🌮 

@jpomfret said that you guys worked together on this. I'd like to add you as a collaborator. Please check your email shortly 👍

**Comment by jpomfret** [comment]
Oh the work was all @awickham10 I just pestered him into contributing :D

**Comment by potatoqualitee** [comment]
Oh sorry i meant the github portion! thank you for the pestering 😂

**Comment by potatoqualitee** [comment]
Thanks again @awickham10 - your code is now in master and in the PowerShell Gallery 💯 🏅

**Comment by awickham10** [comment]
Thanks! Love the taco reference haha. More tests to come!

**Pull request merged**
