### PR TITLE
pester autodetection, fix

### PR DESCRIPTION
**Pull request by niphlod**
## Type of Change
 - [x] Bug fix (non-breaking change, fixes #<enter issue number>)
 - [ ] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 
### Purpose
Fix a problem in autodetection. There are (and there will be additional) tests which are not using neither $script:instance1 nor $script:instance2, like InModule.Help.Tests.ps1

### CODE REVIEW

**Comment by potatoqualitee** [comment]
this looks close to  done but has a werid error about help missing from a command that doesnt exist?

**Comment by niphlod** [comment]
gotcha, this is a byproduct of having the module dot-sourced. 
I'll change the routine to test only functions within the "functions" folder rather than the current behaviour of checking everything except internals.

**Comment by niphlod** [comment]
aaand, it correctly reports fails for two commands which do not have corresponding help params defined.

**Comment by niphlod** [comment]
groan, better to revert this

**Comment by niphlod** [comment]
@potatoqualitee can you merge this ? I'll fix the two commands help params missing in another PR ASAP.

**Comment by niphlod** [comment]
The PR fixing those params is https://github.com/sqlcollaborative/dbatools/pull/2561 .

**Comment by potatoqualitee** [comment]
btw, @niphlod - i believe you are admin, feel free to  merge when required like stuart does.

**Pull request merged**
