### PR TITLE
Rename-DbaDatabase, new command

### PR DESCRIPTION
**Pull request by niphlod**
## Type of Change
 - [ ] Bug fix (non-breaking change, fixes #<enter issue number>)
 - [x] New feature (non-breaking change, adds functionality, see #289)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Pester test is included

### Purpose
#289 holds pretty much everything. Not sure if this needs to handle also "moves" other than renames, such as "move this datafile to another disk".

This is just a first draft, but it's a working one nonetheless.
Cringe points:
- the templating system (I'm not good at naming things)
- general code style and loops, I feel there's a better way but can't find it
- it tries to proceed a database at a time and stop if anything goes wrong as soon as possible. Unfortunately reverting to the previous state can surely be done but could incur in the same errors, so for the moment...let's hope to not break everything
- the "default recursive behaviour" (see latest examples)
- what to return to the user, as it's a process made of several steps and ATM I can't figure a proper "layout" for the resulting object

For testers: do a backup of everything (or even better, a system image). This can (and probably will) nuclearize everything (again, "new born code alert").

I'm open to reviews and/or comments (don't go too technical on me, let's do that on round 2 or 3) ^_^

### CODE REVIEW

**Comment by niphlod** [comment]
clean reproposition for https://github.com/sqlcollaborative/dbatools/pull/2030, which is stale as ..... something stale. @zippy1981 test-psremoting is out of the picture. @potatoqualitee I'd go ahead and merge this, surely there will be improvements in the future but IMHO it does what it says it does.

**Comment by gbargsley** [comment]
First test shows issues with EnableException it looks like.

image

**Comment by niphlod** [comment]
yeah, this comes from before "the big rename" and I'm not sure why it has been left out to dry. I'll revamp in a bit.

**Comment by niphlod** [comment]
umpf. Need to open yet another PR.....wait for it.

**Pull request closed without merging**
