### PR TITLE
add cu7 for 2019

### PR DESCRIPTION
**Pull request by niphlod**
CU7 for 2019 is out

### CODE REVIEW

**Comment by niphlod** [comment]
not sure why the one on sqlcollaborative was reverted back ....

**Comment by wsmelton** [comment]
It is being reverted because of the automation processing we have in place that pulls the file from this repo into the assets folder of the docs repo.

Please only update this repo with the changes to the build file.

**Comment by wsmelton** [comment]
Ref: https://github.com/sqlcollaborative/dbatools/wiki/Asset-Update-Process

**Comment by niphlod** [comment]
whoppsie, okie so this should be merged before the bot passes at 4:00.

**Review by wsmelton — APPROVED** [review]

**Comment by wsmelton** [comment]
http://gph.is/2pr38pF

**Pull request merged**
