### PR TITLE
Test-ElevationRequirement

### PR DESCRIPTION
**Pull request by FriedrichWeinmann**
Fixes # 

Changes proposed in this pull request:
 - Replaces Test-RunAsAdmin with Test-ElevationRequirement
 - Functionality overhaul to avoid breaking functions and scripts
 - Updated usage in all functions that previously used `Test-RunAsAdmin`
 - A ton of minor updates and improvements while retrofitting the new command

### CODE REVIEW

**Comment by potatoqualitee** [comment]
LOL don't be trynna call this a bug fix!

**Comment by FriedrichWeinmann** [comment]
Well ... it fixes a bug. Or two.

**Comment by potatoqualitee** [comment]
in order to avoid conflicts, I will merge and test this tomorrow prior to release

**Comment by potatoqualitee** [comment]
hey @skatta5868  - this is an internal function that is not publicly exposed to end-users.

**Pull request merged**
