### PR TITLE
Connect-DbaInstance - Set the new code path as default

### PR DESCRIPTION
**Pull request by andreasjordan**
This will change the default code path inside of Connect-DbaInstance (and New-DbaConnectionString) to the formerly know "experimental" code path.

The config "sql.connection.experimental" is not used anymore. 
The config "sql.connection.legacy" is the way to quickly switch back to the old code path.

### CODE REVIEW

**Comment by potatoqualitee** [comment]
So sorry, this needed to be after my PR was merged. I have a lot of changes to `Connect-DbaInstance` that will conflict. Will have to close 😢

**Comment by potatoqualitee** [comment]
Nice, no conflicts!

**Comment by andreasjordan** [comment]
But tests fail randomly....

**Comment by potatoqualitee** [comment]
yeah thats expected. i added back a bunch of problematic tests to see if they work better with the new SMO and they don't, so i'm paring them back down again.

**Review by potatoqualitee — APPROVED** [review]
looks good! very clean

**Pull request merged**
