### PR TITLE
Connect-SqlInstance / Connect-DbaInstance - Move test for AzureUnsupported to Connect-DbaInstance

### PR DESCRIPTION
**Pull request by andreasjordan**
First step to work on #7319.
Will not change the behavior but only moves the test for AzureUnsupported from Connect-SqlInstance to Connect-DbaInstance.
To always test for AzureUnsupported enable the commented lines of code, but this will change the behavior of some commands (see #7323).

### CODE REVIEW

**Comment by andreasjordan** [comment]
Ok, I try to change the code to find out, why the tests fail.

**Comment by andreasjordan** [comment]
No it works.

**Comment by potatoqualitee** [comment]
Makes sense, thank you!

**Comment by potatoqualitee** [comment]
Going to leave this in dev for a day or so just to be sure since it's a base command.

**Pull request merged**
