### PR TITLE
spliting internal/external history

### LINKED ISSUE #5036: Restore-DbaDatabase changes paths in the backup history object
### Before submitting a bug report:

- [x] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [x] Verified this bug is not already reported in an issue
- [x] Verified errors are not related to permissions
- [x] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)
- [x] If issue is with `Copy-DbaDatabase`, using `Backup-DbaDatabase | Restore-DbaDatabase` still does not work

## Steps to Reproduce

```powershell
$historyObject = Get-DbaBackupHistory -SqlInstance lab-sds-ag1:7221 -Database Ag1Database1
$historyObject[0].FileList

FileType LogicalName      PhysicalName
-------- -----------      ------------
D        AG1Database1     C:\Data\MSSQL13.LIFE\AG1Database1.mdf
L        AG1Database1_log C:\Data\MSSQL13.LIFE\AG1Database1_log.ldf
D        AG1Database1_2   C:\Data\MSSQL13.LIFE\AG1Database1_2.ndf


$null = $historyObject | Restore-DbaDatabase -SqlInstance lab-sds-ag1:7221 -DatabaseName Ag1Database1_copy -TrustDbBackupHistory -ReplaceDbNameInFile -WithReplace -OutputScriptOnly
$historyObject[0].FileList

FileType LogicalName      PhysicalName
-------- -----------      ------------
D        AG1Database1     C:\Data\MSSQL13.LIFE\Ag1Database1_copy.mdf
L        AG1Database1_log C:\Data\MSSQL13.LIFE\Ag1Database1_copy_log.ldf
D        AG1Database1_2   C:\Data\MSSQL13.LIFE\Ag1Database1_copy_2.ndf


$null = $historyObject | Restore-DbaDatabase -SqlInstance lab-sds-ag1:7221 -DatabaseName Ag1Database1_copy -TrustDbBackupHistory -ReplaceDbNameInFile -WithReplace -OutputScriptOnly
$historyObject[0].FileList

FileType LogicalName      PhysicalName
-------- -----------      ------------
D        AG1Database1     C:\Data\MSSQL13.LIFE\Ag1Database1_copy_copy.mdf
L        AG1Database1_log C:\Data\MSSQL13.LIFE\Ag1Database1_copy_copy_log.ldf
D        AG1Database1_2   C:\Data\MSSQL13.LIFE\Ag1Database1_copy_copy_2.ndf

```

## Expected Behavior

$historyObject remaining unchanged

## Actual Behavior

Physical name gets replaced with the new database name every time the restore runs creating enormous filenames after a few runs:
Ag1Database1_copy_copy_copy_copy_copy_copy_copy_log.ldf

## Environmental data

 - PowerShell:
Name                           Value
----                           -----
PSVersion                      5.1.15063.1478
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.1478
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

 - - SQL Server: 2016SP2

### PR DESCRIPTION
**Pull request by Stuart-Moore**
## Type of Change

 - [x] Bug fix (non-breaking change, fixes #5036 )
 - [ ] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [x] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
Backuphistory is being passed by reference so any changes to backup history get made on the original object (like this:
```
$a = [PsCustomObject]@{test = 1}
$a.test
#returns 1
$b = $a
$b.test
$b.test = 2
$a.test
#returns 2
```

### Approach
Use `select-Object *` as a quick way to actually copy the object into a new variable and then use that throughout the function

### CODE REVIEW

**Comment by potatoqualitee** [comment]
thank you so much for the thorough review, @nvarscar ! 🙇 Did the additions cause the increase in processing time or is the original command impacted as well?

**Comment by Stuart-Moore** [comment]
@potatoqualitee he's referring to the Format-DbaBackupInformation call I believe, which has been in there for a fair while. Can't remember why we swapped the ordering from Select-Format-Test-Restore to Format-Select-Test-Restore

See the issue for the new approach. Which works fine outside of the function, but not within in it. Can you spot anything?

**Comment by potatoqualitee** [comment]
i like that new command and wonder if @FriedrichWeinmann would like it in his toolset too

**Comment by nvarscar** [comment]
@potatoqualitee sorry for not being clear, increased execution time was just an observation, it is completely unrelated to the issue in question.

@Stuart-Moore That's a pretty cool function! Although, now the execution time for me jumped from 1m to whopping 3m :( 
As a suggestion, there is an additional property, **OriginalFileList**, that is being added to the backupset in `Format-DbaBackupInformation`. Maybe instead, add a **NewFileList** property and use this new property in the restore instead of replacing the value in the old property? 
Also, this might be something: even though I see OriginalFileList being added as a NoteProperty here:
https://github.com/sqlcollaborative/dbatools/blob/553e9e146563c3aa2d92b63cba859724f89daf48/functions/Format-DbaBackupInformation.ps1#L152
, the original backup history object property list is not modified after running the restore function:
```
[ 26.0ms] git\dbatools-nvarscar> $historyObject[0].FileList|select *| fl


FileType     : D
LogicalName  : AG1Database1
PhysicalName : C:\Data\MSSQL13.LIFE\Ag1Database1_copy.mdf

FileType     : L
LogicalName  : AG1Database1_log
PhysicalName : C:\Data\MSSQL13.LIFE\Ag1Database1_copy_log.ldf

FileType     : D
LogicalName  : AG1Database1_2
PhysicalName : C:\Data\MSSQL13.LIFE\Ag1Database1_copy_2.ndf
```

**Comment by Stuart-Moore** [comment]
@nvarscar Problem with changing them over in the object is that they're public. People may have scripts that hang off of them (I do for some stuff that is really niche to work), and I've handed out various scripts via slack and github over the 18 months they're been there. @potatoqualitee is this a case of waiting for v1.0?

Still can't find the PR that switched the order, have a bit more time this evening after work so I'll try to track them down.

@FriedrichWeinmann is welcome to it, and if he could explain (in simple terms to me) why it doesn't work inside the function that would be even better :)

**Comment by potatoqualitee** [comment]
is there any way to avoid such a big chance? can we duplicate the data and excludeproperty in view?

**Comment by Stuart-Moore** [comment]
Lack of time sorry.  Was trying to duplicate the infomation, but copy-dbaobject doesn't work as expected within the function. Was hoping that @FriedrichWeinmann or some other PS guru could explain why

**Comment by potatoqualitee** [comment]
I'll ask Fred if he can take a look in a DM, thank you Stuart

**Comment by FriedrichWeinmann** [comment]
Heya, just wanted to drop a note on this:
Interesting command you wrote there for sure!
It definitely should be working internally as well, from what it does. The only reason I can see for the effect still to happen is that it actually is also used in its un-cloned state. While this command _is_ rather convoluted, I have traced the input through the command and cannot see where it goes wrong - I may need to take a look again this weekend when I have access again to the lab environment and can reproduce the error (sitting in a hotel room and looking at it from a pure theoretical perspective)

**Comment by Stuart-Moore** [comment]
Thank you for having a look @FriedrichWeinmann much appreciated 👍 

OK, I'll step through it later to see what's reassigning it. Was worried I'd forgotten about scopes or something.

**Comment by potatoqualitee** [comment]
is this mergable? i saw one pass 👌

**Comment by wsmelton** [comment]
Going to just close this one....can do PR as draft if needed to have reviewed.

**Pull request closed without merging**
