### PR TITLE
New features and bug fixes for Backup-DbaDatabase

### PR DESCRIPTION
**Pull request by Stuart-Moore**
## Type of Change

 - [x] Bug fix (non-breaking change, fixes #<enter issue number>)
 - [x] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [x] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [x] Pester test is included
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
The precedence of parameters is now fixed at :
Fully qualified filename beats everything
multiple BackupDirectory beat FileCount

New features:
* OutputScriptOnly 
* NUL as a path, I use this a lot for flushing things or seeing how slow the storage is
* IgnoreFileChecks - useful in some edge cases where the SQL instance has unusual permissions to teh backup area
* BuildPath - Will attempt to build the backup path if it doesn't exist.

### Commands to test
See Backup-DbaDatabase.Tests.ps1

### CODE REVIEW

**Comment by potatoqualitee** [comment]
@niphlod or @Zhunya - yall can give this a lookover? I'm pumped to add new features 😂

**Comment by potatoqualitee** [comment]
Thanks @Stuart-Moore for adding tests too!

**Comment by amaechler** [comment]
@Stuart-Moore I tested this PR in regards to #1890 (specifically your last comment [here](https://github.com/sqlcollaborative/dbatools/issues/1890#issuecomment-383868086)) and `BackupFileName` with `IgnoreFileCheck` now works great. 👍

**Comment by potatoqualitee** [comment]
thank you everyone! sorry i didnt notice the approval earlier D:

**Pull request merged**
