### PR TITLE
Issue 3687

### PR DESCRIPTION
**Pull request by mikepetrak**
## Type of Change

 - [ ] Bug fix (non-breaking change, fixes #<enter issue number>)
 - [X] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
 

Allow searching in TextHeader.
Fix IncludeSystemObjects code branch issue.
Update old-style join.

### CODE REVIEW

**Comment by mikepetrak** [comment]
1 test failed but it doesn't look related to my changes - any thoughts here? Thanks. :

Describe : InModule.Commands Integration Tests
Context  : duplicate commands are not added
Name     : It only indexes one instance per command
Result   : Failed
Message  : Expected $null, but got @('New-DbaDbDataGeneratorConfig', 'Invoke-DbaDbDataGenerator', 'Get-DbaRandomizedValue', 'Get-DbaRandomizedDatasetTemplate', 'Get-DbaRandomizedDataset', 'Get-DbaRandomizedType').
1 tests failed.

**Comment by wsmelton** [comment]
That would be @potatoqualitee needs to update the manifest for some new commands that were added recently it seems.

**Comment by wsmelton** [comment]
You can ignore that test when it fails, it is something we maintain (myself and/or Chrissy).

**Comment by potatoqualitee** [comment]
my bad, lemme merge fixed dev and see the passes 💯

**Comment by potatoqualitee** [comment]
all tests pass! 🍌 💃  thanks so much

**Comment by mikepetrak** [comment]
You're welcome. Thanks for the help, @wsmelton and @potatoqualitee !

**Pull request merged**
