### PR TITLE
Fixing Snapshot tests

### PR DESCRIPTION
**Pull request by potatoqualitee**
Silent just allows Exceptions to be thrown but I don't see any try
catches. This param will soon be renamed to AllowException /cc @niphlod

### CODE REVIEW

**Comment by potatoqualitee** [comment]
awesome, i was able to repro errors locally - will now fix

image

**Comment by niphlod** [comment]
hum, ok. -Silent just remained in because I was trying to see how pester handles exceptions on the callbacks.

**Comment by niphlod** [comment]
they now pass (for whatever reason) and the incorrect failure due to setup is signalled.

**Comment by potatoqualitee** [comment]
hell yes!!!!! thank you!

**Pull request merged**
