### PR TITLE
Get-DbaRoleMember credentialfix

### LINKED ISSUE #748: Get-DBARoleMember uses incorrect $credential value
### Is this a *feature* OR *bug*:
bug

### System Details

Evaluate $PSVersionTable in PowerShell and paste the output here
Name                           Value                                                                                                                                
----                           -----                                                                                                                                
PSVersion                      5.0.10586.117                                                                                                                        
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                              
BuildVersion                   10.0.10586.117                                                                                                                       
CLRVersion                     4.0.30319.42000                                                                                                                      
WSManStackVersion              3.0                                                                                                                                  
PSRemotingProtocolVersion      2.3                                                                                                                                  
SerializationVersion           1.1.0.1   

- Output of dbatools version:

```
Evaluate (Get-Module dbatools -ListAvailable).Version and paste output here
```
Major  Minor  Build  Revision
-----  -----  -----  --------
0      8      900    -1      

- SQL Server version for source/target
N/A

### Steps to Reproduce

- Create a pscredential using $credential

- Use it to create a user Beard_Service_User16 

- Run Get-DbaRoleMember -SqlInstance $server |ogv

- Try  to delete Beard_Service_User16 

- Error Beard_Service_User16  has a connection open

- Have a look at processes

Beard_Service_User16             dbatools PowerShell module - dbatools.io        tempdb             0

I was surprised as I make sure I don't use $SQLCredential in my scripts ;-) but it looks like the code would not use the parameter passed in for a SQL Credential

https://github.com/sqlcollaborative/dbatools/blob/master/functions/Get-DbaRoleMember.ps1#L73

### PR DESCRIPTION
**Pull request by PowerDBAKlaas**
Fixes #748 

Changes proposed in this pull request:
 - replace '$Credentail' with '$SqlCredential'
 - add $functionName
 - improve verbosity

How to test this code: 
- [ ] 
- [ ] 

Has been tested on minimum requirements:
- [ ]  Powershell 3
- [ ]  Windows 7
- [ ]  SQL Server 2000

Has been tested on maximum requirements:
- [ ]  SQL Server vNext
- [ ]  Windows 10
- [ ]  Azure Database

Tests for tester:
- [ ] Working/useful help content, including link to command on dbatools web site
- [ ] All examples work as advertised
- [ ] Does not contain template content
- [ ] Does not contain excessive/unnecessary amounts of comments
- [ ] Works remotely
- [ ] Works locally
- [ ] Works on lower versions or throws error specifying version not supported
- [ ] Works with named instances
- [ ] Works with clustered instances
- [ ] Handles offline/read only databases
- [ ] Supports multiple servers (at the command line or piped from Get-SqlRegisteredServerName)
- [ ] No un-handled errors which stop the command working with multiple servers

### CODE REVIEW

**Comment by PowerDBAKlaas** [comment]
@SQLDBAWithABeard can you give feedback on this, please?

**Comment by SQLDBAWithABeard** [comment]
@PowerDBAKlaas  Approved :-)

**Comment by ctrlbold** [comment]
@PowerDBAKlaas @Stuart-Moore and @FriedrichWeinmann - we should create an internal Write-DbaVerbose that has the command name in it, that way we dont have to include this trick in every change.

Usually, I don't like attaching Dba to internal commands, but I couldn't come up with anything that would make sense and still be memorable.

**Comment by ctrlbold** [comment]
@FriedrichWeinmann said he's working on a Write-Message command that will address this.

**Pull request merged**
