### PR TITLE
Update Find-DbaStoredProcedure.ps1

### PR DESCRIPTION
**Pull request by mikepetrak**
Fixed main problem in Issue 3687 - find in TextHeader. Updated old-style join to normal join. Ran Invoke-DbaToolsFormatter.

## Type of Change

 - [ ] Bug fix (non-breaking change, fixes #<enter issue number>)
 - [X] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
 
Address Issue 3687 - find in TextHeader

### CODE REVIEW

**Comment by wsmelton** [comment]
Seems the formatting is broke, that is what the test fails for on this command....not sure what editor you are using?

**Comment by wsmelton** [comment]
Also we ask that you ensure you have your development branch in sync with upstream when submitting PRs. I believe the other test failure will be resolved once you sync your branch with ours.

**Comment by mikepetrak** [comment]
Thanks, @wsmelton . Let me try this again: I did a fresh fork from dbatools and a clone and then re-did my changes. I used Visual Studio Code as the editor. It formats things correctly, but I try to use Invoke-DbaToolsFormatter on the file before committing, and that messed up the formatting when I removed the unnecessary IncudeSystemObjects SMO branch at the bottom. I run Invoke-DbaToolsFormatter because the automated testing often fails for me with that suggestion. Thanks.

**Comment by wsmelton** [comment]
We have a format file for VS Code in the repository so when you clone it down and open the workspace you can just use the formatting in VS Code.

After you have forked the repository you will simply need to add an upstream on your local system (not something VS Code allows in the UI). It is `git remote add upstream https://github.com/sqlcollaborative/dbatools.git` (or the SSH address if that is what you prefer to use).

After you add that upstream you can go into VS Code, make sure you have development checked out and then do the command palette option to pull from another remote. Just type in `git pull from`, you will see the 'upstream' added above in that list and then pick the development branch. That will "sync" our changes to your local development, then you can just create a branch from there.

**Comment by mikepetrak** [comment]
Thanks, @wsmelton . For git work I have been using GitHub desktop, but will give this approach in VS Code a try next time. I tried fixing this issue this morning but got a separate (unrelated?) issue: https://github.com/sqlcollaborative/dbatools/pull/5340

**Pull request closed without merging**
