### PR TITLE
Login to SMO Output

### PR DESCRIPTION
**Pull request by potatoqualitee**

### CODE REVIEW

**Comment by nvarscar** [comment]
👍 
PS There is $newLogin variable that contains the SMO object already, no need to call Get-DbaLogin.
```
$newLogin.Refresh()
$newLogin
```

**Comment by potatoqualitee** [comment]
Get-DbaLogin makes it pretty 💅

**Comment by potatoqualitee** [comment]
Can you plz help with my failing tests 😂

**Comment by nvarscar** [comment]
Looking into it 👀 
For some reason it fails to return objects in the same order, it seems. I wonder if it's "by design".

**Comment by potatoqualitee** [comment]
thank you 💃  about to publicize it on twitter if we can get it merged within 2h rs

**Comment by nvarscar** [comment]
Hopefully it should be good now. There is a renaming pattern in that test that swap login names - `-LoginRenameHashtable @{claudio = 'port'; port = 'claudio'}`, it expected the logins to appear in a different order.

**Comment by potatoqualitee** [comment]
passed!

**Pull request merged**
