### PR TITLE
Fix Get-DbaDBFile to return filestream file info, too

### PR DESCRIPTION
**Pull request by iampeterdaniels**
## Type of Change

 - [ ] Bug fix (non-breaking change, fixes # )
 - [ ] New feature (non-breaking change, adds functionality, fixes # )
 - [X ] Breaking change (effects multiple commands or functionality, fixes # )
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
Get-DbaDbFile was not returning information on FILESTREAM files(folders), so I
wanted to update it so it would.

### Approach
Changed the inner join to sys.dm_io_virtual_file_stats to a left join
and updated a number of columns in the select list to coalesce NULLs
into 0s.

### Screenshots

image

### CODE REVIEW

**Comment by iampeterdaniels** [comment]
Create new issue for this:
https://github.com/sqlcollaborative/dbatools/issues/7109

I'm wondering if a less impactful way to add this functionality might be to add a flag/switch parm, -IncludeFileStream so it doesn't break existing code.

**Comment by wsmelton** [comment]
Have not done much on this command but how did this break other commands? If you can reference which commands are showing as broken we will review and verify the impact.

**Comment by iampeterdaniels** [comment]
Hi Shawn.  I actually was not certain that I broke other commands - just assumed it could since we're outputting additional objects (the FILESTREAM file type).  However, now that I look ate the failed checks in appveyor above, I wonder if my changes did break something.  Apologies for my newbosity - much handholding through this process will be helpful for me.

**Comment by wsmelton** [comment]
Sadly we have some tests that are not consistent in the Appveyor environment.

If you are using VS Code it should give you a reference count on where it finds the function being used:

image

That tends to pick up anywhere it finds `Get-DbaDbFile` referenced, which could include tests files so to be sure I do a search filtering on just ps1 files:
image

The command is used a good bit but the tests that failed do not seem to be where this command is being referenced that I can see. I can look at it more closely this weekend and let you know if needed.

**Comment by wsmelton** [comment]
If you are able to run that test locally though without any issue we generally are good to go but I'm not sure what all the test for this function covers.

**Comment by potatoqualitee** [comment]
Hey @iampeterdaniels ! Thank you so very much for the PR. I'm so sorry this has taken a bit to get merged. This part of the lockdown has been particularly challenging and I, for one, am just busted. We'll work to get your PR merged this week.

**Comment by jpomfret** [comment]
The tests for `Get-DbaDbFile` run successfully for me locally.
image

Also pulled down the PR branch and did a little testing:
(First database has a filestream file, second doesn't)
image

The failed tests are different this morning from when @potatoqualitee ran them last night 
- Get-DbaPermission - runs successful locally
- Get-DbaHelpIndex - runs successful locally
- Get-DbaFile - **fails locally**
- Get-DbaLastBackup - **fails locally**
- Get-DbaDbVirtualLogFile - runs successful locally
- Save-DbaKbUpdate - runs successful locally

Not sure that the two that are failing for me are related to this PR - will dig a little deeper later today.

**Comment by jpomfret** [comment]
Alright brought in changes @potatoqualitee merged earlier and now tests are all green - merging..

**Review by jpomfret — APPROVED** [review]
tested it out - looks good

**Comment by jpomfret** [comment]
Also @iampeterdaniels thanks so much for contributing!

**Comment by iampeterdaniels** [comment]
Chrissy, you never cease to amaze me.  No apology necessary!  It is I that should apologize.  I put up my first PR and did not follow up and run the tests the Shawn requested.  I’m struggling with pandemic brain fog, too.  Many thanks for all you and the team do!  Thank you Jess Pomfret for your merge efforts!

Much love for this team,

-Peter

**Pull request merged**
