### PR TITLE
Improve ConvertTo-DbaDatatable

### LINKED ISSUE #4938: ConvertTo-DbaDataTable is not converting all data (Out-DbaDataTable is)
```powershell
<#
param (
    $Instances      = ('xxxxx','xxxxxx','xxxxxx')
 )

[System.Reflection.Assembly]::LoadWithPartialName('Microsoft.SqlServer.SMO') | out-null 

$Results = @()

foreach($instance in $Instances){
    $srv = new-object ('Microsoft.SqlServer.Management.Smo.Server') $instance  

    $Q = "SELECT @@SERVERNAME AS Instance,
	Name AS DatabaseName,
	Compatibility_level,
	Collation_name,
	State_desc,
	Snapshot_isolation_state_desc,
	Is_read_committed_snapshot_on,
	Recovery_model_desc,
	Page_verify_option_desc,
	Is_trustworthy_on,
	Is_auto_shrink_on 
    FROM sys.databases 
    WHERE 1=1
    and Database_id > 4
    "

    $srv = new-Object Microsoft.SqlServer.Management.Smo.Server($instance)
    $db = New-Object Microsoft.SqlServer.Management.Smo.Database
    $db = $srv.Databases.Item('master')
        
    $result = $db.ExecuteWithResults($Q)

    if($result.Tables.Instance.Count -gt 0){
        $Results += $result.Tables
    }
}

$dtable = $Results|ConvertTo-DbaDataTable #Run this on Last version
$dtable = $Results|Out-DbaDataTable #Run this on 0.8.957 

#>
```

## Expected Behavior

All data that is in $Results to be converted and piped into $dtable

## Actual Behavior

With ConvertTo, only the first(!) server is piped over. Even thou $Results got more data.

## Environmental data

PSVersion   5.1.14393.2636
SQL 2017 CU 12

### PR DESCRIPTION
**Pull request by ClaudioESSilva**
## Type of Change

 - [x] Bug fix (non-breaking change, fixes #4938)
 - [ ] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
Support multiple tables within $inputObject (do ConvertTo-DbaDataTable)

### Approach
Instead of Copy the table once and no more, this way we will merge each row and retrieve only the DISTINCT rows.

### Screenshots
image
Top - Before
bottom - After

code was the one that @wabby80 shared on #4938

### CODE REVIEW

**Comment by potatoqualitee** [comment]
@wabby80 can you give us the thumbs up?

**Comment by potatoqualitee** [comment]
and thanks forever claudio!!!

**Comment by ClaudioESSilva** [comment]
You need to test with this branch. This wasn't merge into prerelease yet 😃

**Comment by potatoqualitee** [comment]
got a confirmation in the channel, adding now 💯 it's a beautiful fix, thank you

**Pull request merged**
