### PR TITLE
Fixing up Azure credential handling in Backup and Restore

### LINKED ISSUE #4322: Restore-DbaDatabase AzureCredential fails when using Shared Access Signature
### Before submitting a bug report:

- [x ] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [x ] Verified this bug is not already reported in an issue
- [x ] Verified errors are not related to permissions
- [x] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

## Steps to Reproduce

CREATE CREDENTIAL [yourBlobStoreCredentialName]
WITH IDENTITY = 'Shared Access Signature',
SECRET = 'yourLongSAS'

```

```powershell PS C:\dbatools> Restore-DbaDatabase -AzureCredential yourBlobStoreCredentialName -SqlInstance TargetSQLInstanceToRestoreTo  -Path <URL Path to BACKUP FILE>
```

## Expected Behavior

Database is restored from Backup File

## Actual Behavior

WARNING: [15:03:49][Get-DbaBackupInformation] Failure reading backup header | Use of WITH CREDENTIAL syntax is not valid for credentials containing a Shared Access Signature. RESTORE HEADERONLY is terminating abnormally.

Looks to me like the Credential is required to be created with the Access Key and not a Shared Access Signature.  It's my understaning that using the SAS is preferred over an Access Key as they can be generated and destroyed on demand while the two Access Keys are tied tightly to the Storage Account.

## Environmental data

 - PowerShell: 

Name                           Value
----                           -----
PSVersion                      5.1.14393.2515
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.2515
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

 - - SQL Server: 
Microsoft SQL Server 2017 (RTM-GDR) (KB4293803) - 14.0.2002.14 (X64)   Jul 21 2018 07:47:45   Copyright (C) 2017 Microsoft Corporation  Standard Edition (64-bit) on Windows Server 2016 Datacenter 10.0 <X64> (Build 14393: ) (Hypervisor)

### PR DESCRIPTION
**Pull request by Stuart-Moore**
## Type of Change

 - [x] Bug fix (non-breaking change, fixes #4322)
 - [ ] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [x] Pester test is included
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
Fixing up the issues with Azure Credential handling from #4322 
### Approach
Test-DbaBackupInformation now doesn't try to path check 'files' begining http

Backup-DbaDatabase now checks for a SAS credential before complaining if a URL is passed in. Allows all allowed backup features when using SAS for backup to URL

Restore-DbaDatabase uses the same SAS/Key testing as well.

Got the Azure backup integration tests working

Added test for striping with restore from URL with SAS

Paramterised the tests for Azure Restore/Backup so people can modify a local constants.ps1 if they want to check locally than blocking appveyor time.

### CODE REVIEW

**Comment by potatoqualitee** [comment]
thank you so much for all of your work on this

**Comment by sqldba-today** [comment]
I posted this back to my original issue - #4322 , not sure if it will be very visible since it's been closed.. so reposting here..

This is VERY CLOSE! There is an issue with the regexp you added on line 544 of Restore-DbaBackup.ps1
$f.BackupPath -match 'https://././'

The regex is greedy and the first .*/ matches to the last / found. In my case, the backup path from Get-DbaBackupHistory comes out as

https://mystorageaccount.blob.core.windows.net/mycontainer/myservername/myinstancename\mydaabasename\mybackupfile.bak

And so $matches[0] holds
https://mystorageaccount.blob.core.windows.net/mycontainer/myservername/

If I change the regex to https://.?/.?/ it works as expected. It matches only the first two /'s after https://
https://mystorageaccount.blob.core.windows.net/mycontainer/
and $matches[0].trim('/') will match to my SAS credential.

**Comment by sqldba-today** [comment]
Actually, this regex would match forward or trailing slashes after the container portion of the URI.  
Lines 544 and 545
````
$f.BackupPath -match 'https://.*?/.*?[/\\]'
                            if (Get-DbaCredential -SqlInstance $RestoreInstance -name .trimend('/').trimend('\')) {
```

And, awesome work on this entire ecosystem!!!!

**Comment by Knicker** [comment]
It still doens't working for me: 

```
DETALLADO: [18:50:30][Test-DbaLastBackup] Getting recent backup history for STAGE_CO_DB on BSWPA78.
DETALLADO: [18:50:30][Test-DbaLastBackup] Skipping Log backups as requested.
DETALLADO: [18:50:30][Get-DbaDbBackupHistory] Processing STAGE_CO_DB
DETALLADO: [18:50:30][Get-DbaDbBackupHistory] Executing sql query on [BSWPA78].
DETALLADO: [18:50:30][Get-DbaDbBackupHistory] Processing as grouped output.
DETALLADO: [18:50:30][Get-DbaDbBackupHistory] 16 result-groups found.
DETALLADO: [18:50:30][Get-DbaDbBackupHistory] Processing STAGE_CO_DB
DETALLADO: [18:50:30][Get-DbaDbBackupHistory] Executing sql query on [BSWPA78].
DETALLADO: [18:50:30][Get-DbaDbBackupHistory] Processing as grouped output.
DETALLADO: [18:50:30][Get-DbaDbBackupHistory] 1 result-groups found.
DETALLADO: [18:50:30][Test-DbaLastBackup] SQL Server cannot find backup.
DETALLADO: [18:50:30][Test-DbaLastBackup] Looking good.
DETALLADO: [18:50:30][Read-DbaBackupHeader] Checking: https://pruebaoh.blob.core.windows.net/contenedorprueba/BSWPA78/STAGE_CO_DB/FULL/BSWPA78_STAGE_CO_DB_FULL_20200127_162611_01.bak
DETALLADO: [18:50:30][Read-DbaBackupHeader] Checking: https://pruebaoh.blob.core.windows.net/contenedorprueba/BSWPA78/STAGE_CO_DB/FULL/BSWPA78_STAGE_CO_DB_FULL_20200127_162611_02.bak
DETALLADO: [18:50:30][Read-DbaBackupHeader] Checking: https://pruebaoh.blob.core.windows.net/contenedorprueba/BSWPA78/STAGE_CO_DB/FULL/BSWPA78_STAGE_CO_DB_FULL_20200127_162611_03.bak
DETALLADO: [18:50:30][Read-DbaBackupHeader] Checking: https://pruebaoh.blob.core.windows.net/contenedorprueba/BSWPA78/STAGE_CO_DB/FULL/BSWPA78_STAGE_CO_DB_FULL_20200127_162611_04.bak
DETALLADO: [18:50:30][Read-DbaBackupHeader] Checking: https://pruebaoh.blob.core.windows.net/contenedorprueba/BSWPA78/STAGE_CO_DB/FULL/BSWPA78_STAGE_CO_DB_FULL_20200127_162611_05.bak
DETALLADO: [18:50:30][Read-DbaBackupHeader] Checking: https://pruebaoh.blob.core.windows.net/contenedorprueba/BSWPA78/STAGE_CO_DB/FULL/BSWPA78_STAGE_CO_DB_FULL_20200127_162611_06.bak
DETALLADO: [18:50:30][Read-DbaBackupHeader] Checking: https://pruebaoh.blob.core.windows.net/contenedorprueba/BSWPA78/STAGE_CO_DB/FULL/BSWPA78_STAGE_CO_DB_FULL_20200127_162611_07.bak
DETALLADO: [18:50:30][Read-DbaBackupHeader] Checking: https://pruebaoh.blob.core.windows.net/contenedorprueba/BSWPA78/STAGE_CO_DB/FULL/BSWPA78_STAGE_CO_DB_FULL_20200127_162611_08.bak
DETALLADO: [18:50:30][Read-DbaBackupHeader] Checking: https://pruebaoh.blob.core.windows.net/contenedorprueba/BSWPA78/STAGE_CO_DB/FULL/BSWPA78_STAGE_CO_DB_FULL_20200127_162611_09.bak
DETALLADO: [18:50:30][Read-DbaBackupHeader] Checking: https://pruebaoh.blob.core.windows.net/contenedorprueba/BSWPA78/STAGE_CO_DB/FULL/BSWPA78_STAGE_CO_DB_FULL_20200127_162611_10.bak
DETALLADO: [18:50:30][Read-DbaBackupHeader] Checking: https://pruebaoh.blob.core.windows.net/contenedorprueba/BSWPA78/STAGE_CO_DB/FULL/BSWPA78_STAGE_CO_DB_FULL_20200127_162611_11.bak
DETALLADO: [18:50:30][Read-DbaBackupHeader] Checking: https://pruebaoh.blob.core.windows.net/contenedorprueba/BSWPA78/STAGE_CO_DB/FULL/BSWPA78_STAGE_CO_DB_FULL_20200127_162611_12.bak
DETALLADO: [18:50:30][Read-DbaBackupHeader] Checking: https://pruebaoh.blob.core.windows.net/contenedorprueba/BSWPA78/STAGE_CO_DB/FULL/BSWPA78_STAGE_CO_DB_FULL_20200127_162611_13.bak
DETALLADO: [18:50:30][Read-DbaBackupHeader] Checking: https://pruebaoh.blob.core.windows.net/contenedorprueba/BSWPA78/STAGE_CO_DB/FULL/BSWPA78_STAGE_CO_DB_FULL_20200127_162611_14.bak
DETALLADO: [18:50:30][Read-DbaBackupHeader] Checking: https://pruebaoh.blob.core.windows.net/contenedorprueba/BSWPA78/STAGE_CO_DB/FULL/BSWPA78_STAGE_CO_DB_FULL_20200127_162611_15.bak
DETALLADO: [18:50:30][Read-DbaBackupHeader] Checking: https://pruebaoh.blob.core.windows.net/contenedorprueba/BSWPA78/STAGE_CO_DB/FULL/BSWPA78_STAGE_CO_DB_FULL_20200127_162611_16.bak
DETALLADO: [18:50:30][Read-DbaBackupHeader] 16 unique files to scan.
DETALLADO: [18:50:30][Read-DbaBackupHeader] Checking accessibility for all the files.
DETALLADO: [18:50:31][Read-DbaBackupHeader] Scanning file https://pruebaoh.blob.core.windows.net/contenedorprueba/BSWPA78/STAGE_CO_DB/FULL/BSWPA78_STAGE_CO_DB_FULL_20200127_162611_01.bak.
DETALLADO: [18:50:31][Read-DbaBackupHeader] Scanning file https://pruebaoh.blob.core.windows.net/contenedorprueba/BSWPA78/STAGE_CO_DB/FULL/BSWPA78_STAGE_CO_DB_FULL_20200127_162611_02.bak.
DETALLADO: [18:50:31][Read-DbaBackupHeader] Scanning file https://pruebaoh.blob.core.windows.net/contenedorprueba/BSWPA78/STAGE_CO_DB/FULL/BSWPA78_STAGE_CO_DB_FULL_20200127_162611_03.bak.
DETALLADO: [18:50:31][Read-DbaBackupHeader] Scanning file https://pruebaoh.blob.core.windows.net/contenedorprueba/BSWPA78/STAGE_CO_DB/FULL/BSWPA78_STAGE_CO_DB_FULL_20200127_162611_04.bak.
DETALLADO: [18:50:31][Read-DbaBackupHeader] Scanning file https://pruebaoh.blob.core.windows.net/contenedorprueba/BSWPA78/STAGE_CO_DB/FULL/BSWPA78_STAGE_CO_DB_FULL_20200127_162611_05.bak.
DETALLADO: [18:50:31][Read-DbaBackupHeader] Scanning file https://pruebaoh.blob.core.windows.net/contenedorprueba/BSWPA78/STAGE_CO_DB/FULL/BSWPA78_STAGE_CO_DB_FULL_20200127_162611_06.bak.
DETALLADO: [18:50:31][Read-DbaBackupHeader] Scanning file https://pruebaoh.blob.core.windows.net/contenedorprueba/BSWPA78/STAGE_CO_DB/FULL/BSWPA78_STAGE_CO_DB_FULL_20200127_162611_07.bak.
DETALLADO: [18:50:31][Read-DbaBackupHeader] Scanning file https://pruebaoh.blob.core.windows.net/contenedorprueba/BSWPA78/STAGE_CO_DB/FULL/BSWPA78_STAGE_CO_DB_FULL_20200127_162611_08.bak.
DETALLADO: [18:50:31][Read-DbaBackupHeader] Scanning file https://pruebaoh.blob.core.windows.net/contenedorprueba/BSWPA78/STAGE_CO_DB/FULL/BSWPA78_STAGE_CO_DB_FULL_20200127_162611_09.bak.
DETALLADO: [18:50:31][Read-DbaBackupHeader] Scanning file https://pruebaoh.blob.core.windows.net/contenedorprueba/BSWPA78/STAGE_CO_DB/FULL/BSWPA78_STAGE_CO_DB_FULL_20200127_162611_10.bak.
DETALLADO: [18:50:31][Read-DbaBackupHeader] Scanning file https://pruebaoh.blob.core.windows.net/contenedorprueba/BSWPA78/STAGE_CO_DB/FULL/BSWPA78_STAGE_CO_DB_FULL_20200127_162611_11.bak.
DETALLADO: [18:50:31][Read-DbaBackupHeader] Scanning file https://pruebaoh.blob.core.windows.net/contenedorprueba/BSWPA78/STAGE_CO_DB/FULL/BSWPA78_STAGE_CO_DB_FULL_20200127_162611_12.bak.
DETALLADO: [18:50:31][Read-DbaBackupHeader] Scanning file https://pruebaoh.blob.core.windows.net/contenedorprueba/BSWPA78/STAGE_CO_DB/FULL/BSWPA78_STAGE_CO_DB_FULL_20200127_162611_13.bak.
DETALLADO: [18:50:31][Read-DbaBackupHeader] Scanning file https://pruebaoh.blob.core.windows.net/contenedorprueba/BSWPA78/STAGE_CO_DB/FULL/BSWPA78_STAGE_CO_DB_FULL_20200127_162611_14.bak.
DETALLADO: [18:50:31][Read-DbaBackupHeader] Scanning file https://pruebaoh.blob.core.windows.net/contenedorprueba/BSWPA78/STAGE_CO_DB/FULL/BSWPA78_STAGE_CO_DB_FULL_20200127_162611_15.bak.
DETALLADO: [18:50:31][Read-DbaBackupHeader] Scanning file https://pruebaoh.blob.core.windows.net/contenedorprueba/BSWPA78/STAGE_CO_DB/FULL/BSWPA78_STAGE_CO_DB_FULL_20200127_162611_16.bak.
DETALLADO: Se está realizando la operación "Restoring STAGE_CO_DB as dbatools-testrestore-STAGE_CO_DB." en el destino "BSWPA78".
DETALLADO: [18:51:32][Test-DbaLastBackup] Performing restore.
DETALLADO: [18:51:33][Restore-DbaDatabase] Changing statement timeout to infinity
DETALLADO: [18:51:33][Restore-DbaDatabase] ParameterSet  = Restore
DETALLADO: [18:51:33][Restore-DbaDatabase] Trust Database Backup History Set
DETALLADO: [18:51:33][Restore-DbaDatabase] adding BackupPath - https://pruebaoh.blob.core.windows.net/contenedorprueba/BSWPA78/STAGE_CO_DB/FULL/BSWPA78_STAGE_CO_DB_FULL_20200127_162611_01.bak https://pruebaoh.blob.core.windows.net/contenedorprueba/BSWPA78/ST
AGE_CO_DB/FULL/BSWPA78_STAGE_CO_DB_FULL_20200127_162611_02.bak https://pruebaoh.blob.core.windows.net/contenedorprueba/BSWPA78/STAGE_CO_DB/FULL/BSWPA78_STAGE_CO_DB_FULL_20200127_162611_03.bak https://pruebaoh.blob.core.windows.net/contenedorprueba/BSWPA78/ST
AGE_CO_DB/FULL/BSWPA78_STAGE_CO_DB_FULL_20200127_162611_04.bak https://pruebaoh.blob.core.windows.net/contenedorprueba/BSWPA78/STAGE_CO_DB/FULL/BSWPA78_STAGE_CO_DB_FULL_20200127_162611_05.bak https://pruebaoh.blob.core.windows.net/contenedorprueba/BSWPA78/ST
AGE_CO_DB/FULL/BSWPA78_STAGE_CO_DB_FULL_20200127_162611_06.bak https://pruebaoh.blob.core.windows.net/contenedorprueba/BSWPA78/STAGE_CO_DB/FULL/BSWPA78_STAGE_CO_DB_FULL_20200127_162611_07.bak https://pruebaoh.blob.core.windows.net/contenedorprueba/BSWPA78/ST
AGE_CO_DB/FULL/BSWPA78_STAGE_CO_DB_FULL_20200127_162611_08.bak https://pruebaoh.blob.core.windows.net/contenedorprueba/BSWPA78/STAGE_CO_DB/FULL/BSWPA78_STAGE_CO_DB_FULL_20200127_162611_09.bak https://pruebaoh.blob.core.windows.net/contenedorprueba/BSWPA78/ST
AGE_CO_DB/FULL/BSWPA78_STAGE_CO_DB_FULL_20200127_162611_10.bak https://pruebaoh.blob.core.windows.net/contenedorprueba/BSWPA78/STAGE_CO_DB/FULL/BSWPA78_STAGE_CO_DB_FULL_20200127_162611_11.bak https://pruebaoh.blob.core.windows.net/contenedorprueba/BSWPA78/ST
AGE_CO_DB/FULL/BSWPA78_STAGE_CO_DB_FULL_20200127_162611_12.bak https://pruebaoh.blob.core.windows.net/contenedorprueba/BSWPA78/STAGE_CO_DB/FULL/BSWPA78_STAGE_CO_DB_FULL_20200127_162611_13.bak https://pruebaoh.blob.core.windows.net/contenedorprueba/BSWPA78/ST
AGE_CO_DB/FULL/BSWPA78_STAGE_CO_DB_FULL_20200127_162611_14.bak https://pruebaoh.blob.core.windows.net/contenedorprueba/BSWPA78/STAGE_CO_DB/FULL/BSWPA78_STAGE_CO_DB_FULL_20200127_162611_15.bak https://pruebaoh.blob.core.windows.net/contenedorprueba/BSWPA78/ST
AGE_CO_DB/FULL/BSWPA78_STAGE_CO_DB_FULL_20200127_162611_16.bak
DETALLADO: Se está realizando la operación "Showing results" en el destino "console".


SourceServer   : BSWPA78
TestServer     : BSWPA78
Database       : STAGE_CO_DB
FileExists     : True
Size           : 3,01 GB
RestoreResult  : A URL to a backup has been passed in, but no credential can be found to access it
DbccResult     : Skipped
RestoreStart   : 2020-01-27 18:51:32.983
RestoreEnd     : 2020-01-27 18:51:33.200
RestoreElapsed : 00:00:00
DbccStart      : 
DbccEnd        : 
DbccElapsed    : 
BackupDates    : {01/27/2020 16:26:13}
BackupFiles    : {https://pruebaoh.blob.core.windows.net/contenedorprueba/BSWPA78/STAGE_CO_DB/FULL/BSWPA78_STAGE_CO_DB_FULL_20200127_162611_01.bak, 
                 https://pruebaoh.blob.core.windows.net/contenedorprueba/BSWPA78/STAGE_CO_DB/FULL/BSWPA78_STAGE_CO_DB_FULL_20200127_162611_02.bak, 
                 https://pruebaoh.blob.core.windows.net/contenedorprueba/BSWPA78/STAGE_CO_DB/FULL/BSWPA78_STAGE_CO_DB_FULL_20200127_162611_03.bak, 
                 https://pruebaoh.blob.core.windows.net/contenedorprueba/BSWPA78/STAGE_CO_DB/FULL/BSWPA78_STAGE_CO_DB_FULL_20200127_162611_04.bak...}
``` 

I use this command: 
``` powershell
Test-DbaLastBackup -SqlInstance BSWPA78 -Database STAGE_CO_DB -IgnoreLogBackup -Verbose
```

**Comment by wsmelton** [comment]
Please post to the issue, it has been reopened.

**Pull request merged**
