### PR TITLE
Bunch of new commands revolving around exports

### PR DESCRIPTION
**Pull request by potatoqualitee**
Export-DbaInstance needs a smidge more work, then will be ready

### CODE REVIEW

**Comment by wsmelton** [comment]
We not going to add the warning on deprecated parameters (e.g. FilePath to just Path)?

**Comment by potatoqualitee** [comment]
naw, just gonna leave the alias in forever. it's useful for gci piping

**Comment by potatoqualitee** [comment]
thank you for looking

**Comment by potatoqualitee** [comment]
also wrt get-dbatrigger, just gonna make an announcement or something because the new proper commands are so drastically different. there's no new replacement.

**Pull request merged**
