### PR TITLE
Adjust test for Find-DbaOrphanedFile

### PR DESCRIPTION
**Pull request by wsmelton**
- Standardized test to be against one instance.
- Added unit test for parameters

### CODE REVIEW

**Comment by potatoqualitee** [comment]
i poked around this one for a while and found the combination in there worked the best, though not always 100% 👎  but it did have the best odds

**Comment by wsmelton** [comment]
I'm not sure I see what the need is to just validate a database is not on instance1, but all the work of creating and detaching are being done for testing the command against instance2?

**Comment by wsmelton** [comment]
Right now I'm having the issue Appveyor is having on this test. It fails on loading the library, so the Query() method is not available.

**Comment by wsmelton** [comment]
This is all I'm getting on this test now:

image

If I go run another command that uses that Query() method get same result:
image

**Comment by niphlod** [comment]
uhm, lemme check if that happens for me too.

**Comment by wsmelton** [comment]
This is because of VS Code and the integrated terminal @niphlod

**Comment by niphlod** [comment]
to be fair, I can't use development in a fresh PS console 2 out of 3 times.... and why would appveyor fail ?

**Comment by niphlod** [comment]
hum. dotsource is maybe the answer ....

**Comment by niphlod** [comment]
nope. it's the fact we import the psm1 in appveyor (which enables us testing internals, I *think*) and the dll module not being loaded correctly.

**Comment by potatoqualitee** [comment]
looks like you guys got it to work 👍 thank you!

**Pull request merged**
