### PR TITLE
Reset-DbaAdmin - Corrected some wrong variables

### PR DESCRIPTION
**Pull request by andreasjordan**
## Type of Change

 - [x] Bug fix (non-breaking change, fixes # )
 - [ ] New feature (non-breaking change, adds functionality, fixes # )
 - [ ] Breaking change (effects multiple commands or functionality, fixes # )
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 
Corrected some obviously wrong variables and changed the case of some varible names to the standard.

### CODE REVIEW

**Comment by andreasjordan** [comment]
In addition to the changes made: Can someone have a look at the variable $password. Is it necessary or can it be replaced by $SecurePassword?

**Comment by andreasjordan** [comment]
And another question: Why is it necessary to get $ipaddr and $hostName? 
$hostName is used to open the session and $ipaddr is used to get the services.
This can not be done with $baseaddress (= $instance.ComputerName)?

**Comment by wsmelton** [comment]
The functionality in the command to prompt for password stays.

**Comment by wsmelton** [comment]
Trying with the host and IP is required due to various customer configurations in both networks and servers. This command has been around for many years and some changes were made around it because of user feedback.

**Comment by wsmelton** [comment]
Memory serves the IP and hostname stuff had to deal with users that have multiple-tier DNS or multiple site domains, where the IP had to be used vs the hostname. We had same situations around the resolve command for that too....but can't recall if we ever put all that "story" in an issue/PR.

**Comment by andreasjordan** [comment]
> Memory serves the IP and hostname stuff had to deal with users that have multiple-tier DNS or multiple site domains, where the IP had to be used vs the hostname. We had same situations around the resolve command for that too....but can't recall if we ever put all that "story" in an issue/PR.

Thanks for the info. The reason for the question was to learn something about the modul and the command. I think there is a bug inside that part of the code, but I'll do more testing and open an issue then.

**Comment by andreasjordan** [comment]
> The functionality in the command to prompt for password stays.

@wsmelton I don't want to delete this. Just wanted to understand the reason for the new variable, because later on the use is not consistent in my eyes. $password is used to construct the sql, but later the login test is done with $SecurePassword. But in the case the user is prompted for the password, $SecurePassword is never updated with that so the test will fail. Is this intended?

**Comment by wsmelton** [comment]
The password prompt does work as I've used it many times in resetting instances.

**Pull request merged**
