### PR TITLE
Copy-DbaTableData, fixes #3468

### LINKED ISSUE #3468: Copy-DbaTableData fails with more than 1 -Table provided
### General Troubleshooting steps

Tested with 0.9.315, 0.9.318, 0.9.319
- [X] Verified running the latest release of dbatools?
- [X] Verified errors are not related to permissions?
- [X] Can duplicate in new/clean PowerShell session (clean = `powershell -NoProfile`)?

### Version Information
 - Operating System (Windows 10): 
 - PowerShell Version: 5.1
 - SQL Server (Enterprise | 13.0.4474.0): 

## Issue
When I supply 2 tables to the -Table parameter, I get an error that the DataReader is already open.  This occurs when I use 2 different shapes available in the Examples in the .ps1 file.

## Steps to Reproduce
```Powershell
Copy-DbaTableData -SqlInstance 'usServer,1234' -Database 'TemporaryDB' -Destination 'usServer,1234' -DestinationDatabase 'MyDestinationDatabase' -Table 'ww.Comment', 'ww.Entity' -KeepIdentity -KeepNulls -BatchSize 5000 -Truncate
```
The following option from the Example section also fails for the same reason:
```Powershell
Get-DbaTable -SqlInstance 'usServer,1234' -Database TemporaryDB -Table ww.Comment, testing.Competitor | Copy-DbaTableData -Destination 'usServer,1234' -DestinationDatabase 'MyDestinationDatabase' -KeepIdentity -KeepNulls -BatchSize 5000 -Truncate
```

image

### Problem to solve
Allow for an array of tables to copy be used in -Table

### PR DESCRIPTION
**Pull request by niphlod**
## Type of Change

 - [X] Bug fix (non-breaking change, fixes #3468)
 - [ ] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [x] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 
### Purpose
Fix the bug. Also, fix other bugs, slipped in in recent commits because the test file didn't actually include any test (and that's probably why this slipped in). New pester mantra "No `It` without `Should`"

### Approach
@potatoqualitee : please take a look. Had to obliterate $InputObject because it accumulates over and over. Not sure the mass-rewrite about $InputObject had impacts or not, but basically without nulling it at the bottom the only piped element considered is the first one on the pipeline. Couldn't wrap my head around it after the first hour, sorry for the not elegant fix.

### CODE REVIEW

**Comment by potatoqualitee** [comment]
lemme take a look at this party...

**Comment by potatoqualitee** [comment]
Soooo the InputObject thing was a hack and not properly implemented. I just fixed it and the tests pass locally, thanks for those!  🎉

**Comment by niphlod** [comment]
watch out, you replaced the tests with the function ^_^

**Comment by potatoqualitee** [comment]
oh god! nooooo!

**Comment by potatoqualitee** [comment]
thanks please check my work (also github was being dumb which is why i have dupes)

**Comment by niphlod** [comment]
now if tests pass you're good to go ^_^

**Comment by potatoqualitee** [comment]
it's failing on some close :/

**Comment by potatoqualitee** [comment]
merging to new branch so i can sync with dev

**Pull request merged**
