### PR TITLE
Get-DbaDependency - detect a circular reference

### LINKED ISSUE #7139: Get-DbaDependency gets stuck in loop when InputObject has a circular reference.
### Report

Get-DbaDependency gets stuck in loop when InputObject has a circular reference.

#### Host used
Name             : Visual Studio Code Host
Version          : 2020.6.0
InstanceId       : 447ac6de-6823-4100-86ee-ae7ba383d496
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : en-US
CurrentUICulture : en-US
PrivateData      : Microsoft.PowerShell.EditorServices.Services.PowerShellContext.EditorServicesPSHost+ConsoleColorProxy
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace

#### Errors Received
None.  The command is stuck in loop.

#### Steps to Reproduce
Create a couple inter dependent tables.
```
CREATE TABLE [dbo].[TableA](
	[TableAId] [int] NOT NULL,
	[TableBId] [int] NULL,
 CONSTRAINT [PK_TableA] PRIMARY KEY CLUSTERED 
(
	[TableAId] ASC
))
GO
CREATE TABLE [dbo].[TableB](
	[TableBId] [int] NOT NULL,
	[TableAId] [int] NOT NULL,
 CONSTRAINT [PK_TableB] PRIMARY KEY CLUSTERED 
(
	[TableBId] ASC
))
GO
ALTER TABLE [dbo].[TableA]  WITH CHECK ADD  CONSTRAINT [FK_TableA_TableB] FOREIGN KEY([TableBId])
REFERENCES [dbo].[TableB] ([TableBId])
GO
ALTER TABLE [dbo].[TableA] CHECK CONSTRAINT [FK_TableA_TableB]
GO
ALTER TABLE [dbo].[TableB]  WITH CHECK ADD  CONSTRAINT [FK_TableB_TableA] FOREIGN KEY([TableAId])
REFERENCES [dbo].[TableA] ([TableAId])
GO
ALTER TABLE [dbo].[TableB] CHECK CONSTRAINT [FK_TableB_TableA]
GO
```
Execute these
```
$tablea = Get-DbaDbTable -SqlInstance localhost -Database CircRef -table "tablea"
$tableA | Get-DbaDependency
## this is where it gets stuck
```
#### Expected Behavior
When descending the dependency tree and parent object is detected as a child
Then include child object in output and ascend dependency tree and continue to traverse the remaining siblings and children.

#### Actual Behavior
Command gets stuck with no output.

### Environmental information
```poweshell
PowerShell Version        : 7.1.0
dbatools latest installed : 1.0.135
Culture of OS             : en-US
```

#### SQL Server:

```sql
select @@VERSION
-- Microsoft SQL Server 2016 (SP1-GDR) (KB4505219) - 13.0.4259.0 (X64)   Jun 15 2019 19:20:12   Copyright (c) Microsoft Corporation  Developer Edition (64-bit) on Windows 10 Pro 6.3 <X64> (Build 19042: ) (Hypervisor) ```
select @@LANGUAGE
-- us_english
```

### PR DESCRIPTION
**Pull request by lancasteradam**
Get-DbaDependency - detect a circular reference

## Type of Change

 - [x] Bug fix (non-breaking change, fixes # )
 - [ ] New feature (non-breaking change, adds functionality, fixes # )
 - [ ] Breaking change (effects multiple commands or functionality, fixes # )
 - [x] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [x] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
 
Ensure the dependency check does not get into an infinite loop.

### Approach

The code checks if it has already processed the dependency.

### Commands to test

See the new integration test.

### CODE REVIEW

**Review by SamWalkerRxSense — COMMENTED** [review]
@lancasteradam  Thanks for getting on this so quickly, I'd started fork over here, but was still fussing around with it.
https://github.com/SamWalkerRxSense/dbatools/blob/circ_ref/functions/Get-DbaDependency.ps1
I'd took a different approach to examine the Parent properties recursively to detect the circular reference instead of maintaining a separate object list, which avoided passing another parameter, but added another function.  Not sure if one is preferable over the other, but thought I'd let you know.

**Comment by lancasteradam** [comment]
@SamWalkerRxSense, your solution looks great. I would defer to your proposed fix and integration tests as the preferred solution. I suggest a minor change to the output message to be the 'warning' level and to output all available info to the caller. Something like this:

```
$circularReferenceCheck = Read-Parent -InputObject $Parent
if ($Tier -gt 0 -and $circularReferenceCheck.Value -Contains $InputObject.Urn.Value) {
    Write-Message -Message "Circular Reference detected. $circularReferenceCheck" -Level Warning
    return # End dependency tree descension here.
}
```

Do you want to create a new pull request with your proposed changes? It's important you get credit for your fix. I'm happy to withdraw this PR.

**Comment by SamWalkerRxSense** [comment]
@lancasteradam Thanks, I could use a little experience with GitHub PR process.  I'm a novice.  I cleaned up my changes and opened this PR.  Thanks for the advice, I wasn't sure on those message levels.  I also added Tier to final grouping to allow the same object to appear at different Tiers when -IncludeSelf is true.
https://github.com/sqlcollaborative/dbatools/pull/7151

**Comment by lancasteradam** [comment]
@SamWalkerRxSense, the new PR looks great. I'll close this one. Great work!

**Pull request closed without merging**
