### PR TITLE
Get-DbaPrivilege: Include "Logon as a service" right

### PR DESCRIPTION
**Pull request by andreasjordan**
## Type of Change

 - [x] Bug fix (non-breaking change, fixes # )
 - [x] New feature (non-breaking change, adds functionality, fixes # )
 - [ ] Breaking change (effects multiple commands or functionality, fixes # )
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1`)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Unit test is included
 - [ ] Documentation
 - [ ] Build system

### CODE REVIEW

**Comment by andreasjordan** [comment]
Is a replacement for #7735

**Comment by potatoqualitee** [comment]
hey @andreasjordan - thanks so much for figuring this out! would you mind copy/pasting your changes onto the code of #7735 and reopen that one so that the author gets to be included in the contributor since they contributed the idea?

**Comment by andreasjordan** [comment]
Yes, would like to do that - just don't know how to commit to a foreign repo. Can you do that?

**Comment by potatoqualitee** [comment]
yes, no problem! i do it in GitHub Desktop, I'll reopen now and close that one once it's been committed

**Comment by andreasjordan** [comment]
Thanks!

**Comment by potatoqualitee** [comment]
Thanks again, updated in other PR and closing this one.

**Pull request closed without merging**
