### PR TITLE
Migration++

### PR DESCRIPTION
**Pull request by potatoqualitee**
Migrate to multiple servers at once

`Copy-DbaLogin -Source sql2012 -Destination sql2016, sql2017 -Force`

image

When performing Copy-DbaDatabase, the backup is only performed once. Subsequent restores are performed from the original backup, then it's deleted at the end unless `-NoBackupCleanup` or whatever is specified.

`Get-DbaDatabase -SqlInstance sql2012 -Database db_2005_CL80 | Copy-DbaDatabase -Destination sql2016, sql2017 -BackupRestore -NetworkShare \\dc\sql -Force`

image

`Copy-DbaDatabase -Source sql2012 -Destination sql2016, sql2017 -BackupRestore -NetworkShare \\dc\sql -Database db2 -Force -NoBackupCleanup`

Since SqlInstances are now a thing, I should probably modify the default output.

### CODE REVIEW

**Comment by potatoqualitee** [comment]
Still need to modify start-dbamigration

**Comment by niphlod** [comment]
those are gonna be renamed in Spread/Distribute-Dba* hehe .... I'd personally not taken this route to complication for any Copy-Dba* .
A certain number of those are hellish to tame if some "element" doesn't get copied for some reason, and this just spreads yet another level of "to-tame" on top. 
In the end, maybe just copy-dbadatabase "backup-restore" plan was the only one that couldn't be solved by a simple outer loop (and even that sooner or later needs to be broken apart, or each new feature will just add another level of complexity).

**Comment by potatoqualitee** [comment]
@Zhunya - that is an `exception` while I wait for the fix ;)

**Comment by potatoqualitee** [comment]
@niphlod  - that beauty is reserved for the next round where i enable piping 😰

**Comment by niphlod** [comment]
codecov is there because this branch spawned before the last fix ^_^

**Comment by potatoqualitee** [comment]
oh yay @niphlod  great news!

**Pull request merged**
