### PR TITLE
[internal command] Get-JobList to filter the job object

### LINKED ISSUE #196: Copy-SqlAgentJob - Allow the ability to exclude/incldue jobs based on partial name
Copy-SqlAgentJob - Allow the ability to exclude/include jobs based on partial name. (I.e. All jobs that start with Admin)

### PR DESCRIPTION
**Pull request by wsmelton**
## Type of Change

 - [ ] Bug fix (non-breaking change, fixes #<enter issue number>)
 - [x] New feature (non-breaking change, adds functionality, fixes #196 )
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Pester test is included

### Purpose
 
Internal command per discussion with Chrissy to offer a cleaner way to filter the JobServer.Jobs object for commands.

### Approach

See issue for details on purpose of this command. I'm just doing what the boss says.
### Commands to test

```powershell
Import-Module dbatools.psm1

# (1) return all jobs on the server
Get-JobList -SqlInstance YourServer

# (2) return all jobs with "job" in the name
Get-JobList -SqlInstance YourServer -Filter '*job*'

# (3) return all jobs that don't have "job" in the name
Get-JobList -SqlInstance YourServer -Filter '*job*' -Not

# (4) return a job that is JobName
Get-JobList -SqlInstance YourServer -Filter 'JobName'

# (5) return all jobs that are not JobName
Get-JobList -SqlInstance YourServer -Filter 'JobName' -Not

# (6) return jobs "collection_set_3_upload" and "collection_set_3_collection"
Get-JobList -SqlInstance YourServer -Filter collection_set_3_upload, collection_set_3_collection

# (7) return all jobs that are not "collection_set_3_upload" or "collection_set_3_collection"
Get-JobList -SqlInstance YourServer -Filter collection_set_3_upload, collection_set_3_collection -Not
```
### Screenshots

image

image

image

image

### CODE REVIEW

**Comment by potatoqualitee** [comment]
very nice! would you be able to add this functionality to Find-DbaAgentJob (or whatever its name ;)) 🙇  and attach to PR> Thnk youuuuu

**Comment by wsmelton** [comment]
Will do, but may have to adjust a good bit on that one at first glance. To prevent calling this command multiple times.

**Comment by gbargsley** [comment]
@wsmelton 
Not sure I know how to test internal functions.  I did the import you list and when I run the first test it does not return anything.

image

**Comment by potatoqualitee** [comment]
Do psm1 in this case 👍

**Comment by gbargsley** [comment]
Ok, it is just the first command. Returns nothing.  I thought it was because I had my agent stopped, but once I started agent still the test that is supposed to get all jobs get nothing.

Get-JobList -SqlInstance L7DR15466

**Comment by gbargsley** [comment]
I am still not sure why this is not displaying anything?  Downloaded the latest code and still nothing.

image

**Comment by wsmelton** [comment]
You need to remove the module or restart your PS session before trying to import the psm1 file.

**Comment by gbargsley** [comment]
I still get no output after following your suggestion.

image

**Comment by wsmelton** [comment]
Updated it to return all jobs.

Also note there are no message output in this command so verbose and such will never show anything.

**Comment by wsmelton** [comment]
@potatoqualitee Updated `Find-DbaAgentJob`

I renamed a few of the parameters to be `IsXxxx` or `IsNot` but some just don't sound right so if you want to rename them or I need to put them back as is, just let me know.

@gbargsley the main variation in the find command is I dropped the need for the `-Exact` parameter. It now supports regular expression in the `JobName` and `StepName` parameter.

```powershell
# return all jobs that start with "backup" in the job name
Find-DbaAgentJob -SqlInstance sql2016 -JobName backup*

# return all jobs that have the name equal "backup"
Find-DbaAgentJob -SqlInstance sql2016 -JobName backup
```

**Pull request merged**
