### PR TITLE
WorkstationId, MARS and password

### PR DESCRIPTION
**Pull request by zippy1981**
This is the final list of parameters I think should be in there unless someone asks for more. I'm wondering at this point if this cmdlet still makes sense with New-DbaSqlConnectionString though. This will work without SMO, which is good.

Moving on to other things either way, probably password encryption.

Changes proposed in this pull request:
 - `-Password` works now
 - ``New paramaters
  - `-WorkstationID`
  - `-MultipleActiveResultSets` `-MARS`
  - `ColumnEncryptedSetting`, `-Mars`

How to test this code: 
- [ ] Set those settings

Has been tested on minimum requirements:
- [ ]  Powershell 3
- [ ]  Windows 7
- [ ]  SQL Server 2000

Has been tested on maximum requirements:
- [ ]  SQL Server vNext
- [ ]  Windows 10
- [ ]  Azure Database

Tests for tester:
- [ ] Working/useful help content, including link to command on dbatools web site
- [ ] All examples work as advertised
- [ ] Does not contain template content
- [ ] Does not contain excessive/unnecessary amounts of comments
- [ ] Works remotely
- [ ] Works locally
- [ ] Works on lower versions or throws error specifying version not supported
- [ ] Works with named instances
- [ ] Works with clustered instances
- [ ] Handles offline/read only databases
- [ ] Supports multiple servers (at the command line or piped from Get-SqlRegisteredServerName)
- [ ] No un-handled errors which stop the command working with multiple servers

### CODE REVIEW

**Comment by potatoqualitee** [comment]
hey zippy - dont forget to add help for your new params. as for SMO, the module autoloads it so there's no need to avoid it. And I can see the benefit of both commands :)

**Comment by potatoqualitee** [comment]
So close! Just need documentation for 3 params and we can merge.

**Comment by zippy1981** [comment]
merge away!

**Comment by potatoqualitee** [comment]
Excellent! Thank you 🌮🌮 🌯

**Pull request merged**
