### PR TITLE
Find dbaloginingroup fix

### PR DESCRIPTION
**Pull request by ctrlbold**

### CODE REVIEW

**Comment by ctrlbold** [comment]
hey @niphlod and @Staggerlee011 -- I removed the pipe holdup and cleaned up a couple things but I don't think the -Login param is working as expected. Please fix in Find-DbaLoginInGroup-Fix branch.

image

**Comment by ctrlbold** [comment]
Also, login should be the whole login, no? like BASE\ctrlb instead of ctrlb

**Comment by ctrlbold** [comment]
dang, this command is making other tests fail until it's in dev. I'll merge then file bug report.

**Comment by niphlod** [comment]
the only culrpit I see is that the loginname is not reported with the domain. everything else works as expected

**Comment by niphlod** [comment]
sent a fix over .

**Comment by niphlod** [comment]
this should be fixed already. @ctrlbold ping me if not

**Pull request merged**
