### PR TITLE
initial commit of New-DbaDatabaseSnapshot

### PR DESCRIPTION
**Pull request by niphlod**
How to test this code: 
- [ ] start testing with one/two instances and one/two databases, to see if any of the core method fail or warns
- [ ] carefully enlarge the set
- [ ] the most error-prone part for the code is figuring out the entire filestructure. Try throwing at it your most intricated structures
- [ ] test if a database with FileStream gets partially snapshotted (with -Force)

Has been tested on minimum requirements:
- [ ]  Powershell 3
- [ ]  Windows 7
- [ ]  SQL Server 2000

Has been tested on maximum requirements:
- [ ]  SQL Server vNext
- [ ]  Windows 10
- [ ]  Azure Database

Tests for tester:
- [ ] Working/useful help content, including link to command on dbatools web site
- [ ] All examples work as advertised
- [ ] Does not contain template content
- [ ] Does not contain excessive/unnecessary amounts of comments
- [ ] Works remotely
- [ ] Works locally
- [ ] Works on lower versions or throws error specifying version not supported
- [ ] Works with named instances
- [ ] Works with clustered instances
- [ ] Handles offline/read only databases
- [ ] Supports multiple servers (at the command line or piped from Get-SqlRegisteredServerName)
- [ ] No un-handled errors which stop the command working with multiple servers

### CODE REVIEW

**Comment by niphlod** [comment]
found a bug. db with filestream fail. need to check it before starting the snap process and require -Force to create a "partial" snapshot leaving FS out of it.

**Comment by niphlod** [comment]
fixed the case where a Filestream is in the database

**Comment by ctrlbold** [comment]
Unfortunately, on .create(), I'm getting: Failed to update database "Application_Registry_Service_DB_cde90313b64848408b625cb9b083eaf3_20161219_120245" because the database is read-only.

**Comment by niphlod** [comment]
ok, we need to change the approach. 
The underlying problem is that SMO is somewhat bugged and *can* issue multiple statements, but we can't anticipate beforehand if all of them are plain wrong or just "additional details" we can't foresee. 
Given though the first is always the one actually creating the snapshot and all of the following are "post-creation" statements, I'd go for a double try{}catch{} (the first with what SMO suggests, if it fails just the first statement it generates) and we'll track the "partial" execution with a "status" column. In the "notes" section, if it's a known case, we'll add progressively what we find out (e.g. Filestream Groups, Read-Only database, etc)
On top of that, to be able to receive user inputs, I'll add a Write-Debug with the generated statement so we can figure out ourselves without requiring the user to trace the error at the backend what is going on under the hood of SMO.

**Comment by niphlod** [comment]
@ctrlbold : could you try again please ?

**Comment by ctrlbold** [comment]
PS C:\Users\ctrlb.BASE> New-DbaDatabaseSnapshot -SqlInstance sqlserver -Databases Application_Registry_Service_DB_cde90313b64848408b625cb9b083eaf3


Server          : sqlserver
Database        : Application_Registry_Service_DB_cde90313b64848408b625cb9b083eaf3_20161219_215033
SnapshotOf      : Application_Registry_Service_DB_cde90313b64848408b625cb9b083eaf3
SizeMB          : 9.75
DatabaseCreated : 12/19/2016 12:50:34 PM
Status          : Partial
Notes           :

Unsure what Partial means? otherwise, works!

**Comment by niphlod** [comment]
dang. Partial means something along the line errored. But if that is a ReadOnly db, it should have been accompanied by a "proper" Notes column.

**Comment by ctrlbold** [comment]
notes are empty D: want access to my lab?

**Comment by niphlod** [comment]
please try one more time, if it doesn't work I'll need to review the logic in a proper 2016 instance

**Comment by ctrlbold** [comment]
So sorry, still partial and did a copy / paste of new code. this is 2016

**Comment by niphlod** [comment]
at least with -Debug you can now inspect what SMO is trying to do ^_^ . lemme fire up a remote connection to a 2016 instance and report back

**Comment by niphlod** [comment]
image
 this is what I get on mine, which is 13.0.4001.0, for a snapshot on a read-only database

**Comment by ctrlbold** [comment]
Hey @niphlod - this works beautifully in 2005-2014, but fails in both 2016 and vnext. Can you put in a check -- if version is < 2016 use the whole statement, but if more then just use the first statement? or alternatively, check for a -match of "ALTER DATABASE SCOPED CONFIGURATION" and remove that array item from the resulting script.

**Comment by niphlod** [comment]
It should still create the snap...or doesn't it?
The whole point is having feedback if something doesn't go as SMO plans,
but the snap is created nonetheless, and work around before issuing the
creation if it fails even to create the snap.

Il 24 dic 2016 01:23, "Chrissy LeMaire" <notifications@github.com> ha
scritto:

**Comment by ctrlbold** [comment]
Yes, it works, but I'm left with the impression that it didn't. And it's not being honest -- the snapshot was created just fine but SMO has a bug where it tries to do something it shouldn't. I'm going to merge then modify.

**Pull request merged**
