### PR TITLE
Reset-DbaAdmin - Fix indentation

### PR DESCRIPTION
**Pull request by andreasjordan**
Only changed the indentation because VSCode showed me "a see of yellow".

### CODE REVIEW

**Comment by andreasjordan** [comment]
"Sea of yellow"

**Comment by wsmelton** [comment]
The formatting on VS Code is not perfect. Test fails showing it is off for that command now. We have a command to run that fixes the indenting.

```
Describe : dbatools style
Context  : formatting
Name     : It Reset-DbaAdmin.ps1 is adopting OTSB formatting style. Please run Invoke-DbatoolsFormatter against the failing file and commit the changes.
Result   : Failed
Message  : Expected 0, but got 1.
```

**Comment by andreasjordan** [comment]
Cool, Invoke-DbatoolsFormatter also changes the "-eq" to "-EQ" in the "Where-Object". So this could be corrected automatically in all commandlets - is this planned?

**Comment by wsmelton** [comment]
No, not planned.

**Comment by wsmelton** [comment]
@andreasjordan I'm not sure what sea of yellow you are referring to for this PR.

I've checked the file in VS Code and see no formatting issues. Also ran the `Invoke-DbatoolsFormatter` against the current version in development and it shows no issues.

**Comment by andreasjordan** [comment]
image

This is what my VSCode shows. The mouse over says: "Indentation not consistent PSScriptAnalyzer(PSUseConsistentIndentation)". 
So I thought it would be nice to fix this. I did this manualy because I didn't know about Invoke-DbatoolsFormatter.

If you think I broke the command with my changes then just reject the PR.

**Comment by wsmelton** [comment]
Ah, yeah that rule is bogus and does not parse legitimate formatting properly. I recall there is an issue submitted for that rule to the PSSA repo.

We don't acknowledge or apply that rule at this time and do not test for it because of the issues it cannot handle.

**Comment by andreasjordan** [comment]
@wsmelton Just that I do this right in the future: You generally don't care about wrong indentation? Or do you think that the try-catch-block from line 179 to 204 is formatted correctly?

**Comment by wsmelton** [comment]
That command is formatted properly with correct indentations.

**Comment by andreasjordan** [comment]
Sorry, I don't understand that. Maybe I can't express myself good in englisch, so let me draw a picture:

image

But I think I've already annoyed enough, I will sleep over that (so we say in germany) and mybe I get it then.

**Comment by wsmelton** [comment]
I follow. You will have to restructure the command to fix those indentation issues.

**Comment by wsmelton** [comment]
The way this PR reads on the changes makes it look like chunks of code were removed..not sure if that was from an issue with GitHub that cleared up about an hour ago or not.

**Pull request closed without merging**
