### PR TITLE
Connect-DbaInstance: Masking password in verbose output

### LINKED ISSUE #6328: Connect-DbaInstance displays sensitive Information.
When you have $VerbosePreference = 'Continue'
Connect-DbaInstance will display sensitive information (Login and Password) in the verbose Output.

```
$AZServer = (Connect-DbaInstance -SqlInstance "azure-sql-server.windows.net" -Database $AZDatabase -MaxPoolSize 10 -SqlCredential $AzureAdminCreds)

#Output.....
VERBOSE: [11:47:07][Connect-DbaInstance] Data Source=TCP:azure-sql-server.windows.net,1433;Initial Catalog=DWdb;User 
ID=sqluser;Password=password;Max Pool Size=10;MultipleActiveResultSets=False;Connect Timeout=30;Encrypt=True;
TrustServerCertificate=False;Application Name="dbatools PowerShell module - dbatools.io"

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.0.0.0    CredentialTools                     {Export-Credential, Get-MyCredential}
Script     1.0.85     dbatools                            {Select-DbaObject, Set-DbatoolsConfig, Add-DbaAgDatabase, Add-DbaAgListener...}

Name                           Value
----                           -----
PSVersion                      5.1.18362.145
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.145
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

### LINKED ISSUE #6330: [Bug] Set-DbaPrivilege showing verbose message
image

Note: There is no -Verbose switch provided and preference is set to silent for the session, yet still shows that one verbose message for some reason.

### PR DESCRIPTION
**Pull request by nvarscar**
## Type of Change

 - [x] Bug fix (non-breaking change, fixes #6328   )
 - [ ] New feature (non-breaking change, adds functionality, fixes # )
 - [ ] Breaking change (effects multiple commands or functionality, fixes # )
 - [x] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
Hide sensitive data yet still allow for some debugging

### Approach
Replace the Password field with ********

### Commands to test
Connect-DbaInstance when used with Azure

### CODE REVIEW

**Comment by nvarscar** [comment]
marked wrong issue. Should be #6328

**Comment by potatoqualitee** [comment]
yall are awesome, thank you will publish now

**Comment by niphlod** [comment]
hi @cl wait a bit, i have a fix for get-dbadatabase on azure

**Comment by potatoqualitee** [comment]
shoot done already

**Pull request merged**
