### PR TITLE
Set-DbaTempDbConfiguration: fix Split-Path error

### LINKED ISSUE #1363: Set-DbaTempDbConfiguration fails with "Split-Path : Cannot bind argument to parameter 'Path' because it is null", generates incorrect T-SQL statements
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [ ] *feature* 
- [X] *bug*:

## System Details

- Operating system name and version: Windows 8.1 Enterprise
- Output from `$PSVersionTable`:

```
Name                           Value
----                           -----
PSVersion                      5.1.14409.1005
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1005
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

- Output of dbatools version:

```
Major  Minor  Build  Revision
-----  -----  -----  --------
0      8      957    -1
```

- SQL Server version for source/target
SQL Server 2014
SQL Server 2012

## Steps to Reproduce

1. New server with default tempdb configuration (1 data file, 1 log file.)
```
name     db_size       owner     dbid   created     status                                                                                                                                                                                                 compatibility_level
-------- ------------- --------- ------ ----------- ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ -------------------
tempdb        11.44 MB sa        2      May 30 2017 Status=ONLINE, Updateability=READ_WRITE, UserAccess=MULTI_USER, Recovery=SIMPLE, Version=782, Collation=SQL_Latin1_General_CP1_CI_AS, SQLSortOrder=52, IsAutoCreateStatistics, IsAutoUpdateStatistics  120

 
name     fileid filename                                        filegroup  size       maxsize    growth  usage
-------- ------ ----------------------------------------------- ---------- ---------- ---------- ------- ---------
tempdev  1      F:\MSSQL12.MSSQLSERVER\MSSQL\Data\tempdb.mdf    PRIMARY    10944 KB   Unlimited  10%     data only
templog  2      F:\MSSQL12.MSSQLSERVER\MSSQL\Data\templog.ldf   NULL       768 KB     Unlimited  10%     log only
```

2. Run Command:
```powershell
Set-DbaTempDbConfiguration -SqlInstance SERVERNAME -DataFileSizeMB 2048 -LogFileSizeMB 500 -WhatIf -Verbose
```
3. Received following error
```powershell
Split-Path : Cannot bind argument to parameter 'Path' because it is null.
At line:223 char:28
+                 $Filename = Split-Path $File.FileName -Leaf
+                                        ~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Split-Path], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.SplitPathCo
   mmand

Split-Path : Cannot bind argument to parameter 'Path' because it is null.
At line:223 char:28
+                 $Filename = Split-Path $File.FileName -Leaf
+                                        ~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Split-Path], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.SplitPathCo
   mmand
```

## Action Results
Set-DbaTempDbConfiguration fails to determine the logical file and physical file name for the existing tempdb data file. Generated statements are incorrect, with the logical file and physical file names missing, and three MODIFY FILE statements rather than two MODIFY FILE and one ADD FILE:

```
ALTER DATABASE tempdb MODIFY FILE(name=,filename='F:\MSSQL12.MSSQLSERVER\MSSQL\Data\',size=1024 MB,filegrowth=512);
ALTER DATABASE tempdb MODIFY FILE(name=,filename='F:\MSSQL12.MSSQLSERVER\MSSQL\Data\',size=1024 MB,filegrowth=512);
ALTER DATABASE tempdb MODIFY FILE(name=templog,filename='F:\MSSQL12.MSSQLSERVER\MSSQL\Data\templog.ldf',size=500 MB,filegrowth=512);
```
## Expected Results

1. New server with default tempdb configuration (1 data file, 1 log file.)
2. Run Command:
```powershell
Set-DbaTempDbConfiguration -SqlInstance SERVERNAME -DataFileSizeMB 2048 -LogFileSizeMB 500 -WhatIf -Verbose
```
3. Receive following output (if applicable)
No errors, generated statements have correct logical and physical file names.

```
ALTER DATABASE tempdb MODIFY FILE(name=tempdev,filename='F:\MSSQL12.MSSQLSERVER\MSSQL\Data\tempdb.mdf',size=1024 MB,filegrowth=512);
ALTER DATABASE tempdb MODIFY FILE(name=templog,filename='F:\MSSQL12.MSSQLSERVER\MSSQL\Data\templog.ldf',size=500 MB,filegrowth=512);
ALTER DATABASE tempdb ADD FILE (name=tempdev2,filename='F:\MSSQL12.MSSQLSERVER\MSSQL\Data\tempdev2.ndf',size=1024MB,filegrowth=512);
```
## Attached screen shots/console output

image

### Import - Attach dbatools logs

[dbatools_27876_message_0.log.txt](https://github.com/sqlcollaborative/dbatools/files/1039746/dbatools_27876_message_0.log.txt)

### PR DESCRIPTION
**Pull request by kozloski**
Fixes #1363 

Changes proposed in this pull request:
 - explicitly reference first table (and first row, if single value expected) from ExecuteWithResults() 
    * `.ExecuteWithResults().Tables[0]` - first table
    * `.ExecuteWithResults().Tables[0].Rows[0]` - first row
 - also found issue with case-sensitive server collations, correct `select f.Name` to `select f.name as Name`

How to test this code: 
- SQL Server 2005+ instance with default tempdb configuration (one data file, one log file.)
```
Set-DbaTempDbConfiguration -SqlInstance SERVERNAME -DataFileSizeMB <DataFileSizeMB> -WhatIf -Verbose
```
Failure:
image

Success:
image

Has been tested on minimum requirements:
- [ ]  Powershell 3
- [ ]  Windows 7
- [ ]  SQL Server 2000

Has been tested on maximum requirements:
- [ ]  SQL Server vNext
- [ ]  Windows 10
- [ ]  Azure Database

Tests for tester:
- [ ] Working/useful help content, including link to command on dbatools web site
- [ ] All examples work as advertised
- [ ] Does not contain template content
- [ ] Does not contain excessive/unnecessary amounts of comments
- [ ] Works remotely
- [ ] Works locally
- [ ] Works on lower versions or throws error specifying version not supported
- [ ] Works with named instances
- [ ] Works with clustered instances
- [ ] Handles offline/read only databases
- [ ] Supports multiple servers (at the command line or piped from Get-SqlRegisteredServerName)
- [ ] No un-handled errors which stop the command working with multiple servers

### CODE REVIEW

**Comment by ConstantineK** [comment]
Looks like the appveyor tests are still breaking around unrelated stuff, PR looks pretty good 👍

**Comment by potatoqualitee** [comment]
wow! so fast! awesome 🌮  🌮  🌮  🌮  Will test shortly.

and yeah @ConstantineK  - sometimes that frikken restore test doesnt work, especially in dev branch. im assuming it runs out of memory? 👎  Will figure it out.

**Comment by potatoqualitee** [comment]
Thanks again, @kozloski!

**Comment by potatoqualitee** [comment]
Heck yeah, worked great! 😎

**Comment by kozloski** [comment]
Awesome! Thanks @potatoqualitee  and @ConstantineK !

**Pull request merged**
