### PR TITLE
New-DbaDbMailAccount

### PR DESCRIPTION
**Pull request by potatoqualitee**
new command with tests - another command is still needed tho, one that makes mail servers

`Microsoft.SqlServer.Management.Smo.Mail.MailServer`

### CODE REVIEW

**Comment by wsmelton** [comment]
Reviewing this now to fix some of the issues on the test failures.

One note is that you don't create mail servers with DB Mail. You just create profiles and accounts. The mail server ican be setup within a given profile or each account can have a mail server. Your ideal setup would be your profile to have the SMTP configured so it is reusable and does not require you to adjust all the accounts.

**Comment by wsmelton** [comment]
Debugging this one a bit more because I'm getting the same failure on my container that Appveyor shows.

**Comment by wsmelton** [comment]
Ok....took me to long to figure that one out. Missing the parameter name for `Stop-Function`.

Fixed and the command fails properly when the mail server does not exists.

**Comment by potatoqualitee** [comment]
heyy thanks @wsmelton ! fixed a merge issue and tests have been running better, let's see if this works

**Comment by potatoqualitee** [comment]
finalllllly i can merge this!

**Comment by potatoqualitee** [comment]
the problem was indeed my code which was suitable to work only when the server name was typed w/o aliases. so localhost\sql2016 failed cuz it was appveyor-win\slq2016. yay pester tests

**Pull request merged**
