### PR TITLE
Warning instead of sea of blood - fixes #3945

### LINKED ISSUE #3945: Issue restoring diffs with Restore-Dba-Backups
# sql server 2016 dev edition - windows 10
# backup and restore with no recovery, later we want a diff
Backup-DbaDatabase -SqlInstance server1 -Database (Get-Content C:\temp\dbs.txt) -BackupDirectory "\\server2\Backup" -Type Full | Restore-DbaDatabase -SqlInstance server2 -NoRecovery
# make a diff backup and restore it
Backup-DbaDatabase -SqlInstance server1 -Database (Get-Content C:\temp\dbs.txt) -BackupDirectory "\\server2\Backup" -Type Diff | Restore-DbaDatabase -SqlInstance server2

# error thrown

The property 'Fullname' cannot be found on this object. Verify that the property exists and can be set.
At C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.395\allcommands.ps1:70899 char:17
+ ...             $full.Fullname = ($DatabaseHistory | Where-Object {$_.Typ ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound

# a backup is created and restored and then a diff is created so its the final restore that seems to have an issue

### PR DESCRIPTION
**Pull request by potatoqualitee**
## Type of Change

 - [x] Bug fix (non-breaking change, fixes #3945
 - [ ] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 
### Purpose
Inform people and do not error so hard

### Approach
catch dat

### Commands to test
check screenshot

### Screenshots
image

### CODE REVIEW

**Comment by FriedrichWeinmann** [comment]
Awesome reaction time, looking good 👍

**Comment by potatoqualitee** [comment]
thanks, bud!

**Comment by Stuart-Moore** [comment]
That's not the only thing that could be at issue. It really means that no
Full backup has been found. So could be a bad set of files or someone
forgetting the continue switch

Backseating as I'm in and out of meetings atm. Will put something more
robust around the lack of full if continue not specified later on

**Comment by potatoqualitee** [comment]
Thanks @Stuart-Moore - can you also take a look at the failing unit tests? I did update the wording to be more accurate.

**Comment by Stuart-Moore** [comment]
The test was broken from the setup. Just tweaked the fake fullname header and all is good

**Pull request merged**
