### PR TITLE
WIP: Tag connections as NewDbaConnection (True|False)

### LINKED ISSUE #6211: [Bug] Connect-DbaInstance creates new connections even when we already have a connection
#### PowerShell version:

```
Name                           Value
----                           -----
PSVersion                      5.1.18362.145
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.145
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
#### dbatools Module version:
```
Name    : dbatools
Path    : C:\Users\joel\Documents\PowerShell\Modules\dbatools\1.0.72\dbatools.psd1
Version : 1.0.72
```

#### SQL Server: 

```
Microsoft SQL Azure (RTM) - 12.0.2000.8
   Oct 12 2019 22:46:48
   Copyright (C) 2019 Microsoft Corporation
```

### Report

Because of #6210 we are trying to call `Invoke-DbaQuery` with a connection pre-created by calling `Connect-DbaInstance` so that we can then `Disconnect` it after, but this doesn't work and we _still_ run out of connections in the pool.

After reading and re-reading the source we narrowed it down to the fact that line 421 is the only way (with an Azure database) to escape creating a new connection:

https://github.com/sqlcollaborative/dbatools/blob/ce04da16798e9b4019d03ac6934b8d7a7d141ca8/functions/Connect-DbaInstance.ps1#L420-L423

So unless I explicitly specify `-Database master` it will create a new connection every time, and use _that_ connection instead of the one that I gave it. 

To summarize the problems with this:
1. Given that in Azure there's no support for `default_database` for users, `Connect-DbaInstance` should assume that if `-Database` is not specified, then it's _master_.
2. `Connect-DbaInstance` needs to add note properties on the connections it returns to indicate whether it's returning what was passed in or a copy it created. Otherwise, there's no way for a caller to detect they have created a new connections -- and since this is used by every function in dbaTools, none of them can do the right thing.
3. Because of this, any query run using `Connect-DbaInstance` and `Invoke-DbaQuery` without _explicitly_ specifying the same `-Database` on both is creating two connections unecessarily. (And will leak a connection, due to #6210)

Once this is all fixed, the documentation needs to explain that you're doing this differently for Azure SQL databases, because it's not obvious. Users need to know that even if they specify the `-Database` explicitly, each distinct database _must_ create a new connection and therefore a new connection pool (users who are new to Azure SQL may need an explanation that you can't switch databases in a connection or query (which is suggested in [Microsoft's docs on connection pool fragmentation](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/sql-server-connection-pooling#pool-fragmentation-due-to-many-databases) or set default_database on users). Currently, it _looks_ like I can call `Invoke-DbaQuery` multiple times against different databases with the same $DbaInstance from a Connect-DbaInstance call, and then close it:

```PowerShell
$DbaInstance = Connect-DbaInstance -SqlInstance $InstanceName -SqlCredential $Credential
Invoke-DbaQuery -SqlInstance $DbaInstance -Query $CreateDbQuery -Database master
Invoke-DbaQuery -SqlInstance $DbaInstance -Query $CreateTableQuery -Database $DbName
$DbaInstance.ConnectionContext.Disconnect()
```

But in reality **each** of those queries created it's own connection (and, currently, leaked it), meaning there was **no value** in creating the connection myself the way I did!

#### Host used

- [x] powershell.exe
- [ ] ISE
- [ ] VS Code
- [ ] Other (please specify)

#### Errors Received

```
writeErrorStream      : True
PSMessageDetails      :
Exception             : System.Exception: Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred                           because all pooled connections were in use and max pool size was reached. ---> System.Exception: Timeout expired.  The timeout period                           elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool                          size was reached. ---> System.Management.Automation.MethodInvocationException: Exception calling "Connect" with "0" argument(s):                                "Failed to connect to server TCP:ausc1-frg9sqlwttqrx.database.windows.net,1433." --->
                        Microsoft.SqlServer.Management.Common.ConnectionFailureException: Failed to connect to server
                        TCP:ausc1-frg9sqlwttqrx.database.windows.net,1433. ---> System.InvalidOperationException: Timeout expired.  The timeout period elapsed                          prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size                             was reached.
                           at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry,                                DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
                           at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory                                 connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
                           at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
                           at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
                           at System.Data.SqlClient.SqlConnection.Open()
                           at Microsoft.SqlServer.Management.Common.ConnectionManager.InternalConnect(WindowsIdentity impersonatedIdentity)
                           at Microsoft.SqlServer.Management.Common.ConnectionManager.Connect()
                           --- End of inner exception stack trace ---
                           at Microsoft.SqlServer.Management.Common.ConnectionManager.Connect()
                           at CallSite.Target(Closure , CallSite , Object )
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
                           at Connect-DbaInstance<Process>(Closure , FunctionContext )
                           --- End of inner exception stack trace ---
                           --- End of inner exception stack trace ---
TargetObject          : ausc1-frg9sqlwttqrx.database.windows.net
CategoryInfo          : NotSpecified: (ausc1-frg9sqlwttqrx.database.windows.net:PSObject) [Write-Error], Exception
FullyQualifiedErrorId : dbatools_Invoke-DbaQuery,Stop-Function
ErrorDetails          : Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled                          connections were in use and max pool size was reached.
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Stop-Function, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.72\allcommands.ps1: line 81869
                        at Invoke-DbaQuery<Process>, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.72\allcommands.ps1: line 46563
                        at <ScriptBlock>, <No file>: line 2
PipelineIterationInfo : {0, 1}
```

#### Steps to Reproduce

```PowerShell
$DbaInstance = Connect-DbaInstance -SqlInstance $Db.SqlInstance -SqlCredential $Db.SqlCredential -MaxPoolSize 2
Invoke-DbaQuery -SqlInstance $DbaInstance -Query "SELECT @@Version"
Invoke-DbaQuery -SqlInstance $DbaInstance -Query "SELECT @@Version"
$DbaInstance.ConnectionContext.Disconnect()
```

#### Expected Behavior

It should run both queries using the same connection from the connection pool, and then disconnect

#### Actual Behavior

Each query creates another connection, exhausting the connection pool.

#### Steps to Reproduce

```PowerShell
Clear-DbaConnectionPool
$DbaInstance = Connect-DbaInstance -SqlInstance $Db.SqlInstance -SqlCredential $Db.SqlCredential -MaxPoolSize 2
$DbaInstance = Connect-DbaInstance -SqlInstance $DbaInstance 
$DbaInstance = Connect-DbaInstance -SqlInstance $DbaInstance 
$DbaInstance.ConnectionContext.Disconnect()
```

#### Expected Behavior

The first call should connect to the database, and the others should merely confirm the connection

#### Actual Behavior

Each call creates another connection, exhausting the connection pool.

### PR DESCRIPTION
**Pull request by Jaykul**
Should be adding `NewDbaConnection` NoteProperty and correctly setting it to `$true` or `$false` depending on whether we created a new connection or (wrapped and) returned one that was passed in to us. There's also a minor change to initialization of (and detection of existing_ Azure connections.

I'm only opening a PR at this stage (before I've worked on test changes) because I have questions about the code:

### 1. IsAzure?

There is a block starting on line 415/418 with the comment `# Gracefully handle Azure connections` which sets `$IsAzure`. It appears to me that if you go into that block, you don't come ever out (that is, it either outputs and `continue`s the foreach loop, or it calls `Stop-Function`).  Despite that, the `$IsAzure` variable is checked in several places below that _inside_ the foreach loop.  I think that referring to $IsAzure outside the block is a potential bug. 

If it was my module, I would separate the function into private functions to be clearer that most of the code is exclusive: "Azure" or "NotAzure" and then within those, I would try to more clearly separate the "ExistingConnectionObject" vs "NewConnection" handling.

My concern is that maybe this exclusion is unintentional, and some of the code outside that loop really _ought_ to run when it's azure.

### 2. Conditions in Azure connections

There's some confusing checks around Tenant or MFA and Credentials (see my `#BUGBUG` comments). I don't quite understand what the requirements are, but I'm sure the tests aren't consistent with the messages.

----

## Type of Change

 - [x] Bug fix (non-breaking change, fixes #6211)
 - [ ] New feature (non-breaking change, adds functionality, fixes # )
 - [ ] Breaking change (effects multiple commands or functionality, fixes # )
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system

### CODE REVIEW

**Comment by potatoqualitee** [comment]
> If it was my module, I would separate the function into private functions

This would likely make it a lot clearer. This command is huge and got that way over time so it didn't occur to me. If you are up for it, I think this is a good approach

**Comment by potatoqualitee** [comment]
ping-a-ling 😅

**Comment by Jaykul** [comment]
The nerve of some people ... 😋

It's been intense at work, and then Thanksgiving, and I've been totally exhausted. I should have some time later this week.

**Comment by potatoqualitee** [comment]
LOL, I get itchy when a PR hangs out too long, even in WIP. I tried my best to wait it out! 🤗 Hope you're feeling better. I've been exhausted for about 6 months, so I get it.

**Comment by potatoqualitee** [comment]
🌬

**Comment by potatoqualitee** [comment]
Haven't heard back on this in a while. In order to avoid dissuading potential contributors seeing old PRs and thinking that we don't merge, I will close this but welcome the PR back when it is no longer in draft 💯

**Pull request closed without merging**
