### PR TITLE
Get-DbaHelpIndex, added fragmentation, fixes #1216

### LINKED ISSUE #1216: Add Index Fragmentation information
## Is this:

- [X] *feature* 
- [ ] *bug*:

Add the index fragmentation to the output of `Get-DbaHelpIndex` function. If this is not a good fit, or not easily added we can just as easily come up with a dedicated function for it...something like `Get-DbaIndexFragmentation` (which may be the best option).

### PR DESCRIPTION
**Pull request by niphlod**
## Type of Change

 - [ ] Bug fix (non-breaking change, fixes #<enter issue number>)
 - [x] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
Add fragmentation info as requested in #1216

### Approach
A simple join to dm_db_index_physical_stats sufficed.

-----
Let's review this in the process and while I'm fresh with it, the select is a beast.........seems to me it needs a bit of love but ATM I lack forces for a good style review to port this to 1.0 readyness.

### CODE REVIEW

**Comment by potatoqualitee** [comment]
I'd be happy to.

**Comment by niphlod** [comment]
on top of my head, I'd start with:
- it accepts only a single sqlinstance

**Comment by potatoqualitee** [comment]
check that, it was a bunch of changes

**Comment by potatoqualitee** [comment]
oh wait, i need to add our normal 3, brb

**Comment by potatoqualitee** [comment]
i messed up the test. will fix in dev if it fails, i wanna get this show on the roadd

**Pull request merged**
