### PR TITLE
Move formatting of dates and times to the begin block Fixes #4386

### LINKED ISSUE #4386: [New|Set]-DbaAgentSchedule - Error when working with job schedules on multiple servers or jobs
### Before submitting a bug report:

- [x] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [x] Verified this bug is not already reported in an issue
- [x] Verified errors are not related to permissions
- [x] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

## Steps to Reproduce

```powershell
New-DbaAgentSchedule -SqlInstance server1,server2 -Schedule '11:50am' -FrequencyType Daily -FrequencyInterval 1 -StartTime '115000'
```

## Expected Behavior

The job is created on each server

## Actual Behavior

The first server works correctly but the second throws this error:
Exception setting "ActiveStartTimeOfDay": "Cannot convert value "00::0:0:00" to type "System.TimeSpan". Error: "String was not recognized as a valid TimeSpan.""

## Environmental data

 - PowerShell:
Name                           Value
----                           -----
PSVersion                      5.1.17134.228
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.228
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
 - - SQL Server: Microsoft SQL Server 2014 (SP2-CU13) (KB4456287) - 12.0.5590.1 (X64)   Aug  1 2018 01:23:36   Copyright (c) Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows NT 6.3 <X64> (Build 9600: )

### PR DESCRIPTION
**Pull request by cfradenburg**
## Type of Change

 - [x] Bug fix (non-breaking change, fixes #4386)
 - [ ] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
When looping through servers or jobs the dashes and colons are inserted into dates and times multiple times resulting in bad formats

### Approach
The formatting code has been moved to the begin block

### Commands to test
sql1, sql2, sql3 | New-DbaAgentSchedule -Schedule daily -FrequencyType Daily -FrequencyInterval Everyday -StartTime '020000' -Force

sql1, sql2, sql3 | Set-DbaAgentSchedule -Job Job1 -ScheduleName 'daily' -FrequencyType Daily -FrequencyInterval Everyday -StartTime '020000'

### CODE REVIEW

**Comment by potatoqualitee** [comment]
fantastic! Thank you 💯  I'll ask @sanderstad to take a look.

**Comment by sanderstad** [comment]
This looks good to me. I have not tested the code but I assume Chris did that before he made the PR

**Comment by cfradenburg** [comment]
I didn't test the date fotmatting but I tested the time formatting with multiple server instances in the parameter and the pipeline. The check code didn't change so at the very least I shouldn't have broken it.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by potatoqualitee** [comment]
tested and works 🎉 ! previous test failed, perfect fix, ty!

**Comment by potatoqualitee** [comment]
image

**Pull request merged**
