### PR TITLE
Fix Setting Agent Schedules and Steps do not function as expected #6809

### LINKED ISSUE #6809: [Bug] Setting Agent Schedules and Steps do not function as expected
### Environmental information

```powershell
PowerShell Version        : 5.1.19041.1
dbatools latest installed : 1.0.116
Culture of OS             : en-US
```

#### SQL Server:

```sql
Microsoft SQL Server 2019 (RTM-GDR) (KB4517790) - 15.0.2070.41 (X64)   Oct 28 2019 19:56:59   Copyright (C) 2019 Microsoft Corporation  Developer Edition (64-bit) on Windows 10 Pro 10.0 <X64> (Build 19042: ) (Hypervisor) 
```

```sql
us_english
```

### Report
Using dbatools version 1.0.116 the following issues are observed:

1. Set-DbaAgentSchedule was observed to be unable to update an existing schedule by name to a monthly schedule when provided the parameter -FrequencyType "Monthly" and a FrequencyType with a numeric value (1-31).

Set-DbaAgentSchedule -SqlInstance localhost -Job 'Multi-Step Job' -Schedule 'Monthly Schedule' -FrequencyType Monthly -Disabled -FrequencyRecurrenceFactor 1 -StartDate 20200907 -StartTime 000000 -EndDate 99991231 -EndTime 000000 -FrequencyInterval 3

Running sp_help_job on local instance shows the following for the schedule:

image

Alternatively running Get-DbaAgentSchedule -SqlInstance localhost -Schedule 'Monthly Schedule' shows:

image

2. Set-DbaAgentSchedule and New-DbaAgentSchedule were outputting informational text to the console without context when -Verbose was not passed.

New-DbaAgentSchedule -SqlInstance localhost -Job 'Multi-Step Job' -Schedule 'Monthly Schedule' -FrequencyType Monthly -Disabled -FrequencyRecurrenceFactor 1 -StartDate 20200907 -StartTime 000000 -EndDate 99991231 -EndTime 000000 -FrequencyInterval 1

image

3. Set-DbaAgentJobStep and New-DbaAgentJobStep failed to create a job step when 'AppendToTableLog' was provided in the -Flag parameter.

New-DbaAgentJobStep -SqlInstance localhost -Job 'Job Step Test' -StepId 1 -StepName 'Test Step' -Subsystem TransactSql -Command "SELECT 1" -Database "master" -Flag AppendToTableLog,AppendToJobHistory

image

#### Host used

- [ ] powershell.exe
- [ ] ISE
- [X] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [ ] Still buggy in powershell.exe

### PR DESCRIPTION
**Pull request by pagerwho**
## Type of Change

 - [X] Bug fix (non-breaking change, fixes #6809  )
 - [ ] New feature (non-breaking change, adds functionality, fixes # )
 - [ ] Breaking change (effects multiple commands or functionality, fixes # )
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
Fix several bugs as indicated in bug. During local development for wrapper function all four functions and associated bugs needed to be fixed.

### Commands to test
1. Set-DbaAgentSchedule -SqlInstance localhost -Job 'Multi-Step Job' -Schedule 'Monthly Schedule' -FrequencyType Monthly -Disabled -FrequencyRecurrenceFactor 1 -StartDate 20200907 -StartTime 000000 -EndDate 99991231 -EndTime 000000 -FrequencyInterval 3

2. New-DbaAgentSchedule -SqlInstance localhost -Job 'Multi-Step Job' -Schedule 'Monthly Schedule' -FrequencyType Monthly -Disabled -FrequencyRecurrenceFactor 1 -StartDate 20200907 -StartTime 000000 -EndDate 99991231 -EndTime 000000 -FrequencyInterval 1

3. New-DbaAgentJobStep -SqlInstance localhost -Job 'Job Step Test' -StepId 1 -StepName 'Test Step' -Subsystem TransactSql -Command "SELECT 1" -Database "master" -Flag AppendToTableLog,AppendToJobHistory
--OR--
Set-DbaAgentJobStep -SqlInstance localhost -Job 'Job Step Test' -StepName 'Test Step' -Subsystem TransactSql -Command "SELECT 1" -Database "master" -Flag AppendToTableLog,AppendToJobHistory

### Screenshots
Issue 1:
image

Issue 2:
image

Issue 3:
image

### CODE REVIEW

**Comment by wsmelton** [comment]
Please complete the requested info for the PR.

**Comment by wsmelton** [comment]
Commands to test and screenshots would be helping the most.

**Comment by pagerwho** [comment]
Pull request has been updated as requested.

**Comment by potatoqualitee** [comment]
sweet af thanks so much, Travis! @sanderstad - you approve?

**Comment by potatoqualitee** [comment]
k gonna merge since Shawn approves 💯 Thanks again!

**Comment by potatoqualitee** [comment]
oh, and cuz there's screenshots and tests pass 👍

**Pull request merged**
