### PR TITLE
Publish-DbaDacPackage

### LINKED ISSUE #4824: Publish-DbaDacPackage should accept -whatif and -confirm parameters
---
name: Publish-DbaDacPackage should accept -whatif and -confirm 
about: Publish-DbaDacPackage should accept -whatif and -confirm parameters so we can avoid potential  :bomb:
---

### Summary of new feature

* Publish-DbaDacPackage does not accept -whatif or -confirm, which are normally fairly standard on functions that would make changes to an environment

### Proposed technical details (if applicable)

* Normally this is done by using SupportsShouldProcess. If there is a preferred DBATools means to do this, then we should use that

### Latest version of dbatools as of writing

* 0.9.718

### PR DESCRIPTION
**Pull request by potatoqualitee**
## Type of Change

 - [x] Bug fix (non-breaking change, fixes #4824)
 - [ ] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [x] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system

### CODE REVIEW

**Comment by potatoqualitee** [comment]
@nvarscar - what do you think about the confirmation impact? this is deployment, so a confirmation prompt could be considered a breaking change. Should it be Medium?

**Comment by potatoqualitee** [comment]
wait but doesnt publish touch a server? it asks for a server?

**Comment by potatoqualitee** [comment]
ohh needed *there*, that's fine, i still want it covered in whatif

**Comment by potatoqualitee** [comment]
im thinking medium, what say you? ill have to fix the examples if so

**Comment by nvarscar** [comment]
Restore-DbaDatabase is medium, I'd vote for Medium here as well, but uhhh it's choosing between UX and following standards.

**Comment by potatoqualitee** [comment]
i agree, k

**Pull request merged**
