### PR TITLE
Get-DbaService - Add Credential when calling Get-DbaCmObject

### PR DESCRIPTION
**Pull request by PsPsam**
## Type of Change

 - [X] Bug fix (non-breaking change, fixes # )
 - [ ] New feature (non-breaking change, adds functionality, fixes # )
 - [ ] Breaking change (effects multiple commands or functionality, fixes # )
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1`)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Unit test is included
 - [ ] Documentation
 - [ ] Build system

### Purpose
Fixing the check if the command can connect the Server with Get-DbaCmObject that missed the Credential parameter

### Approach
Added Credential parameter to the Get-DbaCmObject command at line 152

### CODE REVIEW

**Comment by andreasjordan** [comment]
You mixed the fix with a new command. Please remove the new command.

**Comment by PsPsam** [comment]
That I missed!
Will try to fix it. I have to learn that :)

**Comment by andreasjordan** [comment]
If you like I can try to delete the file from the pull request.

**Comment by PsPsam** [comment]
Thanks that would be great! @andreasjordan

**Comment by andreasjordan** [comment]
Worked. Tests should pass now. Will have a look later.

**Review by niphlod — APPROVED** [review]

**Comment by potatoqualitee** [comment]
Thanks everyone!

**Pull request merged**
