### PR TITLE
Issue3163

### LINKED ISSUE #4173: Issues with Get-DbaOperatingSystem retreiving Powershell and PowerPlan information
### Before submitting a bug report:

- [X] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [X] Verified this bug is not already reported in an issue
- [X] Verified errors are not related to permissions
- [X] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

## Steps to Reproduce
Run Get-DbaOperatingSystem against any of the following Windows configurations
(a) A Windows 2003 Server
(b) A Windows Server without Powershell Remoting enabled
(c) A Windows Server running SSRS with an SPN registered. 

## Expected Behaviour

The command should return all possible information.

## Actual Behavior
For Servers without PowerShell Remoting enabled the following error is received

Failure collecting PowerShell version on ServerName | Connecting to remote server ServerName failed with the following error message :
 WinRM cannot process the request. The following error occurred while using Kerberos authentication: Cannot find the computer ServerName. Verify that the computer exists on the network and that the name provided is spelled correctly. For more information, see the about_Remote_Troubleshooting Help topic.

This is a result of the code using PowerShell Remoting to try and get the PowerShell Version on the Server

Windows Servers with Windows 2008 or earlier with PowerShell Remoting enabled will receive the following error:
Failure collecting PowerPlan information on ServerName | An error occurred while enumerating through a collection: The WS-Management service cannot process the request. The CIM namespace oot/cimv2/power is invalid. .

This is an expected error as the WMI Class being queried Win32_PowerPlan only exists on Windows 2008R2 or Higher

Windows Servers running SSRS and having an SPN set may receive the following error message:
Failure collecting PowerShell version on ServerName | Connecting to remote server ServerName failed with the following error message : WinRM
 cannot process the request. The following error with errorcode 0x80090322 occurred while using Kerberos authentication: An unknown security error occurred.  
 Possible causes are:
  -The user name or password specified are invalid.
  -Kerberos is used when no authentication method and no user name are specified.
  -Kerberos accepts domain user names, but not local user names.
  -The Service Principal Name (SPN) for the remote computer name and port does not exist.
  -The client and remote computers are in different domains and there is no trust between the two domains.
 After checking for the above issues, try the following:
  -Check the Event Viewer for events related to authentication.
  -Change the authentication method; add the destination computer to the WinRM TrustedHosts configuration setting or use HTTPS transport.
 Note that computers in the TrustedHosts list might not be authenticated.
   -For more information about WinRM configuration, run the following command: winrm help config. For more information, see the about_Remote_Troubleshooting Help topic.

This issue is documented in
https://dba.stackexchange.com/questions/129286/how-do-i-enable-both-powershell-remoting-and-spn-for-sql-server-reporting

### PR DESCRIPTION
**Pull request by sqllensman**
## Type of Change

 - [X ] Bug fix (non-breaking change, fixes #4173
 - [X] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [X] Pester test is included
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
Fix issues in Get-DbaOperatingSystem with Older Systems. 
Add additional properties to those already being returned. In particular adds a field indicating if Server is part of a Windows Failover Cluster

### Commands to test
Get-DbaOperatingSystem

### CODE REVIEW

**Comment by potatoqualitee** [comment]
Thanks so much! There is one failure in Copy-DbaDbTableData tho I'm not sure why. Can you take a look?

**Comment by sqllensman** [comment]
Will look now

**Comment by sqllensman** [comment]
The Copy-DbaDbTableData.Tests.ps1 should not have been in Pull request.  It is part of another change and depends on fixes to Copy-DbaDbTableData. 

How do I remove this file?

**Comment by potatoqualitee** [comment]
The way I do it is kinda barbaric but works. I switch to Dev, copy the file elsewhere, switch the branch back and paste the dev version and commit 👍

**Comment by potatoqualitee** [comment]
Sorry I didn't notice before, but your CBH is messed up too. I'm assuming you are using an older branch? It's changing it back to our old formats.

image

**Comment by potatoqualitee** [comment]
fab thank you!

**Pull request merged**
