### PR TITLE
Restore-DbaDatabase -Continue fails on dbs with multiple data files

### PR DESCRIPTION
**Pull request by maddhatter**
## Type of Change

 - [x] Bug fix (non-breaking change, fixes #<enter issue number>)
 - [ ] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
 
I was trying to restore log backups from a share to a database in `Restoring...`, but received this error:
image

Digging into the error, `Get-RestoreContinuableDatabase` was returning 4 rows, since my database has 4 data files - but `Select-DbaBackupInformation` was expecting a single row.

### Approach

Add a `distinct` to the query to ensure one row per database. 

### Commands to test

`Get-RestoreContinuableDatabase` (with a database in Restoring w/ multiple data files)

The actual command I was running to produce the error (I'm essentially log shipping by hand, long story): 
```powershell
$src = 'srcServer'
$dst = 'dstServer'

$lastRestoredLsn = (Get-DbaRestoreHistory -SqlInstance $dst -Last -Database testdb).last_lsn

Get-DbaBackupHistory -SqlInstance $src -Database testdb -LastLsn $lastRestoredLsn -Type Log | % {
    Get-ChildItem "\\$src\testdb\$(Split-Path $_.Path[0] -Leaf)"
} | Restore-DbaDatabase -SqlInstance $dst -DatabaseName testdb -NoRecovery -Continue -Verbose -WhatIf
```

I'm unsure how to write a test for this scenario. If someone can give me an idea of what that test should look like, I'd be happy to write it.

### Screenshots

Original query results:
image

### CODE REVIEW

**Comment by Stuart-Moore** [comment]
rebased PR to development.

We always merge into dev first, and then that get's merged into mast eventually

**Comment by Stuart-Moore** [comment]
As for testing, it'd take a mock to do a unit test as they're won't be a SQL instance for that bit.

But looking at the code I'll be happy if it passes the Integration tests (running now on Appveyor), so I'll take a look once they've passed. But it makes sense and is a logical solution, so not expecting it to break anything

**Comment by Stuart-Moore** [comment]
OK, there were some fails on the tests (https://ci.appveyor.com/project/sqlcollaborative/dbatools/build/0.9.9099/job/aj1rt148m60uak49), but they weren't anything to do with this code, so going to merge to Development.

Just for future reference, normally we'll open an issue first so we can tie a PR back to that. Just keeps track of what fixed what over time.

Thanks for spotting and catching this :+1:

**Comment by potatoqualitee** [comment]
awesome!! thanks to you both. btw, I'm working on those GD tests that keep failing for no good reason.

**Pull request merged**
