### PR TITLE
Added TrustDbBackupHistory switch

### PR DESCRIPTION
**Pull request by Stuart-Moore**
Now allows users to say they trust the input from Get-DbaBackupHistory or Backup-DbaDatabase and shortcut the header scans for better speed

﻿Fixes # 

Changes proposed in this pull request:
 - Get-DbaBackupHistory now returns a few extra properties, but these are hidden to general users
 - Backup-DbaDatabase now returns a few extra properties which are hidden
 - 

How to test this code: 
- [ ] Get-DbaDatabaseHistory -SqlServer SomeServer -Database x,y,z | Restore-DbaBackupHistory -SqlServer SomeServer -TrustDbBackupHistory -.........
Should restore everything without touching Read-DbaBackupHeader
Checks that files exist at a basic level, but other than that it's up to the user to have not moved anything
- [ ] Backup-DbaDatabase -SqlInstance localhost\sqlexpress2016 -db x,y,x | Restore-DbaBackupHistory -SqlServer SomeServer -TrustDbBackupHistory -.........
Again Shouldn't touch Read-DbaBackupHeader

Run  with Measure-Command shows a decent reduction in time to begin restore writing to disk.

Last batch of Tests for usual functionality passed on my end, there shouldn't be any changes there

Has been tested on minimum requirements:
- [ ]  Powershell 3
- [ ]  Windows 7
- [ ]  SQL Server 2000

Has been tested on maximum requirements:
- [ ]  SQL Server vNext
- [ ]  Windows 10
- [ ]  Azure Database

Tests for tester:
- [ ] Working/useful help content, including link to command on dbatools web site
- [ ] All examples work as advertised
- [ ] Does not contain template content
- [ ] Does not contain excessive/unnecessary amounts of comments
- [ ] Works remotely
- [ ] Works locally
- [ ] Works on lower versions or throws error specifying version not supported
- [ ] Works with named instances
- [ ] Works with clustered instances
- [ ] Handles offline/read only databases
- [ ] Supports multiple servers (at the command line or piped from Get-SqlRegisteredServerName)
- [ ] No un-handled errors which stop the command working with multiple servers

### CODE REVIEW

**Comment by ctrlbold** [comment]
oh damn, i didnt realize this touched so many files. it's no problem, but please ask for ASAP code review so that i can get them in. I may need some @ConstantineK magic up in here to resolve that conflict.

**Comment by Stuart-Moore** [comment]
Sorry, didn't think I saw any conflict when I put it in :(

Am happy to redo this file and repush if that makes life easier for all concerned?

**Comment by ctrlbold** [comment]
HEY!!! I resolved a conflict 👍 Just had to paste this changes. Now I know how to fix. haha

**Comment by Stuart-Moore** [comment]
Yay. That's my way of fixing as well!

No idea why that claimed a conflict, was just some extra lines here and
there

**Comment by ctrlbold** [comment]
Glad you are here, can you make sure that the command you submitted is indeed the one in there?

**Comment by ctrlbold** [comment]
Actually just triple checked and it is, thanks!

**Pull request merged**
