### PR TITLE
Add linguist overrides for correct github syntax highlighting

### PR DESCRIPTION
**Pull request by ktaranov**
## Type of Change

 - [x] New feature (non-breaking change, adds functionality)
 

### Purpose
 
correct github syntax highlighting to TSQL language. More details here https://github.com/github/linguist/issues/4622

image

### CODE REVIEW

**Comment by potatoqualitee** [comment]
Oh, I love this! I've wanted this for so long but didn't know we could make that change ourselves. Thank you 🙇🏼‍♂️🙇🏼‍♂️

**Comment by potatoqualitee** [comment]
will merge once all checks are complete

**Comment by wsmelton** [comment]
This got merged into master, didn't catch that when I reviewed.

**Comment by potatoqualitee** [comment]
ohhh k ill be matching them up today, in about 2 minutes

**Comment by potatoqualitee** [comment]
should we also create a .gitattributes repo?

**Pull request merged**
