### PR TITLE
Update build info to include SQL Server 2019 RC builds

### LINKED ISSUE #6059: Add 2019 versions to the build ref
### Summary of new feature
Not sure if this is a new feature/enhancement or a bug. There is no 2019 versions in the build ref yet. Can this be added? Got the below off of http://sqlserverbuilds.blogspot.com/#sql2019x.
(This can be assigned to me if they can be added... 😄 

https://sqlcollaborative.github.io/builds

- 15.0.1900.47 - Microsoft SQL Server 2019 Release Candidate Refresh for Big Data Clusters only (RC1.1)
- 15.0.1900.25 - Microsoft SQL Server 2019 Release Candidate 1 (RC1)
- 15.0.1800.32 - Microsoft SQL Server 2019 Community Technology Preview 3.2 (CTP 3.2)
- 15.0.1700.37 - Microsoft SQL Server 2019 Community Technology Preview 3.1 (CTP 3.1)
- 15.0.1600.8 - Microsoft SQL Server 2019 Community Technology Preview 3.0 (CTP 3.0)
- 15.0.1500.28 - Microsoft SQL Server 2019 Community Technology Preview 2.5 (CTP 2.5)
- 15.0.1400.75 - Microsoft SQL Server 2019 Community Technology Preview 2.4 (CTP 2.4)
- 15.0.1300.359 - Microsoft SQL Server 2019 Community Technology Preview 2.3 (CTP 2.3)
- 15.0.1200.24 - Microsoft SQL Server 2019 Community Technology Preview 2.2 (CTP 2.2)
- 15.0.1100.94 - Microsoft SQL Server 2019 Community Technology Preview 2.1 (CTP 2.1)
- 15.0.1000.34 - Microsoft SQL Server 2019 Community Technology Preview 2.0 (CTP 2.0)

### PR DESCRIPTION
**Pull request by wsmelton**
## Type of Change

 - [x] Bug fix (non-breaking change, fixes #6059 )
 - [x] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [x] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
Adding RC builds for 2019. This required changing the test a bit because the version numbering for RCs is not the same as previous versions of SQL Server. It is not a 4-part build number (e.g. `15.0.1900.34`). I also had to add a place holder for RTM due to how are test is done, and I want to keep that test in place to catch things like this. So the RTM build for 2019 is set to `15.0.9999.0`. (_It should be pretty clear to users that this is just a place holder._)

Against local system the test for `Get-DbaBuildReference` passes with the changes made in this PR.
image

### CODE REVIEW

**Comment by jpomfret** [comment]
Can we trust users to know 15.0.9999 isn't real? Also what if someone is using this within code to get the latest available RTM or something along those lines?

**Comment by wsmelton** [comment]
Nothing really we can do if you want it to be added.

**Comment by wsmelton** [comment]
This is also data on a version of SQL Server that is not even released yet. So if they have code that is looking for RTM of SQL Server 2019 there are other issues with that out of our control.

**Comment by potatoqualitee** [comment]
looks great! 😍

**Pull request merged**
