### PR TITLE
Fix for potential race conditions with backups and history

### LINKED ISSUE #4401: Copy-DBADatabase command gives error, references source server's backup folder
### Before submitting a bug report:

- [ ] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [ ] Verified this bug is not already reported in an issue
- [ ] Verified errors are not related to permissions
- [ ] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

## Steps to Reproduce
DBATools module version 0.9.497
Copy-DBADatabase command was previously working but recently I started to receive an error message.  I am attempting to copy a database from sourceserver to targetserver using a specified networkshare.  The service accounts for sourceserver and targetserver both have modify rights to the networkshare.  SourceServer is in Domain A and targetserver is in Domain B.  the two domains have a two way trust established.  Since this same exact command had worked previously I do not believe that this is a permissions issue.  I have double checked permissions.  The error references a file that would exist at the backup location of the sourceserver.  I'm not sure why it's trying to reference that location.  That is not where I specified the backup files to go with the networkshare parameter.


```sql

N/A
```

```powershell
<#
*PowerShell code and output has been sanitzed*

PS C:\Windows\system32> Copy-DbaDatabase -Source $SourceServer -Destination $DestinationServer -AllDatabases -ExcludeDatabase "<Excluded DBName>"  -BackupRestore -WithReplace -NetworkShare $BackupDirectory -Verbose #-IncludeSupportDbs 
VERBOSE: [08:07:59][Copy-DbaDatabase] Ensuring user databases exist (counting databases).
VERBOSE: [08:08:00][Copy-DbaDatabase] Performing SMO version check.
VERBOSE: [08:08:00][Copy-DbaDatabase] Checking to ensure the source isn't the same as the destination.
VERBOSE: [08:08:00][Copy-DbaDatabase] Checking to ensure network path is valid.
VERBOSE: [08:08:00][Copy-DbaDatabase] <NetworkShare> share can be accessed.
VERBOSE: [08:08:00][Copy-DbaDatabase] Checking to ensure server is not SQL Server 7 or below.
VERBOSE: [08:08:00][Copy-DbaDatabase] Checking to ensure detach/attach is not attempted on SQL Server 2000.
VERBOSE: [08:08:00][Copy-DbaDatabase] Checking to ensure SQL Server 2000 migration isn't directly attempted to SQL Server 2012.
VERBOSE: [08:08:00][Copy-DbaDatabase] Warning if migration from 2005 to 2012 and above and attach/detach is used.
VERBOSE: [08:08:00][Copy-DbaDatabase] Ensuring destination server version is equal to or greater than source.
VERBOSE: [08:08:00][Copy-DbaDatabase] Writing warning about filestream being enabled.
VERBOSE: [08:08:00][Copy-DbaDatabase] Building database list.
VERBOSE: [08:08:00][Copy-DbaDatabase] Performing count.
VERBOSE: [08:08:00][Copy-DbaDatabase] Building file structure inventory for 2 databases.
VERBOSE: [08:08:00][Get-SqlFileStructure] <DBName>
VERBOSE: [08:08:00][Get-SqlFileStructure] <Excluded DBName>
VERBOSE: [08:08:01][Copy-DbaDatabase] 
######### Database: <DBName> #########
VERBOSE: [08:08:01][Copy-DbaDatabase] Checking for accessibility.
VERBOSE: [08:08:01][Copy-DbaDatabase] Checking Availability Group status.
VERBOSE: [08:08:01][Copy-DbaDatabase] Started: 11/02/2018 08:08:01.
VERBOSE: Performing the operation "Backup <DBName> from <SourceServer> and restoring" on target "<TargetServer>".
VERBOSE: [08:08:01][Backup-DbaDatabase] Setting Default timestampformat
VERBOSE: [08:08:01][Backup-DbaDatabase] 1 database to backup
VERBOSE: [08:08:01][Backup-DbaDatabase] Backup database <DBName>
VERBOSE: [08:08:01][Backup-DbaDatabase] Creating full backup
VERBOSE: [08:08:01][Backup-DbaDatabase] Building file name
VERBOSE: [08:08:01][Backup-DbaDatabase] Setting filename - 201811020808
VERBOSE: [08:08:01][Backup-DbaDatabase] Building backup path
VERBOSE: [08:08:01][Backup-DbaDatabase] Devices added
VERBOSE: [08:08:45][Get-DbaBackupHistory] Processing <DBName>
VERBOSE: [08:08:45][Get-DbaBackupHistory] Executing sql query.
VERBOSE: [08:08:45][Get-DbaBackupHistory] Processing as grouped output.
VERBOSE: [08:08:45][Get-DbaBackupHistory] 1 result-groups found.
VERBOSE: [08:08:46][Get-DbaBackupHistory] Processing <DBName>
VERBOSE: [08:08:46][Get-DbaBackupHistory] Executing sql query.
VERBOSE: [08:08:46][Get-DbaBackupHistory] Processing as grouped output.
VERBOSE: [08:08:46][Get-DbaBackupHistory] 0 result-groups found.
VERBOSE: [08:08:46][Get-DbaBackupHistory] No Diff found
VERBOSE: [08:08:46][Get-DbaBackupHistory] Executing sql query.
VERBOSE: [08:08:46][Get-DbaBackupHistory] Processing as grouped output.
VERBOSE: [08:08:46][Get-DbaBackupHistory] 1 result-groups found.
VERBOSE: [08:08:46][Copy-DbaDatabase] Reuse = False.
VERBOSE: [08:08:46][Restore-DbaDatabase] Changing statement timeout to infinity
VERBOSE: [08:08:46][Restore-DbaDatabase] ParameterSet  = Restore
VERBOSE: [08:08:46][Restore-DbaDatabase] Trust Database Backup History Set
VERBOSE: [08:08:46][Restore-DbaDatabase] Processing DatabaseName - <DBName>
VERBOSE: [08:08:46][Format-DbaBackupInformation] Starting
VERBOSE: [08:08:46][Format-DbaBackupInformation] String passed in for DB rename
VERBOSE: [08:08:46][Format-DbaBackupInformation] New DbName (String) = <DBName>
VERBOSE: [08:08:46][Format-DbaBackupInformation]  1 PhysicalName = E:\Data\Seed_DB_6.3_SQL2012.mdf 
VERBOSE: [08:08:46][Format-DbaBackupInformation] PhysicalName = E:\Data\Seed_DB_6.3_SQL2012.mdf 
VERBOSE: [08:08:46][Format-DbaBackupInformation]  1 PhysicalName = E:\Logs\Seed_DB_6.3_SQL2012_log.ldf 
VERBOSE: [08:08:46][Format-DbaBackupInformation] PhysicalName = E:\Logs\Seed_DB_6.3_SQL2012_log.ldf 
VERBOSE: [08:08:46][Format-DbaBackupInformation]  1 PhysicalName = d:\Program Files\Microsoft SQL Server\MSSQL.1\MSSQL\Faster3G_2.Faster3G 
VERBOSE: [08:08:46][Format-DbaBackupInformation] PhysicalName = d:\Program Files\Microsoft SQL Server\MSSQL.1\MSSQL\Faster3G_2.Faster3G 
VERBOSE: [08:08:46][Select-DbaBackupInformation] Filtering by DatabaseName
VERBOSE: [08:08:46][Select-DbaBackupInformation] processing diffs
VERBOSE: [08:08:46][Select-DbaBackupInformation] Found LogBaseLsn: 187717000000937500001 and FirstRecoveryForkID: 
VERBOSE: [08:08:46][Restore-DbaDatabase] VerifyOnly = False
VERBOSE: [08:08:46][Test-DbaBackupInformation] Testing restore for <DBName>
VERBOSE: [08:08:46][Test-DbaBackupInformation] VerifyOnly = False
WARNING: [08:08:46][New-DbaDirectory] Failure | xp_create_subdir() returned error 5, 'Access is denied.'
VERBOSE: [08:08:46][Test-DbaBackupInformation] Created Folder d:\Program Files\Microsoft SQL Server\MSSQL.1\MSSQL on <TargetServer>
VERBOSE: [08:08:47][Test-DbaLsnChain] Testing LSN Chain
VERBOSE: [08:08:47][Test-DbaLsnChain] Testing LSN Chain - Type Type
VERBOSE: [08:08:47][Test-DbaLsnChain] Passed LSN Chain checks
VERBOSE: [08:08:47][Test-DbaBackupInformation] Marking <DBName> as verified
VERBOSE: [08:08:47][Restore-DbaDatabase] <DBName> passed testing
VERBOSE: [08:08:47][Restore-DbaDatabase] Passing in to restore
VERBOSE: [08:08:47][Invoke-DbaAdvancedRestore] Killing processes on <DBName>
VERBOSE: [08:08:54][Invoke-DbaAdvancedRestore] Performing restore action
VERBOSE: [08:08:54][Invoke-DbaAdvancedRestore] Failed, Closing Server connection
VERBOSE: [08:08:54][Invoke-DbaAdvancedRestore] Succeeded, Closing Server connection
WARNING: [08:08:54][Copy-DbaDatabase] Failure attempting to restore <DBName> to <TargetServer> | System.Data.SqlClient.SqlError: Cannot open backup device '<SourceServerBackupFileUNCPath><DBName>_Backup_201702022200.BAK'. Operating system er
ror 2(The system cannot find the file specified.).
VERBOSE: [08:08:54][Copy-DbaDatabase] Failed to restore <DBName> to <TargetServer>. Aborting routine for this database.

VERBOSE: [08:08:54][Copy-DbaDatabase] 
######### Database: < #########
VERBOSE: [08:08:54][Copy-DbaDatabase] <Excluded DBName> excluded. Skipping.
Type     Name     Status Notes                                                                                                                                                                                                                 
----     ----     ------ -----                                                                                                                                                                                                                 
Database <DBName> Failed System.Data.SqlClient.SqlError: Cannot open backup device '<SourceServerBackupFileUNCPath><DBName>_Backup_201702022200.BAK'. Operating system error 2(The system cannot find the file specified.).
#>
```

## Expected Behavior
Expected behavior is that database would be copied to targetserver successfully.  The process is able to write the backup files to the networkshare but then gives an error message.

<!--
Sample output or detail explanation if possible
-->

## Actual Behavior

Error message is received.  Full error is detailed above in the powershell section

## Environmental data

<!-- Provide output of the following two commands -->

 - PowerShell: <!-- $PSVersionTable output -->
$PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      14393  2248 
 - - SQL Server: <!-- SELECT @@VERSION output -->
SourceServer: Microsoft SQL Server 2012 - 11.0.5058.0 (X64)   May 14 2014 18:34:29   Copyright (c) Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) (Hypervisor) 
TargetServer:Microsoft SQL Server 2016 (SP2) (KB4052908) - 13.0.5026.0 (X64)   Mar 18 2018 09:11:49   Copyright (c) Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor)

### PR DESCRIPTION
**Pull request by Stuart-Moore**
## Type of Change

 - [x] Bug fix (non-breaking change, fixes #4401 )
 - [x] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [x] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [x] Pester test is included
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
We've had a couple of tickets where people have seen funnies with Copy-DbaDatbase, for example #4401 

In the first case I'm guessing that another backup is happening at the same time as the one in the cmdlet, and history is returning the other backup's details

### Approach
Grab the Current LSN before just before the backup starts, and then push that into Get-DbaBackuphistory via it's LastLSN parameters

Should reduce the chances of getting the wrong backup back by quite a bit.

Added a RowLimit switch to Read-DbaTransactionLog as we only want the first row back for a guesstimate of LSN
Added a Convert-LSN internal function to convert from hex to numeric and numeric to hex.

If we keep getting them, then the next option would be to read the backup headers as we definitely know the filenames, just everything else that doesn't get returned. But that's probably got more of an impact that this option.

### CODE REVIEW

**Comment by Stuart-Moore** [comment]
hang fire on this. Going to do another branch with the header option to see how much slower it would be, Working it through in my head that one will potentially fix more issues

**Comment by potatoqualitee** [comment]
How's this looking Stuart?

**Comment by Stuart-Moore** [comment]
It's the better of the 2 options atm. The read-backupheader option is causing a few issues with some of the types of backup.

Failed tests appear to be nothing with this PR

**Comment by Stuart-Moore** [comment]
Last comment may have been ambiguous. This is ready to merge 👍

**Comment by potatoqualitee** [comment]
fantastic 💯 thanks so much, Stuart.

**Pull request merged**
