### PR TITLE
DatabaseHealthTrigger is only available on 2016 & later

### PR DESCRIPTION
**Pull request by sphallsphall**
## Type of Change

 -  Bug fix (non-breaking change, fixes #<enter issue number>)
 - [ ] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
 
Make function work against my SQL2014 servers

### Approach

Wrap parameter that only applies to 2016 or greater in server version test

### CODE REVIEW

**Comment by niphlod** [comment]
perfect but I'd move BasicAvailabilityGroups too. Aren't they from 2016 onwards ?

**Comment by niphlod** [comment]
ok, more coffee needed...
13 IS 2016. 
Perfect PR!

**Comment by potatoqualitee** [comment]
awesome, thank you! this will be released sometime today.

**Comment by sphallsphall** [comment]
Least I can do, thanks for all the great code

**Pull request merged**
