### PR TITLE
Fix Remove-DbaDatabase - RESTORING databases

### LINKED ISSUE #2035: Remove-DbaDatabase fails when DB is in restoring state
### General Troubleshooting steps

- [x] Verified running latest release of dbatools?
- [x] Verified errors are not related to permissions?
- [x] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - Operating System (Name|Version): Windows 10 Enterprise
 - PowerShell Version: Platform: V5 64Bit
 - SQL Server (Edition|Version): SQL Server 2016 Enterprise Edition (build 13.0.4435)

## Steps to Reproduce

1. Leave a DB in the restoring state (in my case this was the secondary replica after removing the DB from an AG).
2. Run the following:

`Remove-DbaDatabase -SqlInstance <ServerName> -Databases <DBName>`

 - [ ] Attach any screenshots (if possible/allowed)
 - [ ] Attach logs generated by dbatools (`Get-DbatoolsLog`)
 - [x] Attach output from PowerShell console (if possible/allowed)
```
VERBOSE: [Remove-DbaDatabase][15:58:23] Connecting to !ServerName!
VERBOSE: Performing the operation "KillDatabase" on target "[!DatabaseName!] on [!ServerName!]".
VERBOSE: Performing the operation "alter db set single_user with rollback immediate then drop" on target "[!DatabaseName!] on [!ServerName!]".
VERBOSE: Performing the operation "SMO drop" on target "[!DatabaseName!] on [!ServerName!]".
VERBOSE: [Remove-DbaDatabase][15:58:27] Could not drop database [!DatabaseName!] on [!ServerName!]
ComputerName : !ServerName!
InstanceName : MSSQLSERVER
SqlInstance  : !ServerName!
Database     : !DatabaseName!
Status       : Index operation failed; the array index evaluated to null.
```
Does the logic need to be changed to just attempt to drop a database when it is in a restoring state?

### PR DESCRIPTION
**Pull request by nvarscar**
Added a verification that the database is ONLINE before running ALTER DB SET SINGLE_USER

## Type of Change

 - [x] Bug fix (non-breaking change, fixes #2035)
 - [ ] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [x] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [x] Pester test is included

### Purpose
Fixing #2035

### Approach
Adding `if exists (select * from sys.databases where name = 'db' and status = 0)` to check if the database is online and thus should be put into a single_user mode.

### Commands to test
Included in pester test

### Screenshots
image

### CODE REVIEW

**Comment by potatoqualitee** [comment]
Oh dude, hell yes! 🔥 🚒 🚒

**Comment by potatoqualitee** [comment]
Omg and you wrote a test 😻 Thank you ! Will let the tests run and merge. I did have to change your PR to commit to development instead of mater. right now, I merge so often that it's not a big deal but it may cause a conflict in the future.

**Comment by nvarscar** [comment]
@potatoqualitee not a big deal :blush: I'll make sure to push into the dev branch next time

**Comment by potatoqualitee** [comment]
It failed but on the credential. It's interesting, appveyor fails far less at night. We had a streak of green there. Either way, thank you!

**Pull request merged**
