### PR TITLE
Rename Test-DbaValidLogin, fixes #437

### LINKED ISSUE #437: Test-DbaValidLogin - output properties
I like this function a lot, it's very handy. And it is very fast too in my environment. Great work.

But, the object properties should be renamed to be clearer, and consistent with other functions.

My suggestion:

ComputerName
SqlInstance (split in ComputerName and SqlInstance)
Domain
LoginName (or SAMAccountName if the AD property used)
LoginType
ExistsinAD
EnabledinAD
EnabledinSqlServer

maybe 'PasswordIsExpired' could be of interest too

I would definitely choose for two [enabled] or two [disabled] properties, even if the original is one time enabled = true, and the other one disabled = false.
This is exactly where dbatools can add value: a weak point in the MS methodology that we can make better and consistent for users.
Another option is to have [ADstatus] and [SqlStatus] as 'enabled' or 'disabled' instead of true and false

I don't know what the ADLoginDetails column is for, what I see is like a concatenation of  other properties? If they are useful there, than they can be more useful as separate properties, no?

The values of [LoginType] could remain what they are: 'Windows User', 'Windows Group',... That would be what DBA's are used to. So there's no need to manipulate those.

A general  way to go is to replace all -Detailed switches with -Simple. Default we'll always show all we have, and with -Simple we reduce the output to the essentials
 ( as a shortcut to the most probable ' | Select-Object a, b, c')

- [ ] Rename output properties
- [ ] Replace -Detailed with -Simple
- [ ] Add PasswordIsExpired
- [ ] Change Login Type values to original name

### PR DESCRIPTION
**Pull request by niphlod**
## Type of Change

 - [x] Bug fix (non-breaking change, fixes #437)
 - [ ] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
This rename was long due.
/cc @gbargsley to rename the relevant page on dbatools.io
/cc @potatoqualitee to update properly manifest

### CODE REVIEW

**Comment by potatoqualitee** [comment]
thanks @niphlod ! Should this be named anything else like DomainLogin? thinking xplat.

**Comment by niphlod** [comment]
This is what was ruled a long time ago,  see #437. I'm unaware of further
"developments" on the naming side of things

Il lun 25 giu 2018, 12:28 Chrissy LeMaire <notifications@github.com> ha
scritto:

**Comment by gbargsley** [comment]
The dbatools.psd1 does not have the name updated?

**Comment by gbargsley** [comment]
Or what branch should I be pulling from?

**Comment by niphlod** [comment]
This is the branch but modifications to manifest and module core are only
allowed to miss potatoqualitee ;-)

Il lun 25 giu 2018, 19:57 Garry Bargsley <notifications@github.com> ha
scritto:

**Comment by potatoqualitee** [comment]
makes sense since it's doing a bunch of ad queries, thanks @niphlod.

@gbargsley - it'll be there in the next release, i'll ping you 👍

**Pull request merged**
