### PR TITLE
Clean up of MaxMemory commands (Get, Set, and Test)

### PR DESCRIPTION
**Pull request by wsmelton**
## Type of Change

 - [x] Bug fix (non-breaking change, fixes #<enter issue number>)
 - [ ] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [x] Pester test is included
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 
A bit of a bug found in Set-DbaMaxMemory in how connections were managed. However, in the end, this required touching all three commands to clean up things.

Conversation in Slack but overall the commands were not following the standard we use for making connections to a given instance, and then use that connection in any sub call we have. This PR address that among other things.

The test for `Set-DbaMaxMemory` I also added a revert with BeforeAll and AfterAll so if you run this against your local instance it will put the values back the way they were found.

### CODE REVIEW

**Comment by wsmelton** [comment]
We do need to likely expand the test on the set command...just don't have time to put in on it today....best to get fix out on issue with the command.

**Comment by potatoqualitee** [comment]
awesome, thanks so much shawn!

**Comment by potatoqualitee** [comment]
Tests pass except for tabs(?)

**Comment by wsmelton** [comment]
Unsure what converted it...

**Comment by wsmelton** [comment]
@potatoqualitee @niphlod so yall will have to explain what that test is looking for because from VS Code the file is set to spaces. So why does your test show it is not?

**Comment by wsmelton** [comment]
Finally

**Comment by potatoqualitee** [comment]
oh la la!

**Comment by potatoqualitee** [comment]
Thank youuuuuuuuu 🙇

**Pull request merged**
