### PR TITLE
Import-DbaCsv - Trying to resolve #6553 field header not found

### LINKED ISSUE #6553: [Import-DbaCsv] Failure |  field header not found.
While attempting to import a .csv file into a database, I have received this error for the last 3 versions. I am currently running version 1.0.111 

This is the full command I am using:
Import-DbaCsv -Path 'C:\Temp\TempData.csv' -SqlInstance $ServerName  -Database FirePowerData -ParseErrorAction AdvanceToNextLine -SkipEmptyLine -Table TempData

### Environmental information

```
#### PowerShell version:

Name                           Value                                               
----                           -----                                               
PSVersion                      5.1.17763.1007                                      
PSEdition                      Desktop                                             
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                             
BuildVersion                   10.0.17763.1007                                     
CLRVersion                     4.0.30319.42000                                     
WSManStackVersion              3.0                                                 
PSRemotingProtocolVersion      2.3                                                 
SerializationVersion           1.1.0.1                                             




#### dbatools Module version:


Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.111\dbatools.psd1
Version : 1.0.111




```

```powershell
# Replace with output of Get-Culture
```

#### SQL Server:

```sql
/* REPLACE WITH output of @@VERSION */
```
Microsoft SQL Server 2016 (SP2-CU12) (KB4536648) - 13.0.5698.0 (X64)   Feb 15 2020 01:47:30   Copyright (c) Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) 

```sql
/* REPLACE WITH output of @@LANGUAGE */
```

### Report

Yes, I have tested this in the Powershell command.

#### Host used

- [ x] powershell.exe
- [ x] ISE
- [ ] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [x ] Still buggy in powershell.exe

#### Errors Received

```


PSMessageDetails      : 
Exception             : System.Management.Automation.RuntimeException: You cannot call a method on a 
                        null-valued expression.
                           at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(Functi
                        onContext funcContext, Exception exception)
                           at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(Interpret
                        edFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(I
                        nterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(I
                        nterpretedFrame frame)
TargetObject          : 
CategoryInfo          : InvalidOperation: (:) [], RuntimeException
FullyQualifiedErrorId : InvokeMethodOnNull
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Import-DbaCsv<End>, C:\Program 
                        Files\WindowsPowerShell\Modules\dbatools\1.0.108\allcommands.ps1: line 38891
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}

```

#### Steps to Reproduce

Import-DbaCsv -Path 'C:\Temp\TempData.csv' -SqlInstance 'RWR-SQL-00-IG'  -Database FirePowerData -ParseErrorAction AdvanceToNextLine -SkipEmptyLine -Table TempData
#### Expected Behavior

I expected success. It used to work with earlier builds, but the last 3 builds have been broken.
#### Actual Behavior

WARNING: [10:41:06][Import-DbaCsv] Failure | '"DestinationPort"' field header not found.
Parameter name: name

### PR DESCRIPTION
**Pull request by jpomfret**
## Type of Change

 - [X] Bug fix (non-breaking change, fixes #6553 
 - [ ] New feature (non-breaking change, adds functionality, fixes # )
 - [ ] Breaking change (effects multiple commands or functionality, fixes # )
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
 
Compared v1.0.61 which was reported to work and then worked through changes since then - I believe this rolls back the change that broke it - however I'm not sure if I've broken something else.

Also couldn't run pester tests locally - looks like I'm missing csv files to import?

This was causing me an issue at work and making this change resolved the issue and I could successfully load the file. 

_**This needs some testing!**_

### CODE REVIEW

**Comment by wsmelton** [comment]
This test you need to pull down the appveyor lab repo that has some premade files in it.

https://github.com/sqlcollaborative/appveyor-lab

**Comment by jpomfret** [comment]
Sweet - I'll give that a go

**Comment by jpomfret** [comment]
Tests pass locally when you have the right files to import - thanks @wsmelton 

Not sure how to add a test for what was broken, as I'm struggling to replicate it on this laptop. I'll keep trying

**Comment by jpomfret** [comment]
Ok I have it!

The following CSV:
```csv
"20210221","test","test2"
```

The current version fails, fixed version succeeds if I run:
```
Import-DbaCsv -Path ..\appveyor-lab\csv\HeaderIssues.csv  -SqlInstance mssql1 -Database tempdb
```

Ok If I add this csv to the appveyor-lab repo and then write a test based off that?

**Comment by potatoqualitee** [comment]
yes, please feel free to add @jpomfret ! Then the code looks good, feel free to squash and merge once tests pass. this test passed but i'll wait till you add what you'd like to add.

**Comment by jpomfret** [comment]
Added a new csv file to appveyor-lab repo ([CommaSeparatedWithHeader.csv](https://github.com/sqlcollaborative/appveyor-lab/blob/master/csv/CommaSeparatedWithHeader.csv)) so I can write a test to ensure this bug stays fixed.

Fails against current development branch:
image

Success against this branch 😄 
image

**Pull request merged**
