### PR TITLE
Get-DbaSqlLog - Add filters for Text, Source, and DateTime

### PR DESCRIPTION
**Pull request by wsmelton**
## Type of Change

 - [ ] Bug fix (non-breaking change, fixes #<enter issue number>)
 - [x] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [x] Pester test is included

### Purpose
 
Who does want to be able to query their enterprise and find out how many login failed attempts have been found:
image

### Approach

We all want to filter error logs based on various use cases. I've tried to expand this to include most of the ones I have seen used: Text, Source, Before and After.

### Commands to test

The test pretty much cover the methods that can be used...almost 100% code coverage I think.

image

### CODE REVIEW

**Comment by potatoqualitee** [comment]
bombass test! only issue is that there's no Help for Before and After. Should taht be Start and End like other ommands? Haven't checked, just wondering.

**Comment by wsmelton** [comment]
I had thought of that @potatoqualitee 

Checked commands for that builtin to PS use before and after when reading various logs. 

Start and End don't sound right to me. I'm looking for messages start of this date? Or I'm looking for messages after this date?

**Comment by wsmelton** [comment]
Forgot to add examples to. Will do that when I get back home later this evening.

**Comment by wsmelton** [comment]
Help has been added....bonus points to anyone that find the significance of the dates I used in the examples.

**Comment by potatoqualitee** [comment]
beautiful! 🌷

**Pull request merged**
