### PR TITLE
Connect-DbaInstance - Accept NonPooledConnection with SMO (new code path)

### LINKED ISSUE #7279: [Bug] Connect-DbaInstance - SMO is reused even if -NonPooledConnection is used
The behavior can be shown very well at the command Install-DbaMaintenanceSolution, because it absolutely needs a connection with the option NonPooledConnection (to reuse a temp table).

I use this code:
```
$instance = 'SRV1'
$serverPooled = Connect-DbaInstance -SqlInstance $instance
Install-DbaMaintenanceSolution -SqlInstance $serverPooled -InstallJobs -ReplaceExisting
$serverNonPooled = Connect-DbaInstance -SqlInstance $instance -NonPooledConnection
Install-DbaMaintenanceSolution -SqlInstance $serverNonPooled -InstallJobs -ReplaceExisting
```

image

In a first step I will update the new code path of Connect-DbaInstance to test for -NonPooledConnection when reusing an SMO and then not reusing it but building a new one. I am not yet sure what the options are, as I must "clone" the SMO with the authentication information and just change `.ConnectionContext.NonPooledConnection` to `$true`. I anybody has ideas - you're welcome to help.

### PR DESCRIPTION
**Pull request by andreasjordan**
## Type of Change

 - [ ] Bug fix (non-breaking change, fixes # )
 - [x] New feature (non-breaking change, adds functionality, fixes #7279 )
 - [ ] Breaking change (effects multiple commands or functionality, fixes # )
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system

### CODE REVIEW

**Comment by potatoqualitee** [comment]
oh la la, i like this! Thank you. Changes seem reasonable and will be merged once the tests pass.

**Comment by potatoqualitee** [comment]
@jpomfret - i recall you having issues with pooling in the past. can you check to see if this continues to work for you?

**Comment by jpomfret** [comment]
I'll take a look and test it out - thanks folks

**Review by jpomfret — COMMENTED** [review]
Looks good to me - thanks

**Comment by potatoqualitee** [comment]
awesome, thanks @jpomfret and @andreasjordan !

**Pull request merged**
