### PR TITLE
Manage Instance doesn't script WithReplace

### PR DESCRIPTION
**Pull request by potatoqualitee**
it may be a bug we need to report

image

this is a workaround

### CODE REVIEW

**Comment by potatoqualitee** [comment]
This seems a bit slower than WithReplace btw.

**Comment by potatoqualitee** [comment]
Confirmed unsupported by Jovan.

WITH REPLACE option is not supported in RESTORE statement in Managed Instance - see https://docs.microsoft.com/en-us/azure/sql-database/sql-database-managed-instance-transact-sql-information#restore-statement . Here is a list of differences: https://docs.microsoft.com/en-us/azure/sql-database/sql-database-managed-instance-transact-sql-information#restore-statement

**Comment by Stuart-Moore** [comment]
There's a load of other bits it does't support. Would suggest we do a check at the top of the restore and then ignore the bits that don't exist (like file moves, etc).

**Comment by potatoqualitee** [comment]
should i close this PR? If they use WithReplace should we recommend they use Remove then Restore, instead? ty 💯

**Comment by Stuart-Moore** [comment]
Yes, I've a working version that hides the drop under withreplace so user doesn't notice.  

I'll push up a draft PR in the morning to track the changes as I make them.  

Trying to make it all as transparent as poss for the users  
--  
Stuart Moore

**Comment by potatoqualitee** [comment]
thanks so much 🙇

**Pull request closed without merging**
