### PR TITLE
Find-DbaCommand - it's looking for aliases

### PR DESCRIPTION
**Pull request by potatoqualitee**
hey uh @niphlod  - any idea why this fix didn't work? When I run it, it looks for help for the alises as well.

### CODE REVIEW

**Comment by potatoqualitee** [comment]
image

**Comment by niphlod** [comment]
-type function is a good way to go but then you must use $c.Name not $c.Key

**Comment by niphlod** [comment]
also, no getenumerator needed anymore

**Comment by potatoqualitee** [comment]
fixed :D

**Pull request merged**
