### PR TITLE
new command: Set-DbaResourceGovernor

### LINKED ISSUE #7752: New command: Set-DbaResourceGovernor
### Summarize Command's Functionality

Will enable/disable Resource Governor on an instance and set the classifier function for it.

I'm aiming to start with these, then later build out other Set-DbaRg* commands for the remaining Resource Governor components. Feel free to assign the issue to me.

### Is there a command that is similiar or close to what you are looking for?

No

### PR DESCRIPTION
**Pull request by LowlyDBA**
## Type of Change

 - [ ] Bug fix (non-breaking change, fixes # )
 - [x] New feature (non-breaking change, adds functionality, fixes #7752 
 - [ ] Breaking change (effects multiple commands or functionality, fixes # )
 - [x] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1`)
 - [ ] Adding code coverage to existing functionality
 - [x] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [x] Unit test is included
 - [ ] Documentation
 - [ ] Build system

### Purpose
To add functionality for enabling and disabling resource governor. More resource gov related functions to come.

### Commands to test
Set-DbaResourceGovernor

### CODE REVIEW

**Comment by LowlyDBA** [comment]
Not sure if it makes more sense to do a separate `Set-DbaResourceGovernor` command for specifying the [ClassifierFunction](https://docs.microsoft.com/en-us/dotnet/api/microsoft.sqlserver.management.smo.resourcegovernor.classifierfunction?view=sql-smo-160) or to include it in the enable/disable commands ?

**Comment by LowlyDBA** [comment]
Should be a in quasi-finalized state, ready for review, after this last build completes.

**Review by niphlod — APPROVED** [review]

**Comment by niphlod** [comment]
watch out, usually in PRs dbatools.psd1 and dbatools.psm1 should not be "touched" but I'm sure who'll merge will adapt.

**Comment by potatoqualitee** [comment]
Fantastic! Thank you. It is convenient that I don't have to add them to the psd1 and psm1. This used to be problematic when we were adding commands galore, but now that it's slowed down, it's not such a problem 👍🏼

**Pull request merged**
