### PR TITLE
Internal: Replace Connect-SqlInstance by Connect-DbaInstance (part 8)

### LINKED ISSUE #7319: We should really remove Connect-SqlInstance and replace it with Connect-DbaInstance
This is the only code inside of Connect-SqlInstance:

https://github.com/sqlcollaborative/dbatools/blob/de024aaa616fe37de7c8eedb796a2352ab08529a/internal/functions/Connect-SqlInstance.ps1#L58-L75

For already created SMOs (`$SqlInstance.InputObject.GetType().Name -eq 'Server'`) to Azure (`$SqlInstance.InputObject.DatabaseEngineType -eq "SqlAzureDatabase"`) it does test for `$AzureUnsupported` and would fail. Inside of Connect-DbaInstance, this is only done in the new code path, not in the old one. So we would have to address this.
Here is the reference to the new code path:
https://github.com/sqlcollaborative/dbatools/blob/de024aaa616fe37de7c8eedb796a2352ab08529a/functions/Connect-DbaInstance.ps1#L821-L823

For all other cases it just starts Connect-DbaInstance with the bound parameters and sets `-ClientName (Get-DbatoolsConfigValue -FullName 'sql.connection.clientname')` which is the default there anyway (`[string]$ClientName = (Get-DbatoolsConfigValue -FullName 'sql.connection.clientname')`).
Problem here: Connect-SqlInstance has a parameter `[switch]$NonPooled`, Connect-DbaInstance calls it `[switch]$NonPooledConnection` (without an alias - as far as I see). So this would be a bug, right?

### PR DESCRIPTION
**Pull request by andreasjordan**
Not a bug fix and not a new feature, just internal refactoring to align the part where commands open a connection.
This is the last step and finally fixes #7319.

Please have a look at the scripts in internal/dynamicparams/:
* Do we need the `-ErrorAction Stop`?
* Why is the connection made if the resulting `$serverObject` is never used?
* Should we change processHostname.ps1, processProgram.ps1 and processSpid.ps1 to align them with the others? They use the resulting `$instance` (which should be named `$server`?).

Please have a look at Get-BackupAncientHistory.ps1, I think the command has more issues. But as it is only called once from Backup-DbaDatabase we should maybe remove all the functionality that is not used.

Some internal commands use try catch around Connect-DbaInstance, some don't. As they are internal commands, I think we should rely on the calling external command that SqlInstance is an already opened connection and to not use try catch in the internal commands. We could also think of not using Connect-DbaInstance again and just say `$server = $SqlInstance.InputObject`. I'm not sure which is the best way, but we should have one rule for all the internal commands.

### CODE REVIEW

**Comment by wsmelton** [comment]
> Do we need the -ErrorAction Stop?

Yes

**Comment by wsmelton** [comment]
A note that TEPP has to be manually tested everywhere that code is referenced or expected because we do not have tests for any of it (not sure it can be).

**Comment by andreasjordan** [comment]
I just testet TEPP and I have seen no issues.
We could try to do an automatic test to see if the cache is filled - that should work with no problem.
But I don't have an idea how to see if the cache is used while using <TAB> with a command.

**Comment by potatoqualitee** [comment]
I tested and cache is used. Unfortunately, I don't have the bandwidth to address the questions asked and will rely on others to Approve 👍🏼

**Comment by andreasjordan** [comment]
So who can approve this? @niphlod ?

**Review by niphlod — APPROVED** [review]

**Comment by niphlod** [comment]
sorry, somewhat got lost in the notifications, thanks for the ping @andreasjordan

**Comment by potatoqualitee** [comment]
sweet, thanks to both of you 🙇🏼

**Pull request merged**
