### PR TITLE
Fixed integer issue

### PR DESCRIPTION
**Pull request by sanderstad**
Invoke-DbaLogShipping:
- Fixed example in help
- Removed the integer values for the schedule for the frequency types
and the frequency subday types
- Fixed error mesages that referred to the wrong parameters
New-DbaAgentSchedule
- Added values to switch statements to support the log shipping better
Set-DbaAgentSchedule
- Added values to switch statements to support the log shipping better
- Changed parameter types to be in line with the New-DbaAgentSchedule
function
New-DbaLogShipping...:
- Changed the function Connect-SqlServer to Connect-DbaSqlServer
- Fixed some mall issues with parameters

### CODE REVIEW

**Comment by potatoqualitee** [comment]
Can you plz attach some screenshots of this working, @sanderstad ? Sorry it's been so challenging getting a tester.

**Comment by gbargsley** [comment]
What am I. :(

**Comment by sanderstad** [comment]
Example
invoke-dbalogshipping_working

**Comment by potatoqualitee** [comment]
LOL! No no, @gbargsley ! This specific command is hard because it requires a complex setup. You are the best tester 💟 💝 💟 💝💟 💝💟 💝💟 💝💟 💝💟 💝💟 💝💟 💝💟 💝💟 💝💟 💝💟 💝💟 💝💟 💝💟 💝💟 💝💟 💝💟 💝💟 💝💟 💝💟 💝💟 💝💟 💝💟 💝💟 💝💟 💝💟 💝💟 💝💟 💝💟 💝💟 💝💟 💝💟 💝💟 💝💟 💝💟 💝💟 💝💟 💝💟 💝💟 💝💟 💝💟 💝💟 💝💟 💝💟 💝💟 💝💟 💝💟 💝💟 💝💟 💝💟 💝💟 💝💟 💝💟 💝💟 💝💟 💝💟 💝💟 💝💟 💝💟 💝💟 💝💟 💝💟 💝

**Comment by potatoqualitee** [comment]
Thank you, @sanderstad ! Also, for the most part, I'll be standardizing _some_ of your commands to remove Output  and replace with Verbose unless there's a significant reason (I've used output in my own for specific reasons, and will keep that in mind)

**Pull request merged**
