### PR TITLE
Get-DbaDatabaseFile add next growth

### PR DESCRIPTION
**Pull request by PowerDBAKlaas**
- [ ] Bug fix (non-breaking change, fixes #<enter issue number>)
 - [X] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 
### Purpose
show the size of the next growth event in a friendly format

### Approach
@josh-simar added the calculations
@powerdbaklaas added a check to compare with available space

### CODE REVIEW

**Comment by josh-simar** [comment]
@PowerDBAKlaas  Should that growth greater check not be greater than the way it is written?

**Comment by wsmelton** [comment]
It does not return an accurate value...At most by default if growth is set to a static value, the next growth event should be showing that size value.

image

It would only be where growth is set to no value, or auto growth is disabled that the next growth event would show zero.

image

If interested this could be more easily done via adjusting the T-SQL than trying to get the right login in PowerShell:
[_Database_NextGrowthIncrement - Copy.txt](https://github.com/sqlcollaborative/dbatools/files/1485353/_Database_NextGrowthIncrement.-.Copy.txt)

**Comment by PowerDBAKlaas** [comment]
oops
I made a lot of mistakes in one line:
+ I assumed availablespace was up to maxsize, but it is actually the unusedspace. I believe we named this differently in other functions.
+ I forgot to check for unlimited maxsize
+ I checked with `-lt` while it should obviously be `-gt`, you're right @josh-simar 

This should all be corrected now.
@wsmelton I'll look at the T-SQL version tomorrow, at work.

**Comment by PowerDBAKlaas** [comment]
After a bit of examination, I think we can indeed move all calculations inside a T-SQL statement.
I've also had a look at `Get-DbaDatabaseSpace`. If we include the last 3 properties from that function in here, that one becomes totally redundant.
Should that be a goal for 1.0? @wsmelton @potatoqualitee @ck @Stuart-Moore ?

**Comment by potatoqualitee** [comment]
hey @PowerDBAKlaas, thanks so much for all of your work! I see what you're saying about the redundancy but these are two things that people will look for (Space perhaps moreso than File) so I'd like to keep them, even with the overlap, as the name is just intuitive for both. I'd like to merge these fixes then get another PR for moving to T-SQL, does that work for everyone?

**Comment by wsmelton** [comment]
Yeah, been thinking about that a bit the last day or so. Compare with T-SQL folks match up `Get-DbaDbSpace` with running something like `exec sp_spaceused` and running something different to get file info on a database, even though the latter can give you both.

I'd say in this specific situation it would be best to keep them both.

**Comment by PowerDBAKlaas** [comment]
Well, in the beginning there was overlap, but after all modifications both functions are exactly the same.
If we keep `Get-DbaDbSpace` it could better return the DB totals instead of files.

**Comment by potatoqualitee** [comment]
Agreed there! Let's change both the name and the output - returning totals instead of files (most of the time, I care about totals, not files, and wouldnt like to have to sum manually)

**Comment by potatoqualitee** [comment]
Would you be up for doing that bit this week @PowerDBAKlaas ?

**Comment by PowerDBAKlaas** [comment]
Actually, 'Size', 'Dataspaceusage','IndexSpaceUsage','AvailableSpace' and 'MaxSize' are in `Get-DbaDatabase` too. So I'm back at "`Get-DbaDatabaseSpace` is completely redundant.

Anyway, that has nothing to do with this PR: this is improving the DBFile function. This one can be merged, can't it?

**Comment by potatoqualitee** [comment]
Oh, oops! You're right. My apologies.

**Comment by potatoqualitee** [comment]
merged 😌

**Pull request merged**
