### PR TITLE
New improved unit tests - version2

### PR DESCRIPTION
**Pull request by jpomfret**
## Type of Change

 - [] Bug fix (non-breaking change, fixes #<enter issue number>)
 - [ ] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
 
Combining unit tests into one that confirms no parameters were added/removed/renamed

### CODE REVIEW

**Comment by potatoqualitee** [comment]
you the best 💯

**Comment by jpomfret** [comment]
Ok... @awickham10 had a thought..

If we replaced 
`(Get-ChildItem function:\Watch-DbaUpdate).Parameters.Keys` 
with 
`(Get-Command $CommandName).Parameters.Keys`

That would mean we didn't have to hard code the function name into every test file. Any reason not to do this that you know about?

**Comment by potatoqualitee** [comment]
i believe the answer is speed, can you test that part?

**Comment by potatoqualitee** [comment]
and we may be able to increase the speed by doing `Get-Command -Module dbatools`

**Comment by jpomfret** [comment]
Using `function` vs `get-command` performed pretty similarly and the results were all in ms
`Get-Command -Module dbatools` made it slower for some reason?!? more filtering?

**Comment by potatoqualitee** [comment]
wow! im surprised, k that works!

**Comment by sqllensman** [comment]
All the Unit tests that I have written use $Command Name. Never seen any issues

**Comment by jpomfret** [comment]
@potatoqualitee just checked the last run for appveyor which was merging all these tests into development and it ran in 13 mins 3 seconds, looks right in line for previous runs... if anything a little faster.

**Pull request merged**
