### PR TITLE
Copy-DbaDatabase, drop existing correctly

### LINKED ISSUE #3358: Copy-DbaDatabase, remove reference to Remove-SqlDatabase
## Bug Report
Remove-SqlDatabase needs to be removed from Copy-DbaDatabase

### PR DESCRIPTION
**Pull request by niphlod**
## Type of Change
 - [x] Bug fix (non-breaking change, fixes #3358 )
 - [ ] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [x] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [X] Adding code coverage to existing functionality
 - [x] Pester test is included
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 
### Purpose
Make Copy-DbaDatabase behave correctly. Frankly, tests were skipped for no reason, so reenabled them. 
Heck, this is probably one of the most used functions around and has many cogs moving... we should add definitely more in here.

### Approach
Same deal as previous rewrites with Remove-SqlDatabase --> Remove-DbaDatabase.
Plus some removal of unused variables, plus a bit of rewrite around unuseful thingies lying around.

### CODE REVIEW

**Comment by niphlod** [comment]
grrr. hopped on appveyor's, problem is the test does not run when launched by .\Tests\appveyor.pester.ps1 -IncludeCoverage but works fine with manual.pester.ps1 .... ideas ?

I have the support package directly from the appveyor server if someone wants to dive in.

**Comment by niphlod** [comment]
I can also reproduce locally. to do a quick test you can try

```
cd path\to\repo
.\tests\manual.pester.ps1 copy-dbadatabase -testintegration
```
vs
```
cd path\to\repo
$env:APPVEYOR_REPO_COMMIT_MESSAGE = '(do copy-dbadatabase)'
.\tests\appveyor.pester.ps1 -IncludeCoverage -ProjectRoot path\to\repo
```

**Comment by potatoqualitee** [comment]
unfortunately, i could never figure out how to get it working and added getting it working to the todo list. is it possible to skip it in a normal run then use manual pester to call it from appveyor?

**Comment by niphlod** [comment]
the skipping time is past.
I'm gonna remove all workarounds/shortcuts in all written tests.

We need to address those intricacies sooner rather than later. 
This sums up to the - relevant - "technical debt".

A quick fix with a simple regr test was ready on my dev rig in less than 20 minutes
Trying to get into our CI ended up in a 4 hour chase

**Comment by potatoqualitee** [comment]
merged this and will get it working in my branch

**Pull request merged**
