### PR TITLE
Enhances in the log shipping function

### PR DESCRIPTION
**Pull request by sanderstad**
Added option NoInitialization to skip the creation of the secondary database
Added option UseBackupFolder to use an entire folder to restore a secondary database
Added option StandbyDirectory to set where the TUF files need to be saved
Added timeout settings to make sure no connection will time out
Added extra checks to make sure contradicting variables are not allowed
Enhanced the standby to use new features from the Restore-DbaDatabase function
Fixed an issue with the name of the secondary database that in some cases did not work out

### CODE REVIEW

**Comment by sanderstad** [comment]
Proof that it still works
image

**Comment by potatoqualitee** [comment]
can we have some pics of it working or commands/setups that could help us test? 

merci!

**Comment by potatoqualitee** [comment]
LOL!

**Comment by potatoqualitee** [comment]
Thanks bud 💞

**Comment by sanderstad** [comment]
Command used for the test:
`Invoke-DbaLogShipping -SourceSqlInstance sstad-pc -DestinationSqlInstance localhost -Database DB2 -BackupNetworkPath "\\sstad-pc\logshipping\backup" -BackupLocalPath "C:\temp\logshipping\backup" -GenerateFullBackup -CompressBackup -SecondaryDatabaseSuffix "_LS" -Force`

**Pull request merged**
