### PR TITLE
feature-DbaGlennBerryDMV

### PR DESCRIPTION
**Pull request by andrekamman**
Hi, introducing automated downloading, parsing and running of Glenn Berry's DMV scripts. 
It can save the results to clixml, csv and excel.
Hope you like it!

Simplest option to run it is:
Get-DbaGlennBerryDMV

This will download the latest versions of Glenn's script for every version, run all scripts on the default instance., and save it to a clixml file in "My Documents". 
Many other options available, like showing a grid to select only the scripts you want to run, pipe in a list of servers. It can parse and run all versions that Glenn Berry supports. (from 2005 to vnext currently)

### CODE REVIEW

**Comment by niphlod** [comment]
cooooooooooooooool !

**Comment by PowerDBAKlaas** [comment]
Geweldig, André!

Wonderful addition, @andrekamman .
(Allthough I wouldn't make "run everything" the default.)

**Comment by ctrlbold** [comment]
@andrekamman - Soooo good, what a strong addition :bowtie:! We will be reviewing this magic and have it merged within the next week 👍 

@FriedrichWeinmann - would you be able to assist with configuring the default location? I promise to pick it up for 1.0 ;)

@PowerDBAKlaas - Will you be able to help with the naming? DMV should be Dmv and I saw a param and some validations that were all lower case. Should the Invoke be Invoke or an Install? If it remains Invoke, should we change Install-SqlSpWhois for 1.0?

**Comment by wsmelton** [comment]
`Invoke-Sqlcmd` is being used to connect to a SQL Server instance. Need to change this to `Invoke-Sqlcmd2` or the connect command we use in other commands.

**Comment by PowerDBAKlaas** [comment]
Function names could be more concise and clear, I feel.
Can't "Invoke-DbaGlennBerryDMVDownloadScript" be renamed to "Get-DbaDiagnosticQueries",
and "Invoke-DbaGlennBerryDMVScriptParser" to "Convert-DbaDiagnosticQueries", and so on?
Or would that be incorrect?

**Comment by andrekamman** [comment]
Glenn calls them diagnostic queries, so I don't see a problem with the suggested naming. More concise and clear for sure. Perhaps the help can explain the source and explain who Glenn is and were to find his documentation about the scripts?

**Comment by PowerDBAKlaas** [comment]
Oh yes,
I certainly want to honour Glenn and give him the credits and thanks we owe him.
In the help would be a good place, and in a blog and the dbatools website too.
I just don't like to see personal names in function names.

**Comment by andrekamman** [comment]
I think we agree on this. So forgive me the n00b question. How does this work? Do I change and update the PR?

**Comment by PowerDBAKlaas** [comment]
If your branch still exists, yes. You can make your changes, add, commit and push. The PR will then automatically be updated.
You should be careful when renaming a file, though. You can search for that on the git documentation or help for the application you use,
or you can ask @ConstantineK or @wsmelton 😄

**Comment by andrekamman** [comment]
If I rename Invoke-DbaGlennBerryDmvDownloadScript to Get-DbaDiagnosticQueries
What do I name Get-DbaGlennBerryDmv ? (the script that runs the queries)
Invoke-DbaDiagnosticQuery for instance?

**Comment by andrekamman** [comment]
Perhaps use Get-DbaDiagnosticScript for the download function and Invoke-DbaDiagnosticQuery for the function that runs queries from the script. (Keeps it from having plural in the names as well)

**Comment by PowerDBAKlaas** [comment]
Start-DbaDiagnosticQuery

**Comment by andrekamman** [comment]
Start is the new Invoke? 
Ok, changing it now...

**Comment by PowerDBAKlaas** [comment]
Start- is around for a while 😄 
Invoke- is possible too
https://msdn.microsoft.com/en-us/library/ms714428(v=vs.85).aspx

**Comment by potatoqualitee** [comment]
LOL, i was like "mmm start is async, and i kinda messed up when i named Start-SqlMigratin tho it's good to convey whats up." I'll be renaming back to invoke!

**Comment by potatoqualitee** [comment]
btw, @PowerDBAKlaas - i really like the new command names you offered up. @andrekamman, Klaas made us change all -Ola switches to MaintenancePlans, so it's going with the theme ;)

I will be updating your commands to be more in-line with the rest of our commands. Invoke-DbaDiagnosticQuery will output PSCustomObject instead of CSV, XML or Excel. I know this is super painful but we'll include how to do the above with examples so that the spirit remains.

**Comment by potatoqualitee** [comment]
So here's what I'm thinking...

Back in the day, I learned something very relieving from Poshaholic - he said that I shouldn't be the one doing the exports or imports for people within a script (unless it's an import/export script). It was relieving because I was spending so much time verifying paths and export options and all that. 

Since then, I've moved to putting that on the user. I know it's sad face (I'm still debating with Klaas about Show-SqlWhoisActive ;). So here's what I propose and if it doesn't work out, then we'll revert it.

````
Invoke-DbaDiagnosticQuery
Save-DbaDiagnosticQuery
ConvertFrom-DbaDiagnosticQuery
```
`Invoke-DbaDiagnosticQuery` will return a pscustomobject. That way, people can `| Export-Csv` or `| Export-Excel` and those modules take care of testing the paths.

I did notice that ConvertFrom-DbaDiagnosticQuery did some fancy things, so I'm thinking

`Invoke-DbaDiagnosticQuery | ConvertFrom-DbaDiagnosticQuery` ...maybe. Though that may be Export instead of Convert-From.

I do see that the results is just one field. I may unroll that to build that custom object if it will make things more useful. Still exploring.

**Comment by potatoqualitee** [comment]
oh also, im gonna add the Save to my Publish script for the gallery and the accompanying scripts will be updated as we release. K night! Will continue working on it more tomorrow.

**Comment by potatoqualitee** [comment]
Merging and patching! Will tag you in new PR. Thanks so much, this looks really awesome!

**Pull request merged**
