### PR TITLE
New-Command Invoke-DbaBalanceDataFiles

### PR DESCRIPTION
**Pull request by sanderstad**
Initial commit to enable the option to balance out data between multiple data files.

### CODE REVIEW

**Comment by sanderstad** [comment]
image

**Comment by potatoqualitee** [comment]
hey sander, thanks for the PR! Please rely less on Write-Message Output (Turn those to verbose) and create a new [pscustomobject] that's basically

-- start of script --
$startingsizes = Get-DbaDatabaseFile whateverwhatever

-- do your fancy footwork --
$endingsize = Get-DbaDatabaseFile whateverwhatever

then output

````
[pscustomobject]@{
     ComputerName = $server.ComputerName ... (and so on)
     Database
     StartingX = $startingsizes.X
     StartingY = $startingsizes.Y
    EndingX = $endingsizes.X
     EndingX = $endingsizes.Y
}

Also, please add help for Confirm , Whatif and RebuildOffline

**Comment by Stuart-Moore** [comment]
Really needs to check for multiple files in the same file group. Could have
multiple file groups with one file each which would currently pass the
check but fail with the rewrite.

Could ado with checking space in files, at least double the original table,
half of which needs to be in each file or you're back where you started
with unbalanced files

Also a warning that you're about to generate a lot of log. Probably alert
if table larger than x

Bare in mind people using this will probably be worried about large tables
rather than smaller ones. So there'll be a lot of IO.

**Comment by potatoqualitee** [comment]
Thanks so much, @Stuart-Moore !

**Comment by potatoqualitee** [comment]
This is looking so good, Sander! Did it address all of the points Start made?

Also, can you send me the code that you used to test (from creating the db and clustered indexes?) That way, I can write an integration test. Or if you would prefer, that is good too. I want it to be as easy as you need.

**Comment by Stuart-Moore** [comment]
Yep, it does. We've been going over some bits on slack, and think we've covered all of them.

Just wanted to make sure people don't shoot themselves in both feet,  and being up front about limitations from the start (even doing it manually isn't going to get a pure 50% split without some tuning to each case)

**Comment by potatoqualitee** [comment]
awesome, thanks stuart! i just dm'd sander, he'll add one more check and then I'll merge 👍

**Comment by potatoqualitee** [comment]
Hello @sanderstad - can you please add your last change so we can get this bad boy merged? Danke!

**Comment by sanderstad** [comment]
Added the free space check 
image

**Comment by potatoqualitee** [comment]
@niphlod can you please add the two failing tests to the 2008 instance instead?

**Comment by potatoqualitee** [comment]
Thanks @sanderstad for another fabulous command! <3

**Pull request merged**
