### PR TITLE
Unit Test Revamp - all the tests

### PR DESCRIPTION
**Pull request by jpomfret**
## Type of Change

 - [ ] Bug fix (non-breaking change, fixes #<enter issue number>)
 - [ ] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [X] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
Changing all the unit tests to match that of #4966 

### Additional Changes
- `Invoke-DbaDbCorruption.Tests.ps1` - file was renamed to match the correct function name `Invoke-DbaDbCorruption`
- `Test-DbaJobOwner.Tests.ps1` - file renamed to match the correct function name `Test-DbaAgentJobOwner`
- `Get-DbaClusterAvailableDisk.Tests.ps1` - removed file, it was testing `Get-DbaWsfcAvailableDisk` and there is already a test file for that one.

### CODE REVIEW

**Comment by wsmelton** [comment]
@jpomfret this is way to big a PR to review and merge.

The renames are best for tracking purposes to be their own individual PR. The cleanup of the unit test if you can do as you have done previously keeping each PR to around 50-60 is best, then we know if something is breaking the current test. The failure right now is effected by some change that was made in this PR but with 521 changes I'm not going to try and figure out what 😁

**Comment by potatoqualitee** [comment]
i asked her to, if they all get to pass, i'll be good merging. she used regex so it's the same changes over and over 😁

**Comment by potatoqualitee** [comment]
I'm going to merge into the `unit` branch and see if those unrelated test failures continue. If so, I'll dig a bit deeper today.

**Comment by jpomfret** [comment]
Three unit tests were still failing for a real reason. They have no params and the "one size fits all" unit test I wrote didn't work for those... I'll dig in a little later and see whether I need to make a change to the test again or not..  Thanks folks

**Comment by potatoqualitee** [comment]
working it now!

**Pull request merged**
