### PR TITLE
Backup

### PR DESCRIPTION
**Pull request by Stuart-Moore**
Fixes # 

Changes proposed in this pull request:
New Backup-DbaDatabase command
New New-DbaSqlDirectory command
 - 
 - 

How to test this code: 
- [ ] 
- [ ] 

Has been tested on minimum requirements:
- [ ]  Powershell 3
- [ ]  Windows 7
- [ ]  SQL Server 2000

Has been tested on maximum requirements:
- [ ]  SQL Server vNext
- [ ]  Windows 10
- [ ]  Azure Database

Tests for tester:
- [ ] Working/useful help content, including link to command on dbatools web site
- [ ] All examples work as advertised
- [ ] Does not contain template content
- [ ] Does not contain excessive/unnecessary amounts of comments
- [ ] Works remotely
- [ ] Works locally
- [ ] Works on lower versions or throws error specifying version not supported
- [ ] Works with named instances
- [ ] Works with clustered instances
- [ ] Handles offline/read only databases
- [ ] Supports multiple servers (at the command line or piped from Get-SqlRegisteredServerName)
- [ ] No un-handled errors which stop the command working with multiple servers

### CODE REVIEW

**Comment by ctrlbold** [comment]
Tested with this

- [ ]  Get-DbaDatabase -SqlInstance sql2005 | Backup-DbaDatabase
- [ ]  Get-DbaDatabase -SqlInstance sql2005 -Databases db_2005_CL80 | Backup-DbaDatabase
- [ ]  Get-DbaDatabase -SqlInstance sql2005 -Databases db_2005_CL80 | Backup-DbaDatabase  -BackupDirectory C:\temp
- [ ]  Get-DbaDatabase -SqlInstance sql2005 -Databases db_2005_CL80 | Backup-DbaDatabase  -- [ ]  - [ ]  BackupDirectory C:\temp -NoCopyOnly
- [ ]  Backup-DbaDatabase
- [ ]  Get-DbaDatabase -SqlInstance sql2005 -Databases db_2005_CL80 | Backup-DbaDatabase  -BackupDirectory C:\temp -NoCopyOnly -BackupFileName adfadf

**Comment by ClaudioESSilva** [comment]
I did some tests here is the comments:

1. 
Databases without full backup spills a warning (which make senses) but can be easily lost one the other output:
image

2.
Then I think this message is misleading:
I already have a database backup done before? Is this message we want? It is trying to find a database backup on the destination folder and if not find, don't do the tlog backup?
image

This reminds me, it is possible to just backup Tlog? Or it is the default behavior if database is in FULL RECOVERY MODEL?

3.
Already reported but to write it down:
Can't backup for multiple files
image

4.
I think the most important bug I found is ignoring my chosen location and don't show file extension:
image

But, if I remove the -FileName with works like expected.
image

With nomenclature "-1" missing? Also we should validate and add the extension. (I haven't test, but if we don't have the extension will we be able to restore from it?, is the command extension agnostic? @Stuart-Moore )
image

**Comment by Stuart-Moore** [comment]
1- There was  a fail reasons property on the return object which has been commented out which would have repeated it in the output

2 - It's using Get-DbaBackupHistory for that bit, so might need to check  the output from that command for that db/instance

You can only backup tlog if you've got a full backup to anchor the chain, even if it's years old. 

3 - It did, will be put back at some point

4 - Yep, that's expected behaviour. There was a check to prevent you using both params
Filename is a FQ file name (C:\something\other\backup.bak) for if you want to do a one off to a specific location. So enter something silly and it'll do that
BackupDirectory was just where you wanted the files dumping. Probably just needed the help clearing up for that one

And it's then dropping into a loop that does the renaming.

yeah, sql doesn't care what the file's called, as long as the internal header is correct

TBH, with all that I'd say it's not worth merging as is.
I don't have time tonight to put everything back together.

**Comment by ctrlbold** [comment]
@Stuart-Moore just updated not to use backuphistory but $database.LastBackupDate -- need to test it. Looking at you and claudio's responses now.

**Comment by ctrlbold** [comment]
removed option to backup to multiple dirs

**Comment by ctrlbold** [comment]
Fixed all of @ClaudioESSilva's issues :D

**Comment by ctrlbold** [comment]
Well, except the one about the warning getting lost in the mess 

what action should i take? just return? does it already? k gotta go work on my demo while somebody tests. plz test yall!

**Comment by Stuart-Moore** [comment]
Give me a minute and I'll put it back

**Comment by ctrlbold** [comment]
🥇 so relieved to see you, @Stuart-Moore !

**Comment by Stuart-Moore** [comment]
IT's now warning
WARNING: Backup-DbaDatabase - You must specify -Databases when not using the pipeline
when I run this:
Get-DbaDatabase -SqlInstance localhost\sqlexpress2016 -Databases fgs,historyrest | Backup-DbaDatabase -SqlInstance localhost\sqlexpress2016 -type full -backupDirectory C:\dbatools\stri1

Works fine as 
Backup-DbaDatabase -SqlInstance localhost\sqlexpress2016 -Databases fgs,datetest -Type Full -BackupDirectory C:\dbatools\stri1 

So looks like the pipeline stuff is broken. And I'm not sure how that's been implemented now.

IF that can be fixed then it should hang together, probably.....

**Comment by ctrlbold** [comment]
fixing now

**Comment by ctrlbold** [comment]
hey @Stuart-Moore - you dont need to (and should not) specify the SqlInstance on Backup-DbaDatabase as it's being passed from Get-DbaDatabase - working on a fix now

**Comment by ctrlbold** [comment]
well, ish ;) It's just enforcing stuff and bypassing stuff

**Pull request merged**
