### PR TITLE
Fix nouns and verbs

### LINKED ISSUE #4346: Fix PSUseSingluarNouns and PSUseApprovedVerbs
### Summary of new feature

This may take some discussion before a PR is submitted.

There quiet a few cases of plural noun cmdlets (and plural noun internal functions)
```
Clear-DbaLatchStatistics.ps1
Clear-DbaWaitStatistics.ps1
Copy-DbaLinkedServer.ps1 (Copy-DbaLinkedServers)
Find-DbaLoginInGroup.ps1 (Get-AllLogins)
Get-DbaDatabase.ps1(Invoke-QueryRawDatabases)
Import-DbaCsvToSql.ps1 (Get-Columns)
Install-DbaMaintenanceSolution.ps1 (Get-DbaOlaWithParameters)
Invoke-DbaBalanceDataFiles.ps1 (Invoke-DbaBalanceDataFiles)
Remove-DbaXESession.ps1 (Remove-XESessions)
Start-DbaXESession.ps1 (Start-XESessions)
Stop-DbaXESession.ps1 (Stop-XESessions)
Update-dbatools.ps1
```
as well as cmdlets which contain internal functions using unapproved verbs
```
Find-DbaInstance.ps1 (IP-toINT64, INT64-toIP)
Get-DbaMaintenanceSolutionLog.ps1 (process-block)
Get-DbaSpn.ps1 (Process-account)
Register-DbatoolsConfig.ps1 (Ensure-RegistryPath)
```

Not sure if we should take the same approach for these, but it could be a combination of fixing words where it makes sense and overriding the rule where it doesn't.

### Proposed technical details (if applicable)

Update the Verbs and Nouns to be valid and singular, or Include an override for the rule in that function.
`[Diagnostics.CodeAnalysis.SuppressMessageAttribute("PSUseSingluarNouns", "")]`
`[Diagnostics.CodeAnalysis.SuppressMessageAttribute("PSUseApprovedVerbs", "")]`

### PR DESCRIPTION
**Pull request by joshcorr**
## Type of Change

 - [x] Bug fix (non-breaking change, fixes #4346 )
 - [ ] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
 
Include rules for PSScriptAnalyzer to Ignore rules in specific situations

### Approach

added:
`[Diagnostics.CodeAnalysis.SuppressMessageAttribute("PSUseSingularNouns","",Justification="It is the proper noun of the cmdlet")]`
`[Diagnostics.CodeAnalysis.SuppressMessageAttribute("PSUseApprovedVerbs","",Justification="Internal functions are ignored")]`

### CODE REVIEW

**Comment by joshcorr** [comment]
Kinda confused why commit b6296f7 failed..

Here are my VSCode settings. What am I missing @niphlod? `shift` + `alt` + `F` ?

image

**Comment by potatoqualitee** [comment]
😻 😻  this is so awesome, thank you so much @joshcorr !! 

I see your tests are passing but you had a question, shall I wait?

**Comment by potatoqualitee** [comment]
oh wait, question is unrelated 👍

**Comment by niphlod** [comment]
@joshcorr : seems fine. Take a look at the bottom of VSCode though, usually when you have 6-7 open files the spawned PS process that talks with VSCode hangs and dies (so, e.g., when you do shift-alt-f it gets to "Formatting..." but then drops dead).

**Pull request merged**
