### PR TITLE
Fix Repair-DbaOrphanUser skipping contained databases

### PR DESCRIPTION
**Pull request by sirsql**
Fix Repair-DbaOrphanUser skipping contained databases

## Type of Change

 - [ ] Bug fix (non-breaking change, fixes #<enter issue number>)
 - [x] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [x] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
 
Fix for issue #5887  so that contained databases are not ignored when attempting to fix orphaned users. 
### Approach

Eliminates the code that looks to see if the database is contained. The existing db level checks cover handling contained users correctly (see SQL below for DB creation on testing this).

### Commands to test

Create database, logins, users, contained users, orphaned users using SQL code at https://gist.github.com/sirsql/760c0c052fbd3d7ef6be5c0f9db09887
Then run `repair-dbadborphanuser -sqlinstance localhost
`

### CODE REVIEW

**Comment by potatoqualitee** [comment]
thanks @sirsql - while waiting for claudio's review, i reformatted it to OTSB standard using `Invoke-DbatoolsFormatter`. I'm not sure why this one in particular got reformatted, but wanted to let you know so that you can sync the branch before making any changes.

**Comment by ClaudioESSilva** [comment]
Hi @sirsql can you please also remove from `Remove-DbaDbOrphanUser` and `Get-DbaDbOrphanUser` to be equal on all commands

**Comment by potatoqualitee** [comment]
@sirsql - will you have time to update Remove and Get?

**Comment by sirsql** [comment]
I'll get it done this weekend

**Comment by sirsql** [comment]
Don't know what the deal is with the formatting. 
Ran - 
```
invoke-dbatoolsformatter "C:\Users\nic\OneDrive\Documents\GitHub\dbatools\functions\Get-DbaDbOrphanUser.ps1"
invoke-dbatoolsformatter "C:\Users\nic\OneDrive\Documents\GitHub\dbatools\functions\Repair-DbaDbOrphanUser.ps1"
Invoke-DbatoolsFormatter "C:\Users\nic\OneDrive\Documents\GitHub\dbatools\functions\Remove-DbaDbOrphanUser.ps1"
```

Also did a pull prior to doing anything else and there's the merge conflict (no conflict on my machine and able to pull from upstream without issues). Are there possible problems with the workspace setup that I am using in vscode?

**Comment by potatoqualitee** [comment]
I think your local branch is extremely out of date. I'll reformat the files then remove the changes to Remove- would you be able to update then resubmit a PR just for the single file?

The formatting issue may be a problem with the version of psscriptanalyzer which I've found to cause problems. @niphlod is there any way you can look into that? I have not been able to update psscriptanalyzer in months.

**Comment by imyourdba** [comment]
I just wanted to check in on this

**Comment by wsmelton** [comment]
Please comment on your issue whether this PR fixed you problem.

The fix was merged 3 months ago.

**Pull request merged**
