### PR TITLE
Measure-DbaBackupThroughput

### PR DESCRIPTION
**Pull request by ctrlbold**
I don't doubt my code is messed up somewhere -- please anyone take a look. I am bad at math.

- [ ] Measure-DbaBackupThroughput -SqlInstance sql2012  | Format-Table
- [ ] Measure-DbaBackupThroughput -SqlInstance sql2005 -Databases SharePoint_Config | Format-Table
- [ ] Measure-DbaBackupThroughput -SqlInstance sql2016 -Since (Get-Date).AddDays(-30) | Format-Table
- [ ] Measure-DbaBackupThroughput -SqlInstance sql2005 -Databases SharePoint_Config -Since (Get-Date).AddDays(-30)

### CODE REVIEW

**Comment by ctrlbold** [comment]
image

yehh

**Comment by ctrlbold** [comment]
image

added avgduration. I'm not so sure I did this part right.

**Comment by ctrlbold** [comment]
Doing total rewrite, don't judge except for AvgDuration. That one isn't working 👎

**Comment by ctrlbold** [comment]
Okay almost done. Can someone help me with the math? There's no way my backup wrote 2404 MB a second. It's shared storage. Perhaps this has something to do with compression?

```
Database                          AvgThroughputMB                AvgSizeMB AvgDuration                       MinThroughputMB          MaxThroughputMB MinBackupDate            MaxBackupDate
WSS_Content                 2404.65                 197278.4 01:15:48.5000000                           142.49                  4345.43 1/8/2017 2:35:45 AM      1/29/2017 3:52:14 AM```

**Comment by niphlod** [comment]
lemme try

**Comment by niphlod** [comment]
my timings and averages are aligned correctly...and I don't see a flaw in the math.

**Comment by ctrlbold** [comment]
Thanks for looking @niphlod - do you have compression enabled? I mean, maybe this is why compression is so awesome is that it's effectively writing at that speed but not really. So this tests your backup throughput but not your storage throughput :brainfry:

**Comment by niphlod** [comment]
math is right doesn't mean command is right. I'm checkin the underlying data.

**Comment by niphlod** [comment]
yep. the underlying data reports the uncompressed size. Get-DbaBackupHistory should need to be modified to report the size of the compressed backup if you want disk throughput.

**Comment by ClaudioESSilva** [comment]
Get-DbaBackupHistory is unaware of compression.

https://github.com/sqlcollaborative/dbatools/blob/master/functions/Get-DbaBackupHistory.ps1#L230

**Comment by niphlod** [comment]
yes but why ? meaning: it's for a specific reason or what ? all that it takes is that for < 2008 the size for TotalSizeMB is get from Backup_Size and from there onwards from compressed_backup_size ...

**Comment by niphlod** [comment]
also, be aware that there's an hiccup in get-dbadatabasehistory .... try running it in a case-sensitive instance :P . Should I log a bug ?

**Comment by ClaudioESSilva** [comment]
@niphlod Yes for sure!

Regarding the compression is different columns:

An example from a script that I use a lot.
```
CASE 
				WHEN bup.compressed_backup_size < bup.backup_size THEN 'Compressed'
				ELSE 'Not Compressed'
			  END AS isBackupCompressed
```

**Comment by niphlod** [comment]
@ClaudioESSilva : 

> yes but why ? meaning: it's for a specific reason or what ? all that it takes is that for < 2008 the size for TotalSizeMB is get from Backup_Size (column) and from there onwards from compressed_backup_size (column)...

**Comment by ClaudioESSilva** [comment]
Sorry misread it 😳 

**I think** he just leaved the sql 2008+ support for later and never finished.

**Comment by niphlod** [comment]
yeah there's also a nasty RANK() that could be easily avoided if we want this to support even 2000...

**Comment by ctrlbold** [comment]
I'd have zero idea how to implement that within a timely manner. Any help? It was necessary for something.

**Comment by niphlod** [comment]
@ctrlbold : I'll try to fix get-dbabackupheader in an hour or two if nothing urgent comes up.

**Comment by ctrlbold** [comment]
@niphlod hell yeah, thanks man!

**Comment by ctrlbold** [comment]
Was this fixed, @niphlod ?

**Comment by niphlod** [comment]
the bug totally. the fact that we could work out it even for mssql 2000 no. we can log an enhancement for it if there is traction for it but I'd refrain from doing it for each and every command. we should have a list of supported targets for each command and see if enough people want it.

**Comment by ctrlbold** [comment]
naw, i dont wanna put in too much effort for 2000. It's always best try within a reasonable amount of time, if not, nbd. thank you for fix! I couldn't remember and my github profile reminded me.

**Pull request merged**
