### PR TITLE
New commands AgentJobCategory fixes #561 #2887

### LINKED ISSUE #561: Create / Find / Assign -DBAAgentCategory
Is this a *feature* OR *bug*:
Enhancement 

https://trello.com/c/GVLuqcdR

**Additional comments**
Create-DBAAgentCategory to create new a category
Find-DBAAgentCategory to list out (not sure if needed to be honest).
Assign-DBAAgentCategory assign a category to a job/s

### PR DESCRIPTION
**Pull request by sanderstad**
New functions to manage the job categories in SQL Sever. Commands added:
- Get-DbaAgentJobCategory
- New-DbaAgentJobCategory
- Set-DbaAgentJobCategory
- Remove-DbaAgentJobCategory

Changed the following functions to support the job categories:
- New-DbaAgentJob
- Set-DbaAgentJob

Added tests for the new functions

Cleaned up the existing functions.

### CODE REVIEW

**Comment by sanderstad** [comment]
Creating new job with category
image

Changing existing job with category
image

Get the job categories and create new ones
image

Change the existing job categories
image

**Comment by sanderstad** [comment]
Solved issue #2887 
image

**Comment by potatoqualitee** [comment]
uitstekend, dank je! Wordt samengevoegd zodra de tests zijn voltooid

**Comment by potatoqualitee** [comment]
one pass! 🥇

**Pull request merged**
