### PR TITLE
Fix Test-DBAFullRecoveryModel -Detailed (#2217)

### PR DESCRIPTION
**Pull request by joshcorr**
## Type of Change

 - [x] Bug fix (non-breaking change, fixes #2217 )
 - [ ] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [x] Pester test is included
 - [ ] Nunit test is included
 - [x] Documentation
 - [ ] Build system
 

### Purpose
 
Update the output of the command to use Select-DefaultView instead of `-Detailed`
Update Documentation and Examples

### Approach

Replaced the `-Detailed` Parameter with Select-DefaultView
Added `Test-DbaDeprecation` to throw a warning
Added `-EnableException`  to allow `Test-DbaDeprecation` to run without error
Added new example demonstrating `| Select * ` to demonstrate returning all properties.

### Screenshots

Before:
image

After:
image

### CODE REVIEW

**Comment by joshcorr** [comment]
The first appveyor failure was because I forgot to check for trailing spaces (didn't know that was a thing). The second failure appears to be something wrong with the appveyor environment as I couldn't find any reference to the cmdlet posted in the pull request in the failing tests.

**Comment by potatoqualitee** [comment]
LOVE IT! thank you!!

**Comment by wsmelton** [comment]
I'm not sure of the intent @ClaudioESSilva had with this command but I'd actually like to see this one turned into just `Test-DbaRecoveryModule` and have a parameter passed into test a given recovery module (e.g. `Test-DbaRecoveryModule -SqlInstance MyServer -RecoveryModel Simple`)

I mean I don't enforce Full recovery module in all environments with most clients, which means this command in the current state is one-sided.

@joshcorr if you are up for that task we can close this PR and rework the command to test any recovery module provided?

**Comment by wsmelton** [comment]
Also if you will, take a look at `Test-DbaVirtualLogFile` as this is one that has been adjusted to the standards we'd like to see...particularly the output object and properties.

**Comment by wsmelton** [comment]
I guess I missed that this one was already merged. So disregard.

**Pull request merged**
