### PR TITLE
Development

### PR DESCRIPTION
**Pull request by sqlworldwide**
## Type of Change

 - [x] Bug fix (non-breaking change, fixes #<enter issue number>)
 - [ ] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
While install/update sp_whoisactive was iterating through every database and checking for all stored procedure to determine if sp_whoisactive exist.  Interacting through every database will fail for offline or Always On Availability Group secondary replica where secondary is set to `read-intent only`.

Example of error I got while deploying:

> WARNING: [Install-DbaWhoIsActive][09:47:15] Failed to install stored procedure. | The following exception occurred while trying to enumerate the coll
> ection: "The target database ('databaseinAG') is in an availability group and is currently accessible for connections when the application intent is set to r
> ead only. For more information about application intent, see SQL Server Books Online.".

### Approach
It will only check for database passed through -database parameter or the database chosen via GUI.

### Learning
@ck helped setting up git on my desktop and walked me through the whole process. Also helped my with the code.

### CODE REVIEW

**Comment by potatoqualitee** [comment]
Ohh how exciting! Will merge tomorrow morning once it’s confirmed working. If anyone can approve this PR, I’d appreciate it

**Comment by sqlworldwide** [comment]
Thank you @ConstantineK , @potatoqualitee and @wsmelton .

**Comment by potatoqualitee** [comment]
Excellent! I do believe you are our 100th contributor!! :party:

**Comment by potatoqualitee** [comment]
Thanks for the approvals everyone! Will merge this today once I’m at my desk in a few hours

**Pull request merged**
