### PR TITLE
Add new login support for Azure SQL Dbs

### LINKED ISSUE #5100: New-DbaLogin does not work on Azure SQL "Keyword or statement option 'hashed' is not supported"
## Steps to Reproduce

```powershell
$connection = @{SqlInstance = $SqlInstance
                SqlCredential = $SqlCredential}
$Password = ConvertTo-SecureString -String $pass -AsPlainText -Force  
New-DbaLogin -Login $UserName -SecurePassword $Password @connection
```

## Expected Behavior

Create a new `SqlLogin`.

## Actual Behavior

```
VERBOSE: [19:04:58][New-DbaLogin] Adding as login type SqlLogin
VERBOSE: [19:04:58][New-DbaLogin] Failed to create SQLRO on sql1.database.windows.net using SMO, trying T-SQL.
WARNING: [19:04:58][New-DbaLogin] Failed to add SQLRO to sql1.database.windows.net. | Keyword or statement option 'hashed' is not supported in this version of SQL Server.
```

## Environmental data

 - PowerShell:  5.1.14393.2791   
 - SQL Server: Microsoft SQL Azure (RTM) - 12.0.2000.8   Dec 19 2018 08:43:17

### PR DESCRIPTION
**Pull request by cdhunt**
## Type of Change

 - [x] Bug fix (non-breaking change, fixes #5100
 - [ ] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [x] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
 

Add Azure SQL Db support.

### Approach

An extra conditional branched based on `$server.DatabaseEngineType`.

### Commands to test

`New-DbaLogin -Login $UserName -SecurePassword $Password`

### CODE REVIEW

**Comment by potatoqualitee** [comment]
awwww yeahh! thank you, fabulous addition. will merge when tests pass 💯

**Comment by potatoqualitee** [comment]
Tests pass! Gonna merge, do a few other PRs and publish to gallery. Thanks so much!

**Comment by wsmelton** [comment]
@potatoqualitee This needs to include a validation that if a login name is passed with `@` to throw a warning that it does not support creating Azure Logins for Azure AD accounts. It will be a bit misleading if we say the command supports creating "Azure SQL Logins", it will be strictly SQL Logins.

**Comment by cdhunt** [comment]
@wsmelton Can you provide some more context? I don't use Azure Logins. If you want to open a new issue, I can try and put in the extra validation.

**Comment by wsmelton** [comment]
You cannot create an Azure SQL Login for an Azure AD account using `"CREATE LOGIN [$loginName] FROM WINDOWS" + $withParams ` it will fail.

If we want to support both there has to be a same check for the type of database engine and then using the T-SQL `"CREATE LOGIN [$loginName] FROM EXTERNAL PROVIDER" `, that is all you can do for Azure AD accounts....there are no additional parameters and such. Logins in Azure SQL do not grant access to the databases, you have to explicitly create those after you create the login because there is no `sysadmin` role and such.

**Comment by cdhunt** [comment]
@wsmelton Would you suggest creating another condition at [New-DbaLogin.ps1#L273](https://github.com/sqlcollaborative/dbatools/blob/development/functions/New-DbaLogin.ps1#L273) to add a `AzureADLogin` for `$loginType`?

**Pull request merged**
