### PR TITLE
Update Documentation -detailed (#2217)

### PR DESCRIPTION
**Pull request by joshcorr**
## Type of Change

 - [x] Bug fix (non-breaking change, fixes #2217 )
 - [ ] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] Nunit test is included
 - [x] Documentation
 - [ ] Build system
 

### Purpose
 
- To Update the Documentation in Cmdlets that no longer use -Detailed Parameter (Specifically in Test-DbaDatabaseCollation, Test-DbaDiskAllocation, and Test-DbaMaxDop)
- To Update Examples using the old Syntax

### Approach

- Replace the Description with language provided by Shawn Melton
- Include Test-DbaDeprecation if it was not included already

### Commands to test

Test-DbaDatabaseCollation -SqlInstance sqlserver2014a -Database db1, db2
Test-DbaDatabaseCollation -SqlInstance sqlserver2014a -Database db1, db2 -Detailed (Should Return Warning)
Test-DbaDiskAllocation -ComputerName sqlserver2014 | Select-Output *
Test-DbaDiskAllocation -ComputerName sqlserver2014 -Detailed (Should Return Warning)
Test-DbaMaxDop -SqlInstance sqlserver2016 | Select-Object *
Test-DbaMaxDop -SqlInstance sqlserver2016 -Detailed (Should Return Warning)

### CODE REVIEW

**Comment by potatoqualitee** [comment]
TEARIN IT UP!! 🔥 🔥🔥 🚒

**Comment by joshcorr** [comment]
LOL just trying to earn my stripes...

**Comment by potatoqualitee** [comment]
Thanks much! Just one thing, I changed the word from depreciated to deprecated. Merged 💃

**Comment by joshcorr** [comment]
Wish I could say that was the first time I mixed those up... :unamused: Thanks for the fix.

**Pull request merged**
