### PR TITLE
Update dbatools on Remote Computers without Internet

### PR DESCRIPTION
**Pull request by gbargsley**
## Type of Change

 - [ ] Bug fix (non-breaking change, fixes #<enter issue number>)
 - [X] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
 
This function allows you to copy dbatools version(s) from a source computer to one or multiple remote computers that do not have access to the internet to download from the gallery.
### Approach

Allows non internet connected servers to get new versions of dbatools.
### Screenshots

image

### CODE REVIEW

**Comment by gbargsley** [comment]
I might need some guidance on best practices and dbatools standards.  I haven't done a new function in a while and things have changed a little.

**Comment by niphlod** [comment]
Do we reallllly need a glorified Copy-Item, in a function that will just work on windows envs, and just where  SMB Admin shares are enabled ? This sounds more like a snippet than a function...

**Comment by potatoqualitee** [comment]
Still unsure about this one and will have to think on it

**Comment by Zhunya** [comment]
I got local github (tfs or anything else) server setup. Download dbatools push it to local git, then just pull on local servers.

**Comment by wsmelton** [comment]
First point would be @gbargsley myself or Chrissy handle updating that PSD1 file, simply due to conflicts hitting that file from in PRs is a bit more pain than most files to fix.

The current state of the command in this PR is making very large assumptions on setup and access. Overall, unless they are Local Administrator on any server they will not be able to access the admin share (if it is even enabled). I would say this is out of scope for the module itself being that it pertains to module management, which should not be something dbatools takes care of as well.

I think an expansion on the current install blog post would be sufficient and include this as a snippet example. (Or it can be created as a wiki article on this repository if desired.)

**Comment by gbargsley** [comment]
This can be cancelled. I was asked how I update my off internet servers.

**Comment by potatoqualitee** [comment]
yeah i think this would better as a blog post, would you be willing to blog about it at dbatools.io/blog, garry?

**Pull request closed without merging**
