### PR TITLE
Force $server.Databases for AzureSql - fixes #5621

### LINKED ISSUE #5621: Workaround for Azure Database Issue
$server.Databases['name'] is empty or doesnt work but Get-DbaDatabase is awesome. Explore forcing add-member if its azuresqldb and just overwriting that whole .Databases since it's useless

### PR DESCRIPTION
**Pull request by potatoqualitee**
Helps avoid enumeration issues. Still unsure about this. Gotta wonder why Get-DbaDatabase works.

### CODE REVIEW

**Comment by potatoqualitee** [comment]
changed up the code a bit, this should be better

**Comment by wsmelton** [comment]
Are you going to duplicate these changes down to `Connect-SqlInstance` as well?

**Comment by potatoqualitee** [comment]
no need, connect-sqlinstance is just a wrapper now 👍

**Comment by potatoqualitee** [comment]
that one fail i believe is becaue of the encrypted password, we'll see

**Pull request merged**
