### PR TITLE
Appintentfix - fixes #2070 

### LINKED ISSUE #2070: Connect-DbaSqlServer with -ApplicationIntent parameter
## Bug Report
Connect-DbaSqlServer throws error when used with -ApplicationIntent parameter:

image

### General Troubleshooting steps

- [x] Verified running latest release of dbatools?
- [x] Verified errors are not related to permissions?
- [x] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - Operating System (Name|Version): Win7
 - PowerShell Version: 5
 - SQL Server (Edition|Version): SQL2016

## Steps to Reproduce
```
Connect-DbaSqlServer -SqlInstance $instance -ApplicationIntent readwrite

The property 'ApplicationIntent' cannot be found on this object. Verify that the property exists and can be set.
At line:225 char:39
+ ... onIntent) { $server.ConnectionContext.ApplicationIntent = $Applicatio ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyAssignmentException
```
 - [x] Attach any screenshots (if possible/allowed)
 - [ ] Attach logs generated by dbatools (`Get-DbatoolsLog`) - no entries in the log related to Connect-DbaSqlServer
 - [x] Attach output from PowerShell console (if possible/allowed)

## Feature Request
Thinking about some AG-related scenarios where queries should be run on a secondary instances.

### Problem to solve
Don't have one yet.
Seems that at some point the connection object type has been changed and this new object does not support this parameter anymore.

### PR DESCRIPTION
**Pull request by potatoqualitee**

### CODE REVIEW

**Comment by potatoqualitee** [comment]
daaamn, this PR blows. @nvarscar can you take a look and see if this solves your issues? /cc @galador @wsmelton 

Shawn, check out what I did - I saw issues with the GUID I;m trying to get around but when I mod Connect-sqlInstance with the same approach everything just dies. Maybe I should Copy/Dispose

**Comment by potatoqualitee** [comment]
@FriedrichWeinmann - any idea why my Connect-SqlInstance approach isn't working? I"m finding issues with setting GUID first then changing the name. See line 124 of this.

[Connect-SqlInstance.ps1.txt](https://github.com/sqlcollaborative/dbatools/files/1216597/Connect-SqlInstance.ps1.txt)

Here are the errors I get - can replicate locally - https://ci.appveyor.com/project/potatoqualitee/dbatools/build/0.9.1099

I tried cloning an object too and it' just bein a B.

**Comment by wsmelton** [comment]
What issue on Connect-SqlInstance are you trying to solve?

**Comment by potatoqualitee** [comment]
The GUID is problematic - not only as output but it exists in so many places in the object. I'm trying to get the real name in there again.

**Comment by potatoqualitee** [comment]
will merge then submit PR with internal updates

**Comment by nvarscar** [comment]
@potatoqualitee thanks for the fix, it doesn't return any errors now!
Now I only need to build AG that would support readonly routing to test it..

**Pull request merged**
