### PR TITLE
Fix for Get-FilteredRestoreFile - switch TLog backups to use full's LastLsn

### LINKED ISSUE #2374: Get-FilteredRestoreFile - TLog selection starts too early
Hi,

I found that the list of filtered TLogs produced by Get-FilteredRestoreFile (via Restore-DBADatabase) was including 1 TLog that was too early for our SQL instance to restore.

In the example below (I redacted first portion of LSN for clarity) the filter was including Tlog backups 3, 4 and 5, however SQL can only restore starting with Tlog backup 4.

I fixed this locally by changing filter to specify TLog backup Last LSN must be greater than Full Backup **Last LSN**. Currently the script specifies TLog backup Last LSN must be greater than Full Backup **First LSN**.

  | First LSN | Last LSN
-- | -- | --
Full Backup | 65,600,001 | 74,400,001
  |   |  
Tlog Backup 1 | 46,400,001 | 52,800,001
Tlog Backup 2 | 52,800,001 | 59,200,001
Tlog Backup 3 | 59,200,001 | 65,600,001
Tlog Backup 4 | 65,600,001 | 81,600,001
Tlog Backup 5 | 81,600,001 | 88,000,001

### PR DESCRIPTION
**Pull request by nvarscar**
## Type of Change

 - [x] Bug fix (non-breaking change, fixes #2374 )
 - [ ] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [x] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [x] Pester test is included
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
Fixing tlog backup chain to use full's lastlsn instead of firstlsn, as log backups between first and last lsns are not required in the backup chain

### Approach
voodoo magic; 
pointing TLogStartLsn towards LastLsn instead of FirstLsn; 
bonus: fixing sorting for fulls and diffs to use Lsn's instead of date - more reliable;

### Commands to test
new pester test for this particular scenario included

### CODE REVIEW

**Comment by Zhunya** [comment]
Need more testing, have lot of `WARNING: Test-DbaLsnChain - Break in LSN Chain between` with and w/o `-RestoreTime`, when TLOG not skipped for restore process.
Restore with FULL with or w/o DIFF finished w/o errors.

**Comment by nvarscar** [comment]
Hey @Zhunya , thanks for testing! Will you be able to provide LSNs that you're testing? It's working fine for me

**Comment by Zhunya** [comment]
As far as my test running I see one point when we get LSN chain broken - we have `DIFF` backups in directory and `-RestoreTime`.

DIFF|RestoreTime|Error?
----|-----------|------
no|no|no
yes|no|no
no|yes|no
yes|yes|yes

JSON for testing purposes will be later if needed.
(_comment will be updated when more tests finish_)

**Comment by potatoqualitee** [comment]
thanks to you both!

**Pull request merged**
