### PR TITLE
Get-DbaMemoryCondition: convert to bigint when calculating the NotificationTime

### LINKED ISSUE #7238: Get-DbaMemoryCondition - WARNING: [16:39:27][Get-DbaMemoryCondition] Issue collecting data | Arithmetic overflow error converting expression to data type int.
#### Host used

- [X] powershell.exe
- [ ] ISE
- [ ] VS Code
- [ ] Other (please specify)

#### Errors Received

```
WARNING: [16:39:27][Get-DbaMemoryCondition] Issue collecting data | Arithmetic overflow error converting expression to data type int.

```

### Environmental information

🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
Please provide the output of the below script

```PowerShell Version        : 5.1.17134.858
dbatools latest installed : 1.0.141
Culture of OS             : en-ZA
```

#### SQL Server:

```sql 
Microsoft SQL Server 2016 (SP2-CU15-GDR) (KB4583461) - 13.0.5865.1 (X64)   Oct 31 2020 02:43:57   Copyright (c) Microsoft Corporation  Enterprise Edition (64-bit) on Windows Server 2016 Datacenter 10.0 <X64> (Build 14393: ) (Hypervisor) 
```

```sql
us_english
```

### PR DESCRIPTION
**Pull request by lancasteradam**
Get-DbaMemoryCondition: convert to bigint when calculating the NotificationTime

## Type of Change

 - [x] Bug fix (non-breaking change, fixes #7238 )
 - [ ] New feature (non-breaking change, adds functionality, fixes # )
 - [ ] Breaking change (effects multiple commands or functionality, fixes # )
 - [x] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
 
Minor change to ensure the calculation of NotificationTime does not result in an arithmetic error as reported in #7238.

### Commands to test

See the integration test.

### CODE REVIEW

**Review by jpomfret — APPROVED** [review]
Looks good to me - thanks @lancasteradam 
(Just waiting on tests to pass for another PR so I can merge it in, then I'll update this branch, kick off tests and merge).

**Comment by jpomfret** [comment]
test failure unrelated

**Comment by SicilianNajdorf** [comment]
How do I get the fix for this?

**Comment by lancasteradam** [comment]
@SicilianNajdorf, typically a new release of dbatools will be created after multiple pull requests have been merged. The new released version will be visible in the PowerShell Gallery under the Version History: https://www.powershellgallery.com/packages/dbatools

More details are here: https://dbatools.io/download/

**Comment by SicilianNajdorf** [comment]
Thanks
How do I get the new release?

**Pull request merged**
