### PR TITLE
Initial commit of Get-DbaLocaleSetting

### PR DESCRIPTION
**Pull request by PowerDBAKlaas**
Gets the locale settings on one or more computers.

How to test this code: 
- [ ] 
- [ ] 

Has been tested on minimum requirements:
- [ ]  Powershell 3
- [ ]  Windows 7
- [ ]  SQL Server 2000

Has been tested on maximum requirements:
- [ ]  SQL Server vNext
- [ ]  Windows 10
- [ ]  Azure Database

Tests for tester:
- [ ] Working/useful help content, including link to command on dbatools web site
- [ ] All examples work as advertised
- [ ] Does not contain template content
- [ ] Does not contain excessive/unnecessary amounts of comments
- [ ] Works remotely
- [ ] Works locally
- [ ] Works on lower versions or throws error specifying version not supported
- [ ] Works with named instances
- [ ] Works with clustered instances
- [ ] Handles offline/read only databases
- [ ] Supports multiple servers (at the command line or piped from Get-SqlRegisteredServerName)
- [ ] No un-handled errors which stop the command working with multiple servers

### CODE REVIEW

**Comment by PowerDBAKlaas** [comment]
Probably needs a Selecct-Defaultview to make something user friendly.
Any suggestions?
@ctrlbold @wsmelton @niphlod @ClaudioESSilva @Stuart-Moore @ConstantineK

**Comment by ctrlbold** [comment]
@PowerDBAKlaas  playing now

**Comment by ctrlbold** [comment]
Very useful stuff! 

But yes, it needs some column name love. You can either create an object or use a lot of "as"es in the Select-DefaultView (that adds aliases and hides the original, unsure which you want).

Would you want it to have no "s" or "i" unless there are overlapping things then you can do BlahString or BlahNumeric ?

**Comment by PowerDBAKlaas** [comment]
Well there are methods to set the values via CIM too, so it may be useful to have the real object at some point. For that reason I would choose Select-Defaultview with indeed a lot of " as ".

But I'd like to have an idea on which columns the team considers the most useful.
BTW I just discovered I've got one computer that has an aberrant firstweekoftheyear, so I'd put that definitely in 😄

**Comment by ctrlbold** [comment]
I like them all, honestly 👍

**Comment by PowerDBAKlaas** [comment]
There may be inconsistent output:
I take all values in the subkey, so there's a risk older OS or so may have a different collection.

**Comment by ctrlbold** [comment]
i have some win2003's, win2000 and xps if you wanna try.

**Comment by ctrlbold** [comment]
Where are we at with this, @PowerDBAKlaas ?

**Comment by PowerDBAKlaas** [comment]
@ctrlbold  It works.
Maybe we can include it and prettify later?

**Comment by ctrlbold** [comment]
k!

**Comment by ctrlbold** [comment]
later on, what you can do is an array of pretty column names, and then an array of replacement column names. and if it matches, then it turns pretty, if it doesnt, then it goes thru with the ugz i and s

**Comment by PowerDBAKlaas** [comment]
OK,
only ...
with the what?

**Pull request merged**
