### PR TITLE
New Function - Get-DbaSqlDump

### PR DESCRIPTION
**Pull request by gbargsley**
## Type of Change

 - [ ] Bug fix (non-breaking change, fixes #<enter issue number>)
 - [X] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [X] Pester test is included
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
 
Find a memory dump on one or multiple SQL instances.

### Screenshots

image

### CODE REVIEW

**Comment by potatoqualitee** [comment]
this looks fabulous! thank you for the test too <3

Can you remove the warning - we can just return null. Also, can you please change the name of size_in_bytes to Size then do `[dbasize]($result.size_in_bytes)` - that makes it pretty

**Comment by potatoqualitee** [comment]
in addition, we're starting to move away from -Detailed. Can you remove that Param and just return all of the detailed by default? 🙇

**Comment by gbargsley** [comment]
@potatoqualitee 
I added the size conversion.

You want me to take the warning out about no memory dumps found?

Also, if you want me to remove detailed param, then I will just show the output only and not worry about a count?

**Comment by potatoqualitee** [comment]
Correct! We've got some folks excited about this command, so I'll merge and patch. Thanks so much! We'll be adding this to a new project we're working on as well 💃

**Pull request merged**
