### PR TITLE
Fix Find-DbaDatabase -Detailed (#2217)

### PR DESCRIPTION
**Pull request by joshcorr**
## Type of Change

 - [ x] Bug fix (non-breaking change, fixes #<enter issue number>)
 - [ ] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ x] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ x] Pester test is included
 - [ ] Nunit test is included
 - [ x] Documentation
 - [ ] Build system
 

### Purpose
 

- To Replace the Parameter -Detailed with Select-DefaultView in Find-DbaDatabase
- To Update any Examples or Documentation to Reflect the Changes
- To Include a Unit and Intigration Test for the Cmdlet since it does not exist.

### Approach

- Removed the Functionality of -Detailed, but kept a warning via Test-DbaDeprecation
- Added a Parameter for $EnableException as Test-DbaDeprecation seemed to require it
- Created a pester test to validate the parameters and basic functionality by looking up the Master DB 

### Commands to test

Find-DbaDatabase -SqlInstance TestDB -Pattern Master | Select-Object *

### CODE REVIEW

**Comment by potatoqualitee** [comment]
test failure is not from yours! thanks so much for this 💯 will merge asap.

**Comment by joshcorr** [comment]
Thanks, I was just looking into that.

**Comment by wsmelton** [comment]
The issue with that test that failed has been identified and will be fixed shortly.

**Comment by potatoqualitee** [comment]
Bon bon! Merci 🌮

**Pull request merged**
