### PR TITLE
Fixing Striped restores

### LINKED ISSUE #2871: Restore-DbaDatabase reads only 1 file with striped backup sets
Restore-DbaDatabase reads only 1 file when I pass multiple backups files in the pipe.

You can reproduce the issue with : 

`Backup-DbaDatabase -SqlInstance server\instance -Database test -FileCount 4 -BackupDirectory \\myshare`
`$files = Get-ChildItem \\myshare`
`$files | Restore-DbaDatabase -SqlInstance server\instance`

The output of the command : 
[output 1.txt](https://github.com/sqlcollaborative/dbatools/files/1562209/output.1.txt)

The output of $error[0] | select * : 
[output 2.txt](https://github.com/sqlcollaborative/dbatools/files/1562213/output.2.txt)

### PR DESCRIPTION
**Pull request by Stuart-Moore**
## Type of Change

 - [x] Bug fix (non-breaking change, fixes #2871)
 - [ ] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [x] Pester test is included
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
Get the restoring of striped backups working again.

### Approach
Group based on backupset and 'arrayise' the filepaths

### Learning
Write tests to save yourself forgetting things

### CODE REVIEW

**Comment by potatoqualitee** [comment]
Sorry, @Stuart-Moore! One test failed on test lsn chain

**Comment by Stuart-Moore** [comment]
Yep saw that. Will fix it later when I'm back on computer.

**Comment by potatoqualitee** [comment]
once you've got the restore-dbatabase tests done, ill fix for merge

**Comment by potatoqualitee** [comment]
nm fixed it!

**Comment by Stuart-Moore** [comment]
Yay, all green except for someone else's failing test!

Apologies for the issues with the lab repo. I've got another db that'll need to go up for Claudio's request for Filestream stuff, I'll shove it in a seperate folder to save causing issues.

**Comment by potatoqualitee** [comment]
one passes, thank you!

**Pull request merged**
