### PR TITLE
#5688 file size calc wrong

### LINKED ISSUE #5688: [Bug] Restore-DbaDatabase backup size calc
### Environmental information
```
#### PowerShell version:

Name                           Value                                                                                                                                                                                                                                
----                           -----                                                                                                                                                                                                                                
PSVersion                      5.1.14409.1018                                                                                                                                                                                                                                                                                                                                                                                                                                                  

#### dbatools Module version:
Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.834\dbatools.psd1
Version : 0.9.834

#### SQL Server: 
Microsoft SQL Server 2016 (SP2-CU6)

#### Errors Received
NO ERRORS

#### Steps to Reproduce
Restore a database consisting of multiple files.

#### Expected Behavior
expect BackupSize to be the backup full size.

#### Actual Behavior
multiplying backup full size by backup file count, think it should divide it.

### PR DESCRIPTION
**Pull request by garethnewman**
- [X ] Bug fix (non-breaking change, fixes #5688

Divided the sum of backup size by the file count to get the actual backup size.

### CODE REVIEW

**Comment by potatoqualitee** [comment]
awww yeahhh, thanks a ton! can you paste a screenshot of it working properly, @garethnewman ?

**Comment by garethnewman** [comment]
image

**Comment by garethnewman** [comment]
The BackupSizeMB and CompressedBackupSizeMB are not normally shown, I was just testing. I removed them from the output after testing.

**Comment by potatoqualitee** [comment]
yeah, ive noticed different rounding, not a problem at all, close enough & totally common. fantastic fix, thank you 🙇 !

**Comment by garethnewman** [comment]
awesome :+1:

**Pull request merged**
