### PR TITLE
initial commit of Test-DbaMaxDop

### PR DESCRIPTION
**Pull request by ClaudioESSilva**
Ready for QA! :metal:

### CODE REVIEW

**Comment by ClaudioESSilva** [comment]
Set of tests for this PR
SQL Server 2000
- [ ] Don't run on version 2000 and throw an message

SQL Server 2005 - 2014
- [ ] Run on instance with max dop configured as recommended - See if the message on 'Notes' column is according with the scenario
- [ ] Run on instance with max dop lower than the recommended - See if the message on 'Notes' column is according with the scenario
- [ ] Run on instance with max dop higher than the recommended - See if the message on 'Notes' column is according with the scenario
- [ ] Run on instance with max dop equals 1 - See if the message on 'Notes' column is according with the scenario
- [ ] Run on instance with max dop equals 0 - See if the message on 'Notes' column is according with the scenario

SQL Server 2016
- [ ] Run on instance where all databases have MaxDop scoped configuration equal 0 - See if the message on 'Notes' column is according with the scenario
- [ ] Run on instance where at least one database have MaxDop scoped configuration equal 1 - See if the message on 'Notes' column is according with the scenario
- [ ] Run on instance where at least one database have MaxDop scoped configuration higher than 1 - See if the message on 'Notes' column is according with the scenario

For now I think it is that :smile:

**Comment by ctrlbold** [comment]
@ClaudioESSilva can you resubmit this PR without the .psd1? @Splaxi are you available to test this command this week?

**Comment by ctrlbold** [comment]
QA checklist:

- [ ] Working/useful help content, including link to command on dbatools web site
- [ ] All examples work as advertised
- [ ] Does not contain template content
- [ ] Does not contain excessive/unnecessary amounts of comments
- [ ] Works remotely
- [ ] Works locally
- [ ] Works on lower versions or throws error specifying version not supported
- [ ] Works with named instances
- [ ] Works with clustered instances
- [ ] Handles offline/read only databases
- [ ] Supports multiple servers (at the command line or piped from Get-SqlRegisteredServerName)
- [ ] No un-handled errors which stop the command working with multiple servers

**Comment by ClaudioESSilva** [comment]
Will remove. But I only can tonight.

**Comment by ClaudioESSilva** [comment]
@ctrlbold psd1 removed :smile:

**Pull request merged**
