### PR TITLE
Created tests for Test-DbaIdentityUsage

### PR DESCRIPTION
**Pull request by jpomfret**
## Type of Change

 - [ ] Bug fix (non-breaking change, fixes #<enter issue number>)
 - [X] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [X] Pester test is included

### Purpose
 
Created pester tests for Test-DbaIdentityUsage

### Approach

Creates table in tempdb, inserts certain number of rows and tests that the 'NumofUses' and 'PercentUsage' of the identity column returns as expected.

### Commands to test

`Invoke-Pester .\tests\Test-DbaIdentityUsage.Tests.ps1`

### Screenshots

image

### CODE REVIEW

**Comment by jpomfret** [comment]
For the second set of tests I used a table with Identity(0,5) and inserted 25 rows, the NumberOfUses for identity shows 24, I have set the test to check for 24 in this instance (for now at least) but I'm wondering if that is the expected result. Personally I think I would expect 25 uses for 25 inserts?

**Comment by wsmelton** [comment]
I think if your identity was set to `(1,5)` then it would have been 25, but since you started with 0 it is 24.

**Comment by jpomfret** [comment]
Confirmed - if my identity is (1,5) it shows 25, but even if the first id is 0 it's still been used right? So 25 rows should be 25 uses no matter what the id starts at? I also just tested an int identity with (-1,5) and that has 25 uses.

**Comment by potatoqualitee** [comment]
I believe this is the off by one issue @ConstantineK was talkin about eh, the SQL query needs to be fixed I believe. Unsure if the new PR addresses it.

**Comment by jpomfret** [comment]
Also I think the AppVeyor tests failed because the Math fix isn't merged in yet.

**Comment by potatoqualitee** [comment]
K, I'll merge this then merge that then if it doesn't work, please submit a PR to fix 😄

**Comment by wsmelton** [comment]
The test didn't fail because the code was not merged. The test in Appveyor is done against the code in the PR itself.

Why the test failed:

```Describe : Test-DbaIdentityUsage.Tests Integration Tests
Context  : Verify Test Identity Usage on TinyInt
Name     : It TinyInt identity column with 128 rows inserted should be 50.20% full
Result   : Failed
Message  : Expected: {50.2}
           But was:  {50.39}
Describe : Test-DbaIdentityUsage.Tests Integration Tests
Context  : Verify Test Identity Usage on TinyInt
Name     : It TinyInt with 255 rows should be 100% full
Result   : Failed
Message  : Expected: {100}
           But was:  {100.39}
Describe : Test-DbaIdentityUsage.Tests Integration Tests
Context  : Verify Test Identity Usage with increment of 5
Name     : It TinyInt identity column with 25 rows using increment of 5 should be 47.06% full
Result   : Failed
Message  : Expected: {47.06}
           But was:  {9.41}
```

**Comment by wsmelton** [comment]
@potatoqualitee would have been best to just merge the math fix PR, then do a minor change to this PR to make the test run again...just saying. If it is indeed broke then other PRs are going to start failing because of it. This way it prevents that from happening and the test itself can be corrected in this PR and only this PR will be showing the failed test for that command.

**Comment by jpomfret** [comment]
For this one I inserted 255 rows into a tiny int, that should be 100% full but is showing 100.39

Message  : Expected: {100}
But was:  {100.39}

**Comment by jpomfret** [comment]
I created this PR as a quick fix, changed the numbers to 100.39 so other things wouldn't break, then appveyor failed again so I changed them back... so I'm not actually sure it needs merged now 😕 
https://github.com/sqlcollaborative/dbatools/pull/2110

**Pull request merged**
