### PR TITLE
internal, trailing spaces, folding, scriptanalyzer

### PR DESCRIPTION
**Pull request by niphlod**
## Type of Change

 - [x] Bug fix (non-breaking change, fixes #<enter issue number>)
 - [ ] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 
### Purpose
keeping internals up with 1.0 standards

### CODE REVIEW

**Comment by potatoqualitee** [comment]
hey niph, can you look into these failures?

**Comment by niphlod** [comment]
yup

**Comment by niphlod** [comment]
did it, fingers crossed

**Comment by potatoqualitee** [comment]
yessssssssssssss

**Pull request merged**
