### PR TITLE
New-DbaDatabase - Ensure Autogrowth is set in all cases (#6780)

### LINKED ISSUE #6780: [Bug] New-DbaDatabase - Autogrowth set to NONE
### Environmental information

```powershell
PowerShell Version        : 5.1.19041.1
dbatools latest installed : 1.0.115
Culture of OS             : ru-RU
```

#### SQL Server:

```sql
Microsoft SQL Server 2017 (RTM-CU21) (KB4557397) - 14.0.3335.7 (X64)
        Jun 12 2020 20:39:00
        Copyright (C) 2017 Microsoft Corporation
        Developer Edition (64-bit) on Windows Server 2012 R2 Standard 6.3 <X64> (Build 9600: ) (Hypervisor)
```

```sql
us_english
```

### Report

The new database is created with Autogrowth set to `NONE`

`Model` database configuration:
```powershell
> Get-DbaDbFile -SqlInstance <SQLInstance> -Database model | FT -Property Database,TypeDescription,MaxSize,Growth,GrowthType

Database TypeDescription MaxSize   Growth GrowthType
-------- --------------- -------   ------ ----------
model    ROWS            Unlimited  65536 kb
model    LOG             Unlimited  65536 kb
```
#### Host used

- [x] powershell.exe
- [x] pwsh.exe

#### Steps to Reproduce

```powershell
New-DbaDatabase -SqlInstance <SQLInstance> -Name test_NewDbaDatabase_debug -Recoverymodel Simple -Owner <owner> -DataFilePath F:\MSSQL\DATA -LogFilePath L:\MSSQL\DATA

ComputerName       : <SQLInstance>
InstanceName       : MSSQLSERVER
SqlInstance        : <SQLInstance>
Name               : test_NewDbaDatabase_debug
Status             : Normal
IsAccessible       : True
RecoveryModel      : Simple
LogReuseWaitStatus : Nothing
SizeMB             : 16
Compatibility      : Version140
Collation          : Cyrillic_General_CI_AS
Owner              : <owner>
LastFullBackup     : 01.01.0001 0:00:00
LastDiffBackup     : 01.01.0001 0:00:00
LastLogBackup      : 01.01.0001 0:00:00

```

#### Expected Behavior

Autogrowth properties set the same as the `model` database.

#### Actual Behavior

Autogrowth set to `0`

```powershell
> Get-DbaDbFile -SqlInstance <SQLInstance> -Database test_NewDbaDatabase_debug | FT -Property Database,TypeDescription,MaxSize,Growth,GrowthType

Database                  TypeDescription MaxSize   Growth GrowthType
--------                  --------------- -------   ------ ----------
test_NewDbaDatabase_debug ROWS            Unlimited      0 kb
test_NewDbaDatabase_debug LOG             2,00 TB        0 kb
```

### PR DESCRIPTION
**Pull request by lancasteradam**
- Updated to set the autogrowth based on the model db when the caller has not specified the growth parameters
- Consolidated the parameter validation for the 'advanced config' workflow
- Fixed bug with "-SecondaryFileCount 1" resulting in two secondary files because of the do-while comparison operator
- Added a parameter for LogMaxSize
- Added validation for the db collation
- Updated the SecondaryFileSize and SecondaryFileMaxSize to be modified based on the model db similar to how it is done for the PrimaryFileSize and PrimaryFileMaxSize
- Added logic to create one secondary data file if the user has passed in "-DefaultFileGroup Secondary"
- Updated the unit test that checks the command params to use the modern approach
- Added more integration tests to increase test coverage
- Updated the examples to show what the resulting filenames would be
- Updated the documentation to describe the format of the db filenames

## Type of Change

 - [x] Bug fix (non-breaking change, fixes #6780  )
 - [x] New feature (non-breaking change, adds functionality, fixes # )
 - [ ] Breaking change (effects multiple commands or functionality, fixes # )
 - [x] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [x] Adding code coverage to existing functionality
 - [x] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Nunit test is included
 - [x] Documentation
 - [ ] Build system
 

### Purpose
 
This PR resolves the issue with the AutoGrowth settings for new databases. Other minor issues encountered along the way were also addressed, see the notes above.

### Commands to test

The examples in the command description and the integration tests can be used.

### CODE REVIEW

**Comment by potatoqualitee** [comment]
awesome! we'll review it and merge momentarily. first look, looks good thank you @lancasteradam

**Comment by potatoqualitee** [comment]
I didn't realize my ESX machine with SQL Server 2000 was offline 😩  I gotta get it booted up then I can test this, unless you have access to a 2000 machine.

**Comment by lancasteradam** [comment]
Sorry, I don't have access to a SQL 2000 instance.

**Comment by potatoqualitee** [comment]
Got it tested by a colleague and it works! Thanks again 🤩

**Pull request merged**
