### PR TITLE
Added password hashing C# code

### PR DESCRIPTION
**Pull request by zippy1981**
Changes proposed in this pull request:
 - C# code to create passworh hash objects

How to test this code: 
- [ ] `New-Object Sqlcollaborative.Dbatools.Utility.DbaPasswordHash hashes from sql server`
- [ ] `[Sqlcollaborative.Dbatools.Utility.DbaPasswordHash]::GenerateHash()`

Has been tested on minimum requirements:
- [ ]  Powershell 3
- [ ]  Windows 7
- [ ]  SQL Server 2000

Has been tested on maximum requirements:
- [ ]  SQL Server vNext
- [ ]  Windows 10
- [ ]  Azure Database

Tests for tester:
- [ ] Working/useful help content, including link to command on dbatools web site
- [ ] All examples work as advertised
- [ ] Does not contain template content
- [ ] Does not contain excessive/unnecessary amounts of comments
- [ ] Works remotely
- [ ] Works locally
- [ ] Works on lower versions or throws error specifying version not supported
- [ ] Works with named instances
- [ ] Works with clustered instances
- [ ] Handles offline/read only databases
- [ ] Supports multiple servers (at the command line or piped from Get-SqlRegisteredServerName)
- [ ] No un-handled errors which stop the command working with multiple servers

### CODE REVIEW

**Comment by potatoqualitee** [comment]
hey @zippy1981 - take a look at the resulting error in Appveyor. Seems the library cannot load.

**Comment by zippy1981** [comment]
Rather than guess why I broke things (although I'm pretty sure I know why) I'll write another pull request so the the output of msbuild (the thing that compiles the DLL) to a build artifact first.

My Guess BTW is I'm using C# 6.0 anguage syntax specificall `$"String with a {Variable}"`instead of `string.Format("String with a {0}", Variable);` which probably isn't supported by our lowest common denominator of the msbuild that comes with .NET framework 4.5.2.

**Comment by potatoqualitee** [comment]
Thanks for taking a look - just wanted to make sure it was prepped for when Fred reviews.

Thanks for all the magic you're doing!

**Comment by FriedrichWeinmann** [comment]
Looking good as far as I can see. Once the library builds again I'll be happy to approve.

**Comment by potatoqualitee** [comment]
Sup yall? Has the library been built?

**Comment by zippy1981** [comment]
I have not touched this since I opend the PR. Kids, job search, Fourth of July, wife traveling etc. Its on my radar though.

**Comment by zippy1981** [comment]
I need a decision as to how to proceed on #1672 before fixing this.

**Comment by potatoqualitee** [comment]
ruh roh, got conflicts too

**Comment by potatoqualitee** [comment]
hey zips, can you please resubmit this PR once you've got it worked out? 

Merci 🙇

**Comment by zippy1981** [comment]
I'm going to say, lets just merge all this wonderfully thouht out unit tested C# code now, and I'll write the powershell cmdlets to actually use it later.  I just remerged in development branch and I'll make sure pester succeeds.

**Comment by zippy1981** [comment]
Nevermind I remember why this was unnecessarily difficult. I'll close this for now again.

**Pull request closed without merging**
