### PR TITLE
Get-DbaLogin update

### LINKED ISSUE #4671: Get-DbaLogin needs loving
plural parameter names and windows login / sql login should be -Type

### PR DESCRIPTION
**Pull request by ijeb**
## Type of Change

 - [x] Bug fix (non-breaking change, fixes #4671)
 - [ ] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
Fix parameters. Some cleanup.

### Commands to test
See examples and test script.

### CODE REVIEW

**Comment by potatoqualitee** [comment]
awesome thank you! I'll merge on pass and then add in some aliases along with Test-DbaDeprecation to make it backwards compat.

**Comment by ijeb** [comment]
I am not sure why these tests fail only on 2008R2 part 2/2

Describe : Get-DbaLogin Unit Tests
Context  : Validate parameters
Name     : It Should only contain 12 parameters
Result   : Failed
Message  : Expected 12, but got 13.

Describe : Test-DbaLoginPassword Unit Tests
Context  :  Name Input
Name     : It Should have Alias of ServerInstance and SqlServer for Parameter SQLInstance
Result   : Failed
Message  : Expected @('ServerInstance', 'SqlServer'), but got $null.

**Comment by potatoqualitee** [comment]
looks like the numbers were swapped. the default param count will only ever be 11 (no SupportsShouldProcess) or 13 (SupportsShouldProcess inc whatif and confirm). I'll fix 👍

**Comment by potatoqualitee** [comment]
the other test was failing because it was loking at get-dbalogin, i removed both and filed an issue cuz it's redundant

**Pull request merged**
