### PR TITLE
Improve Import-DbaRegServer

### LINKED ISSUE #5706: [Bug] - Import-DbaRegServer doesn't properly import subgroups
repro :(

```powershell
"Name, ServerName, Group, Description
SP Cluster1, sql20171, Test\Prod, For SharePoint
ConfigMgr1, sql20161, Test\Dev, John's test" | Set-Content -Path C:\temp\cms.csv

Import-Csv C:\temp\cms.csv | Import-DbaRegServer -SqlInstance sql2008
```

image

### PR DESCRIPTION
**Pull request by ClaudioESSilva**
## Type of Change

 - [x] Bug fix (non-breaking change, fixes #5706)
 - [ ] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
 
Being able to create all tree path to add a server.
Please see the #5706 

### Approach

Split path by '\' and create the non-existing folders.

### Screenshots

image

### CODE REVIEW

**Comment by ClaudioESSilva** [comment]
@potatoqualitee can you please take a look? 😞 
image

**Comment by potatoqualitee** [comment]
doesn't look too bad. maybe that empty strings should be handled? 

image

tested with

```
$object = [pscustomobject]@{
                ServerName = 'dbatoolsci-randobject'
            }
            $results = $object | Import-DbaRegServer -SqlInstance $script:instance2
            $results.ServerName | Should -Be 'dbatoolsci-randobject'
            $results.Name | Should -Be 'dbatoolsci-randobject'
```

**Comment by ClaudioESSilva** [comment]
Thank you @potatoqualitee ! Always good to have a good night of sleep 😃

**Comment by potatoqualitee** [comment]
finalllly!

**Comment by potatoqualitee** [comment]
thank you so much 🙇  im happy to have someone take a better look at the groups parsing 💃

**Pull request merged**
