### PR TITLE
Wait statistics

### LINKED ISSUE #3965: Add Commands to collect latch stats, spinlock_stats, virtual_file_stats  and waiting_tasks.
---
Currently dbatools includes a command Get-DbaWaitStatistic based on Paul Randal's post "Wait statistics, or please tell me where it hurts".
This collects data from sys.dm_os_wait_stats

Similar performance information is available for:

sys.dm_os_latch_stats
sys.dm_os_spinlock_stats
sys.dm_io_virtual_file_stats 

For completeness and consistency these should also be available
---

### Summary of new feature

Capture output from:
sys.dm_io_virtual_file_stats
sys.dm_os_latch_stats
sys.dm_os_spinlock_stats

### Proposed technical details (if applicable)

https://www.sqlskills.com/blogs/paul/advanced-performance-troubleshooting-waits-latches-spinlocks/
https://www.sqlskills.com/blogs/paul/how-to-examine-io-subsystem-latencies-from-within-sql-server/

### Latest version of dbatools as of writing

0.9.399

### PR DESCRIPTION
**Pull request by sqllensman**
## Type of Change

 - [X] Bug fix (non-breaking change, fixes #3965)
 - [X] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [X] Adding code coverage to existing functionality
 - [X] Pester test is included
 - [ ] Nunit test is included
 - [X] Documentation
 - [ ] Build system
 

### Purpose
Add coverage to collect other Performance related statistics available in DMVs
Currently dbatools has commands that collect Wait Related information based on posts from Paul Randal of SQLSkills. The posts also refer to other Performance information that was not covered by dbatools.

Also modifies Clear-DbaWaitStatistics and Get-DbaWaitStatistic to 
(a) Fix potential Division by Zero issue in Get-DbaWaitStatistic 
(b) Standardise documentation

### Approach
Uses T-SQL queries to collect information from 
sys.dm_os_ring_buffers 
sys.dm_os_latch_stats
sys.dm_os_spinlock_stats
sys.dm_io_virtual_file_stats

### Commands to test
Clear-DbaLatchStatistics
Clear-DbaWaitStatistics
Get-DbaCpuRingBuffer
Get-DbaIoLatency
Get-DbaLatchStatistic 
Get-DbaSpinLockStatistic
Get-DbaWaitStatistic

### Learning
Based on 
https://www.sqlskills.com/blogs/glenn/sql-server-diagnostic-information-queries-detailed-day-16/
https://www.sqlskills.com/blogs/paul/how-to-examine-io-subsystem-latencies-from-within-sql-server/ 
https://www.sqlskills.com/blogs/paul/capturing-io-latencies-period-time/
https://www.sqlskills.com/blogs/paul/advanced-performance-troubleshooting-waits-latches-spinlocks/ 
https://www.sqlskills.com/blogs/paul/most-common-latch-classes-and-what-they-mean/

### CODE REVIEW

**Comment by sqllensman** [comment]
Have noticed some potential issue in Pester test for Get-DbaLatchStatistic

On systems with little activity or where the Latch Statistics have been cleared there can be no data to return.

This can cause Pester test to fail even when result is expected

**Comment by potatoqualitee** [comment]
this is awesome!! thank you so very much. unsure what to do about the inconsistently failing tests. Perhaps a mock?

**Comment by sqllensman** [comment]
Both failing tests are "expected" for a Server that has just been restarted and has no history.

The Get-DbaCpuRingBuffer requires Server to be running for at least 1 minute while Get-DbaLatchStatistic will also return zero results for freshly started Servers

Not sure how these can be fixed and still actually run the code.

**Comment by potatoqualitee** [comment]
oh yeah! i always forget about that. i need to move all of my tests that say if $env:appveyor if i havent already

**Comment by potatoqualitee** [comment]
I'll do that now, patrick, then merge 💃

**Comment by potatoqualitee** [comment]
in master and the PS gallery! 💃

**Pull request merged**
