### PR TITLE
 Write-DbaDbTableData.ps1: Moving Connection to Server code to the beginning of the Command code

### LINKED ISSUE #7107: [Bug] Write-DbaDbTableData - Fully Qualified Tablename includes database name for Azure SQL Databases
#### Host used

- [ ] powershell.exe
- [x] ISE
- [x] VS Code
- [ ] Other (please specify)

#### Errors Received

```
WARNING: [08:21:58][Write-DbaDbTableData] databasetest does not exist.

PSMessageDetails      : 
Exception             : System.Management.Automation.RuntimeException: Cannot index into a null array.
                           at CallSite.Target(Closure , CallSite , Object , Int32 )
                           at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
TargetObject          : 
CategoryInfo          : InvalidOperation: (:) [], RuntimeException
FullyQualifiedErrorId : NullArray
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Write-DbaDbTableData<End>, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.137\allcommands.ps1: line 78796
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}
```

#### Steps to Reproduce

$SqlInstance is a name like 'azuresqlserver', without the domain part 'database.windows.net'. Our DNS translates it into an Azure vnet IP used by a private end point configured for that Azure SQL Server. 
```
"test" | Write-DbaDbTableData -SqlInstance $SqlInstance   -Database $databaseName -Table table01 -AutoCreateTable  -SqlCredential  $credential -verbose
```
Output: 
```
VERBOSE: [08:21:57][Write-DbaDbTableData] FQTN processed: [databasetest].[dbo].[table01]
WARNING: [08:21:58][Write-DbaDbTableData] databasetest does not exist.
You cannot call a method on a null-valued expression.
```
With the same variables:
```
$AzureSQL= Connect-DbaInstance -SqlInstance $SqlInstance -Database $databasename  -SqlCredential $credential  -TrustServerCertificate -verbose
$AzureSQL.ServerType
$AzureSQL.Databases[$databaseName].name
```
Output: 
```
SqlAzureDatabase
databasetest
```

#### Expected Behavior

I expect to get the following message:

```
VERBOSE: [08:21:57][Write-DbaDbTableData] FQTN processed: [dbo].[table01]
```
Because ServerType is 'SqlAzureDatabase', as per line 394  of Write-DbaDbTableData code, database name should not be included in the Fully Qualified Tablename for Azure Databases

#### Actual Behavior

```
VERBOSE: [08:21:57][Write-DbaDbTableData] FQTN processed: [databasetest].[dbo].[table01]
```

### Environmental information

🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
Please provide the output of the below script

```
PowerShell Version        : 5.1.18362.1171
dbatools latest installed : 1.0.137
Culture of OS             : nl-NL
```

#### SQL Server:

```sql
Azure SQL Database
```

```sql
/* REPLACE WITH output of @@LANGUAGE */
```

### PR DESCRIPTION
**Pull request by miguelmolgar**
## Type of Change

 - [X] Bug fix (non-breaking change, fixes #7107 )
 - [ ] New feature (non-breaking change, adds functionality, fixes # )
 - [ ] Breaking change (effects multiple commands or functionality, fixes # )
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
 
I saw that in command Write-DbaDbTableData $server variable was called (line 394) before being initialised in line 430. So I moved the block of code where the connection is set to the beginning, as the first step of the command.

### Approach

Moving part of the code will make that the connection of the server is made before checking if it is an Azure SQL server or not.

### Commands to test

Write-DbaDbTableData with an Azure SQL Server using a private enpoint.

### CODE REVIEW

**Comment by wsmelton** [comment]
What error of being received when used against Azure to require the change?

**Comment by miguelmolgar** [comment]
Hi @wsmelton, I continue here the discussion of pull request #7105. I had to close that one because I pointed to master instead of development branch.

As I see in the current version of the code line 394 is outside any of the two internal functions (Invoke-BulkCopy and New-Table). And for me line 394 and 430 are in the same workflow, so it seems that it may try to get info form $server before the connection is stablished. 

I created the PR because I was seeing there a clear issue with the order of the lines more than because of the issues I'm having with Azure, but maybe I'm not understanding the code properly. If it is not so clear as I see it I'll create then an issue explaining the error I get with an Azure SQL Databases and Private Link.

**Comment by wsmelton** [comment]
Creating an issue would be good. I'm not sure we have had anyone use use the private link feature though not sure that should matter.

I've used the command against Azure SQL with no issues.

**Comment by wsmelton** [comment]
Looking at the history of that command it seems this code was put there intentionally to address an issue with Azure SQL connections #6338

**Comment by wsmelton** [comment]
@sqllensman can you verify if this change will cause a regression on the issue you fixed in PR #6338?

I tested the code as-is in the development branch and it works with my test.

**Comment by miguelmolgar** [comment]
I created the related bug: #7107

**Comment by potatoqualitee** [comment]
Thank you so much for the PR @miguelmolgar. Sorry this is taking a while, the lockdown is crushing right now 😭  @wsmelton did you test with Azure SQL? Should we say IfAzure then there else here?

**Review by wsmelton — APPROVED** [review]
There was already a proper check for Azure in the command. I don't have the setup to test the networking changes with private links right now but I tested this PR compared to what is released and everything is still working.

**Comment by potatoqualitee** [comment]
awsome, thanks shawn!

**Comment by miguelmolgar** [comment]
Thank you @potatoqualitee and @wsmelton!

**Pull request merged**
