### PR TITLE
Get-FilteredRestoreFile - 1.0.0 Compliance update

### PR DESCRIPTION
**Pull request by FriedrichWeinmann**

### CODE REVIEW

**Comment by potatoqualitee** [comment]
mmm this one has a test (I believe one that fails). But its unit tests, i can add fucntional tests.

**Comment by potatoqualitee** [comment]
OOPS
how do i unopen, and merge brb

**Comment by Stuart-Moore** [comment]
Please don't get rid of the unit tests. They can't be replicated as
functional ones as we can't get the original backups.

**Comment by potatoqualitee** [comment]
Oh, I wasn't! I am going to add functional on top.

**Pull request merged**
