### PR TITLE
Get-DbaSqlBuildReference - added SMO pipe support

### PR DESCRIPTION
**Pull request by ctrlbold**

### CODE REVIEW

**Comment by niphlod** [comment]
it conflicts partially with what was originally discussed with klaas, but it works.  BTW: current development seems to have a small issue now, but that's not a fault for this commit 

```Unable to find type [sqlcollective.dbatools.dbaSystem.MessageLevel]```

**Comment by FriedrichWeinmann** [comment]
Hi @niphlod ,

can't reproduce the issue and the tests seem fine. Can you reproduce the issue?

Cheers,
Fred

**Comment by niphlod** [comment]
will do in approximately 2 hours. Stay tuned.

**Comment by niphlod** [comment]
The problem originated from reimporting the new development in the powershell process
in a fresh one, no issues. Sorry for the wrong report.

**Comment by ctrlbold** [comment]
How's that @niphlod ?

**Comment by niphlod** [comment]
Perfect. 

Styleguide police is coming .... one target less ^_^

**Pull request merged**
