### PR TITLE
New Command: Find-DbaInstance

### PR DESCRIPTION
**Pull request by FriedrichWeinmann**
## Type of Change

 - [ ] Bug fix (non-breaking change, fixes #<enter issue number>)
 - [x] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 
### New Functionality
Introducing a scanning function, that will search and list instances.
- Supports multiple discovery types (SPNs from AD, IP Range, explicit target list, ...)
- Supports multiple scan types, building confidence in the result

### Known Issues
Currently, all operations are synchronous. This has a significant impact on overall execution time. Nonavailable computers might add 60 seconds to overall execution each :(
Got a plan, going to work on it as time permits, to introduce truly awe-inspiring parallelism.

### Special Thanks
Special thanks go to Scott Sutherland from NetSPI (@nullbind) for coming up with the overall concept and a large portion of the code that allowed me to wrap this up into a working proposition for dbatools.

### CODE REVIEW

**Comment by potatoqualitee** [comment]
Can't wait to play!

**Comment by FriedrichWeinmann** [comment]
Then don't ^^

**Comment by potatoqualitee** [comment]
Soon! 💃 And for sure by 9pm tonight.

**Comment by potatoqualitee** [comment]
Thank you, this is glorious!

1. Can you add a timestamp column that shows when it was found?
2. If something is on port `1433` can we give that medium confidence? In addition, if it is on port 1433 , can/should we assume it's MSSQLSERVER for the instance name?
3. Can `FullSmoName` be `SqlInstance` instead and placed in the order that we usually do?


```powershell
ComputerName       : WORKSTATIONX
InstanceName       : SQL2008R2SP2
SqlInstance        : WORKSTATIONX\SQL2008R2SP2
```

**Comment by potatoqualitee** [comment]
Thanks so much!! 🏆 

after i add a few examples, I'll merge!

**Comment by potatoqualitee** [comment]
🏆 💯 👍 🏆 💯 👍 🏆 💯 👍 🏆 💯 👍 🏆 💯 👍

**Pull request merged**
