### PR TITLE
Attempting to fix the filename replace issues - restoreobject branch

### LINKED ISSUE #5036: Restore-DbaDatabase changes paths in the backup history object
### Before submitting a bug report:

- [x] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [x] Verified this bug is not already reported in an issue
- [x] Verified errors are not related to permissions
- [x] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)
- [x] If issue is with `Copy-DbaDatabase`, using `Backup-DbaDatabase | Restore-DbaDatabase` still does not work

## Steps to Reproduce

```powershell
$historyObject = Get-DbaBackupHistory -SqlInstance lab-sds-ag1:7221 -Database Ag1Database1
$historyObject[0].FileList

FileType LogicalName      PhysicalName
-------- -----------      ------------
D        AG1Database1     C:\Data\MSSQL13.LIFE\AG1Database1.mdf
L        AG1Database1_log C:\Data\MSSQL13.LIFE\AG1Database1_log.ldf
D        AG1Database1_2   C:\Data\MSSQL13.LIFE\AG1Database1_2.ndf


$null = $historyObject | Restore-DbaDatabase -SqlInstance lab-sds-ag1:7221 -DatabaseName Ag1Database1_copy -TrustDbBackupHistory -ReplaceDbNameInFile -WithReplace -OutputScriptOnly
$historyObject[0].FileList

FileType LogicalName      PhysicalName
-------- -----------      ------------
D        AG1Database1     C:\Data\MSSQL13.LIFE\Ag1Database1_copy.mdf
L        AG1Database1_log C:\Data\MSSQL13.LIFE\Ag1Database1_copy_log.ldf
D        AG1Database1_2   C:\Data\MSSQL13.LIFE\Ag1Database1_copy_2.ndf


$null = $historyObject | Restore-DbaDatabase -SqlInstance lab-sds-ag1:7221 -DatabaseName Ag1Database1_copy -TrustDbBackupHistory -ReplaceDbNameInFile -WithReplace -OutputScriptOnly
$historyObject[0].FileList

FileType LogicalName      PhysicalName
-------- -----------      ------------
D        AG1Database1     C:\Data\MSSQL13.LIFE\Ag1Database1_copy_copy.mdf
L        AG1Database1_log C:\Data\MSSQL13.LIFE\Ag1Database1_copy_copy_log.ldf
D        AG1Database1_2   C:\Data\MSSQL13.LIFE\Ag1Database1_copy_copy_2.ndf

```

## Expected Behavior

$historyObject remaining unchanged

## Actual Behavior

Physical name gets replaced with the new database name every time the restore runs creating enormous filenames after a few runs:
Ag1Database1_copy_copy_copy_copy_copy_copy_copy_log.ldf

## Environmental data

 - PowerShell:
Name                           Value
----                           -----
PSVersion                      5.1.15063.1478
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.1478
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

 - - SQL Server: 2016SP2

### PR DESCRIPTION
**Pull request by nvarscar**
## Type of Change

 - [ ] Bug fix (non-breaking change, fixes #5036 )
 - [ ] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
A variation of #5049 that works as expected. For @Stuart-Moore 's review and assessment.

### Approach
Using a new property to store the file name data instead of relying on the native one.

### Commands to test
see original issue

### Screenshots
image

### CODE REVIEW

**Comment by nvarscar** [comment]
The tests are fine now - though failing on some appveyor-related issues.

**Comment by potatoqualitee** [comment]
Hello kind sirs. @Stuart-Moore is there any way we can get some movement on this? I'd like to work on some changes that'll move code around a lot. (gonna try to support multiple instances again) and would like a solid code base to merge. Thank you 🙇‍♀️🙇‍♂️

**Comment by wsmelton** [comment]
I would prefer to see the history object support this rather than trying to keep up with a PSCustomObject...especially if you want to move to supporting multiple instances.

**Comment by wsmelton** [comment]
This PR will also have a conflict if previous PR Stuart has open is merged first....we should all be working on this branch to resolve this instead of creating new PRs.

So changes should all be updated to [dbatools/restoreobject](https://github.com/sqlcollaborative/dbatools/tree/restoreobject) branch to prevent having conflicts.

**Comment by wsmelton** [comment]
As a side note @nvarscar you can do draft PRs in GitHub and it will prevent the ability for a PR to be merged. It is feature around WIP PRs that many repo maintainers have been asking GitHub to implement (they finally released it this past week).
image

**Comment by nvarscar** [comment]
@wsmelton it shouldn't, as this PR has all the commits from that branch. 
And yeah, I believe, DPR feature was released the day after I opened this PR (or maybe that was when I learned about it?), otherwise I'd definitely opened it as a Draft.
Let me know if you want me to close this PR or re-create it as a draft. I simply wanted to share an idea with @Stuart-Moore and PR looked as a decent way of doing it.

**Comment by wsmelton** [comment]
If it is an underlying fix for his PR I would just do a commit against that branch. That gives him easier access to it for testing and such.

**Comment by nvarscar** [comment]
Duh. Retargeted the PR to that branch, but now it contains all the recent dev changes and won't show proper difference. I guess, I'll merge development into restoreobject.

**Comment by nvarscar** [comment]
Hey @Stuart-Moore, I'm not sure I follow. Which public interface did you mean and which scripts it's going to break? Are you saying that previous behavior (where the restore function changed the history object) was a feature, not a bug?

**Comment by Stuart-Moore** [comment]
The path through the 5 restore cmdlets (Get, Select, Format, Test, Invoke) is documented and people could be running them separately (I do, and I’ve handed out solutions to do the same via slack) so they’ll have scripts that break if things change without warning




On 19 February 2019 at 15:36:22, Kirill Kravtsov (notifications@github.com) wrote:

Hey @Stuart-Moore, I'm not sure I follow. Which public interface did you mean and which scripts it's going to break? Are you saying that previous behavior (where the restore function changed the history object) was a feature, not a bug?

**Comment by potatoqualitee** [comment]
can we duplicate and hide the things that will change and break, @Stuart-Moore ? That way, they won't break?

**Comment by wsmelton** [comment]
Closing this off as it is stale now....next PR can be created as draft if needed.

**Pull request closed without merging**
