### PR TITLE
Backup restore progress

### PR DESCRIPTION
**Pull request by mb2o**
## Type of Change

 - [ ] Bug fix (non-breaking change, fixes # )
 - [*] New feature (non-breaking change, adds functionality, fixes # )
 - [ ] Breaking change (effects multiple commands or functionality, fixes # )
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
Returns all active BACKUP and RESTORE operations on the provided instance(s) 

### Approach
Get the results through a query on the sys.dm_exec_requests DMV

### Commands to test
- Get-DbaBackupRestoreProgress -SqlInstance sql2017
- Get-DbaBackupRestoreProgress -SqlInstance sql2017 -SqlCredential sqladmin
- Get-DbaBackupRestoreProgress -SqlInstance sql2017,sql2019 | where {$_.Command -like 'RESTORE*'} | ft -AutoSize

### CODE REVIEW

**Comment by niphlod** [comment]
looks slightly as Get-DbaEstimatedCompletionTime, what is missing from there ?

**Comment by potatoqualitee** [comment]
Thank you, @mb2o ! I will create tests and merge once/if @niphlod approves 👍🏼

**Comment by mb2o** [comment]
@niphlod Absolutely nothing! It is just that I never noticed `Get-DbaEstimatedCompletionTime` before. Sorry for the inconvenience.

**Comment by niphlod** [comment]
no probls @mb2o . if you wanna reuse it and/or augment it to match some kind of missing feature, please do!

**Pull request closed without merging**
