### PR TITLE
Adding some more pester tests for Restores to catch a couple of commo…

### PR DESCRIPTION
**Pull request by Stuart-Moore**
…n fails

Ongoing work, but need a PR to trigger appveyor runs.

Fixes # 

Changes proposed in this pull request:
 - 
 - 
 - 

How to test this code: 
- [ ] 
- [ ] 

Has been tested on minimum requirements:
- [ ]  Powershell 3
- [ ]  Windows 7
- [ ]  SQL Server 2000

Has been tested on maximum requirements:
- [ ]  SQL Server vNext
- [ ]  Windows 10
- [ ]  Azure Database

Tests for tester:
- [ ] Working/useful help content, including link to command on dbatools web site
- [ ] All examples work as advertised
- [ ] Does not contain template content
- [ ] Does not contain excessive/unnecessary amounts of comments
- [ ] Works remotely
- [ ] Works locally
- [ ] Works on lower versions or throws error specifying version not supported
- [ ] Works with named instances
- [ ] Works with clustered instances
- [ ] Handles offline/read only databases
- [ ] Supports multiple servers (at the command line or piped from Get-SqlRegisteredServerName)
- [ ] No un-handled errors which stop the command working with multiple servers

### CODE REVIEW

**Comment by potatoqualitee** [comment]
hey stuart - i notice some of my tests sometimes fail - perhaps because the instance runs out of memory? Feel free to comment them out until we get it figured out.

**Comment by Stuart-Moore** [comment]
Don't think it's that in this case. I'm finding a few faults that noone's picked up on before, and it's taking a bit of unpicking. 

Think I need to setup my dev environment to be a bit more like appveyor. Saves pushing stuff every time to test things.

**Comment by Stuart-Moore** [comment]
Going to push some of my test dbs into the other repo. they're simple time series ones so will be good for testing the continue and point in time functionality.

**Comment by potatoqualitee** [comment]
yeah thats what i ended up doing - installed a local instance with the same name of sql2008r2 express then developer sql2016

**Comment by Stuart-Moore** [comment]
will also save having quite such a long queue for PR tests....... ;)

**Pull request merged**
