### PR TITLE
Adding KeepReplication switch to Restore-DbaDatabase

### LINKED ISSUE #6039: Restore-DbaDatabase Add Keep_Replication parameter
### Summary of new feature

It would be great to have WITH KEEP_REPLICATION as a parameter for Restore-DbaDatabase. I am doing multiple restores from PROD backups to a TEST environment where keeping the replication configuration would be useful. 

### Proposed technical details (if applicable)

This would be similar to how MS SQL server powershell module [Restore-SqlDatabase](https://docs.microsoft.com/en-us/powershell/module/sqlserver/restore-sqldatabase?view=sqlserver-ps) would work. The parameter is called -KeepReplication. 

### Latest version of dbatools as of writing

dbatools 0.9.809

### PR DESCRIPTION
**Pull request by nvarscar**
## Type of Change

 - [x] Bug fix (non-breaking change, fixes #6039)
 - [x] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
Adding an ability to use WITH KEEP_REPLICATION clause in the restores

### Approach
Modify properties of the restore object

### Commands to test
Restore-DbaDatabase

### CODE REVIEW

**Comment by nvarscar** [comment]
The CI failure is unrelated to the change.

**Comment by potatoqualitee** [comment]
hell yessss thank you 😻

**Comment by wsmelton** [comment]
Should add this param to copy command as well.

**Comment by wsmelton** [comment]
Also wouldn't WithReplication be bit more in line on naming? Being that we have WithReplace maybe we also look at having a string parameter to accept inputs instead of a parameter for each option

**Comment by potatoqualitee** [comment]
agreed on the copy command, but unsure about the name - it'd be WithKeepReplication, per T-SQL

WITH KEEP_REPLICATION

In retrospect, kinda wish we'da done a `-With KeepReplication, Replace`

**Pull request merged**
