### PR TITLE
Restore LSN fix

### LINKED ISSUE #2674: Restore-DbaDatabase: -IgnoreLogBackup is not ignoring log backups and broken LSN chain
## Bug Report
- `IgnoreLogBackup` is not working, and we get broken LSN chain (see screenshot *1)
- If `IgnoreLogBackup` not used, database restored w/o error
- If `OutpuScriptsOnly` with `IgnoreLogBackup` restore finished normally in SSMS

### General Troubleshooting steps

- [X] Verified running latest release of dbatools - 0.9.100
- [X] Verified errors are not related to permissions?
- [X] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - Operating System (Name|Version): Windows 10
 - PowerShell Version: 5.1
 - SQL Server (Edition|Version): Restore database from SQL Server 2008R2 to SQL Server 2016 SP1

## Steps to Reproduce
*1
default

### PR DESCRIPTION
**Pull request by Stuart-Moore**
## Type of Change

 - [x] Bug fix (non-breaking change, partially fixes #2674 )
 - [ ] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [x] Pester test is included
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Approach
@zhunya was finding that he was getting errors with empty tlog backups being part of the restore chain. We now *don't* return the empty tlog records at all.

This passes all usual pester tests. 2 tests needed modifying as we are now returning less tlogs in those cases.

As the empty tlog error only affects a very small number of users, and they all appear to have been happy with the previous fix I don't think this will change outcomes for most of our users.

Oleg, could you give this branch another spin just to confirm it all works and then we're good to go

### CODE REVIEW

**Comment by Zhunya** [comment]
Will do more testing, and with one big database too.

**Comment by Zhunya** [comment]
Restored to server SQL Server 2012 (11.0.6607.3)

Got this little erorr:

default

For this command:
`Restore-DbaDatabase -Path '\\SRV-BACKUP01\SQL_Backup\SRV-SQL-FA$FA\DV' -SqlInstance srv-dv-dev\inst12 -DatabaseName TEST_DV_20171121_1800 -DestinationDataDirectory D:\SQLData -RestoreTime '2017-11-20 18:00:00' -MaintenanceSolutionBackup -DestinationFilePrefix test_20171120_1800_`

Problem with `RestoreTime` = TLOG backup start time

**Comment by Stuart-Moore** [comment]
That's probably a seperate issue, but I can't replicate with a restore exactly on the start/end of the t-log backup:
t-logboundary

Would be interested to see the t-sql output before and after that, as the error indicates a problem with a file create/move

**Comment by Zhunya** [comment]
```SQL
RESTORE LOG [TEST_231_] FROM  DISK = N'\\SRV-BACKUP01\SQL_Backup\SRV-SQL-FA$FA\DV\LOG\SRV-SQL-FA$FA_DV_LOG_20171120_175000.trn' WITH  FILE = 1,  MOVE N'syntellect' TO N'D:\SQLData\test_231_dv_0_syntellect.mdf',  MOVE N'ftCatalogs' TO N'D:\SQLData\test_231_dv_1_ftCatalogs.ndf',  MOVE N'ftrow_dvcatalog_system' TO N'D:\SQLData\test_231_dv_2_ftrow_dvcatalog_system.ndf',  MOVE N'ftrow_dvcatalog_cards' TO N'D:\SQLData\test_231_dv_3_ftrow_dv_catalog_cards.ndf',  MOVE N'syntellect2' TO N'D:\SQLData\test_231_dv_4_syntellect2.ndf',  MOVE N'syntellect_log' TO N'D:\SQLData\test_231_dv_syntellect_log.ldf',  NORECOVERY,  NOUNLOAD,  STATS = 10,  STOPAT = N'11/20/2017 18:00:00'
RESTORE LOG [TEST_231_] FROM  DISK = N'\\SRV-BACKUP01\SQL_Backup\SRV-SQL-FA$FA\DV\LOG\SRV-SQL-FA$FA_DV_LOG_20171120_175500.trn' WITH  FILE = 1,  MOVE N'syntellect' TO N'D:\SQLData\test_231_dv_0_syntellect.mdf',  MOVE N'ftCatalogs' TO N'D:\SQLData\test_231_dv_1_ftCatalogs.ndf',  MOVE N'ftrow_dvcatalog_system' TO N'D:\SQLData\test_231_dv_2_ftrow_dvcatalog_system.ndf',  MOVE N'ftrow_dvcatalog_cards' TO N'D:\SQLData\test_231_dv_3_ftrow_dv_catalog_cards.ndf',  MOVE N'syntellect2' TO N'D:\SQLData\test_231_dv_4_syntellect2.ndf',  MOVE N'syntellect_log' TO N'D:\SQLData\test_231_dv_syntellect_log.ldf',  NORECOVERY,  NOUNLOAD,  STATS = 10,  STOPAT = N'11/20/2017 18:00:00'
RESTORE LOG [TEST_231_] FROM  DISK = N'\\SRV-BACKUP01\SQL_Backup\SRV-SQL-FA$FA\DV\LOG\SRV-SQL-FA$FA_DV_LOG_20171120_180000.trn' WITH  FILE = 1,  MOVE N'syntellect' TO N'D:\SQLData\test_231_test_231_dv_0_syntellect.mdf',  MOVE N'ftCatalogs' TO N'D:\SQLData\test_231_test_231_dv_1_ftCatalogs.ndf',  MOVE N'ftrow_dvcatalog_system' TO N'D:\SQLData\test_231_test_231_dv_2_ftrow_dvcatalog_system.ndf',  MOVE N'ftrow_dvcatalog_cards' TO N'D:\SQLData\test_231_test_231_dv_3_ftrow_dv_catalog_cards.ndf',  MOVE N'syntellect2' TO N'D:\SQLData\test_231_test_231_dv_4_syntellect2.ndf',  MOVE N'syntellect_log' TO N'D:\SQLData\test_231_test_231_dv_syntellect_log.ldf',  NOUNLOAD,  STATS = 10,  STOPAT = N'11/20/2017 18:00:00'
RESTORE LOG [TEST_231_] FROM  DISK = N'\\SRV-BACKUP01\SQL_Backup\SRV-SQL-FA$FA\DV\LOG\SRV-SQL-FA$FA_DV_LOG_20171120_180000.trn' WITH  FILE = 1,  MOVE N'syntellect' TO N'D:\SQLData\test_231_test_231_dv_0_syntellect.mdf',  MOVE N'ftCatalogs' TO N'D:\SQLData\test_231_test_231_dv_1_ftCatalogs.ndf',  MOVE N'ftrow_dvcatalog_system' TO N'D:\SQLData\test_231_test_231_dv_2_ftrow_dvcatalog_system.ndf',  MOVE N'ftrow_dvcatalog_cards' TO N'D:\SQLData\test_231_test_231_dv_3_ftrow_dv_catalog_cards.ndf',  MOVE N'syntellect2' TO N'D:\SQLData\test_231_test_231_dv_4_syntellect2.ndf',  MOVE N'syntellect_log' TO N'D:\SQLData\test_231_test_231_dv_syntellect_log.ldf',  NOUNLOAD,  STATS = 10,  STOPAT = N'11/20/2017 18:00:00'
```

As you can see, last restore log command changed database file names (but why we need `MOVE` for LOGs?), restore command specified twice for lasy LOG

`CreationTime` and `LastWriteTime` for last log file are same.

I can send you full list if you need it.

**Comment by Stuart-Moore** [comment]
Ah, I see. That make's more senses, it wasn't clear about the double restore in the previous comment.

Can't replicate that, but can see how it could happen in edge cases

Have pushed up a fix

**Comment by Stuart-Moore** [comment]
Now includes the Backup verifiction fix as well.

**Comment by Stuart-Moore** [comment]
@Zhunya has confirmed via slack that all issues raised are now working properly.

**Comment by Zhunya** [comment]
Thank you so much Stuart!

**Pull request merged**
