### PR TITLE
Test-DbaOptimizeForAdHoc - added tests

### PR DESCRIPTION
**Pull request by jpomfret**
## Type of Change

 - [ ] Bug fix (non-breaking change, fixes #<enter issue number>)
 - [ ] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [X] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
 
Added tests for Test-DbaOptimizeAdHoc

### Screenshots

image

### CODE REVIEW

**Comment by niphlod** [comment]
hi, every contribution, especially on tests, is welcome .... 
these are better than nothing but when _the evil contributor_ will introduce a bug all that _the evil_ must comply to is to return something. 
The added value of this test is close to zero (granted, now syntax can't be broken and parameter names can't change).
Especially if this comes from adding tests for dbachecks, the most important part is probably that the output doesn't change ^_^

**Comment by jpomfret** [comment]
Suggestions are more than welcome, was struggling to decide how to test this. Should I do a before all set it to optimize for advice and test that it gets the right result?

**Comment by niphlod** [comment]
Since you're dabbling in writing test, I'll explain my POV here in more detail, hopefully is "logic" even if it's not "the logic".... YMMV. 

I always try to describe the output too in unittests, so the casual (or advanced) contributor can be sure its modifications didn't break some "contract" if, e.g., the function is used in a higher-level tool (like dbachecks).
Mind that this doesn't mean that further modifications are not allowed or that function stops evolving: it just means that an _evil_ commit doesn't pass by without raising flags.
When a new feature is requested and/or the output needs to be tailored to the "next level", a failing test is a good alarm bell that, e.g., can initiate a review (or later spur an impact analysis) and (we'll get there sooner) promote an entry in the CHANGELOG.md . 

In this specific case the core of the function is syntactic sugar over SMO's `Configuration.OptimizeAdhocWorkloads.ConfigValue`, so there's no need to test what _hopefully_ MS tests before releasing SMO (i.e. no need to alter the instance, set forcefully the value and verify that is read correctly, also because users may run tests on *their* instances and this is a pretty high impact change).

Checking for the correctness of the `CurrentOptimizeAdHoc` property is then inherently "wasting resources" on something SMO grants by itself, so IMHO here is worth testing at least:
- for the presence of a `CurrentOptimizeAdHoc` property, of the correct type (int) 
- for the presence of a `RecommendedOptimizeAdHoc` property, of the correct type (int)

At the end, it'll assure that higher level tools that _probably_ use/compare those values continue to work in case of an _evil_ commit

**Comment by jpomfret** [comment]
Thanks for the ideas, I didn't think about testing type of parameters, that would make sense here for sure if things like dbachecks were relying on them.

**Comment by potatoqualitee** [comment]
thank you both 👍

**Pull request merged**
