### PR TITLE
Invoke-DbaDatabaseShrink - Skipping update usage

### PR DESCRIPTION
**Pull request by Zhunya**
## Type of Change

 - [ ] Bug fix (non-breaking change, fixes #<enter issue number>)
 - [x] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose

Speed up things

### Approach

This will exclude DBCC UPDATE USAGE on database, sometimes its not needed or just takes too much time to complete.

### Commands to test

Invoke-DbaDatabaseShrink -SqlInstance $server -Database $restoredDatabase.Name -FileType Log -ExcludeIndexStats -ExcludeUpdateUsage -ExcludeIndexStats

### Screenshots
w/o `-ExcludeUpdateUsage` it takes huge amount of time to complete
image

with -ExcludeUpdateUsage and -ExcludeIndexStats its runs blazing fast

image

### CODE REVIEW

**Comment by potatoqualitee** [comment]
Thanks so much, friend! can you change the word Skip to Exclude, please 👍

**Comment by potatoqualitee** [comment]
In addition, do me a favor and remove the impacted columns from the default view if they dont recacluate, because then the output will be wrong. You can do this using Select-DefaultView (so create $defaultcolumns if it doesnt exist)

**Comment by Zhunya** [comment]
Changed `Skip` to `Exclude`.
I don't see anything related to `UPDATE USAGE` in `Select-DefaultView`.
So, we set and ready. I hope.

**Comment by potatoqualitee** [comment]
I believe the Final Calculations use it as DBCC UPDATEUSAGE allows sp_spaceused do do it's thang.

**Comment by Zhunya** [comment]
I test more then, Thank you for advice!

**Comment by Zhunya** [comment]
As in docs for [DBCC UPDATEUSAGE](https://docs.microsoft.com/en-us/sql/t-sql/database-console-commands/dbcc-updateusage-transact-sql), stated that this command need to be used when you have lot of DML statements running, its recoomended to updates usage start weekly.

So in our command, we don't do anything related to adding or deleting data pages, its ok to just always skip DBCC UPDATE USAGE and change that switch to just `-UpdateUsage`, and for index statistics I propose to do same, when we shrink only LOG file.

For "tests" I have done in my slow test environment, statistics on a database size is not affected by usage update.

**Comment by potatoqualitee** [comment]
excellent! thank you very much. will merge now 🏆

**Pull request merged**
