### PR TITLE
Set-DBAAgentOperator Failsafe Operator Handling Correction

### PR DESCRIPTION
**Pull request by howarthcd**
- Modified to set the failsafe notification method on the AlertSystem
  object rather than the FailSafeOperator object
- Modified the list of possible input values for the
  $FailSafeNotificationMethod input parameter to include 'NotifyAll'
- Comment and variable spelling corrections

## Type of Change

 - [x] Bug fix (non-breaking change, fixes # )
 - [ ] New feature (non-breaking change, adds functionality, fixes # )
 - [ ] Breaking change (effects multiple commands or functionality, fixes # )
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1`)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Unit test is included
 - [ ] Documentation
 - [ ] Build system

### Purpose

Correction to the function to allow the FailSafeOperator to be set without error.
### Approach

By setting the NotificationMethod property of the correct SMO object.
### Commands to test

Set-DbaAgentOperator -SqlInstance localhost -Operator DBA -EmailAddress test@mydomain.com -IsFailsafeOperator NotifyAll

### CODE REVIEW

**Comment by andreasjordan** [comment]
Thanks for that fix.
Just for reference: https://docs.microsoft.com/de-de/dotnet/api/microsoft.sqlserver.management.smo.agent.notifymethods

**Comment by andreasjordan** [comment]
Can we add a validate set for `$FailsafeNotificationMethod`? And that should include also "NetSend" and "None" as they are valid as well.

**Comment by potatoqualitee** [comment]
Wow! I had a whole lot of typos, thanks so much for this 🙇🏼  @andreasjordan - I'll merge then submit a PR for the fix 💯

**Comment by howarthcd** [comment]
Thanks for the feedback @andreasjordan and @potatoqualitee for the merge.

I've got another change to the same function that I will shortly submit via PR - this change will include the suggested validate set for the $FailsafeNotificationMethod input values. The change will also allow multiple values of $FailsafeNotificationMethod to be specified where appropriate.

**Comment by potatoqualitee** [comment]
Oh, cool. I'll wait for your PR then, @howarthcd 🥳

**Comment by howarthcd** [comment]
> Oh, cool. I'll wait for your PR then, @howarthcd 🥳

I'm still finding my feet with git @potatoqualitee so please bear with me. 😄

**Comment by potatoqualitee** [comment]
I get that! congrats on your first pull request with us -- thank you for the time and work you put into it 😊

**Pull request merged**
