### PR TITLE
Get-DbaDatabaseState and Set-DbaDatabaseState, complete revamp

### PR DESCRIPTION
**Pull request by niphlod**
## Type of Change
 - [ ] Bug fix (non-breaking change, fixes #<enter issue number>)
 - [ ] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [x] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [x] Pester test is included

### Purpose
Adhere to codestyle, flowcontrol and messaging standards. Added tests

### CODE REVIEW

**Comment by potatoqualitee** [comment]
one test continues to fail :(

**Comment by niphlod** [comment]
investigating... in the meantime, could you please inspect why enumerating $db.useraccess takes that long on appveyor ?

**Comment by potatoqualitee** [comment]
I'm not even sure where to start. Upon researching, I came across a post that mentioned @dbaduck. Ben, would you have any idea why $db.useraccess is reasonably fast on our own machines, but insanely slow (about 2 minutes) on appveyor?

**Comment by wsmelton** [comment]
Which insurance are you hiring in Appveyor? Does it make a difference on either one (faster, slower, same)?

**Comment by potatoqualitee** [comment]
(I'm merging but we can still keep talking about it)

**Comment by dbaduck** [comment]
I am not familiar with Appveyor. This property is a pretty easy property but may have issues when the database is offline, etc. but there should be no reason for it to be really slow when it is not always show. I try to detect things before by using IsAccessible before interrogating those properties.

**Comment by niphlod** [comment]
@wsmelton both are slow. My first guess would be on the loaded SMO making a difference.
@dbaduck: it's always marginally slower with offline dbs but for whatever reason it takes a hell of a time there rather than in my (and it seems in other) test rigs.

**Pull request merged**
