### PR TITLE
enable rows copied extension method on dotnet core

### PR DESCRIPTION
**Pull request by jasonchester**
## Type of Change

 - [ ] Bug fix (non-breaking change, fixes # )
 - [x] New feature (non-breaking change, adds functionality, fixes # )
 - [ ] Breaking change (effects multiple commands or functionality, fixes # )
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose

This change enables rowscopied to be reported from the SqlBulkCopy on powershell core.

 

### Commands to test

on powershell core:
Write-DbaDbTableData
Import-DbaCsv 

### Learning

Change is based on the the answer in https://github.com/PowerShell/PowerShell/issues/11112

### CODE REVIEW

**Comment by jasonchester** [comment]
it looks like there's multiple places that are already adding the 

https://github.com/sqlcollaborative/dbatools/blob/efe1cab84943abc905de40a3fd967ccfb539650c/functions/Copy-DbaDbTableData.ps1#L207-L244

https://github.com/sqlcollaborative/dbatools/blob/efe1cab84943abc905de40a3fd967ccfb539650c/functions/Copy-DbaDbViewData.ps1#L203-L240

also found another method that can be updated, Write-DbaDbTableData

**Comment by potatoqualitee** [comment]
Hey Jason! Thanks for the PR, sorry for the delay in reviewing, things are crazy right now. Will take a look now.

**Comment by potatoqualitee** [comment]
heck yes, awesome add, thank you! what do you propose for the multiple adds of the RowsCopiedCount extension method? admittedly, i'm not good at all with C# and dont know the implications.

**Comment by jasonchester** [comment]
@potatoqualitee thinking about this a bit more, we might as well just skip the c# and compilation all together.


```powershell
function Get-RowsCopiedCount {
    [OutputType([int])]
    param (
        [System.Data.SqlClient.SqlBulkCopy] $bulkCopy
    )
    $BindingFlags= [Reflection.BindingFlags] "NonPublic,GetField,Instance"
    $rowsCopiedField = [System.Data.SqlClient.SqlBulkCopy].GetField("_rowsCopied", $BindingFlags)
    return [int]$rowsCopiedField.GetValue($bulkCopy)
}
```

**Comment by wsmelton** [comment]
Write command is throwing this for one user from slack:

```
WARNING: [11:12:37][Write-DbaDbTableData] Could not load a usable version of SqlBulkCopy. | error CS1702: Assuming assembly reference 'System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'System.Data.SqlClient' matches identity 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.Runtime', you may need to supply runtime policy
```

**Comment by jasonchester** [comment]
The code I used was copied from existing functions in the dbatools module which I assumed was the path of least resistance.

This looks related to the issue here. https://github.com/PowerShell/PowerShell/issues/11112 

As i suggested in https://github.com/sqlcollaborative/dbatools/pull/6435#issuecomment-606614999 , making an internal function to replace the extension method is probably the better path forward anyways.

**Comment by wsmelton** [comment]
That is actually an error that stops the command, not a warning. Our messaging system just displays it as the "warning" text but it is written to the error stream.

**Comment by konstantinmds** [comment]
Sorry, but couldn't find an more appropriate place to ask than here, 

@jasonchester  can you tell me how can i use this function "Get-RowsCopiedCount " independantly ,
because when i try to mimic your test script, i get error that this function does not exist.

**Comment by jasonchester** [comment]
@konstantinmds this PR is out of date. the up to date PR & Changes are on #6456.

The [Get-RowsCopiedCount](https://github.com/sqlcollaborative/dbatools/blob/development/internal/functions/Get-BulkRowsCopiedCount.ps1) function is internal so isn't exposed to be available for callers externally but feel free to copy the code into your own script since it's nice and short.

```ps
function Get-BulkRowsCopiedCount {
    [OutputType([int])]
    param (
        [System.Data.SqlClient.SqlBulkCopy] $BulkCopy
    )
    $BindingFlags = [Reflection.BindingFlags] "NonPublic,GetField,Instance"
    $rowsCopiedField = [System.Data.SqlClient.SqlBulkCopy].GetField("_rowsCopied", $BindingFlags)
    try {
        return [int]$rowsCopiedField.GetValue($BulkCopy)
    } catch {
        return -1;
    }
}
```

**Pull request merged**
