### PR TITLE
Get database restore information

### PR DESCRIPTION
**Pull request by Zhunya**
## Type of Change

 - [x] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
Sometimes its useful to know when and from which file database was restored and when that backup was taken and by whom.

### Commands to test
Get-DbaDatabase -SqlInstance SERVER -ExcludeDatabase master,model,tempdb,msdb | Select-Object -Property SqlInstance,Name,BackupFinishDate,RestoredDate,RestoredBy,RestoredFrom | OGV

### CODE REVIEW

**Comment by Stuart-Moore** [comment]
Does this supercede Get-DbaRestoreHistory?

**Comment by potatoqualitee** [comment]
Not necessarily - this is a db centric point of view - Get-DbaRestoreHistory will show all history even if the db is dropped after (and the person doesnt delete the history)

**Comment by Stuart-Moore** [comment]
That's cool. I'd just gotten used to the other one.

**Comment by Zhunya** [comment]
So my changes is not needed?

**Comment by potatoqualitee** [comment]
Oh! man, I should have looked at this closer, my bad. I thought it was modifying something else. Yes, it is better in Get-DbaRestoreHistory. Thanks for the attention to detail, @Stuart-Moore

**Comment by Zhunya** [comment]
Is adding this restore information to `Get-DbaDatabase` with switch like `IncludeRestoreInfo` will be useful?

**Comment by potatoqualitee** [comment]
Mmm, no I do think that'd be an overlapping when we could point people to the restore history

**Pull request closed without merging**
