### PR TITLE
Sync-DbaLoginPermission - Added output

### LINKED ISSUE #3665: Sync-DbaLoginPermission needs output
-verbose aint cuttin it

### PR DESCRIPTION
**Pull request by andreasjordan**
Refactoring to be able to work on #3665.

Update: Now with output, so fixes #3665.

### CODE REVIEW

**Comment by andreasjordan** [comment]
A lot of changes, so I did them with individual commits to be able to see the steps.

**Comment by andreasjordan** [comment]
image

**Comment by andreasjordan** [comment]
Now with output:
image

But not for the skipped logins (lines 115, 123, 128). Would you like to have output for those as well?

**Comment by andreasjordan** [comment]
The output is based on this code:
https://github.com/sqlcollaborative/dbatools/blob/development/functions/Copy-DbaAgentJob.ps1#L133-L141
https://github.com/sqlcollaborative/dbatools/blob/development/functions/Copy-DbaAgentJob.ps1#L268-L271
https://github.com/sqlcollaborative/dbatools/blob/development/functions/Copy-DbaAgentJob.ps1#L291-L292

**Comment by potatoqualitee** [comment]
> But not for the skipped logins (lines 115, 123, 128). Would you like to have output for those as well?

Mmm nah. Would it be possible to add the explicit type of change made? Like Grant to whatever -- I think in a lot of cases, this info is included in Verbose. I appreciate that there's now any output at all, so if that is too burdensome, just let me know.

**Comment by andreasjordan** [comment]
This would need changes in Update-SqlPermission. Today, Update-SqlPermission does not have any output at all.

**Comment by andreasjordan** [comment]
Is there anything I can do here?

**Comment by potatoqualitee** [comment]
Ah, no, just have been busy. Will merge!

**Pull request merged**
