### PR TITLE
Adding New-DbaDbMailProfile

### PR DESCRIPTION
**Pull request by ilanham**
## Type of Change

 - [ ] Bug fix (non-breaking change, fixes #<enter issue number>)
 - [x] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [x] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system

### CODE REVIEW

**Comment by ilanham** [comment]
Will check over unit test code, 2016 part 1 failing after attempt to fix initial commit of test code

**Comment by potatoqualitee** [comment]
Thanks so much, @ilanham ! I'll take a closer look at the unit tests and see what's up 👍

**Comment by potatoqualitee** [comment]
This is really fantastic work, thanks a million!

I fixed the tests by adding the account manually within the begin block and then I removed tests for properties that do not exist. I have the New-DbaDbMailAccount in another branch. It's almost ready but needed some tests. I'll be using yours as a base 💯 

Will merge once tests pass

**Comment by potatoqualitee** [comment]
awww yeahh, tests pass!

I added a couple extra things for `New-DbaDbMailAccount` then PR'd it. https://github.com/sqlcollaborative/dbatools/pull/5103

Would you have any interest in creating `New-DbaDbMailServer`?

**Comment by ilanham** [comment]
Excellent, glad to be of help! Definitely have interest in new commands, would New-DbaDbMailServer be a mix of new account + profile? Have some ideas on additional commands myself, but some stuff that's missing "New-" where you have "Get-" commands (alerts, operators, Agent jobs)

**Comment by potatoqualitee** [comment]
Awesome news :D thank you

`New-DbaDbMailServer` would wrap an SMO class called `Microsoft.SqlServer.Management.Smo.Mail.MailServer`

It's generally associated with the Account

image

Then looks like this

image

So I imagine it's pretty similar to the command you created. 

We're missing a whole lot of News, Sets and Removes, too. All of those are very welcomed.

**Comment by ilanham** [comment]
Did some digging on the `New-DbaDbMailServer` command. I took a look at MS Docs, and that class (`Microsoft.SqlServer.Management.Smo.Mail.MailServer`) doesn't have a constructor. I suspect it might be an iterable attribute collection for `Microsoft.SqlServer.Management.SMO.Mail.MailAccount`. I'm wondering if that functionality is already supplied by specifying a mail server with `New-DbaDbMailAccount`?

**Comment by gitsno** [comment]
I have been able to configure the server using the MailServers collection after creating an account, like this:
```
$mailAccount = New-DbaDbMailAccount -SqlInstance myServer -Name SQLDBMail -DisplayName "SQL DB Mail" -EmailAddress "test@example.com" -ReplyToAddress "test@example.com"
# Set the server for the account
$mailServer = $mailAccount.MailServers.Item(0)
$mailServer.Rename('smtp.example.com')
$mailServerUsername = Read-Host "Enter the username for the SMTP account"
$mailServerPassword = Read-Host "Enter the password for the SMTP account" -AsSecureString
$mailServer.SetAccount($mailServerUsername, $mailServerPassword)
$mailServer.EnableSsl = 'True'
$mailServer.Port = 587
$mailServer.Alter()
```

**Pull request merged**
