### PR TITLE
New command for removing a linked server

### LINKED ISSUE #6506: Commands for managing Linked Server
We already have a Get command but need the following:

`New-DbaLinkedServer`
`Set-DbaLinkedServer` -- not sure this would even be possible because there is no support for modifying a linked server via T-SQL, e.g. to update the password it has to be dropped and recreated.

ref #6196

### PR DESCRIPTION
**Pull request by lancasteradam**
## Type of Change

 - [ ] Bug fix (non-breaking change, fixes # )
 - [x] New feature (non-breaking change, adds functionality, fixes #6506 )
 - [ ] Breaking change (effects multiple commands or functionality, fixes # )
 - [x] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [x] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Nunit test is included
 - [x] Documentation
 - [ ] Build system
 

### Purpose
 
Basic command for removing a linked server. 

### Commands to test

See the integration tests and the examples.

### CODE REVIEW

**Comment by andreasjordan** [comment]
Have you tried to use Get-DbaLinkedServer and Remove-DbaLinkedServer in one pipeline? I had issues with that in other Remove- commands and had to move the drop to the end block.
So change the second last test to:
```
Get-DbaLinkedServer -SqlInstance $instance2 -LinkedServer "LS2_$random" | Remove-DbaLinkedServer -WarningVariable warn
```
and then test $warn for beeing null or empty.

**Comment by lancasteradam** [comment]
Thank you @andreasjordan. I have incorporated your feedback.

**Review by andreasjordan — APPROVED** [review]

**Comment by potatoqualitee** [comment]
Thank you 🙇🏼 ! These are great. Will add to manifest and release today.

**Comment by garyhampson** [comment]
Hi @lancasteradam - When running this:
` Get-DbaLinkedServer -SqlInstance MYSERVER -LinkedServer LINKEDSERVERNAME | Remove-DbaLinkedServer -Confirm:$false`
I get the following error:
WARNING: [17:00:32][Remove-DbaLinkedServer] Failure on MYSERVER to remove the linked server dwh.icims.net | There are still remote logins or linked logins for the server 'dwh.icims.net'.

**Comment by lancasteradam** [comment]
Hi @garyhampson, 

Yes, the scope for this first round of linked server commands was more on the simple side of things. Feel free to create an enhancement request to add in the option to remove the logins. In the meantime, you could use https://docs.dbatools.io/Get-DbaLinkedServer to obtain the linked server and then iterate through the logins on that object and call drop() before dropping the linked server itself.

Regards,
Adam

**Pull request merged**
