### PR TITLE
Module - Fix Unable to find type ProtectedData

### LINKED ISSUE #6278: [Bug] - Unable to find type [System.Security.Cryptography.ProtectedData].
i have a second system reporting this issue. will fix with 

`Add-Type -AssemblyName System.Security`

per https://stackoverflow.com/questions/48797700/powershell-date-type-unable-to-find

### PR DESCRIPTION
**Pull request by potatoqualitee**
fixes #6278

### CODE REVIEW

**Comment by wsmelton** [comment]
Would it be better to do this just in the command that needs it instead of module wide?

**Comment by potatoqualitee** [comment]
i believe it's a module-wide problem. i can't even load the module on the servers that have this issue.

**Comment by wsmelton** [comment]
Should be coming from this internal function:

https://github.com/sqlcollaborative/dbatools/blob/cd7a897cf042666e3bdbd18b6fdefb77dd4991fd/internal/functions/Get-DecryptedObject.ps1

**Comment by potatoqualitee** [comment]
I ran into the issue when running a block that only included Get-DbaRegisteredServer, Invoke-DbaQuery and Write-DbaDbTableData

**Comment by potatoqualitee** [comment]
that command also executes `Add-Type -AssemblyName System.Security` explicitly so it appears to be something else

**Pull request merged**
