### PR TITLE
Added 11.0.7469 to buildref json

### LINKED ISSUE #3752: Build number 11.0.7469 missing from buildref
### General Troubleshooting steps

- [x] Verified running the latest release of dbatools?
- [x] Verified errors are not related to permissions?
- [x] Can duplicate in new/clean PowerShell session (clean = `powershell -NoProfile`)?

### Version Information
 - Operating System (Name|Version): Windows Server 2012 R2 Standard
 - PowerShell Version: 5.1.14409.1005
 - SQL Server (Edition|Version): Enterprise 2012

## Steps to Reproduce

 - [ ] Attach any screenshots (if possible/allowed)
 - [ ] Attach logs generated by dbatools (`Get-DbatoolsLog`)
 - [x] Attach output from PowerShell console (if possible/allowed)

"WARNING: [Test-DbaSqlBuild][12:02:43] 11.0.7469 is not recognized as a correct version"

## Feature Request

Add KB4091266 / 11.0.7469 to buildref file.

MSKB URLs:
https://support.microsoft.com/en-us/help/4091266/on-demand-hotfix-update-package-for-sql-server-2012-sp4

### Problem to solve
KB4091266 / 11.0.7469 missing from buildref file.

### PR DESCRIPTION
**Pull request by frank687**
## Type of Change

 - [X] Bug fix (non-breaking change, fixes #3752 )
 - [ ] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
Add missing item to build ref

### CODE REVIEW

**Comment by potatoqualitee** [comment]
thank you very much 🌮 !

**Comment by SQLGB** [comment]
I see this new build number entry in the buildref json in dbatools 0.9.369, but running Test-DbaSqlBuild against an instance with that build is still returning "not recognized as a correct version", even after restarting the PowerShell environment.  Any ideas?

**Comment by frank687** [comment]
What is your exact version string?

**Comment by SQLGB** [comment]
Get-DbaSqlBuildReference reports the following:

SqlInstance    : <removed>
Build          : 11.0.7469
NameLevel      : 2012
SPLevel        : {SP4, LATEST}
CULevel        : 
KBLevel        : 4057116
SupportedUntil : 7/12/2022 12:00:00 AM
MatchType      : Approximate

... and t-sql select @@version reports this:

Microsoft SQL Server 2012 (SP4-OD) (KB4091266) - 11.0.7469.6 (X64)   Feb 28 2018 17:47:20   Copyright (c) Microsoft Corporation  Enterprise Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) (Hypervisor)

**Comment by niphlod** [comment]
needed to bump date at the top, too. lemme redo this PR to make it happen

**Comment by niphlod** [comment]
you can now run the same command with -Update that due to https://github.com/sqlcollaborative/sqlcollaborative.github.io/blob/master/assets/dbatools-buildref-index.json being updated, will fetch the latest version of the build reference file. 

/cc @potatoqualitee : remember to keep both repos in sync when you merge here

**Comment by SQLGB** [comment]
Thanks for the -update parameter tip; that worked for 0.9.369, and I suppose one of the next module updates will include the revised json with updated "LastUpdated" date.  Thanks again!

**Comment by niphlod** [comment]
what you see on https://sqlcollaborative.github.io/builds is what -Update sees, if you have an internet connection. We made it this way 'cause doing so we're not tied to module upgrade to be on par with SQL releases.

**Pull request merged**
