### PR TITLE
Start-DbaAgentJob - fixed piping

### PR DESCRIPTION
**Pull request by potatoqualitee**
it broke at some point and test was too weak

### CODE REVIEW

**Comment by potatoqualitee** [comment]
@tonyfountain oh yeah, looks like it. just tested master and it worked 🤔  the test tests for `-ne Idle` which allows `$null` through, so we will have to address that either way. @wsmelton, let's hold off on releasing dev until we get @nvarscar's comments addressed.

i can close this PR - will you have time to address Kirill's PR soon?

**Comment by wsmelton** [comment]
Yeah adding reminding to take care of that when I keep home this evening.

**Comment by potatoqualitee** [comment]
oh wait, this is not an issue with yours @tonyfountain - I think it was introduced in another PR https://github.com/sqlcollaborative/dbatools/pull/6674

**Comment by nvarscar** [comment]
I feel like #6746 has a potential to resolve the piping issues by itself.

**Comment by potatoqualitee** [comment]
it does indeed, already checked! 👏

**Comment by tonyfountain** [comment]
@potatoqualitee yes, I can work on it tomorrow.  I'm on a staycation until the end of next week ;).

**Comment by tonyfountain** [comment]
@potatoqualitee oh, I see it was introduced in another PR... but this impacts me too so I'll either need to merge yours into mine, or I can just make the proposed changes too.

**Pull request closed without merging**
