### PR TITLE
Restore bits

### PR DESCRIPTION
**Pull request by Stuart-Moore**
## Type of Change

 - [x] Bug fix (non-breaking change, fixes #<enter issue number>)
 - [x] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [x] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [x] Pester test is included
 - [ ] Nunit test is included
 - [x] Documentation
 - [ ] Build system
 

### Purpose
SMO doesn't offer a way to do RESTORE x WITH RECOVERY after the fact, so added that to Restore-DbaDatabase

we were getting caught out with port numbers during restores and copies (as the latter relies on the former) as per #2429 

### Commands to test
setup:
Restore-DbaDatabase -Sqlinstance Instance1 -Path c:\some.bak -DatabaseName db1 -NoRecovery
test:
Restore-DbaDatabase -SqlInstance Instance1 -DatabaseName db1 -Recover
or
Get-DbaDatabase -SqlInstance Instance1 -Database db1 | Restore-DbaDatabase -SqlInstance Instance1 -recover
or 
Get-DbaDatabase -SqlInstance Instance1 -State Recovering | Restore-DbaDatabase -SqlInstance Instance1 -recover

### Learning
Pipelines and parametersets are awkward. Blog post to follow on what I did

### CODE REVIEW

**Comment by ConstantineK** [comment]
Took a look at the conflicts, it appears the first two are fairly trivial to resolve.
However, the third one is a fairly decent amount of difference between the two,  so after I fix the first two I am going to ping him and see if he has any other considerations before overwriting said changes.

**Comment by Stuart-Moore** [comment]
merged and repushed.

FAiling on Fred's changes from the looks of things. 
```
Message  : Cannot process argument transformation on parameter 'EnableException'. Cannot convert value "" to type "System.Boolean". Boolean parameters accept only Boolean values and numbers, such as $True, $False, 1 or 0.
```

Will take a look tomorrow as not time for that this evening unfortunately

**Comment by Stuart-Moore** [comment]
All green bar Stop-DbaAgent tests, appears to be an randomagent thing. Green here - sqlcollaborative/dbatools/build/0.9.8583, just red on @potatoqualitee ci https://ci.appveyor.com/project/potatoqualitee/dbatools/build/0.9.2402  both are for the same commit hash against dev.

**Comment by potatoqualitee** [comment]
yep, that one fails sometimes. i'll look into it on monday!

**Pull request merged**
