### PR TITLE
Add-DbaComputerCertificate - Changed Write-Verbose to Write-Message and UTF-8 BOM Encoding

### PR DESCRIPTION
**Pull request by awickham10**
## Type of Change

 - [ ] Bug fix (non-breaking change, fixes #<enter issue number>)
 - [ ] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
 
Reduce deprecated verbosity commands.

### Approach

Changed Write-Verbose to Write-Message -Level Verbose. Saved file as UTF-8 with BOM encoding.

### CODE REVIEW

**Comment by potatoqualitee** [comment]
SO GOOOOD!

**Comment by wsmelton** [comment]
The encoding no this file needs to be reverted back to UTF-8 @potatoqualitee @awickham10

**Comment by awickham10** [comment]
Why does it need reverted? The reason for the change was for ScriptAnalyzer's recommendation. If it's causing issues, is there anyway to make ScriptAnalyzer ignore this rule for that file?

`Missing BOM encoding for non-ASCII encoded file 'Add-DbaComputerCertificate.ps1'`

**Comment by wsmelton** [comment]
Based on what editor you use you can configure it to ignore this rule, but overall we ignore most every info and warning rule in PSSA...at least right now. The PS Gallery runs PSSA against all modules that are submitted and only flag those that have errors thrown, so we only check against those rules right now to just make sure we are in compliance.

That particular rule has an open issue on PSSA repo if I recall. The reason we are ignoring it is because majority of our files are encoding in UTF-8 and that rule will flag a file needing the BOM encoding because one particular character or something.

**Comment by awickham10** [comment]
Got ya. I thought it was kind of strange, but another file I had opened also had BOM so I didn't think much of it.

Should we need to modify manual.pester.ps1 to include PSUseBOMForUnicodeEncodedFile in $ScriptAnalyzerRulesExclude?

**Pull request merged**
