### PR TITLE
Cleanup - Test-DbaVirtualLogFile

### PR DESCRIPTION
**Pull request by wsmelton**
_I really need to learn how to squash all those noisy commits in my branch._
## Type of Change

 - [ ] Bug fix (non-breaking change, fixes #<enter issue number>)
 - [x] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [x] Pester test is included
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
Cleanup and 1.0 standard applied. Went ahead and created test but I think this command needs to be renamed to `Get-DbaDbVirtualLogFile` or just `Get-DbaDbVlf`. It does not test anything and just returns the VLF count.

After discussions with the boss, the following has been done:

- Test-DbaVirtualLogFile has been reworked to provide the aggregate counts of VLFs along with some Log file growth info for reference
- Get-DbaDbVirtualLogFile has been created, the test command calls this one.
- Test have been created for both of the commands above.

### CODE REVIEW

**Comment by potatoqualitee** [comment]
hey shawn, i can do the squash, it's on my own button. 

Agreed about the name - but `Test` is a placeholder. @ClaudioESSilva had plans to use the formula from his own Expand-Tsqlresponsibly command to judge and thus "test". Claudio is that something you can do within a reasonable time period?

**Comment by Stuart-Moore** [comment]
Not sure if this is of any  use. Something I've recobbled together from old scripts (hence the aliases and bad practice!), but it use liner regression to see if the VLF sizes are growing at fix rates (Perfection is Growthrate of 0 where they're all the same size), positivie values indicate they're getting larger so someone's growing with %. Negative would be something unusual.

```
$srv = connect-dbainstance -SqlInstance localhost\sqlexpress2016
$factorial = 0
$SumTop = 0
$SumBottom = 0 
$data = $srv.Databases['logtest'].Query("DBCC LOGINFO")
$data | %{$_.FileSize = $_.FileSize/1mb}
$stats = $data | Measure-object -Average -Minimum -Maximum -Property filesize

1..$data.count | %{$factorial += $_}

$MeanX = $factorial/$data.count

$i = 0
$data | %{
    $i++
    $SumTop += ($_.FileSize - $stats.average)*($i - $Meanx)
    $SumBottom += ($i - $Meanx)*($i - $Meanx)
}

$growthrate = $SumTop/$SumBottom
if ([Math]::Abs($growthrate) -gt 1){
    Write-Output "Inconsitent growth rates"
}
```

Another good test would be to count the number of VLFs with status 2 as a % of the total VLFs. Gives an idea if your VLFs are too small as you're having to keep them around for long running queries or aren't backing up the logs often enough

**Comment by wsmelton** [comment]
@potatoqualitee the squash I was referring to was for my own fork, so the times when I have to revert something I screwed up those commits don't come over to the upstream repo.

**Comment by wsmelton** [comment]
I also don't know why the last test failed. The one before it passed, and all I did on the last commit was update the tags in the command.

**Comment by potatoqualitee** [comment]
thanks so much @Stuart-Moore ! I like those ideas. @wsmelton - that's a new test entirely, no?

**Comment by wsmelton** [comment]
Yeah, this test passes every time I run it locally so not sure why it failed in Appveyor. 

image

**Comment by wsmelton** [comment]
Ah, just caught something else with my output so don't merge this just yet.

**Comment by wsmelton** [comment]
Updated the PR information, but the following is output associated with each command now...

### Get-DbaDbVirtualLogFile

image

### Test-DbaVirtualLogFile

image

The test for each pass accordingly on my local instance:

image

image

**Comment by wsmelton** [comment]
Finally a green check mark.

**Comment by wsmelton** [comment]
Ok, I got no clue why that keeps failing @potatoqualitee 

It was showing green a few minutes ago and I come back to it and now it is red...don't get that either.

**Comment by potatoqualitee** [comment]
lemme check this out

**Comment by potatoqualitee** [comment]
gonna merge and play

**Pull request merged**
