### PR TITLE
Library - Added documentation on updating version numbers

### PR DESCRIPTION
**Pull request by FriedrichWeinmann**
Fixes # 

Changes proposed in this pull request:
 - Just a minor documentation update, explaining where and how to update the version numbers to avoid warnings

### CODE REVIEW

**Comment by potatoqualitee** [comment]
you wanna add that previous comment from @zippy1981 before I merge, @FriedrichWeinmann ?

**Comment by FriedrichWeinmann** [comment]
Probably a good idea, sec

**Comment by FriedrichWeinmann** [comment]
Alright, updated it. TEST IT FIRST on that win7 smo2008!

**Comment by potatoqualitee** [comment]
k brb

**Comment by potatoqualitee** [comment]
so far, im getting no results from Get-DbaDatabase. Continuing to work it. I believe this occured during the last patch, @FriedrichWeinmann

**Comment by FriedrichWeinmann** [comment]
Um, the instanceparameter works for server objects now or is it still throwing?
Get-DbaDatabase is an entirely different thing - didn't touch that

**Comment by potatoqualitee** [comment]
i think it may be messing with connect-sqlinstance

**Comment by potatoqualitee** [comment]
trying other commands to see if anything works 🤔

**Comment by potatoqualitee** [comment]
Yep, it works! Thank you 🏆  Get-DbaDatabase is broken

**Pull request merged**
