### PR TITLE
Simple query over smo server object

### PR DESCRIPTION
**Pull request by FriedrichWeinmann**
Adds a new method to the server object as returned by `Connect-DbaServer` or `Connect-SqlInstance`:
`$Server.Query($db, Query)`
As a short form for:
`$server.Databases[$db].ExecuteWithResults($Query)).Tables[0]`

### CODE REVIEW

**Comment by potatoqualitee** [comment]
OMGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG this is SO cool! 🏆 🏆 🏆 🏆 🏆 🏆

**Comment by potatoqualitee** [comment]
(can it default to master?)

**Comment by potatoqualitee** [comment]
(oh, can you also make it do .Tables and allow all its tables through? 🌞

**Comment by FriedrichWeinmann** [comment]
Yes and yes:
https://github.com/sqlcollaborative/dbatools/pull/1367

**Pull request merged**
