### PR TITLE
In progress: Improve and consolidate Unit Tests

### PR DESCRIPTION
**Pull request by jpomfret**
## Type of Change

 - [X] Bug fix (non-breaking change, address #4695 )
 - [ ] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [X] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [X] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
 
Current (single) unit test does not fail if you add a parameter to the function. Rewrote this test to fail if parameters are removed or added to functions.

### Screenshots

Missing Param
image
Extra Param
image
All happy
image

### CODE REVIEW

**Comment by wsmelton** [comment]
Just noting the images provided seem to all show failures...is that intended?

**Comment by jpomfret** [comment]
My bad, got the wrong image on the last one. I did find this doesn't work for all functions. If we're using should process it fails currently. Will have. fix for you today.

**Comment by potatoqualitee** [comment]
Thanks so much for your help with this 🙇 does it make any sense to just remove whatif and confirm from all collections?

**Comment by jpomfret** [comment]
Yeah I think so, that is my new improved unit test idea. I'll get it to you when I get to the office (in a couple of hours).

**Pull request merged**
