### PR TITLE
Account for when port number is added to SQL Instance with a colon. Fixes #354

### LINKED ISSUE #354: Support servername:port in addition to SQL Server's native format of servername,port
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Most people expect specifying a port as a colon, including me. So instead of this:

`Test-SqlConnection -SqlServer sql2014:1433`

We are forced to use the native format of a comma: 

`Test-SqlConnection -SqlServer 'sql2014,1433'`

It would be cool if we can do a replace in Connect-SqlServer, though it'd need thorough testing.

### PR DESCRIPTION
**Pull request by shaneis**
@ConstantineK slowly but surely getting the handle of this I think. What do you think of this mess that is my code :tada: 

Fixes #354

Changes proposed in this pull request:
 - 
 - 
 - 

How to test this code: 
- [ ] 
- [ ] 

Has been tested on minimum requirements:
- [ ]  Powershell 3
- [ ]  Windows 7
- [ ]  SQL Server 2000

Has been tested on maximum requirements:
- [ ]  SQL Server vNext
- [ ]  Windows 10
- [ ]  Azure Database

Tests for tester:
- [ ] Working/useful help content, including link to command on dbatools web site
- [ ] All examples work as advertised
- [ ] Does not contain template content
- [ ] Does not contain excessive/unnecessary amounts of comments
- [ ] Works remotely
- [ ] Works locally
- [ ] Works on lower versions or throws error specifying version not supported
- [ ] Works with named instances
- [ ] Works with clustered instances
- [ ] Handles offline/read only databases
- [ ] Supports multiple servers (at the command line or piped from Get-SqlRegisteredServerName)
- [ ] No un-handled errors which stop the command working with multiple servers

### CODE REVIEW

**Comment by mshamann** [comment]
Is this fixing a current ticket? Can you adjust that in the template?

**Comment by ctrlbold** [comment]
This is awesome! Can you add it to the internal Connect-SqlServer command, too?

**Comment by shaneis** [comment]
Sorry still getting familiar with github. I'll do that when I get to a
computer

**Comment by shaneis** [comment]
Sure, I'll give it a go!

**Comment by ctrlbold** [comment]
Nice work, @shaneis! I've tested and merged it and will likely do the Connect-SqlServer myself in this release since I can just copy/paste your code real quick.

**Comment by shaneis** [comment]
No worries @ctrlbold, I can get started seeing if there's other issues I can help out on 👍

**Pull request merged**
