### PR TITLE
[Get-DbaAgBackupHistory] - New command for the availability group functionality of Get-DbaDbBackupHistory

### LINKED ISSUE #3799: New Command: Get-DbaAGBackupHistory
Command will need to provide the ability to pull backup history from all replicas involved in the AG, irrespective of the backup preference.

Original issue: #1712

### PR DESCRIPTION
**Pull request by andreasjordan**
## Type of Change

 - [ ] Bug fix (non-breaking change, fixes )
 - [x] New feature (non-breaking change, adds functionality, fixes #3799 )
 - [x] Breaking change (effects multiple commands or functionality, fixes # )
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
To be able to let Get-DbaDbBackupHistory focus again on the history of just the instances provided in SqlInstance, we want to transfer the code related to availability groups to a separate command called Get-DbaAgBackupHistory.

### Approach
- [x] Create a new command Get-DbaAgBackupHistory which returns the exact same results as Get-DbaDbBackupHistory when SqlInstance is part of an availability group or an availability group listener.
- [ ] Discuss the necessary parameters and their function
- [ ] Implement the result of the discussion
- [ ] Implement tests for the command
- [ ] remove the availability group functionality from Get-DbaDbBackupHistory
- [ ] Add a web page for the command

This is my first new command - so there are maybe some things missing...

### CODE REVIEW

**Comment by andreasjordan** [comment]
My ideas for the parameters:

SqlInstance:
If one object is passed: Test if it is an availability replica or an availability group listener, otherwise quit with hint to Get-DbaDbBackupHistory. Get history from all replicas for the given AvailabilityGroup.
If more than one object is passed: Test if these are all replicas for the given AvailabilityGroup or fail. Use SqlInstance to get history from all given replicas. This enables the use of custom ports.
Accept pipeline input like Get-DbaDbBackupHistory.

AvailabilityGroup:
To keep things simple, just accept one availability group and make this parameter mandatory like in other commands.

IncludeCopyOnly:
Remove this parameter and set it to $true like it is implemented now.

**Comment by andreasjordan** [comment]
I pushed a new commit that removes the parameter `-AgCheck` and all replated code from `Get-DbaDbBackupHistory`.
Can someone please have a look at Get-DbaDbBackupHistory.Tests.ps1? I only removed the parameter `AgCheck`from line 8.

**Comment by potatoqualitee** [comment]
Thank you, @andreasjordan - @Stuart-Moore can you please take a look at this PR and approve/comment? merci

**Comment by Stuart-Moore** [comment]
Looks fine to me for simple AG setups

Tagging in @wsmelton  as he's got more AG experience and likely some better test cases further from the norm

**Comment by potatoqualitee** [comment]
I think this is a good approach and it has good tests, as well. We've had a lot of requests for this functionality and making it a dedicated command makes sense. I'll check on the failing test and also setup an AG and test from there.

**Comment by potatoqualitee** [comment]
thank you for your feedback @Stuart-Moore !

**Comment by potatoqualitee** [comment]
ahh @andreasjordan - it appears that the test is working, which is nice! It's failing for a reason. I'm going to add back AGCheck but tell the user that the command is now dedicated then execute your command instead. In the future, we can remove the parameter all together.

**Comment by potatoqualitee** [comment]
I saw that regression test fail in other branches, but it sometimes passes. I think this is an issue with appveyor :(

**Comment by niphlod** [comment]
> I saw that regression test fail in other branches, but it sometimes passes. I think this is an issue with appveyor :(

yeah, mine to deal with. You can comment it, I'll reintroduce when I find a more stable (and still speedy) way to do the setup part of that regression test

**Comment by potatoqualitee** [comment]
hell yeah, done

**Pull request merged**
