### PR TITLE
Get-DbaDependency - detect a circular reference

### LINKED ISSUE #7139: Get-DbaDependency gets stuck in loop when InputObject has a circular reference.
### Report

Get-DbaDependency gets stuck in loop when InputObject has a circular reference.

#### Host used
Name             : Visual Studio Code Host
Version          : 2020.6.0
InstanceId       : 447ac6de-6823-4100-86ee-ae7ba383d496
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : en-US
CurrentUICulture : en-US
PrivateData      : Microsoft.PowerShell.EditorServices.Services.PowerShellContext.EditorServicesPSHost+ConsoleColorProxy
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace

#### Errors Received
None.  The command is stuck in loop.

#### Steps to Reproduce
Create a couple inter dependent tables.
```
CREATE TABLE [dbo].[TableA](
	[TableAId] [int] NOT NULL,
	[TableBId] [int] NULL,
 CONSTRAINT [PK_TableA] PRIMARY KEY CLUSTERED 
(
	[TableAId] ASC
))
GO
CREATE TABLE [dbo].[TableB](
	[TableBId] [int] NOT NULL,
	[TableAId] [int] NOT NULL,
 CONSTRAINT [PK_TableB] PRIMARY KEY CLUSTERED 
(
	[TableBId] ASC
))
GO
ALTER TABLE [dbo].[TableA]  WITH CHECK ADD  CONSTRAINT [FK_TableA_TableB] FOREIGN KEY([TableBId])
REFERENCES [dbo].[TableB] ([TableBId])
GO
ALTER TABLE [dbo].[TableA] CHECK CONSTRAINT [FK_TableA_TableB]
GO
ALTER TABLE [dbo].[TableB]  WITH CHECK ADD  CONSTRAINT [FK_TableB_TableA] FOREIGN KEY([TableAId])
REFERENCES [dbo].[TableA] ([TableAId])
GO
ALTER TABLE [dbo].[TableB] CHECK CONSTRAINT [FK_TableB_TableA]
GO
```
Execute these
```
$tablea = Get-DbaDbTable -SqlInstance localhost -Database CircRef -table "tablea"
$tableA | Get-DbaDependency
## this is where it gets stuck
```
#### Expected Behavior
When descending the dependency tree and parent object is detected as a child
Then include child object in output and ascend dependency tree and continue to traverse the remaining siblings and children.

#### Actual Behavior
Command gets stuck with no output.

### Environmental information
```poweshell
PowerShell Version        : 7.1.0
dbatools latest installed : 1.0.135
Culture of OS             : en-US
```

#### SQL Server:

```sql
select @@VERSION
-- Microsoft SQL Server 2016 (SP1-GDR) (KB4505219) - 13.0.4259.0 (X64)   Jun 15 2019 19:20:12   Copyright (c) Microsoft Corporation  Developer Edition (64-bit) on Windows 10 Pro 6.3 <X64> (Build 19042: ) (Hypervisor) ```
select @@LANGUAGE
-- us_english
```

### PR DESCRIPTION
**Pull request by SamWalkerRxSense**
## Type of Change

 - [X] Bug fix (non-breaking change, fixes #7139 )
 - [ ] New feature (non-breaking change, adds functionality, fixes # )
 - [ ] Breaking change (effects multiple commands or functionality, fixes # )
 - [X] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [X] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
Ensure the dependency check does not get into an infinite loop.

### Approach
The code checks that dependency is not a parent object.

### Commands to test
See the new integration tests.

### CODE REVIEW

**Comment by lancasteradam** [comment]
@SamWalkerRxSense, great work on this PR. A few small suggestions so this PR is ready for the maintainers to review:

Ensure the issue is referenced in the PR description:

PR auto close issue

After pushing code to a PR there are automation tests that run:

appveyor automation tests

It looks like you'll need to run the formatter on the updated file(s), something like:

Invoke-DbatoolsFormatter -Path <path to dbatools code>\functions\Get-DbaDependency.ps1

dbatools formatter

There are a few other integration tests that failed but they are for other commands that experience occasional environment stability issues.

Have fun with it and thanks for your contribution!

**Comment by SamWalkerRxSense** [comment]
@lancasteradam  thanks for the tips!  PR is updated.

**Comment by jpomfret** [comment]
Hey @SamWalkerRxSense and\or @lancasteradam - any chance you can take a look at these integration tests and see if there is any performance improvements to be had? Tests make sense to me - but for a long time.

Thanks @SamWalkerRxSense for your contribution - sorry for the delays in merging this in!

**Comment by SamWalkerRxSense** [comment]
@jpomfret  What sort test timings are you seeing?  I'm seeing 4 sec 141 ms, I checked some previous build it seems the added tests increase ~500ms.  Is that right?  I'm new to this, just wanted to make sure I was looking at the right thing.

**Comment by potatoqualitee** [comment]
Thank you both so much. I've seen similar increases with this particular command, so it makes sense, @SamWalkerRxSense. Merging now 🥳

**Pull request merged**
