### PR TITLE
Invoke-DbatoolsFormatter, aesthetic fixes

### LINKED ISSUE #4373: Invoke-DbatoolsFormatter leaves space at the bottom
there is an extra carriage return and it would be fab if our commands stopped at the last `}` instead of bracket new line

### LINKED ISSUE #4409: Invoke-DbatoolsFormatter removing trailing spaces
It would be great if this could be added if possible tyvm 🙇

### PR DESCRIPTION
**Pull request by niphlod**
## Type of Change

 - [x] Bug fix (non-breaking change, fixes #4409 and fixes #4373)
 - [ ] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
Fix the reported bugs

### Approach
Another bit of regexes involved

@potatoqualitee : before doing a mass rewrite please check that the output is consistent with what you want. In any case these aesthetics won't - obviously - checked in CI. One thing is consistency, the other is fixation ^_^

### CODE REVIEW

**Comment by potatoqualitee** [comment]
hey niph, i saw some good changes, thanks. the one thing i noticed is that it's still adding a line at the bottom. Can you make it so that it not only doesn't add a line, but makes `}` the last thing at the bottom?

**Comment by niphlod** [comment]
so, instead of
```
....CRLF
}CRLF
```
you want
```
....CRLF
}
```
? is it reaaaaaally necessary to cut the last CRLF ?

**Comment by potatoqualitee** [comment]
Correct, that's what I'd love. Every time I do invoke-formatter right now, I have to go back and remove it. It's not 100% necessary, but it's inconvenient and a gnawing issue for me. Especially because I'm compelled to remove it even though I know we could do a mass rewrite and I'll be behind all over again.

**Comment by niphlod** [comment]
that additional line number makes BFDL creep, the additional line number shall be removed. I'll work on it.

**Comment by potatoqualitee** [comment]
haha 🙇 thank you, you're the best

**Comment by potatoqualitee** [comment]
omg it works perfectly and it's wonderful 😍

**Comment by potatoqualitee** [comment]
will do a mass format once we get PRs down, likely within the next two weeks

**Pull request merged**
