### PR TITLE
Test-DbaDiskAlignment - corrected indentation

### LINKED ISSUE #6406: [Bug] unexpected behavior: disks reported twice
Hi there,

First off, I just wanna say how great the DbaTools are! Please find below what I discovered today...

# Environmental information              
```                                                                                                                                                                                                                                         
PSVersion                      5.1.14393.3383                                                                                                                                                                                                                                                               
PSEdition                      Desktop                                                                                                                                                                                                                                                                      
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                                                                                                                      
BuildVersion                   10.0.14393.3383                                                                                                                                                                                                                                                              
CLRVersion                     4.0.30319.42000                                                                                                                                                                                                                                                              
WSManStackVersion              3.0                                                                                                                                                                                                                                                                          
PSRemotingProtocolVersion      2.3                                                                                                                                                                                                                                                                          
SerializationVersion           1.1.0.1     
```
dbatools Module version:
```
Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.97\dbatools.psd1
Version : 1.0.97
```

Get-Culture:
```
LCID             Name             DisplayName                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
3079             de-AT            German (Austria)
```


#### SQL Server: 
(both instances):
```
Microsoft SQL Server 2016 (SP2-CU11) (KB4527378) - 13.0.5598.27 (X64)   Nov 27 2019 18:09:22   Copyright (c) Microsoft Corporation  Standard Edition (64-bit) on Windows Server 2016 Datacenter 10.0 <X64> (Build 14393: ) (Hypervisor) 
```

### Report


#### Host used

- [ X ] powershell.exe
- [ X ] ISE

- [ X ] Still buggy in powershell.exe

#### Errors Received
None

#### Steps to Reproduce
```
Test-DbaDiskAlignment -ComputerName $env:COMPUTERNAME -Verbose  | ft
```

#### Expected Behavior
Output of one row per disk, like in Test-DbaDiskAllocation

#### Actual Behavior
Each disk is reported twice, running the script with -verbose reveals that this is obviously due to two instances residing on the same machine.

Note: 
For MSSQL01 instance:
```
Select count(*) as Count from sys.master_files where physical_name like 'E:%' 
```
Outputs: **0**
```
Select count(*) as Count from sys.master_files where physical_name like 'D:%'
```
Outputs: **84**

For MSSQL02 instance:
```
Select count(*) as Count from sys.master_files where physical_name like 'E:%' 
```
Outputs: **29**
```
Select count(*) as Count from sys.master_files where physical_name like 'D:%'
```
Outputs: **0**


```
VERBOSE: [09:06:45][Test-DbaDiskAlignment] Processing: X1234.
VERBOSE: [09:06:45][Resolve-DbaNetworkName] Resolving X1234 using .NET.Dns GetHostEntry
VERBOSE: [09:06:45][Resolve-DbaNetworkName] Resolving 127.0.0.1 using .NET.Dns GetHostByAddress
VERBOSE: [09:06:45][Get-DbaCmObject] Configuration loaded | Cache disabled: False
VERBOSE: [09:06:45][Get-DbaCmObject] [x1234] Retrieving Management Information
VERBOSE: [09:06:45][Get-DbaCmObject] [x1234] Accessing computer using Cim over DCOM
VERBOSE: [09:06:46][Get-DbaCmObject] [x1234] Accessing computer using Cim over DCOM - Success
VERBOSE: [09:06:46][Resolve-DbaNetworkName] Resolving X1234.xxxxxx-example.com using .NET.Dns GetHostEntry
VERBOSE: [09:06:46][Test-DbaDiskAlignment] Creating CimSession on X1234.xxxxxx-example.com over WSMan
VERBOSE: Operation '' complete.
VERBOSE: [09:06:46][Test-DbaDiskAlignment] Creating CimSession on X1234.xxxxxx-example.com over WSMan failed. Creating
CimSession on X1234.xxxxxx-example.com over DCOM.
VERBOSE: Operation '' complete.
VERBOSE: [09:06:46][Test-DbaDiskAlignment] Getting Power Plan information from X1234.xxxxxx-example.com.
VERBOSE: [09:06:46][Test-DbaDiskAlignment] Gathering information about first partition on each disk for
X1234.xxxxxx-example.com.
VERBOSE: Perform operation 'Enumerate CimInstances' with following parameters, ''namespaceName' =
root\cimv2,'className' = Win32_DiskPartition'.
VERBOSE: Operation 'Enumerate CimInstances' complete.
VERBOSE: Perform operation 'Query CimInstances' with following parameters, ''queryExpression' = ASSOCIATORS OF
{Win32_DiskPartition.DeviceID="Disk #2, Partition #0"} WHERE AssocClass = Win32_LogicalDiskToPartition,'queryDialect' =
 WQL,'namespaceName' = root\cimv2'.
VERBOSE: Operation 'Query CimInstances' complete.
VERBOSE: Perform operation 'Query CimInstances' with following parameters, ''queryExpression' = ASSOCIATORS OF
{Win32_DiskPartition.DeviceID="Disk #0, Partition #0"} WHERE AssocClass = Win32_LogicalDiskToPartition,'queryDialect' =
 WQL,'namespaceName' = root\cimv2'.
VERBOSE: Operation 'Query CimInstances' complete.
VERBOSE: Perform operation 'Query CimInstances' with following parameters, ''queryExpression' = ASSOCIATORS OF
{Win32_DiskPartition.DeviceID="Disk #0, Partition #1"} WHERE AssocClass = Win32_LogicalDiskToPartition,'queryDialect' =
 WQL,'namespaceName' = root\cimv2'.
VERBOSE: Operation 'Query CimInstances' complete.
VERBOSE: Perform operation 'Query CimInstances' with following parameters, ''queryExpression' = ASSOCIATORS OF
{Win32_DiskPartition.DeviceID="Disk #1, Partition #0"} WHERE AssocClass = Win32_LogicalDiskToPartition,'queryDialect' =
 WQL,'namespaceName' = root\cimv2'.
VERBOSE: Operation 'Query CimInstances' complete.
VERBOSE: Perform operation 'Query CimInstances' with following parameters, ''queryExpression' = ASSOCIATORS OF
{Win32_DiskPartition.DeviceID="Disk #3, Partition #0"} WHERE AssocClass = Win32_LogicalDiskToPartition,'queryDialect' =
 WQL,'namespaceName' = root\cimv2'.
VERBOSE: Operation 'Query CimInstances' complete.
VERBOSE: [09:06:46][Test-DbaDiskAlignment] Gathered CIM information.
VERBOSE: [09:06:46][Test-DbaDiskAlignment] Checking for SQL Services.
VERBOSE: Perform operation 'Enumerate CimInstances' with following parameters, ''namespaceName' =
root\cimv2,'className' = Win32_Service'.
VERBOSE: Operation 'Enumerate CimInstances' complete.
VERBOSE: [09:06:47][Test-DbaDiskAlignment] Found instance MSSQL01
VERBOSE: [09:06:47][Test-DbaDiskAlignment] Found instance MSSQL02
VERBOSE: [09:06:47][Test-DbaDiskAlignment] 2 instance(s) found.
VERBOSE: [09:06:47][Test-DbaDiskAlignment] Query is: Select count(*) as Count from sys.master_files where physical_name
 like 'E:%' 
VERBOSE: [09:06:47][Test-DbaDiskAlignment] SQL Server is: X1234.xxxxxx-example.com\MSSQL01.
VERBOSE: [09:06:49][Test-DbaDiskAlignment] Query is: Select count(*) as Count from sys.master_files where physical_name
 like 'E:%'
VERBOSE: [09:06:49][Test-DbaDiskAlignment] SQL Server is: X1234.xxxxxx-example.com\MSSQL02.
VERBOSE: [09:06:49][Test-DbaDiskAlignment] Query is: Select count(*) as Count from sys.master_files where physical_name
 like 'C:%'
VERBOSE: [09:06:49][Test-DbaDiskAlignment] SQL Server is: X1234.xxxxxx-example.com\MSSQL01.
VERBOSE: [09:06:50][Test-DbaDiskAlignment] Query is: Select count(*) as Count from sys.master_files where physical_name
 like 'C:%'
VERBOSE: [09:06:50][Test-DbaDiskAlignment] SQL Server is: X1234.xxxxxx-example.com\MSSQL02.
VERBOSE: [09:06:50][Test-DbaDiskAlignment] Query is: Select count(*) as Count from sys.master_files where physical_name
 like 'D:%'
VERBOSE: [09:06:50][Test-DbaDiskAlignment] SQL Server is: X1234.xxxxxx-example.com\MSSQL01.
VERBOSE: [09:06:50][Test-DbaDiskAlignment] Query is: Select count(*) as Count from sys.master_files where physical_name
 like 'Z:%'
VERBOSE: [09:06:50][Test-DbaDiskAlignment] SQL Server is: X1234.xxxxxx-example.com\MSSQL01.
VERBOSE: [09:06:51][Test-DbaDiskAlignment] Query is: Select count(*) as Count from sys.master_files where physical_name
 like 'Z:%'
VERBOSE: [09:06:51][Test-DbaDiskAlignment] SQL Server is: X1234.xxxxxx-example.com\MSSQL02.
VERBOSE: [09:06:51][Test-DbaDiskAlignment] Checking 2 partitions.
VERBOSE: [09:06:51][Test-DbaDiskAlignment] Testing for dynamic disks.
VERBOSE: [09:06:51][Test-DbaDiskAlignment] Checking for best practices offsets.

VERBOSE: [09:06:51][Test-DbaDiskAlignment] Testing for dynamic disks.
VERBOSE: [09:06:51][Test-DbaDiskAlignment] Checking for best practices offsets.
ComputerName Name PartitonSize PartitionType   TestingStripeSize OffsetModuluCalculation StartingOffset IsOffsetBestPra
                                                                                                                  ctice
------------ ---- ------------ -------------   ----------------- ----------------------- -------------- ---------------
X1234        E:   149,87 GB    GPT: Basic Data 64,00 KB          0 B                     129,00 MB                False
X1234        E:   149,87 GB    GPT: Basic Data 128,00 KB         0 B                     129,00 MB                False
X1234        E:   149,87 GB    GPT: Basic Data 256,00 KB         0 B                     129,00 MB                False
X1234        E:   149,87 GB    GPT: Basic Data 512,00 KB         0 B                     129,00 MB                False
X1234        E:   149,87 GB    GPT: Basic Data 1 024,00 KB       0 B                     129,00 MB                False
X1234        D:   699,87 GB    GPT: Basic Data 64,00 KB          0 B                     129,00 MB                False
X1234        D:   699,87 GB    GPT: Basic Data 128,00 KB         0 B                     129,00 MB                False
X1234        D:   699,87 GB    GPT: Basic Data 256,00 KB         0 B                     129,00 MB                False
X1234        D:   699,87 GB    GPT: Basic Data 512,00 KB         0 B                     129,00 MB                False
X1234        D:   699,87 GB    GPT: Basic Data 1 024,00 KB       0 B                     129,00 MB                False
```

All the best,
gh-ttgo

### PR DESCRIPTION
**Pull request by andreasjordan**
Just corrected the indentation to better be able to work on #6406. No other change to the code.
Update: Fixes #6406.

### CODE REVIEW

**Review by niphlod — APPROVED** [review]

**Comment by potatoqualitee** [comment]
I can't get this to format properly, @niphlod any suggestions? I even cut/pasted from VSCode, used Invoke-DbatoolsFormatter and I deleted the command and readded it. Wtheck.

**Comment by niphlod** [comment]
don't get crazy over it, sometimes PSScriptAnalyzer is just ....... magic. And I start feeling that VSCode uses PSScriptAnalyzer with an interface Powershell hasn't.
I'll try to extrapolate the subtlety in a few hours, sorry for the hiccup.

**Comment by andreasjordan** [comment]
I thinks it's the `| ForEach-Object {` with a pipeline inside of the block followed by another pipeline. I think we had a similar problem some months ago. Just rewrite the code?

**Comment by andreasjordan** [comment]
Changed the description so we can close #6406. As long as I don't have to work on the command, I don't care about the indentation.

**Comment by potatoqualitee** [comment]
Thank you, @niphlod!

Does that mean I can close this, @andreasjordan ?

**Comment by andreasjordan** [comment]
I changed the description. Can you merge this change?

**Comment by andreasjordan** [comment]
Great. Thanks.

**Comment by potatoqualitee** [comment]
Thanks to you both! How the heck did you get that to work, @niphlod ?

**Comment by niphlod** [comment]
@potatoqualitee : just rewrote the ugly foreach-object with a zillion pipes to a plain foreach() with a returning pscustomobject. 
that doesn't scare psscriptanalyzer that much.

**Pull request merged**
