### PR TITLE
PS Core adjustments related to Test-Connection

### LINKED ISSUE #4840: Resolve-DbaNetworName is not working properly in PS6.0+
### Before submitting a bug report:

- [x] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [x] Verified this bug is not already reported in an issue
- [x] Verified errors are not related to permissions
- [x] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

## Steps to Reproduce
```powershell
$t = Resolve-DbaNetworName -ComputerName computer -Verbose
```
image

image

## Expected Behavior
Normal mode with CIM/PSRemoting hostname verifications.
No extra output.

## Actual Behavior
Turbo mode (due to different parameter set in PS6.0 version of Test-Connection).
Ping results show up on the screen.

## Environmental data

 - PowerShell:
PSVersion                      6.1.0
PSEdition                      Core
GitCommitId                    6.1.0
OS                             Microsoft Windows 10.0.15063
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

### PR DESCRIPTION
**Pull request by nvarscar**
Let's see how many commands will blow after this one
## Type of Change

 - [x] Bug fix (non-breaking change, fixes #4840)
 - [ ] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [x] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
Resolving issues in the commands relying on Test-Connection function in PS6 and a few other issues I discovered while testing them on PS Core

### Approach
Resolve-DbaNetworkName was rewritten, reducing the number of calls to DNS.
Test-Connection was replaced by 
```powershell
$ping = New-Object System.Net.NetworkInformation.Ping
$timeout = 1000 #milliseconds
$reply = $ping.Send($computer, $timeout)
```
### Commands to test
Resolve-DbaNetworkName

### Learning
Test-Connection is a different beast in PS6.0 and has different set of properties
$PSVersionTable.CLRVersion is null in Core.

### CODE REVIEW

**Comment by nvarscar** [comment]
Phew! We're finally in the green. Please review at your leisure 😅

**Comment by potatoqualitee** [comment]
so far, im not getting the same results in my own testing

dev: 
image

this branch:

image

**Comment by nvarscar** [comment]
Woops. Never tested it with websites, gonna look into it.

**Comment by nvarscar** [comment]
I've updated some parts of the code to better build the output object. The difference in ComputerName however is (I think) is a flow in current code logic, since it gets that name right now from the input string unchanged due to being unable to connect via PS remoting. The turbo mode returns proper Computer name from DNS resolution.
New version of code uses DNS name resolution in all cases (which kinda makes sense, to me, at least) and only updates it again when remoting works.

**Comment by nvarscar** [comment]
And Merry Christmas!

**Comment by potatoqualitee** [comment]
thank you both 🙇

**Pull request merged**
