### PR TITLE
fix Test-DbaConnection command

### PR DESCRIPTION
**Pull request by potatoqualitee**
was this horror

image

now is this

image

### CODE REVIEW

**Comment by potatoqualitee** [comment]
actually i take it back, it'll look like this to match the other error

image

**Comment by potatoqualitee** [comment]
also instancename is no longer blank if it's default

**Comment by potatoqualitee** [comment]
dang, what do we do about this

image

that machine is online but sql isnt running, however, what if psremoting is online?

**Comment by wsmelton** [comment]
Since it is a test connection I think it needs to return an object regardless of issue and the inject contain the results of all the test performed.

**Pull request merged**
