### PR TITLE
Dbainstanceparameter hotfixing

### LINKED ISSUE #1797: Commands missing DbaInstanceParmeter type
Following commands need to have the `ComputerName` or `SqlInstance` updated to `[DbaInstanceParameter]` as the parameter type.

- [x] Clear-DbaSqlConnectionPool.ps1
- [x] Get-DbaAgentSchedule.ps1
- [x] Get-DbaClientProtocol.ps1
- [x] Get-DbaCmConnection.ps1
- [x] Get-DbaDiskSpace.ps1
- [x] Get-DbaLocaleSetting.ps1
- [x] Get-DbaMsdtc.ps1
- [x] Get-DbaNetworkActivity.ps1
- [x] Get-DbaPageFileSetting.ps1
- [x] Get-DbaSpn.ps1
- [x] Get-DbaSqlProductKey.ps1
- [x] Invoke-DbaLogShipping.ps1
- [x] Invoke-DbaLogShippingRecovery.ps1
- [x] New-DbaAgentSchedule.ps1
- [x] New-DbaSqlConnectionStringBuilder.ps1
- [x] Remove-DbaAgentJob.ps1
- [x] Remove-DbaAgentSchedule.ps1
- [x] Set-DbaPowerPlan.ps1
- [x] Test-DbaDiskAlignment.ps1
- [x] Test-DbaDiskAllocation.ps1
- [x] Test-DbaLinkedServerConnection.ps1
- [x] Test-DbaPowerPlan.ps1

### PR DESCRIPTION
**Pull request by wsmelton**
## Type of Change

 - [x] Bug fix (non-breaking change, fixes #1797 )
 - [ ] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Pester test is included

### Purpose
 
Addresses remain commands that did not have computer or instance parameter set to `DbaInstanceParameter`.
### Approach

Ensures we have consistent object type for the `SqlInstance` and `ComputerName` parameters we pass into our commands.
### Commands to test

N/A
### Screens

### CODE REVIEW

**Comment by potatoqualitee** [comment]
@gbargsley - can you test all these? code looks good but want to test test

**Comment by gbargsley** [comment]
@potatoqualitee @wsmelton 

I will do first thing.  Do I just test the SqlInstance or ComputerName parameters work?

**Comment by potatoqualitee** [comment]
@gbargsley - yeah just running them should work. @wsmelton - New-DbaSqlConnectionStringBuilder is failing (and doesn't really need that param anyway). Can you please update? Thanks!

**Comment by potatoqualitee** [comment]
Oh yay! This is a local branch!

**Comment by potatoqualitee** [comment]
fixed New-DbaSqlConnectionStringBuilder

**Comment by gbargsley** [comment]
@wsmelton @potatoqualitee  Does Get-DbaCmConnection have the correct code in the DbaInstanceParameter ?  It does not return anything when I run it on different servers.

**Comment by gbargsley** [comment]
`####
Get-DbaCmConnection -ComputerName REGPRSDBS03A
Get-DbaDiskSpace -ComputerName REGPRSDBS03A #worked
Get-DbaLocaleSetting -ComputerName REGPRSDBS03A #worked
Get-DbaMsdtc -ComputerName REGPRSDBS03A #worked
Get-DbaNetworkActivity -ComputerName REGPRSDBS03A #worked
Get-DbaPageFileSetting -ComputerName REGPRSDBS03A #worked
Get-DbaServerProtocol -ComputerName REGPRSDBS03A #worked
Get-DbaSpn -ComputerName L7DR15466 #worked on local, not on remote.  Not sure if I have permissions in AD
Get-DbaSqlProductKey -SqlInstances REGPRSDBS03A #Error Method invocation failed because [Sqlcollaborative.Dbatools.Parameter.DbaInstanceParameter] does not contain a method named 'Split'. but returned Product Key.  Also should it be -SqlInstanceS
Test-DbaDiskAlignment -ComputerName L7DR15466 #worked
Test-DbaDiskAllocation -ComputerName REGPRSDBS03A #message cannot create CimSession, and cannot connect to WMI
Test-DbaLinkedServerConnection -SqlInstance REGPRSDBS03A #worked
Test-DbaPowerPlan -ComputerName REGPRSDBS03A #worked
Remove-DbaAgentJob -SqlInstance l7dr15466 -Job 'DatabaseIntegrityCheck - SYSTEM_DATABASES' #worked
Remove-DbaAgentSchedule -SqlInstance l7dr15466 -Schedule CollectorSchedule_Every_10min #worked
New-DbaAgentSchedule -SqlInstance l7dr15466 -Schedule GarryTest -FrequencyType Daily -Force #worked
New-DbaSqlConnectionStringBuilder # No ComputerName or SqlInstance parameter
"Data Source=localhost,1433;Initial Catalog=AlwaysEncryptedSample;UID=sa;PWD=alwaysB3Encrypt1ng;Application Name=Always Encrypted Sample MVC App;Column Encryption Setting=enabled" | New-DbaSqlConnectionStringBuilder
Set-DbaPowerPlan -ComputerName L7DR15466 -PowerPlan Balanced -WhatIf #worked as WhatIf so I do not break my laptop
Invoke-DbaLogShipping -SourceSqlInstance L7DR15466 -DestinationSqlInstance L7DR15466\sql2012 -Database ElevateMetrics -BackupLocalPath C:\Temp\Testing -BackupScheduleFrequencyType Daily -BackupScheduleFrequencyInterval EveryDay -CopyScheduleFrequencyType Daily -CopyScheduleFrequencyInterval EveryDay -RestoreScheduleFrequencyType Daily -RestoreScheduleFrequencyInterval EveryDay -BackupNetworkPath \\L7DR15466\Backups -Force
# Get error Method invocation failed because [Sqlcollaborative.Dbatools.Parameter.DbaInstanceParameter] does not contain a method named 'Split'.
# and -Force and -GenerateFullBackup do not appear to be working.
`

**Comment by potatoqualitee** [comment]
aw shit, have a conflict. I'm not done fixing this branch. But should be by Sunday.

**Comment by wsmelton** [comment]
@potatoqualitee Do I need to close this one and just do it one at a time?

**Comment by potatoqualitee** [comment]
I'm thinking so, @wsmelton :( I did fix a number of them (so please check their code), but the entire thing was too much at the time.

**Pull request closed without merging**
