### PR TITLE
Get-DbaErrorLog - Implement fix to process all logfiles

### LINKED ISSUE #4774: Get-DbaErrorLog without LogNumber parameter only reads first file
### Before submitting a bug report:

- [X ] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [X ] Verified this bug is not already reported in an issue
- [X ] Verified errors are not related to permissions
- [X ] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

## Steps to Reproduce

```powershell
# pick a data that spans into your second SQL Server event log file
Get-DbaErrorLog -SqlInstance $prodInstance -After '2018-12-04 20:30:00';
```
## Expected Behavior

Reads from first and second file to get full list of logs that match -After

## Actual Behavior

Only returns data from first file

I was able to get the data I needed today by adding the LogNumber parameter:
```powershell
# enough files to get the dates noted in the -After
Get-DbaErrorLog -SqlInstance $prodInstance -After '2018-12-04 20:00:00' -LogNumber (0..6)
```

## Environmental data

PowerShell 5.1

### PR DESCRIPTION
**Pull request by andreasjordan**
## Type of Change

 - [x] Bug fix (non-breaking change, fixes #4774 )
 - [ ] New feature (non-breaking change, adds functionality, fixes # )
 - [ ] Breaking change (effects multiple commands or functionality, fixes # )
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
Read all logfiles if LogNumber is not given.

### Approach
Loop through all possible logfiles.

### Commands to test
(Get-DbaErrorLog -SqlInstance SRV1).Count
(Get-DbaErrorLog -SqlInstance SRV1 -LogNumber 0).Count

### Screenshots
image

### CODE REVIEW

**Review by niphlod — COMMENTED** [review]
can we add a simple test for this just for the sake of being able to trace it back if (when) smo gets fixed ?

**Comment by andreasjordan** [comment]
The more I think of it, I think it's not a bug but intended. Because typically you just look at the current log. 
So this was a bug in our code. There is simply no documentation on this method.

**Review by niphlod — APPROVED** [review]
yeah, this is good.

**Comment by potatoqualitee** [comment]
💯

**Pull request merged**
