### PR TITLE
Few improvements for *-DbaSqlService commands

### LINKED ISSUE #2170: Get-DbaSqlService methods for stop, start and restart
This is not a bug nor a feature request, but a question of what is the need for them?

If I run:
```powershell
(Get-DbaSqlService -ComputerName manatarms -InstanceName mssqlserver -Type Engine).Stop()
```
Will give me the warning that dependent services are still running so it cannot stop the service. That is fine and dandy, so why would we ever use it? If I have to manually call the command for each service that is dependent I could have done it quicker by just calling `Stop-Service mssqlserver -force` and it will stop everything for me.

The odd ball is the Restart() method in the command. If I stop `mssqlserver` and then try the Restart() method it gives a false warning for some reason but then starts the service.

```powershell
C:\GitHub\dbatools [development ≡]> (Get-DbaSqlService -ComputerName manatarms -InstanceName mssqlserver -Type Engine).Restart()
WARNING: [Get-DbaCmObject][21:20:09] [manatarms] Could not find a valid connection protocol, interrupting execution now | Exception ca
lling "GetConnectionType" with "2" argument(s): "No connectiontypes left to try."
WARNING: [Restart-DbaSqlService][21:20:12] The attempt to stop the service MSSQLSERVER on MANATARMS returned the following error: The
requested control code cannot be sent to the service because the state of the service (Win32_BaseService.State property) is equal to 0
, 1, or 2.
[Restart-DbaSqlService][21:20:15] Service MSSQLSERVER on MANATARMS was successfully started.
C:\GitHub\dbatools [development ≡]> Get-DbaSqlService -ComputerName manatarms -InstanceName mssqlserver | select ServiceName, State
WARNING: [Get-DbaCmObject][21:20:33] [manatarms] Could not find a valid connection protocol, interrupting execution now | Exception ca
lling "GetConnectionType" with "2" argument(s): "No connectiontypes left to try."

ServiceName            State
-----------            -----
MSSQLSERVER            Running
MSSQLServerOLAPService Stopped
ReportServer           Stopped
SQLSERVERAGENT         Stopped
```

If I start the agent service and then try to use the restart method again I get a warning about stopping and starting. It seems that `Restart-DbaSqlService` does not quick when it hits the first issue with the service:

```powershell
C:\GitHub\dbatools [development ≡]> (Get-DbaSqlService -ComputerName manatarms -InstanceName mssqlserver -Type Engine).Restart()
WARNING: [Get-DbaCmObject][21:22:16] [manatarms] Could not find a valid connection protocol, interrupting execution now | Exception ca
lling "GetConnectionType" with "2" argument(s): "No connectiontypes left to try."
WARNING: [Restart-DbaSqlService][21:22:17] The attempt to stop the service MSSQLSERVER on MANATARMS returned the following error: The
service cannot be stopped because other services that are running are dependent on it.
WARNING: [Restart-DbaSqlService][21:22:18] The attempt to start the service MSSQLSERVER on MANATARMS returned the following error: The
 service is already running.
C:\GitHub\dbatools [development ≡]> Get-DbaSqlService -ComputerName manatarms -InstanceName mssqlserver | select ServiceName, State
WARNING: [Get-DbaCmObject][21:22:25] [manatarms] Could not find a valid connection protocol, interrupting execution now | Exception ca
lling "GetConnectionType" with "2" argument(s): "No connectiontypes left to try."

ServiceName            State
-----------            -----
MSSQLSERVER            Running
MSSQLServerOLAPService Stopped
ReportServer           Stopped
SQLSERVERAGENT         Running
```

Overall, I would recommend removing those methods from `Get-DbaSqlService`, and just let folks stick with `Stop-Service` and `Start-Service` that are built-in. Truthfully I will likely stick with using those as I'm not going to try and import dbatools just to get a service started, stopped or just restarted.

It may just be my opinion but maintaining extra commands when there is already a built-in way to handle it just seems a bit excessive.

### PR DESCRIPTION
**Pull request by nvarscar**
## Type of Change

 - [x] Bug fix (non-breaking change, fixes #2170, #2158, #2159)
 - [x] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
 
Introducing a few code enhancements and ability to stop Agent service when Engine is being stopped.
### Approach

Added -Force parameter to Stop and Restart functions to deal with Agent services that might prevent Engine services from stopping.
Added an ability to pass -Force into .Stop and .Restart methods of Get-DbaSqlService objects: .Restart($true)
Slightly improved performance by removing second CIM request to the SqlServer namespace.
Get-WmiObject in Update-ServiceStatus was replaced by Get-DbaCmObject. Service commands are now triggered by Invoke-CimMethod.
Replaced Write-Message with Stop-Function where needed.
### Screenshots
image
image
image

### CODE REVIEW

**Comment by nvarscar** [comment]
Forgot to change the branch to dev, sorry about that.

**Comment by potatoqualitee** [comment]
Thanks, bud! Will create tests momentarily.

**Comment by nvarscar** [comment]
I had tests for those commands back in the day, but they were causing contention issues and were removed eventually. Please let me know if I should re-submit them - you can see them here: https://github.com/nvarscar/dbatools-nvarscar/commit/2c363028f7e3f5f618be9c92651aeea70362b4a8

**Comment by potatoqualitee** [comment]
Oh those are really nice! Can you see if they still do? If not, keep as is. If so, perhaps build out a 4th appveyor matrix scenario just dedicated to those?

**Pull request merged**
