### PR TITLE
Get-AgentJobStep Integration Tests

### PR DESCRIPTION
**Pull request by jpomfret**
## Type of Change

 - [ ] Bug fix (non-breaking change, fixes #<enter issue number>)
 - [ ] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [x] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [x] Adding code coverage to existing functionality
 - [x] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
 
Adding some tests on a Saturday morning.

### Screenshots

image

### CODE REVIEW

**Comment by potatoqualitee** [comment]
darn, passed on your side, failed on appveyor

**Comment by jpomfret** [comment]
I'll take a peek .. give me a few

**Comment by jpomfret** [comment]
@potatoqualitee so this ran fine against instance2 (I noticed the other AgnetJob tests were using that). Is this a version issue, instance1 being 2008R2 or is there no agent or something on that instance?

**Comment by joshcorr** [comment]
The SQL Agent is only on Instance2 from what I recall..

**Comment by jpomfret** [comment]
Ok - that would make a lot of sense. It didn't manage to get any job information when running against instance1.

**Comment by wsmelton** [comment]
The only agents that will include Agent are 2016 and 2017 instance. They have Dev Edition, the 2008 one is just express.

**Comment by jpomfret** [comment]
Good deal. Is there documentation on the Appveyor setup, for example versions/editions available? I looked at the Appveyor lab repo but didn't know what I was looking at.

**Comment by potatoqualitee** [comment]
HECK YAHH

**Comment by wsmelton** [comment]
I'm working on documentation for it all. We have some here dbatools.io/appveyor but I'll trying to expand that out a bit more.

**Pull request merged**
