### PR TITLE
add switch for SQL2019

### LINKED ISSUE #6266: Invoke-DbaDiagnosticQuery - Support for SQL Server 2019
Hello (Andre),

Could support for SQL Server 2019 be added to the version check?

Met vr. gr. Ronald

### PR DESCRIPTION
**Pull request by PowerDBAKlaas**
## Type of Change

 - [X] Bug fix (non-breaking change, fixes #6266 )
 - [ ] New feature (non-breaking change, adds functionality, fixes # )
 - [ ] Breaking change (effects multiple commands or functionality, fixes # )
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
 
SQLServerDiagnosticsQuery for SQL 2019 are never executed because the switch statement did not handle version 15. By adding this option, SQLServerDiagnosticsQueries_SQL2019_ will be selected if appropriate.
### Approach

add a line for version 15
### Commands to test

Invoke-DbaDiagnosticQuery on a SQL 2019 instance

### CODE REVIEW

**Comment by wsmelton** [comment]
Please link to the issue....about 90% sure we had one for this one.

**Comment by PowerDBAKlaas** [comment]
@wsmelton I can't find one
there were feature requests and a change in the text parsing

**Comment by wsmelton** [comment]
Your change is not for this one #6266 ?

**Comment by PowerDBAKlaas** [comment]
😲 
what magic did you use?

image

**Comment by wsmelton** [comment]
😉 
image

**Comment by potatoqualitee** [comment]
Merci 😊🇧🇪

**Pull request merged**
