### PR TITLE
Include server certificate information for TDE

### PR DESCRIPTION
**Pull request by awickham10**
## Type of Change

 - [ ] Bug fix (non-breaking change, fixes # )
 - [x] New feature (non-breaking change, adds functionality, fixes # )
 - [ ] Breaking change (effects multiple commands or functionality, fixes # )
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
 
Include server certificate name, last backup date, private key encryption type, owner, expiration date, and object when TDE is enabled instead of just NULL values.

### Approach

If encryption is enabled and the encryption type is a server certificate, include the said information in the returned object.

### Commands to test

```powershell
Get-DbaDbEncryption -SqlInstance MyServerName`
```

### Screenshots

Before
image

After
image

### CODE REVIEW

**Comment by wsmelton** [comment]
Any reason to not also include the thumbprint?

**Comment by awickham10** [comment]
I was conforming to the existing output. Thumbprint could be obtained from $result.Object.Thumbprint if one wanted though.

**Comment by wsmelton** [comment]
I'd say the existing output is voided now that it will return something, we can expand it a bit. Not sure if thumbprint is needed, guess it would depend upon what the output of this command can be used for downstream.

**Comment by awickham10** [comment]
I was trying to keep it consistent between the different types of things (certificates, asymmetric Keys, and symmetric keys). Thumbprint is not applicable to those other things.

**Comment by potatoqualitee** [comment]
looks good! 🏆 thank you both

**Pull request merged**
