### PR TITLE
Adjust Copy-SqlDatabaseMail to enable DBMail on destination

### LINKED ISSUE #868: Copy-SqlDatabaseMail needs to enable database mail as well
### Is this a *feature* OR *bug*:

bug - got a couple complaints about this

### System Details

In Copy-sqlDatabaseMail, use the new Set-DbaSpConfigure (which is still a PR, need to get to it) to do essentially this: sp_configure 'Database Mail XPs', 1;

### PR DESCRIPTION
**Pull request by wsmelton**
Fixes #868 

Changes proposed in this pull request:
 - Added code to first check if DBMail is enabled on source (1) but not enabled on dest (0, zero) server. If not it will enable DBMail on destination server. (Could not use the Get/Set-DbaSpConfigure commands since the dynamic parameter issue...did add a comment to-do that once this is fixed the section of code can be updated).
- Added/Replaced in the messaging system
- Applied most of the format rules we've decided on.

How to test this code: 
- [ ] 
- [ ] 

Has been tested on minimum requirements:
- [ ]  Powershell 3
- [ ]  Windows 7
- [ ]  SQL Server 2000

Has been tested on maximum requirements:
- [ ]  SQL Server vNext
- [ ]  Windows 10
- [ ]  Azure Database

Tests for tester:
- [ ] Working/useful help content, including link to command on dbatools web site
- [ ] All examples work as advertised
- [ ] Does not contain template content
- [ ] Does not contain excessive/unnecessary amounts of comments
- [ ] Works remotely
- [ ] Works locally
- [ ] Works on lower versions or throws error specifying version not supported
- [ ] Works with named instances
- [ ] Works with clustered instances
- [ ] Handles offline/read only databases
- [ ] Supports multiple servers (at the command line or piped from Get-SqlRegisteredServerName)
- [ ] No un-handled errors which stop the command working with multiple servers

### CODE REVIEW

**Comment by potatoqualitee** [comment]
Dude, you're on a frikken roll! Can't tell you how much I appreciate it. Merging & testing. 

btw, Lu is gonna be in Paris this weekend, so I'll get to those dynamic params for you 🙇

**Comment by potatoqualitee** [comment]
Works, hayle yeahhh

**Comment by potatoqualitee** [comment]
Btw, the ultimate output will be a pscustomobject with some info like Source, Destination, Name, Status (and anything else you deem relevant, a timestamp perhaps?)- no write outputs. If you will be working on many of the copy- commands, that will be a necessity by 1.0 and would be awesome to have sooner!

**Comment by wsmelton** [comment]
Would this be a status for each "step" of the process or just for overall status?

e.g. Copying database mail means copying profiles, accounts, and system settings. Is that a custom object that shows something like:
```
Source    Destination    Name            Status
Server1   Server2       Accounts        complete
Server1   Server2       Profiles           complete
Server1   Server2       System Settings complete
```

**Pull request merged**
