### PR TITLE
Restore-DbaDatabase - final touches

### PR DESCRIPTION
**Pull request by ctrlbold**
@Stuart-Moore - I created this one primarily clear the .psd1 from the other one and to easily address the final few things without loading the 60 other comments.

- [ ] There are a few Help params I added so that the tests wouldn't fail. But it looks like -Force is never actually employed to do anything. Please update as needed.
- [x] Please rename UseSourceDirectories to something singular. I use ReuseSourceFolderStructure in Copy-SqlDatabase
- [x] Looks like you sorted the cosmetic comments by @Zhunya

### CODE REVIEW

**Comment by Stuart-Moore** [comment]
Not sure on force! The default is to clobber the existing if they specify WithReplace. Other than that there's nothing else we can really "force"

FIles are either readable or not, and that'll be their permissions setup which we can't force
Don't have permissions Sql instance, can't force that
Are trying to write over datafiles not belonging to the db, can't force that (though we could probably check)

Think that's everything isn't it?

**Comment by ctrlbold** [comment]
hey @Stuart-Moore  - I'm not sure why help was removed. Missing help causes test failures. I've added them back -- please update as appropriate.

If Force is not required, then you can remove it from the params both in the command and where it's referenced later on (but not used) and remove the help for it too. But the rest needs to be updated. Then we should be set. 

Other than that, $file should be $Path to align with the variable that PowerShell usually uses.

**Comment by Stuart-Moore** [comment]
I'm thinking it's probably my cack handed pull and merge to get my existing
changes across.

File -> Path commit is just coming

**Comment by ctrlbold** [comment]
Cool, please refresh -- I was updating help and tests to keep the Tests from failing.

**Comment by Stuart-Moore** [comment]
and just removed force as a parameter

**Comment by ctrlbold** [comment]
WOO! Tests are passing and everything looks great. Gonna do additional manual testing then will merge!

**Comment by Stuart-Moore** [comment]
w00t! I'm around for the next hour or so, so throw anything across that crops up.

**Comment by ctrlbold** [comment]
Excellent! Couple things (lol :/)

- [ ] T-SQL output isnt working for any of m restores so far
- [ ] Can you move NoRecovery to right below Database Owner?
- [ ] Can the files be renamed if the database is renamed? (can wait till 1.1 if you prefer)

```
PS C:\github\dbatools> Restore-DbaDatabase -SqlServer sql2016 -Path "\\dc\sql\SQL2016\Application_Registry_Service_DB_cde90313b64848408b625cb9b083eaf3\FULL\" -WithReplace -DatabaseName foo
WARNING: Restore-DBFromFilteredArray - Microsoft.SqlServer.Management.Smo.FailedOperationException: Restore failed for Server 'sql2016'.  --->
Microsoft.SqlServer.Management.Smo.SmoException: System.Data.SqlClient.SqlError: The file 'C:\Program Files\Microsoft SQL
Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\Application_Registry_Service_DB_cde90313b64848408b625cb9b083eaf3.mdf' cannot be overwritten.  It is being used by database
'Application_Registry_Service_DB_cde90313b64848408b625cb9b083eaf3'.
   at Microsoft.SqlServer.Management.Smo.ExecutionManager.ExecuteNonQueryWithMessage(StringCollection queries, ServerMessageEventHandler dbccMessageHandler, Boolean
errorsAsMessages, Boolean retry)
   at Microsoft.SqlServer.Management.Smo.BackupRestoreBase.ExecuteSql(Server server, StringCollection queries)
   at Microsoft.SqlServer.Management.Smo.Restore.SqlRestore(Server srv)
   --- End of inner exception stack trace ---
   at Microsoft.SqlServer.Management.Smo.Restore.SqlRestore(Server srv)
   at CallSite.Target(Closure , CallSite , Object , Object )
```
- [ ] Anyway to catch the error below before it happens?

image

**Comment by Stuart-Moore** [comment]
All of mine are! I've just made it the default to generate scripts. All the works done, and now we've a nice return object might as well do it at the same time

That's moved on the next push

Yes. It'd have to be just a prefix though. Or you can use the FileMapping parameter?

I'll have a look, thought that should have been caught by the existing db checks

**Comment by Stuart-Moore** [comment]
If I do the prefix what would you like to call it?

DestinationFilePrefix?

**Comment by ctrlbold** [comment]
Closer, but leaves a False hanging out

image

**Comment by ctrlbold** [comment]
DestinationFilePrefix works for me!

**Comment by ctrlbold** [comment]
Dont forget to add help. Mention that if they want total renames, to use a FileMapping

**Comment by Stuart-Moore** [comment]
Done and Done

**Comment by ctrlbold** [comment]
Totally addressed it! Thank you 💃 Will merge once all tests pass.

**Pull request merged**
