### PR TITLE
New command - Export-DbaCertificate

### PR DESCRIPTION
**Pull request by jpomfret**
Changes proposed in this pull request:
 - Add cmdlet for Export-DbaCertificate

How to test this code: 
- [ ] Export-DbaCertificate -SqlServer server1 -Path \\server1\Backups\Certificates
_Prompts for a password and then export all user certificates on server1 to the path (as long as server1 instance account has rights)_

- [ ] Export-DbaCertificate  -SqlServer Server1 -Path \\Server1\Certificates -Certificate CertTDE
_Exports only the certificate named 'CertTDE' from Server1 to the Path specified_

- [ ] $password = ConvertTo-SecureString -AsPlainText "GoodPass1234!!" -force
Export-DbaCertificate  -SqlServer Server1 -Path \\Server1\Certificates -password $password -Databases Database1
_Passes in a password and exports the certificate used to encypt Database1_

Has been tested on minimum requirements:
- [ ]  Powershell 3
- [ ]  Windows 7
- [ ]  SQL Server 2000

Has been tested on maximum requirements:
- [ ]  SQL Server vNext
- [X]  Windows 10
- [ ]  Azure Database

Tests for tester:
- [ ] Working/useful help content, including link to command on dbatools web site
- [ ] All examples work as advertised
- [ ] Does not contain template content
- [ ] Does not contain excessive/unnecessary amounts of comments
- [ ] Works remotely
- [ ] Works locally
- [ ] Works on lower versions or throws error specifying version not supported
- [ ] Works with named instances
- [ ] Works with clustered instances
- [ ] Handles offline/read only databases
- [ ] Supports multiple servers (at the command line or piped from Get-SqlRegisteredServerName)
- [ ] No un-handled errors which stop the command working with multiple servers

### CODE REVIEW

**Comment by jpomfret** [comment]
Not having much luck with dynamic parameters, also not sure if this is the correct way to handle the passwords.

**Comment by Stuart-Moore** [comment]
try removing the $databases parameter and adding
		$databases = $psboundparameters.Databases

in the begin block

Get-DbaProcess is a nice example. TBH, I normally cut and paste from there and delete as needed :)

**Comment by jpomfret** [comment]
Good tips @Stuart-Moore that fixed it, thanks!

**Comment by potatoqualitee** [comment]
awesome work! 🏆 🏆 I'll be merging then submitting a small patch to rename some variables

**Pull request merged**
