### PR TITLE
Get-DbaPrivilege - include 'log on as a service' right

### PR DESCRIPTION
**Pull request by narayana471**
## Type of Change

 - [ ] Bug fix (non-breaking change, fixes # )
 - [ ] New feature (non-breaking change, adds functionality, fixes # )
 - [ ] Breaking change (effects multiple commands or functionality, fixes # )
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1`)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Unit test is included
 - [ ] Documentation
 - [ ] Build system

### CODE REVIEW

**Comment by narayana471** [comment]
@wsmelton  I made small change and re-created this pull request. let me know if this works

**Comment by potatoqualitee** [comment]
Thanks so much for the PR, @narayana471! Unfortunately, the test that failed is related to the changes :/ It appears the results are returning $null, as this is the line that fails `$results | Should Not Be $null`

**Comment by andreasjordan** [comment]
I tested the changes locally and they work - so I don't see why the test fails. Maybe use `-WarningVariable warn` and also test `$warn` for beeing `$null` to see why the commands fails.

**Comment by narayana471** [comment]
Do you think I updated only function "get-DbaPrivilege.ps1" file but not "allcommands.ps1" file. Does that make any difference.

@andreasjordan -- warning variable you recommending. Do I need to update I in file or in build. If in file , can you recommend which section of script requires it.
@potatoqualitee -- I don't see any line "$results | Should Not Be $null" in the script. Is this something in build.  

Sorry, I am not able to get proper error log to troubleshoot this build failure

**Comment by andreasjordan** [comment]
I don't have any time today, but will try to help tomorrow. You don't need to change allcommands.ps1 as it is build automaticly, the tests are in a file called Get-DbaPrivilege.Tests.ps1 in the tests folder.

**Comment by andreasjordan** [comment]
My changed showed this result:

Describe : Get-DbaPrivilege Integration Tests
Context  : Gets Instance Privilege
Name     : It Should not warn
Result   : Failed
Message  : Expected $null, but got [08:55:39][Get-DbaPrivilege] Failure | Value was invalid.
           Parameter name: sddlForm.

Will have a look at the reason...

**Comment by andreasjordan** [comment]
I changed the code and the test and found this:

@('*S-1-5-19', '*S-1-5-20', 'SQLServerReportServerUser$APPVYR-WIN$MSRS10_50.SQL2008R2SP2', 'SQLServer2005SQLBrowserUser$APPVYR-WIN', 'SQLServerSQLAgentUser$APPVYR-WIN$SQL2008R2SP2',           'SQLServerMSASUser$APPVYR-WIN$SQL2016', 'SQLServerMSASUser$APPVYR-WIN$SQL2017', '*S-1-5-80-0', '*S-1-5-80-1019505016-2317702128-3723988348-623047247-3206697967', '*S-1-5-80-1131343884-578742666-314818696-182122926-614429514').

So there are not only SIDs, but also Names of Accounts. And they fail inside of the Convert-SIDToUserName.

So I will change the code to test for "*S-" and only convert those.

**Comment by andreasjordan** [comment]
I opened #7744 - so I will close this. Thanks @narayana471 for the idea and the code.

**Comment by potatoqualitee** [comment]
Reopening per convo in #7744

**Comment by potatoqualitee** [comment]
Thank you both! Now merging 🥳

**Comment by narayana471** [comment]
> I opened #7744 - so I will close this. Thanks @narayana471 for the idea and the code.

Thank you @andreasjordan  for taking care of it. Also , I have one more recommendation similar to get-dbaprivilege. Can you also update for set-DbaPrivilege for "Logon as a Service"
[Set-DbaPrivilege.txt](https://github.com/sqlcollaborative/dbatools/files/7084255/Set-DbaPrivilege.txt)

**Comment by andreasjordan** [comment]
Opened #7748 for that.

**Pull request merged**
