### PR TITLE
Install-DbaInstance - Don't add domain to a local host

### LINKED ISSUE #6976: [Bug] Install-DbaInstance
#### Host used

- [X] powershell.exe
- [ ] ISE
- [ ] VS Code
- [ ] Other (please specify)

#### Errors Received

```powershell
VERBOSE: [17:29:00][Resolve-DbaNetworkName] Resolving SERVERNAME using .NET.Dns GetHostEntry
VERBOSE: [17:29:00][Resolve-DbaNetworkName] Resolving 169.254.0.2 using .NET.Dns GetHostByAddress
VERBOSE: [17:29:09][Get-DbaCmObject] Configuration loaded | Cache disabled: False
VERBOSE: [17:29:09][Get-DbaCmObject] [SERVERNAME] Retrieving Management Information
VERBOSE: [17:29:09][Get-DbaCmObject] [SERVERNAME] Accessing computer using Cim over DCOM
VERBOSE: [17:29:10][Get-DbaCmObject] [SERVERNAME] Accessing computer using Cim over DCOM - Success
VERBOSE: [17:29:10][Resolve-DbaNetworkName] Resolving SERVERNAME.suffix.dns using .NET.Dns GetHostEntry
VERBOSE: [17:29:10][Get-DbaCmObject] Configuration loaded | Cache disabled: False
VERBOSE: [17:29:10][Get-DbaCmObject] [SERVERNAME.suffix.dns] Retrieving Management Information
VERBOSE: [17:29:10][Get-DbaCmObject] [SERVERNAME.suffix.dns] Accessing computer using Cim over WinRM
VERBOSE: [17:29:10][Get-DbaCmObject] [SERVERNAME.suffix.dns] Accessing computer using Cim over WinRM - Success
VERBOSE: [17:29:10][Install-DbaInstance] Looking for installation files in J:\setup.exe on remote machine
SERVERNAME.suffix.dns
VERBOSE: [17:29:10][Get-DbaCmObject] Configuration loaded | Cache disabled: False
VERBOSE: [17:29:10][Get-DbaCmObject] [SERVERNAME.suffix.dns] Retrieving Management Information
VERBOSE: [17:29:10][Get-DbaCmObject] [SERVERNAME.suffix.dns] Accessing computer using Cim over WinRM
VERBOSE: [17:29:12][Get-DbaCmObject] [SERVERNAME.suffix.dns] Accessing computer using Cim over WinRM - Success
VERBOSE: [17:29:12][Write-IniFile] Writing Ini file to
C:\Users\username\AppData\Local\Temp\Configuration_SERVERNAME.suffix.dns_2016.ini

Confirm
Are you sure you want to perform this action?
Performing the operation "Install 2016 from
J:\1033_ENU_LP\x64\Setup\sqlsupport_msi\PFiles\SqlServr\130\Setup\hyvs_tx2\setup.exe" on target
"SERVERNAME.suffix.dns".
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"): Y
VERBOSE: [17:29:21][Get-DbaCmObject] Configuration loaded | Cache disabled: False
VERBOSE: [17:29:21][Get-DbaCmObject] [SERVERNAME.suffix.dns] Retrieving Management Information
VERBOSE: [17:29:21][Get-DbaCmObject] [SERVERNAME.suffix.dns] Accessing computer using Cim over WinRM
VERBOSE: [17:29:21][Get-DbaCmObject] [SERVERNAME.suffix.dns] Accessing computer using Cim over WinRM - Success
VERBOSE: [17:29:22][Invoke-DbaAdvancedInstall] Copying
C:\Users\username\AppData\Local\Temp\Configuration_SERVERNAME.suffix.dns_2016.ini to remote machine into
C:\Users\username\AppData\Local\Temp\
VERBOSE: [17:29:22][Send-File] Starting WinRM copy of
[C:\Users\username\AppData\Local\Temp\Configuration_SERVERNAME.suffix.dns_2016.ini] to
[C:\Users\username\AppData\Local\Temp\]
VERBOSE: [17:29:22][Send-File] WinRM copy of
[C:\Users\username\AppData\Local\Temp\Configuration_SERVERNAME.suffix.dns_2016.ini] to
[C:\Users\username\AppData\Local\Temp\] complete
VERBOSE: [17:29:22][Invoke-DbaAdvancedInstall] Setup starting from
J:\1033_ENU_LP\x64\Setup\sqlsupport_msi\PFiles\SqlServr\130\Setup\hyvs_tx2\setup.exe
VERBOSE: [17:29:22][Invoke-Program] Starting process
[J:\1033_ENU_LP\x64\Setup\sqlsupport_msi\PFiles\SqlServr\130\Setup\hyvs_tx2\setup.exe] with arguments
[/IACCEPTSQLSERVERLICENSETERMS /SAPWD="saPasswordHere"
/CONFIGURATIONFILE="C:\Users\username\AppData\Local\Temp\Configuration_SERVERNAME.suffix.dns_2016.ini"] on
SERVERNAME.suffix.dns through Default protocol
Remove-Item : Cannot find path
'C:\Users\username\AppData\Local\Temp\Configuration_SERVERNAME.suffix.dns_2016.ini' because it does not exist.
At D:\dsi\SQLServer\psmodules\dbatools\allcommands.ps1:41602 char:13
+             Remove-Item $ConfigurationPath
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\usernam...suffix.dns_2016.ini:String) [Remove-Item], ItemNotFoundEx
   ception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand

WARNING: [17:29:22][Invoke-DbaAdvancedInstall] Installation failed with exit code -1073741515. Expand 'Log' property to
 find more details.


ComputerName      : SERVERNAME.suffix.dns
Version           : 13.0
SACredential      : System.Management.Automation.PSCredential
Successful        : False
Restarted         : False
Configuration     : {OPTIONS}
InstanceName      : MyInstanceNameHere
Installer         : J:\1033_ENU_LP\x64\Setup\sqlsupport_msi\PFiles\SqlServr\130\Setup\hyvs_tx2\setup.exe
Port              :
Notes             : {Installation failed with exit code -1073741515. Expand 'Log' property to find more details.}
ExitCode          : -1073741515
Log               :
LogFile           : C:\Program Files\Microsoft SQL Server\130\Setup Bootstrap\Log\Summary.txt
ConfigurationFile : C:\Program Files\Microsoft SQL Server\130\Setup Bootstrap\Log\20201116_134028\ConfigurationFile.ini
```

#### Steps to Reproduce

```powershell
Install-DbaInstance -Verbose -Version 2016 -InstanceName MyInstanceNameHere -InstancePath "E:" -Feature Engine -Configuration @{ SQLCOLLATION = "Latin1_General_CI_AS"; AGTSVCSTARTUPTYPE="Automatic"; SQLSVCSTARTUPTYPE="Automatic" } -AdminAccount "DOMAIN\User1","Domain\User2" -EngineCredential $agentEngineCredential -AgentCredential $agentEngineCredential -PerformVolumeMaintenanceTasks -AuthenticationMode Mixed -SaCredential $saCredential -Path $setupPath
```

#### Expected Behavior

New instance installed on my server

#### Actual Behavior

No instance installed.

I run this command with a PowerShell consol as Admin (run as Administrator).
Before confirmation to install instance or not. I checked content of path: C:\Users\username\AppData\Local\Temp\
And I saw this filename: Configuration_SERVERNAME.suffix.dns_2016.ini
But after confirmation to create this new instance this file is removed.

In the verbose log I saw:
```powershell
VERBOSE: [17:29:22][Invoke-DbaAdvancedInstall] Copying
C:\Users\username\AppData\Local\Temp\Configuration_SERVERNAME.suffix.dns_2016.ini to remote machine into
C:\Users\username\AppData\Local\Temp\
VERBOSE: [17:29:22][Send-File] Starting WinRM copy of
[C:\Users\username\AppData\Local\Temp\Configuration_SERVERNAME.suffix.dns_2016.ini] to
[C:\Users\username\AppData\Local\Temp\]
VERBOSE: [17:29:22][Send-File] WinRM copy of
[C:\Users\username\AppData\Local\Temp\Configuration_SERVERNAME.suffix.dns_2016.ini] to
[C:\Users\username\AppData\Local\Temp\] complete
```
It is strange, because I performed Install-DbaInstance command directly on the server where I wish to have the instance.
It looks like it transfers the file as if I wanted to do the installation remotely.

Is the first instance creation with DBA tools for me :-)
Maybe I put some nonsense in my order in the first place.

### Environmental information
```powershell
PowerShell Version        : 5.1.17763.1490
dbatools latest installed :  1.0.131   (downloaded there are 1 or 2 hours ago)
Culture of OS             : fr-FR
```

### PR DESCRIPTION
**Pull request by andreasjordan**
## Type of Change

 - [x] Bug fix (non-breaking change, fixes #6976  )
 - [ ] New feature (non-breaking change, adds functionality, fixes # )
 - [ ] Breaking change (effects multiple commands or functionality, fixes # )
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1`)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Unit test is included
 - [ ] Documentation
 - [ ] Build system

See https://github.com/sqlcollaborative/dbatools/issues/6976#issuecomment-880562827

### CODE REVIEW

**Review by potatoqualitee — APPROVED** [review]
makes sense

**Comment by andreasjordan** [comment]
But now there is "localhost" in the output - letting all the test fail.
Will try to use `$resolved.ComputerName` instead of `$computer.ComputerName`.

**Comment by potatoqualitee** [comment]
Using Resolve adds .5 seconds to the connect. Should the Resolve be skipped or faked if it it's localhost? Maybe this is something we fix in Resolve, too 🤔

**Comment by andreasjordan** [comment]
Half a second is not much compared to the minutes the installation takes itself.

I would still resolve to change "localhost" so something better:
image

Let's ask @nvarscar - as he is the author.

**Review by nvarscar — APPROVED** [review]
Yup, makes sense. Thanks for tracing that down, I couldn't figure it out.

**Comment by potatoqualitee** [comment]
Thank you both 🥳 !

**Pull request merged**
