### PR TITLE
appveyor msbuild logging

### PR DESCRIPTION
**Pull request by zippy1981**
Changes proposed in this pull request:
 - Logging to figure out what's wrong with the failing build in #1523
 - Appveyor will log msbuild errors
 - 

How to test this code: 
- [ ] Make sure I didn't break anything.
- [ ] Make sure there is msbuild gobblygook in appvoyer.

Has been tested on minimum requirements:
- [ ]  Powershell 3
- [ ]  Windows 7
- [ ]  SQL Server 2000

Has been tested on maximum requirements:
- [ ]  SQL Server vNext
- [ ]  Windows 10
- [ ]  Azure Database

Tests for tester:
- [ ] Working/useful help content, including link to command on dbatools web site
- [ ] All examples work as advertised
- [ ] Does not contain template content
- [ ] Does not contain excessive/unnecessary amounts of comments
- [ ] Works remotely
- [ ] Works locally
- [ ] Works on lower versions or throws error specifying version not supported
- [ ] Works with named instances
- [ ] Works with clustered instances
- [ ] Handles offline/read only databases
- [ ] Supports multiple servers (at the command line or piped from Get-SqlRegisteredServerName)
- [ ] No un-handled errors which stop the command working with multiple servers

### CODE REVIEW

**Comment by zippy1981** [comment]
Dammit its not working hold up on merging. Could use some help debugging why:

* How I'm logging msbuild to appVeyor https://www.appveyor.com/docs/build-phase/
* How I'm trying to do it optionally: https://www.appveyor.com/docs/environment-variables/

**Comment by potatoqualitee** [comment]
hey @SQLDBAWithABeard - can you take a look for zippy?

**Comment by SQLDBAWithABeard** [comment]
have spoken with @zippy1981 He's making changes

**Comment by zippy1981** [comment]
This should be merged. I can do more cleanup, but I'll send those as separate PRs.

This will create a file called `msbuild.log` when the C# code is compiled in the root of the git repo. This is very verbose output and is captured as an artefact. If C# code breaks this will have the errors.

There is a file called msbuild.resp in same folder as the sln. This has commandline switches msbuild picks up. This lowers the verbosity of the console logging and adds detailed file logging.

## Problems

I think these can all be kicked down the road.

### Console output

If I run msbuild manually, the log file gets created and the following console output gets generated:

```
C:\Users\zippy\Documents\dbatools [enhancements/appveyoyMsbuildLogging]> & "C:\WINDOWS\Microsoft.Net\Framework64\v4.0.30319\msbuild.exe" C:\Users\zippy\Documents\dbatools\bin\projects\dbatools\dbatools.sln
Microsoft (R) Build Engine version 4.7.2046.0
[Microsoft .NET Framework, version 4.0.30319.42000]
Copyright (C) Microsoft Corporation. All rights reserved.

Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Users\zippy\Documents\dbatools [enhancements/appveyoyMsbuildLogging]>
```

Any errors and warnings also get outputted. However, this does not happen when I do `Import-Module .\dbatools.psd1` I'd like to fix that. However, having the detailed logs in the file (available from the artifact) means this is not absolutely necessary.

The C# unit tests don't run. I think because `test_scripts:` in the yml file causes everything in `tests` to be ignored.

The appveyorlogger doesn't seem to do anything. I'll keep it in there. That code path is definitely being called.

Ok @FriedrichWeinmann please review and merge.

**Comment by potatoqualitee** [comment]
💃 done didley!

**Pull request merged**
