### PR TITLE
WIP: Add Pipeline Support for New-DbaDbUser

### LINKED ISSUE #6270: [bug] New-DbaDbUser support for input via pipeline
Example #4 for New-DbaDbUser is incorrect.  It states:
`Get-DbaDbUser -SqlInstance sqlserver1 -Database DB1 | New-DbaDbUser -SqlInstance sqlserver2 -Database DB1`

When I attempt to execute similar code, I get "The input object cannot be bound to any parameters for the command either because the command does not take pipeline input or the input and its properties do not match any of the parameters that take pipeline input." 

Which makes sense because none of the params for `New-DbaDbUser` accept pipeline input.
It would be nice if it did in fact accept pipeline input so we could copy one or more users from one DB to another.  In the short term, removing the example from the docs would  be sufficient.

https://github.com/sqlcollaborative/dbatools/blob/master/functions/New-DbaDbUser.ps1

### PR DESCRIPTION
**Pull request by awickham10**
## Type of Change

 - [ ] Bug fix (non-breaking change, fixes # )
 - [x] New feature (non-breaking change, adds functionality, fixes #6270 )
 - [ ] Breaking change (effects multiple commands or functionality, fixes # )
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [x] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
 
Add the ability to pipe databases and users to New-DbaDbUser.

### Approach
Piping Database
- Prohibit use of Database parameter
- Default Database variable to $InputObject.Name

Piping User
- Prohibit use of Username parameter
- Default Username variable to $InputObject.Name
- Default Login variable to $InputObject.Login

### Commands to test

Testing commands available in help.

### CODE REVIEW

**Comment by wsmelton** [comment]
@awickham10 those test are failing because they involve use of `New-DbaDbUser`

If you want to have our test only run a given command, in your commit just use this as the commit message: `{do New-DbaDbUser}`  and that should only have that test run in Appveyor environment.

**Comment by awickham10** [comment]
Good to know, thanks!

**Comment by potatoqualitee** [comment]
hey @awickham10 - is this still a draft or ready to merge? thank you 💯

**Comment by potatoqualitee** [comment]
Haven't heard back on this. In order to avoid dissuading potential contributors seeing old PRs and thinking that we don't merge, I will close this but welcome the PR back when it is no longer in draft 💯

**Pull request closed without merging**
