### PR TITLE
Measure-DbaBackupThroughtput, various fixes

### LINKED ISSUE #1642: Measure-DbaBackupThroughput is inaccurate
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [ ] *feature* 
- [x] *bug*:

## Details

It's hard for me to fix this one because

* I'm bad at math
* All of the backups in my lab are so fast, I assumed the results were correct

Trying this in a prod environment showed that it just..doesn't work. Can someone who knows math and has fat backups please fix? 

image

### PR DESCRIPTION
**Pull request by niphlod**
Fixes #1642

Changes proposed in this pull request:
- Introduced DeviceType for the unfortunate like me in need to fetch the
correct history
- Adopted new messaging system
- Refactored calculation (div instead of mod)
- adopted dba* types where feasible

PS: processing servers with lots of backups is painfully slow. That's
because get-dbabackuphistory can't filter by type ATM, so you get back
full,incr,log and then this cmdlet filters them out. I'll see what can
be done later.

### CODE REVIEW

**Comment by potatoqualitee** [comment]
YESSSSSSSSS thank you!

I'm getting no results, however 

image

**Comment by niphlod** [comment]
I'm experimenting with changes to history too, last commit should be fine

**Comment by potatoqualitee** [comment]
heck yes! that looks SO GOOD! Thanks so much 💯 💯💯

**Comment by niphlod** [comment]
Need to push a PR to get-dbadatabasehistory that in corner-cases doesn't work, then I'll push another one to fix this one

**Comment by potatoqualitee** [comment]
(sorry got a little excited, i just love this command and it looks so good)

**Comment by potatoqualitee** [comment]
which PR is that @niphlod ?

**Comment by niphlod** [comment]
Incoming....

**Comment by niphlod** [comment]
@potatoqualitee : this one https://github.com/sqlcollaborative/dbatools/pull/1648

**Comment by niphlod** [comment]
@potatoqualitee : this one https://github.com/sqlcollaborative/dbatools/pull/1649 is the latest. And finally nippy can measure throughput on its monstrous history without waiting half an hour for results.

**Pull request merged**
