### PR TITLE
Azure support added to test-dbalastbackup

### PR DESCRIPTION
**Pull request by Stuart-Moore**
Fixes # 

Changes proposed in this pull request:
 - Now support Azure backups
 - AzureCredential parameter added 
 - Changed logic to copy with azure backups. Changed from drop through else to an if 

How to test this code: 
- [ ] 
- [ ] 

Has been tested on minimum requirements:
- [ ]  Powershell 3
- [ ]  Windows 7
- [ ]  SQL Server 2000

Has been tested on maximum requirements:
- [ ]  SQL Server vNext
- [ ]  Windows 10
- [ ]  Azure Database

Tests for tester:
- [ ] Working/useful help content, including link to command on dbatools web site
- [ ] All examples work as advertised
- [ ] Does not contain template content
- [ ] Does not contain excessive/unnecessary amounts of comments
- [ ] Works remotely
- [ ] Works locally
- [ ] Works on lower versions or throws error specifying version not supported
- [ ] Works with named instances
- [ ] Works with clustered instances
- [ ] Handles offline/read only databases
- [ ] Supports multiple servers (at the command line or piped from Get-SqlRegisteredServerName)
- [ ] No un-handled errors which stop the command working with multiple servers

### CODE REVIEW

**Comment by potatoqualitee** [comment]
ouuu, can you tell me how to test this, @Stuart-Moore ? I have an Azure account

**Comment by Stuart-Moore** [comment]
Backup a database to Azure

Then run Test-DbaLastBackup against that DB, the only difference it that you need to provide the AzureCredential name

(that assumes you've set sql server and Azure up for Azure backups? MS have an article, but Microsoft.com is down for me here so I can't provided a link)

**Comment by potatoqualitee** [comment]
you tha best, @ConstantineK !

**Comment by potatoqualitee** [comment]
merged AF!

**Pull request merged**
