### PR TITLE
Backup information

### PR DESCRIPTION
**Pull request by Stuart-Moore**
Don't merge yet, just putting the PR in now so I can have a review on the backuphistory type changes (paging @FriedrichWeinmann  or @zippy1981 )

Tests are failing because ideally I'd like to use 2008 and 2016 instances to prove stuff, so hoping someone's got a cunning scheme to do so.

## Type of Change

 - [ ] Bug fix (non-breaking change, fixes #<enter issue number>)
 - [x] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [x] Pester test is included
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
Add an option to build backup history up from file information if source instance isn't available.
Also allows the backup history to be built up over time, so can most files overnight, and then just add logs as neede
It can also be exported for storing or moving.

### Approach
New function Get-DbaBackupInformation to scan a bunch of files and build up a dbatools.BackupHistory object

Fixed Read-DbaBackupHeader so it doesn't have an embedded datatable in the middle

Changed dbatools.BackupHistory so LSNs are longs rather thant BigInts as the latter does CliXml or Json in a nice way

Get-FilteredRestoreFile is less picky about the names of BackupTypes, so saves more workarounds for now

### Commands to test
```
$Date = Get-Date
$history = Get-ChildItem c:\backups -recurse | Get-DbaBackupInformation -SqlInstance Server1
#wait some time
$history +=  Get-ChildItem c:\backups -recurse | Where-object {$_.LastWriteTime -gt $Date} | Get-DbaBackupInformation -SqlInstance Server1
$history | ConvertTo-Json -Depth 3 | Out-File c:\backuphistory.json
#Use method of choice to copy file to another machine
$history = Get-Content c:\backuphistory.json -raw | ConvertFrom-Json
$history | Restore-DbaDatabase -SqlInstance Server2 -TrustDbBackupHistory
```

### CODE REVIEW

**Comment by FriedrichWeinmann** [comment]
Originally, I used long for that class. Long is not large enough for LSNs, which is why I moved to BigInt.

**Comment by Stuart-Moore** [comment]
Dang. I'll change it back then. Had forgotten how large number(25,0) is

Means that porting backup history will be with Export-CliXml then. Not that
much of an issue, just getting people to do it with JSON meant I could dump
it into the test rig/unit tests for support calls.

**Comment by niphlod** [comment]
well, we could have  stringifier somewhere.

**Comment by Stuart-Moore** [comment]
Some Case Sensitive weirdness has occured with git, so closing this and opening a new PR

**Pull request closed without merging**
