### PR TITLE
Include a sample for restoring a single database from a bak file and r…

### PR DESCRIPTION
**Pull request by Splaxi**
…ename physical and logical files.

## Type of Change

 - [ ] Bug fix (non-breaking change, fixes #<enter issue number>)
 - [ ] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] Nunit test is included
 - [X] Documentation
 - [ ] Build system
 

### Purpose
 
Update example to include a simple use case for restoring a database with a new name and having the physical files and logical filenames updated.

### CODE REVIEW

**Comment by potatoqualitee** [comment]
Thanks motz! Will merge once tests pass 👍

**Comment by Splaxi** [comment]
I can see that I have a minor typo between the example code and explanation. The file name isn't the same...

**Comment by wsmelton** [comment]
One minor thing, sentences need to reside on one line and not be broken up manually. So your description of that example should be two lines.

**Comment by Splaxi** [comment]
Will close this and create a new, where I try to do it right :)

**Pull request closed without merging**
