### PR TITLE
Update Test-DbaPowerPlan and Set-DbaPowerPlan 

### LINKED ISSUE #4461: Fix PSAvoidUsingWMICmdlet
### Summary of new feature

There are 4 cmdlets breaking the PSAvoidUsingWMICmdlet script analyzer rule, which could be impacting cmdlet use as well as our BOH. This rule states that CIM cmdlets should be used instead of the older WMI cmdlets
```
ScriptName               Line Extent
----------               ---- ------
Get-DbaCmObject.ps1       310 Get-WmiObject @parameters
Reset-DbaAdmin.ps1        204 Get-WmiObject -Class Win32_NetworkAdapterConfiguration -Filter IPEnabled=TRUE -Compute...
Set-DbaPowerPlan.ps1       93 Get-WmiObject -Namespace Root\CIMV2\Power -ComputerName $ipaddr -Query $query -ErrorAc...
Set-DbaPowerPlan.ps1      116 Get-WmiObject -Name root\cimv2\power -ComputerName $ipaddr -Class Win32_PowerPlan -Fil...
Test-DbaCmConnection.ps1  177 Get-WmiObject -ComputerName $ComputerName -Credential $Credential -Class Win32_Operati...
Test-DbaCmConnection.ps1  210 Get-WmiObject -Class Win32_OperatingSystem -ErrorAction Stop
````

See [PSAvoidUsingWMICmdlet.md](https://github.com/PowerShell/PSScriptAnalyzer/blob/development/RuleDocumentation/AvoidUsingWMICmdlet.md) for more details

### Proposed technical details (if applicable)
Since these are all `Get-WmiObject` cmdlets it seems that it would easy to replace with `Get-CimInstance` cmdlets. However, I saw an [old post in trello](https://trello.com/c/XbStF12s) that suggested making this change was not possible because of support for older clients. Thoughts @cl and @wsmelton ?

### PR DESCRIPTION
**Pull request by sqllensman**
## Type of Change

 - [X] Bug fix (non-breaking change, partially fixes #4461 )
 - [ ] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [X] Pester test is included
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
The functions Test-DbaPowerPlan and Set-DbaPowerPlan were no consistent in how the use CIM commands and were 
1. Not using Get-DbaCmObject  to retrieve information
2. Using Get-WmiObject to update information

The inconsistency meant that some Servers, the function Get-DbaOperatingSystem was able to return the PowerPlan settings but Test-DbaPowerPlan failed.

Modified the commands to have consistent approach that matches style of other commands
Also corrected issue with Piping of Test-DbaPowerPlan to Set-DbaPowerPlan
This was not working as was looking for Server rather than ComputerName 

### Approach
Commands changed to use Get-DbaCmObject, New-CimSession abd Get-CIMInstance

Also added Integration tests and fixed minor issue in Get-DbaCmObject referring to old command name

### Commands to test
Test-DbaPowerPlan
Set-DbaPowerPlan

### CODE REVIEW

**Comment by wsmelton** [comment]
Please show that they work against older versions of PS and Windows Server (my minimum requirement for approval would be 2008...as 2003 they are just out of luck :grin: ).

**Comment by sqllensman** [comment]
2008R2 is minimum as the value is not returned for earlier versions.  Fixes to Get-DbaOperatingSystem needed to take account of this.

**Comment by sqllensman** [comment]
I will run tests tomorrow against various versions from 2003 to 2016 
Please don't merge until updated with results

**Comment by potatoqualitee** [comment]
works! awesome job, thank you both!

**Pull request merged**
