### PR TITLE
Improve repairorphanuser

### PR DESCRIPTION
**Pull request by ClaudioESSilva**
Only validate UserType SqlLogin and SqlUser
- Before this change an database user without login will be seen as
orphaned user.

### CODE REVIEW

**Comment by ClaudioESSilva** [comment]
Do address the issue that @Staggerlee011 found. 

@Staggerlee011 can you please test it? Thanks!

**Comment by ctrlbold** [comment]
@Staggerlee011 messaged me and said that they show up as sqlusers so this does not address the issue

T-SQL - CREATE USER Staggerlee WITHOUT LOGIN

image

**Comment by ClaudioESSilva** [comment]
The screenshot only show all users from avatar database. That is right because no filter was applied. 
The issue was addressed by filtering the users when getting all eligible. 

Please do the test using the -WhatIf as you have done before.

**Comment by ClaudioESSilva** [comment]
To test use the T-SQL script (at the end) to generate:
 - Database named 'dbOrphanUsers'
 - 2 logins
   - UserOrphan
   - UserNOTOrphan
 - 3 users (one without login)
   - UserOrphan
   - UserNOTOrphan
   - UserWithoutLogin

You can use the following code to view the list (SIDLength is the one that differs):
```
$srv  = Connect-DbaSqlServer -SqlServer sql2008
$srv.Databases["dbOrphanUsers"].Users | Select-Object Name, LoginType, UserType, State, HasDBAccess, AuthenticationType, Login, @{ Name="SIDLength"; Expression={$_.Sid.Length}} | Format-Table
```

Then, run the command on this database and **ONLY** UserOrphan should be removed.
`Remove-SqlOrphanUser -SqlServer sql2008 -Databases dbOrphanUsers `

**T-SQL script**
````
USE [master]
GO

CREATE DATABASE dbOrphanUsers
GO


CREATE LOGIN [UserOrphan] WITH PASSWORD=N'123', DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

USE [dbOrphanUsers]
GO
CREATE USER [UserOrphan] FOR LOGIN [UserOrphan]
GO



/* Drop login so user TestOrphan1 will be orphan */
USE [master]
GO
DROP LOGIN [UserOrphan]
GO


CREATE LOGIN [UserNOTOrphan] WITH PASSWORD=N'123', DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

/* This is a user that will not be orphan */
USE [dbOrphanUsers]
GO
CREATE USER [UserNOTOrphan] FOR LOGIN [UserNOTOrphan]
GO

/* Create a user without login. NOTE: This is **NOT** a orphan user */
USE [dbOrphanUsers]
GO
CREATE USER [UserWithoutLogin] WITHOUT LOGIN WITH DEFAULT_SCHEMA=[dbo]
GO
````

**Pull request merged**
