### PR TITLE
Find-DbaCommand, connects to #725

### PR DESCRIPTION
**Pull request by niphlod**
adds proposed enhancement discussed in #725

Changes proposed in this pull request:
 - filter by multiple tags (in "AND")
 - better handling for shouldprocess
 - added examples
 - better tag normalization

### CODE REVIEW

**Comment by ctrlbold** [comment]
👍

**Comment by ctrlbold** [comment]
You saw how many commands got tagged? 💃

**Comment by niphlod** [comment]
I saw that "untitled2.ps1" was probably missing an -encoding utf8    (👎 for me)

**Comment by ctrlbold** [comment]
yah, i fixed! LOL. I renamed it to Tag-Command and put it in internal for future use.

https://github.com/sqlcollaborative/dbatools/blob/development/internal/Tag-Command.ps1

**Pull request merged**
