### PR TITLE
Remove-DbaDatabaseSnapshot, fixes #1634

### LINKED ISSUE #1634: Remove-DbaDatabaseSnapshot, doesn't work when specific -Database is passed
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [ ] *feature* 
- [x] *bug*:

----

Doesn't work when a specific -Database is passed

### PR DESCRIPTION
**Pull request by niphlod**
Fixes #1634 

Changes proposed in this pull request:
 - normalized output properties
 - changed filter logic to match the database parameter

### CODE REVIEW

**Comment by gbargsley** [comment]
Snapshot listed is not being removed.

image

**Comment by niphlod** [comment]
that's good. -Database is when you want to remove snapshots BASED on that database (from the names, you should then pass "DBAdmin")

**Comment by gbargsley** [comment]
Not sure I follow the logic.  If I pass the parent database will all snapshots be deleted?  What if I only want a specific one deleted?

**Comment by niphlod** [comment]
Then you use -snapshot

Il 10 lug 2017 7:57 PM, "gbargsley" <notifications@github.com> ha scritto:

Not sure I follow the logic. If I pass the parent database will all
snapshots be deleted? What if I only want a specific one deleted?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/sqlcollaborative/dbatools/pull/1635#issuecomment-314184899>,
or mute the thread

**Comment by potatoqualitee** [comment]
Agreed, @wsmelton ! I'd wondered that and couldn't fix it because I didn't know what it meant. Thank you for bringing it up. @niphlod - once that is fixed, I'll merge.

**Comment by niphlod** [comment]
help changes come from https://github.com/sqlcollaborative/dbatools/commit/890e9675afde385f5d4b623120fcf435ae40c482 , I think it just slipped in as a copy-paste error. Reverting to the original in a sec

**Comment by niphlod** [comment]
done @potatoqualitee , cc @wsmelton

**Comment by potatoqualitee** [comment]
baww yeahhh

**Pull request merged**
