### PR TITLE
Update-DbaBuildReference: Add parameter LocalFile for offline update

### LINKED ISSUE #7957: Update-DbaBuildReference: Add parameter LocalFile for offline update
### Summarize Functionality

Add a parameter `-LocalFile` like in `Save-DbaCommunitySoftware` to support environments without internet connection to be able to update the local cache of the build reference from a file share.

### Is there a command that is similiar or close to what you are looking for?

No

### Technical Details

Will open a pull request for that...

### PR DESCRIPTION
**Pull request by andreasjordan**
## Type of Change

 - [ ] Bug fix (non-breaking change, fixes # )
 - [x] New feature (non-breaking change, adds functionality, fixes #7957 )
 - [ ] Breaking change (effects multiple commands or functionality, fixes # )
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1`)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Unit test is included
 - [ ] Documentation
 - [ ] Build system

### Purpose
Better support for offline environments.

### Approach
Add parameter to have a file to update from.

I changed some variable names to better reflect thier content. I'm open to change the names if someone has better suggestions.

### CODE REVIEW

**Comment by andreasjordan** [comment]
Hi @potatoqualitee - do you see the reason why "sets up a mirror" is failing? It only says "Expected 'TCP://dockersql2:5022', but got $null".

**Comment by potatoqualitee** [comment]
Quite possibly, the certs expired since it's unrelated and failing in a couple places. I'll take a look tonight!

**Comment by potatoqualitee** [comment]
image

yep, i need to fix

**Comment by potatoqualitee** [comment]
fixed the cert issue! it's now valid for 100 years 😊  Code looks good, thank you

**Pull request merged**
