### PR TITLE
DbaInstanceParameter - Added support for connection strings

### PR DESCRIPTION
**Pull request by FriedrichWeinmann**
## Type of Change

 - [ ] Bug fix (non-breaking change, fixes #<enter issue number>)
 - [x] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [x] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Pester test is included

## What it does

 - Adds support for connection strings as input to the `DbaInstanceParameter`. Must include a server target. The connection will use the connection string, other functions get their usual properties (ComputerName, InstanceName, Port, ...)
 - Adds support for sql notation server names (such as `[Server\Instance]`)
Braces used to fail interpretation.
 - Adds support for named pipe path notations (e.g.: `\\.\pipe\MSSQL$SQLEXPRESS\sql\query`)

### CODE REVIEW

**Comment by wsmelton** [comment]
Verified brackets are parsed now...
image

Also successful with `[DbaInstance]"[server_01\instance1]"` and `[DbaInstance]"[server.01\instance1]"`. Confirmed same result if using the old parameter type `DbaInstanceParameter` as well.

image

**Comment by wsmelton** [comment]
Testing the connection string...tried using `New-DbaSqlConnectionString` to actually generate the string for me but seems it has some extra stuff being added that (1) is not needed but (2) exceeds some character limit.

image

So stripped it down to only what I wanted and seemed to fail connection:

image

Maybe I'm misinterpreting what type of string you are supporting?

**Comment by FriedrichWeinmann** [comment]
Actually, the parameterclass is working as designed ... just forgot to look into how it's implemented in `Connect-DbaSqlServer`
Run
`[DbaInstance]$string` to check out its interpretation.
Looking into where that function fails how.

**Comment by FriedrichWeinmann** [comment]
Ah, mystery solved:
`Connect-DbaSqlServer` doesn't use `[DbaInstanceParameter]` so any refinements I add to the parameter class will not carry over to it. Gonna check out whether that's how it is supposed to be.

**Comment by potatoqualitee** [comment]
Yes, you can add it back @FriedrichWeinmann - I took it out temporarily to make that command work with Named Pipes connections. When you add it back, that'll also give appveyor another chance to process the tests to ensure it all works.

**Comment by potatoqualitee** [comment]
confirmed :( @FriedrichWeinmann whatever happened here made the tests infinitely wait/fail

image

**Comment by potatoqualitee** [comment]
heck yah!

**Pull request merged**
