### PR TITLE
Add IntegrationTests for Some Get Verbs

### PR DESCRIPTION
**Pull request by joshcorr**
## Type of Change

 - [ ] Bug fix (non-breaking change, fixes #<enter issue number>)
 - [ ] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [X] Adding code coverage to existing functionality
 - [X] Pester test is included
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
 
Include Pester Tests for several Get cmdlets which previously didn't have Integration tests

### Approach

Create any objects that need to be retrieved using `Get-`
Get the object and validate values
Drop any objects that were created to test.

### Commands to test

The tests for each cmdlet can be ran, or run the entire suite of tests should pass.

### CODE REVIEW

**Comment by potatoqualitee** [comment]
dream come true 😍  thank you. there was one failure, unsure if it's unrelated, so i merged from dev to spark off another round of tests

**Comment by joshcorr** [comment]
Cool. I will take a look there are still a few more tests that I have as part of the PR. It is odd that some of the tests that never failed the last two or three times failed on this most recent run.

**Comment by joshcorr** [comment]
That last tweak didn't work. I am going to work on some more tests to add to this PR and will re-run in a while.

**Comment by joshcorr** [comment]
Everything on this PR looks to be good now. Seems like I had some issues with Instance3 as well as some tests that worked in my test, but not in CI. Please feel free to merge. Still have quiet a few tests, but will do them in future PRs.

**Comment by potatoqualitee** [comment]
thank you! 🙇

**Pull request merged**
