### PR TITLE
added cu9 for 2019

### PR DESCRIPTION
**Pull request by niphlod**
added cu9 for 2019 in buildref

### CODE REVIEW

**Review by eriund — COMMENTED** [review]
This is just perfect.

**Review by eriund — APPROVED** [review]
This change/update would help a lot.

**Comment by potatoqualitee** [comment]
So sorry for the delay. The lockdown blows and I've been too anxious to check the repo. Will merge now ❤️

**Comment by potatoqualitee** [comment]
Will publish to Gallery once tests pass.

**Comment by eriund** [comment]
Is there some problem with the merge? The update is still not visible in dbatolls Build ref. 👍

**Pull request merged**
