### PR TITLE
fixes #3916

### LINKED ISSUE #3916: Databases with same name on multiple instances
## Steps to Reproduce

- 2 SQL Server instances (non related, different systems/servers) – inst1 e inst2;
- Both instances have SharePoint BD’s, thus you have BD’s  with common names (i.e.: SharePoint_Config, WSS_Logging, WSS_Content, etc.)

powershell
```
#Backup history timeline:
Get-DbaBackupHistory -SqlInstance 'SQL01','SQL02' -Since '2018-08-18 00:00' | ConvertTo-DbaTimeline | Out-File C:\temp\Get-DbaBackupHistory.html -Encoding ascii 

```

## Expected Behavior

The expected behavior should be a timeline for each database, with no aggregation by database name or an added column to the results with the servername/instancename to separate the databases.

## Actual Behavior

Has you can see, looking at the chart it seems that **WSS_Logging** database had **2 Full Backup** on the same day at different hours. The reality is that both SQL Server instances have a  WSS_Logging database and different schedules for the Full Backup on the same weekday.

image

## Final Notes
GREAT WORK!!!!! Kudos for this... 🥇

### PR DESCRIPTION
**Pull request by marcingminski**
## Type of Change

 - [x ] Bug fix (non-breaking change, fixes #3916 )
 - [ ] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
 
Fix an issue
### Approach

Added SqlInstance in front of the item name in the following format: "[SqlInstance] Job Name" for `Get-DbaAgentJobHistory`
and "[SqlInstance] Database Name" for `Get-DbaBackupHistory`
### Commands to test

```
Get-DbaAgentJobHistory -SqlInstance sql-1,sql-2,sql-3 -ExcludeJobSteps | ConvertTo-DbaTimeline | Out-File C:\temp\DbaAgentJobHistory.html -Encoding ascii

Get-DbaBackupHistory -SqlInstance sql-1,sql-2,sql-3 | ConvertTo-DbaTimeline | Out-File C:\temp\DbaAgentJobHistory.html -Encoding ascii
```

### Screenshots
image
(apologies for the vague server names - its docker...)

### Learning
I learnt how to use $dbatools_dotsourcemodule and run in "dev" mode.

### CODE REVIEW

**Comment by marcingminski** [comment]
not sure why there's a conflict, this is just a diff before/after change.... :(

**Comment by potatoqualitee** [comment]
please check now

**Comment by marcingminski** [comment]
ooh... this tells me my version wasn't the latest... ok apologies, I did git fetch upstream... I will see what I did wrong. The code looks good now, thank you!

**Comment by potatoqualitee** [comment]
i thought that may be the case. i am concerned that someone made a change that fixed something then it was overwritten, would you be able to do a comparison to ensure? thanks so much 🙇

**Comment by marcingminski** [comment]
I can see some formatting and `Diagnostics.CodeAnalysis...` added recently. Ok, disregard this PR please I will re-submit new PR, this time with the correct version. Apologies.

**Comment by potatoqualitee** [comment]
k yeah, there were some examples we updated too, will close and await new PR!

**Pull request closed without merging**
