### PR TITLE
Correct EOL date for 2014 SP2

### LINKED ISSUE #5060: Build Reference has wrong EOL date for 2014 SP2
### Before submitting a bug report:

- [X] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [X] Verified this bug is not already reported in an issue
- [X] Verified errors are not related to permissions
- [X] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)
- [ ] If issue is with `Copy-DbaDatabase`, using `Backup-DbaDatabase | Restore-DbaDatabase` still does not work

Note that we do not have the resources to make `Copy-DbaDatabase` work in every environment. Instead, we try to ensure Backup & Restore work in your enviornment.

## Steps to Reproduce
dbatools-buildref-index.json lists SQL Server version 12.0.5000 (2014 SP2) with an EOL date of 2024-07-09.

[Microsoft Product Lifecycle documentation](https://support.microsoft.com/en-au/lifecycle/search?alpha=SQL%20Server%202014%20Service%20Pack%202) shows this version's End of Support as 2020-01-14

image

## Expected Behavior
`SupportedUntil` should match Microsoft documentation

## Actual Behavior
See above

### PR DESCRIPTION
**Pull request by alevyinroc**
## Type of Change

 - [X] Bug fix (non-breaking change, fixes #5060)
 - [ ] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
 
Correct `SupportedUntil` for SQL Server 2014 SP2
### Approach

Update build reference with correct date from documentation

### CODE REVIEW

**Comment by alevyinroc** [comment]
My VSCode settings reformatted everything, hold on merging this until I can fix that

**Comment by alevyinroc** [comment]
It looks like the previous commit, 489845a312122dedf22c11a95342ed85f3c4e979, also did a wide-scale reformat. I think the workspace settings that tag along w/ the project were applied by VSCode on my end tonight, but at this point I'm not sure if I did something wrong here or what.

**Comment by nvarscar** [comment]
Your commit seems to have proper indentation, it's all good 👍

**Comment by potatoqualitee** [comment]
thank you both 🙇

**Pull request merged**
