### PR TITLE
Return more properties about Login

### PR DESCRIPTION
**Pull request by sqllensman**
## Type of Change

 - [ ] Bug fix (non-breaking change, fixes #<enter issue number>)
 - [X] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [X] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
Implement the changes for Feature request #5732 

### Approach
Added option to use SQL Query to get LoginProperty information for
BadPasswordCount
BadPasswordTime
DaysUntilExpiration
HistoryLength
IsMustChange
LockoutTime
PasswordHash
PasswordLastSetTime

### Commands to test
Get-DbaLogin

### CODE REVIEW

**Comment by potatoqualitee** [comment]
great idea! how about `-Detailed` instead of `GetLoginProperty` ?

**Comment by sqllensman** [comment]
Ok.
I will update now

**Comment by sqllensman** [comment]
The ealier Pull request to fix #5840 should have failed as it was missing the $FilePath parameter at Line 418

**Comment by wsmelton** [comment]
I disagree with the detailed parameter here. We spent previous time removing that from every command moving toward 1.0.0.

Why are we know reverting back to it?

**Comment by sqllensman** [comment]
I have no opinion either way.
Only reason I added a switch is avoid overhead of running query for every login if information is not wanted.

**Comment by potatoqualitee** [comment]
Detailed was used without thought or patterns in previous commands. In this case, like Patrick mentioned, it's being used to avoid the overhead of running a query for every login if information is not wanted. 

In this case, Detailed is justified and intentional.

**Comment by wsmelton** [comment]
So switch it to use SMO instead of the query. I haven't verified all but some of those can be returned via SMO: https://docs.microsoft.com/en-us/dotnet/api/microsoft.sqlserver.management.smo.login.passwordhashalgorithm?view=sql-smo-140.17283.0

**Pull request merged**
