### PR TITLE
appveyor.pester, reorder import logic

### PR DESCRIPTION
**Pull request by niphlod**
## Type of Change

 - [x] Bug fix (non-breaking change, fixes #<enter issue number>)
 - [ ] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 
### Purpose
Avoid funny things like the ones happened during #2746

### Approach
Seemingly importing the psm1 doesn't assure a correct DLL module loading (since roughly https://github.com/sqlcollaborative/dbatools/pull/2656 ). We need it to be able to run integrationtests for internal functions so....to sidestep the problem,  we import the psd1 first, to assure DLL is correctly loaded, and then the psm1 file.

### CODE REVIEW

**Comment by potatoqualitee** [comment]
hey niph, you shouldnt need to disablenamechecking anymore, even for psm1 imports. We are aligned again.

**Comment by niphlod** [comment]
those are kinda unexpected, the only change made is on line 51, loading the psm1 after the psd1, which locally doesn't show any errors.

**Comment by niphlod** [comment]
let's see if touching a bit restores the original "behaviour"

**Comment by potatoqualitee** [comment]
Right? I thought that was weird as hell too. Do me a favor and sync with current dev branch which has some of your other changes.

**Comment by niphlod** [comment]
nope, this is apparently completely skipping psm1 import, 'cause everything depending on internals is failing. Boy oh boy did I not understand ANYTHING on what we do on importing the module. At this point 'm more curious than anything, and I'll do the psm1 before the psd1, just to see what happens.

**Comment by niphlod** [comment]
@potatoqualitee : it now seems to hold on fine.
I sooooooo hate this (the solution is the exact opposite of what I thought), but it solved the problem, even with the original Find-DbaOrphanedFile.Tests.ps1

**Comment by potatoqualitee** [comment]
nice@ merging. and yeah, super weird!

**Pull request merged**
