### PR TITLE
Set privileges even if no users currently have them. (Issue #6351)

### LINKED ISSUE #6351: functions/Set-DbaPrivilege.ps1 says nt service\mssqlserver already has LPIM when it doesn't. Silent error output[Bug]
### Environmental information

```
#### PowerShell version:

Name                           Value                                                                                                         
----                           -----                                                                                                         
PSVersion                      5.1.14393.3383                                                                                                
PSEdition                      Desktop                                                                                                       
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                       
BuildVersion                   10.0.14393.3383                                                                                               
CLRVersion                     4.0.30319.42000                                                                                               
WSManStackVersion              3.0                                                                                                           
PSRemotingProtocolVersion      2.3                                                                                                           
SerializationVersion           1.1.0.1                                                                                                       




#### dbatools Module version:


Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.90\dbatools.psd1
Version : 1.0.90




```

#### SQL Server: 

Microsoft SQL Server 2016 (SP2-CU11) (KB4527378) - 13.0.5598.27 (X64)

#### Host used

- [ x] powershell.exe
- [ ] ISE
- [ ] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [x ] Still buggy in powershell.exe

#### Errors Received

```


PSMessageDetails      : 
Exception             : System.Management.Automation.MethodInvocationException: Exception calling "QueryCimRMInstance" 
                        with "4" argument(s): "WinRM cannot process the request. The following error occurred while 
                        using Kerberos authentication: Cannot find the computer <xxxxx>. Verify that 
                        the computer exists on the network and that the name provided is spelled correctly." ---> 
                        Microsoft.Management.Infrastructure.CimException: WinRM cannot process the request. The 
                        following error occurred while using Kerberos authentication: Cannot find the computer 
                        <xxxxx>. Verify that the computer exists on the network and that the name 
                        provided is spelled correctly.
                           at 
                        Microsoft.Management.Infrastructure.Internal.Operations.CimSyncEnumeratorBase`1.MoveNext()
                           at 
                        Sqlcollaborative.Dbatools.Connection.ManagementConnection.QueryCimRMInstance(PSCredential 
                        Credential, String Query, String Dialect, String Namespace) in 
                        D:\Code\Github\dbatools\bin\projects\dbatools\dbatools\Connection\ManagementConnection.cs:line 
                        907
                           at CallSite.Target(Closure , CallSite , Object , Object , String , String , String )
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext 
                        funcContext, Exception exception)
                           at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame 
                        frame)
                           at 
                        System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame 
                        frame)
                           at 
                        System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame 
                        frame)
TargetObject          : 
CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
FullyQualifiedErrorId : CimException
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Get-DbaCmObject<Process>, C:\Program 
                        Files\WindowsPowerShell\Modules\dbatools\1.0.90\allcommands.ps1: line 20443
                        at Get-DbaService<Process>, C:\Program 
                        Files\WindowsPowerShell\Modules\dbatools\1.0.90\allcommands.ps1: line 33940
                        at Set-DbaPrivilege<Process>, C:\Program 
                        Files\WindowsPowerShell\Modules\dbatools\1.0.90\allcommands.ps1: line 65337
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}

```

#### Steps to Reproduce

Open powershell as local admin and run:
`Set-DbaPrivilege -Type LPIM`

#### Expected Behavior

Expect to set nt service\mssqlserver Lock Memory Privileges

#### Actual Behavior

WARNING: NT Service\MSSQLSERVER already has Lock Pages in Memory Privilege on <xxxx>

Checking local policy settings, NT Service\MSSQLSERVER does not have this privilege. There is also a silent error regarding kerberos and winrm (above)

### PR DESCRIPTION
**Pull request by sdwire**
## Type of Change

 - [X] Bug fix (non-breaking change, fixes #6351 )
 - [ ] New feature (non-breaking change, adds functionality, fixes # )
 - [ ] Breaking change (effects multiple commands or functionality, fixes # )
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
Fix bug that claimed user already had a privilege when nobody had that privilege 

### Approach
When the privilege is missing from the file, it adds the entire privilege instead of just adding the user to an existing list of users.

### Commands to test
Set-DbaPrivilege -Type LPIM

### CODE REVIEW

**Comment by potatoqualitee** [comment]
sweet, thanks so much @sdwire ! Going to take a look at the code 👍

**Comment by wsmelton** [comment]
Do you have a screenshot of this working?

Recall we tried to do this previously and sec command didn't like the file. Can't remember how we tried it though.

**Comment by potatoqualitee** [comment]
yes, please! im running out of servers to try it on 😅

**Comment by potatoqualitee** [comment]
(it worked, i was just surprised there was not output so I'm creating some output)

**Comment by sdwire** [comment]
Here's my powershell session...

2020-02-26 12_42_38-Administrator_ PowerShell 6 (x64)

**Comment by potatoqualitee** [comment]
awesome! works for me, thanks so much 🥳🥳🎉🎈 thank you for the contribution, merging and publishing now

**Pull request merged**
