### PR TITLE
Fix Few Final PSSA Rules

### PR DESCRIPTION
**Pull request by joshcorr**
## Type of Change

 - [ ] Bug fix (non-breaking change, fixes #<enter issue number>)
 - [x] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [x] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
 
There were a few PSSA rules that had not been fixed by previous PRs. These should be the last remaining PSSA rules. After this PR it should be possible to enforce PSSA rules on all new PRs.

### Approach

Added required code or override where previously discussed.

### Commands to test

`Invoke-ScriptAnalyzer .\Functions`

### Screenshots

image

### CODE REVIEW

**Comment by potatoqualitee** [comment]
:O 🎉 🎉 🎉 🎉 🎉  🙇 🙇 🙇 🙇 🙇

**Comment by joshcorr** [comment]
My Pleasure! 😁 Now on to writing integration tests to raise code coverage!

**Comment by potatoqualitee** [comment]
Thanks again! Will fix the one formatting failure post mege

**Comment by potatoqualitee** [comment]
* merge

**Comment by joshcorr** [comment]
Was just about to fix that.

**Comment by potatoqualitee** [comment]
We needed to fix the formatter, and niph submitted a change so it worked out well 👍

**Pull request merged**
