### PR TITLE
Master

### PR DESCRIPTION
**Pull request by enriquecatala**
## Type of Change

 - [x] Bug fix (non-breaking change)
 - [ ] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
the purpose of this fix is because there is a bug when you want to deploy a log shipping by specifying a backup folder containing the backup full, and an error is thrown. $BackupPath is never initialized when UseExistingBackup is specified, so it throws an error "$Path is null" when trying to execute the Restore database command
 

### Approach

This change only includes a missing line to specify where is the backup folder after validating that the backup folder is working properly

### Commands to test

Invoke-DbaLogShipping -SourceSqlInstance source -DestinationSqlInstance destination -Database MyDatabase __-FullBackupPath "\\path\FULL" -UseExistingFullBackup__  -BackupNetworkPath "\\PATH\LOG" -CopyDestinationFolder "\\path\LOG" -CompressBackup -CopyScheduleDisabled -PrimaryThresholdAlertEnabled -RestoreThreshold 15 -SecondaryThresholdAlertEnabled

### CODE REVIEW

**Comment by potatoqualitee** [comment]
Thanks so much, @enriquecatala ! allcommands.ps1 is compiled by the publish process so there is no need to modify. I will make slight modifications to your PR so that it is mergeable 👍

**Comment by enriquecatala** [comment]
> Thanks so much, @enriquecatala ! allcommands.ps1 is compiled by the publish process so there is no need to modify. I will make slight modifications to your PR so that it is mergeable 👍

Thank you. Can you please help me to understand what must be executed to force the allcommands.ps1 to be regenerated when working locally? In this case i wasn´t aware of this :(

**Comment by potatoqualitee** [comment]
No problem- when the .git folder exists, it loads each of the files one by one and bypasses allcommands.ps1. So if you are working from a github repo directory, it should work without issues when you do

`Import-Module .\dbatools.psd1 -Force`

**Comment by potatoqualitee** [comment]
Thanks again, your changes have been merged! 💯

**Comment by enriquecatala** [comment]
Thank you.
do you know when is this available in the Powershell Gallery to install via Import-Module? I really don´t know how frequently you update the gallery with the main branch code.

Regards.

**Comment by potatoqualitee** [comment]
Your code is now in the PowerShell Gallery 👍

**Pull request merged**
