### PR TITLE
More PsRemoting coverage (-UseSSL & -IncludePortInSPN)

### PR DESCRIPTION
**Pull request by ClaudioESSilva**
## Type of Change

 - [ ] Bug fix (non-breaking change, fixes #<enter issue number>)
 - [x] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Nunit test is included
 - [x] Documentation
 - [ ] Build system
 

### Purpose
 
Due to different environment configurations, In my work I need to use `-UseSSL` and `-IncludePortInSPN` when running PowerShell remote stuff (which make use of `Invoke-Command2`).
Example: `Get-DbaComputerCertificate`

### Approach

Make configurable these two values by using Get/Set-DbatoolsConfig

### Commands to test

Any that uses internal `Invoke-Command2` function.

Use the following commands to change the values of the configurations:
``` powershell
Set-DbaToolsConfig -Name 'psremoting.pssession.usessl' -Value $true
Set-DbaToolsConfig -Name 'psremoting.pssessionoption.includeportinspn' -Value $true
```
Note: Default values are `$false` which are also defaults values of the `New-PsSessionOption` and `New-PsSession` commands

### Learning

Two blog posts will be published after these improvements are available. On on dbatools blog, related with what these configs are, how to get current values, set new, etc.
The 2nd one will be on my blog and is on the detail why I need it and how I have made the implementation.

Note: This code is currently running without problems on my dbatools installation within the company.
Note2: There is no easy way to test these changes. (AFAIK, our test environment don't have settings for SSL and SPNs needed).

### CODE REVIEW

**Comment by potatoqualitee** [comment]
Unfortunately, this breaks all remoting

image

**Comment by ClaudioESSilva** [comment]
My bad @potatoqualitee . Fixed :-)
Can you try it again? 😃

**Comment by potatoqualitee** [comment]
thanks buddy puddin'

**Comment by potatoqualitee** [comment]
works for me

**Pull request merged**
