### PR TITLE
Added DATA_PURITY, NO_INFOMSGS, ALL_ERRORMSGS

### PR DESCRIPTION
**Pull request by EitanBlumin**
## Type of Change

 - [x] Bug fix (non-breaking change, fixes # )
 - [ ] New feature (non-breaking change, adds functionality, fixes # )
 - [ ] Breaking change (effects multiple commands or functionality, fixes # )
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
 

Assuming there are no extendible parameters, or a "public" variation of this function available which would give us more flexibility when running CHECKDB, we need to think what's the best "default" method to run it.

### Approach

`DATA_PURITY` - Column-value integrity checks are enabled by default and do not require the DATA_PURITY option. For databases upgraded from earlier versions of SQL Server, column-value checks are not enabled by default until DBCC CHECKDB WITH DATA_PURITY has been run error free on the database. After this, DBCC CHECKDB checks column-value integrity by default. In other words: There's no reason not to do this.

`NO_INFOMSGS` - Enabling this option would reduce the "noise" we get from CHECKDB executions, when what really interests us are the high severity errors.

`ALL_ERRORMSGS` - By default, error messages are sorted by object ID. Enabling the `ALL_ERRORMSGS` option causes the command to display all reported errors per object.

### Commands to test

`Test-DbaLastBackup`

### CODE REVIEW

**Comment by wsmelton** [comment]
The output is sent to null so how does adding those additional options make any difference in the test command?

What issue is this fixing/addressing?

**Comment by EitanBlumin** [comment]
The command is enveloped in a try/catch block, so any errors should become visible to the user AFAIK (unless that $null swallows those up as well? that's a problem if it behaves like that).

The main issue that this PR is set to solve, is the DATA PURITY option which was missing, and could be an issue with databases migrated from older versions.

**Comment by potatoqualitee** [comment]
This looks like a great feature - but Shawn is right. It goes to $null so nobody can see the output. Lemme drink some coffee and take a closer look 💯  Thank you so much for the PR, Eitan! Sorry for the delay. New job is taking up all my time.

**Comment by EitanBlumin** [comment]
Thanks!

If that $null it's swallowing all output, including error messages, then that might be a serious oversight.

Kind of misses the whole point of running checks if we don't know when it fails, right?

**Comment by wsmelton** [comment]
@EitanBlumin / @potatoqualitee 

I checked where we use this command and the only places it gets used is with `Test-DbaLastBackup` and `Remove-DbaDatabaseSafely` so setting DATA_PURITY in those cases is a moot point. Either way the method used that we have is still going to spit out the errors along with all the informational messages (_**which I want left in place**_).

**Comment by EitanBlumin** [comment]
> setting DATA_PURITY in those cases is a moot point
Why? What about environments with databases upgraded from older versions?
By the way, as I quoted from Microsoft Docs in the beginning of this PR, even if you specifically set DATA_PURITY when it's not needed, there's no downside anyway.

"... column-value checks are not enabled by default until DBCC CHECKDB WITH DATA_PURITY has been run error free on the database. After this, DBCC CHECKDB checks column-value integrity by default"

> Either way the method used that we have is still going to spit out the errors along with all the informational messages (which I want to be left in place)

What do you mean by "spit out"? As in thrown in the "trash" i.e. $null output? Why is this intentional? What's the point of running `Test-DbaLastBackup` if you're not gonna know when a database backup fails an integrity check?

**Comment by wsmelton** [comment]
It's a moot point because the databases are dropped in both commands. There is no benefit from it.

**Comment by EitanBlumin** [comment]
If that's your approach, then what's the benefit from running CHECKDB at all?

**Comment by wsmelton** [comment]
What are your test results of this change shown the internal command does before and after you made the changes?

**Comment by wsmelton** [comment]
The current output of the command will not be thrown as errors, we are simply capturing the output from the internal function and placing it in a property, at least for `Test-DbaLastBackup`. As soon as this database was restored and the validation/checks completed the database was dropped.

```
[PS 7.0.2] [15:12:20] [  2.2 s ][ git:development ] C:\git\dbatools
[13] > Test-DbaLastBackup -SqlInstance lab-sql-01 -SqlCredential $labSaSqlCred -Database AdventureWorks2014_Corrupt

SourceServer   : lab-sql-01
TestServer     : lab-sql-01
Database       : AdventureWorks2014_Corrupt
FileExists     : True
Size           : 333.08 MB
RestoreResult  : Success
DbccResult     : An exception occurred while executing a Transact-SQL statement or batch.
                  ---> System.Data.SqlClient.SqlException (0x80131904): Table error: Object ID 1237579447, index ID 4, partition ID
                 72057594052149248, alloc unit ID 72057594058964992 (type In-row data), page (1:21880). Test (IS_OFF (BUF_IOERR,
                 pBUF->bstat)) failed. Values are 133129 and -4.
                 Object ID 1237579447, index ID 4, partition ID 72057594052149248, alloc unit ID 72057594058964992 (type In-row data):
                 Page (1:21880) could not be processed.  See other errors for details.
                 Table error: Object ID 1237579447, index ID 4, partition ID 72057594052149248, alloc unit ID 72057594058964992 (type
                 In-row data). Page (1:21880) was not seen in the scan although its parent (1:21881) and previous (1:21878) refer to it.
                 Check any previous errors.
                 Table error: Object ID 1237579447, index ID 4, partition ID 72057594052149248, alloc unit ID 72057594058964992 (type
                 In-row data). Page (1:21882) is missing a reference from previous page (1:21880). Possible chain linkage problem.
                 DBCC results for 'HumanResources.Employee'.
                 There are 290 rows in 13 pages for object "HumanResources.Employee".
                 CHECKDB found 0 allocation errors and 4 consistency errors in table 'HumanResources.Employee' (object ID 1237579447).
                 DBCC results for 'Sales.SalesOrderHeader'.
                 There are 31465 rows in 1333 pages for object "Sales.SalesOrderHeader".
                 DBCC results for 'HumanResources.EmployeeDepartmentHistory'.
                 There are 296 rows in 3 pages for object "HumanResources.EmployeeDepartmentHistory".
                 DBCC results for 'HumanResources.EmployeePayHistory'.
                 There are 316 rows in 3 pages for object "HumanResources.EmployeePayHistory".
                 DBCC results for 'Sales.SalesOrderHeaderSalesReason'.
                 There are 27647 rows in 171 pages for object "Sales.SalesOrderHeaderSalesReason".
                 DBCC results for 'Sales.SalesPerson'.
                 There are 17 rows in 1 pages for object "Sales.SalesPerson".
                 DBCC results for 'Production.Illustration'.
                 There are 5 rows in 1 pages for object "Production.Illustration".
                 DBCC results for 'HumanResources.JobCandidate'.
                 There are 13 rows in 11 pages for object "HumanResources.JobCandidate".
                 DBCC results for 'Production.Location'.
                 There are 14 rows in 1 pages for object "Production.Location".
                 DBCC results for 'Person.Password'.
                 There are 19972 rows in 465 pages for object "Person.Password".
                 DBCC results for 'Sales.SalesPersonQuotaHistory'.
                 There are 163 rows in 3 pages for object "Sales.SalesPersonQuotaHistory".
                 DBCC results for 'Person.Person'.
                 There are 19972 rows in 6351 pages for object "Person.Person".
                 DBCC results for 'Sales.SalesReason'.
                 There are 10 rows in 1 pages for object "Sales.SalesReason".
                 DBCC results for 'Sales.SalesTaxRate'.
                 There are 29 rows in 1 pages for object "Sales.SalesTaxRate".
                 DBCC results for 'Sales.PersonCreditCard'.
                 There are 19118 rows in 119 pages for object "Sales.PersonCreditCard".
                 DBCC results for 'Person.PersonPhone'.
                 There are 19972 rows in 292 pages for object "Person.PersonPhone".
                 DBCC results for 'Sales.SalesTerritory'.
                 There are 10 rows in 1 pages for object "Sales.SalesTerritory".
                 DBCC results for 'Person.PhoneNumberType'.
                 There are 3 rows in 1 pages for object "Person.PhoneNumberType".
                 DBCC results for 'Production.Product'.
                 There are 504 rows in 24 pages for object "Production.Product".
                 DBCC results for 'sys.queue_messages_1977058079'.
                 There are 0 rows in 0 pages for object "sys.queue_messages_1977058079".
                 DBCC results for 'sys.queue_messages_2009058193'.
                 There are 0 rows in 0 pages for object "sys.queue_messages_2009058193".
                 DBCC results for 'Production.vProductAndDescription'.
                 There are 1764 rows in 131 pages for object "Production.vProductAndDescription".
                 DBCC results for 'sys.queue_messages_2041058307'.
                 There are 0 rows in 0 pages for object "sys.queue_messages_2041058307".
                 DBCC results for 'sys.filestream_tombstone_2073058421'.
                 There are 0 rows in 0 pages for object "sys.filestream_tombstone_2073058421".
                 DBCC results for 'sys.syscommittab'.
                 There are 0 rows in 0 pages for object "sys.syscommittab".
                 DBCC results for 'Sales.SalesTerritoryHistory'.
                 There are 17 rows in 1 pages for object "Sales.SalesTerritoryHistory".
                 DBCC results for 'sys.filetable_updates_2105058535'.
                 There are 0 rows in 0 pages for object "sys.filetable_updates_2105058535".
                 DBCC results for 'Person.vStateProvinceCountryRegion'.
                 There are 181 rows in 4 pages for object "Person.vStateProvinceCountryRegion".
                 CHECKDB found 0 allocation errors and 4 consistency errors in database 'dbatools-testrestore-AdventureWorks2014_Corrupt'.
                 repair_allow_data_loss is the minimum repair level for the errors found by DBCC CHECKDB
                 (dbatools-testrestore-AdventureWorks2014_Corrupt).
                 DBCC execution completed. If DBCC printed error messages, contact your system administrator.
RestoreStart   : 2020-07-08 15:12:34.677
RestoreEnd     : 2020-07-08 15:12:36.664
RestoreElapsed : 00:00:01
DbccStart      : 2020-07-08 15:12:36.784
DbccEnd        : 2020-07-08 15:12:48.867
DbccElapsed    : 00:00:12
BackupDates    : {07/08/2020 15:12:20}
BackupFiles    : {F:\SQL\DATA\BACKUPS\AdventureWorks2014_Corrupt_202007081512.bak}
```

**Comment by EitanBlumin** [comment]
Cool, so the errors are not actually being thrown into oblivion. That's probably due to my misunderstanding.

With that out of the way, let's talk about the actual topic at hand:

Adding the DATA_PURITY flag.

It will provide added benefit to databases upgraded from older versions, and it won't cause any issues with newer version databases.

Why not add it?

**Comment by wsmelton** [comment]
Please review the public functions that call this one. 

`Start-DbccCheck` is 100% an internal function that we do not allow users to call as a standalone function. After you do `Import-Module dbatools` a user will never be able to access this function.

The two functions that call this one internal function both delete the databases they touch. `Test-DbaLastBackup` restores to a temporarily named database and then after deletes it. `Remove-DbaDatabaseSafely`, does the same thing with the given database you provide.

**Comment by EitanBlumin** [comment]
Yes, I understand that. But that doesn't answer my question:

Why not always add the DATA_PURITY option to the CHECKDB command?

**Comment by wsmelton** [comment]
Why add it to databases that are deleted?

**Comment by EitanBlumin** [comment]
Because if the user is performing a backup restore test for a database which was upgraded from an older SQL Server version, and this database never had a DATA_PURITY check, and it does in fact contain data type impurities which are a form of corruption, then wouldn't the user want to know about this?

**Comment by wsmelton** [comment]
Older SQL Server version being SQL Server 2000 or SQL Server 7.0....I have not seen or hit a database to date that didn't have the DATA_PURITY flag already enabled.

I will let @potatoqualitee decide if she wants to add it or not.

The conflict will have to be resolved and the other flags removed before she can merge the PR.

**Comment by EitanBlumin** [comment]
That shouldn't be a problem... Although I still think those flags should remain as well, especially considering the example output that you wrote here: https://github.com/sqlcollaborative/dbatools/pull/6601#issuecomment-655733895

**Comment by wsmelton** [comment]
Closing this PR due to being stale.

Further discussion wanting this feature change can be done via an issue.

**Pull request closed without merging**
