### PR TITLE
add type for dac

### PR DESCRIPTION
**Pull request by RichieBzzzt**
missing "add-type" causes function to fail when user does not have dac loaded linked to issue  https://github.com/sqlcollaborative/dbatools/issues/2818

### CODE REVIEW

**Comment by RichieBzzzt** [comment]
## Type of Change

 - [x] Bug fix (non-breaking change, fixes #2818)
 - [ ] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
Fixes #2818

### Approach
Add "Add-Type" to load dac.dll stored in bin/smo

### Commands to test
```
New-DbaPublishProfile -SqlInstance sql2016 -Database db2 -Path C:\temp
```

**Comment by potatoqualitee** [comment]
hey richie, dac should be auto loaded within our SMO loader at import time. @FriedrichWeinmann can you take a look and see what we're missing?

**Comment by RichieBzzzt** [comment]
Oh! I thought something like this might be occurring so I had a look around, didn’t see anything. Obviously I didn’t look hard enough! Can you point me in the direction where this happens and I’ll also take a look.

**Comment by potatoqualitee** [comment]
hey @RichieBzzzt - it's at `\internal\scripts\smoLibraryImport.ps1`

**Comment by RichieBzzzt** [comment]
no longer required as opened a new one

**Pull request closed without merging**
