### PR TITLE
Get-DbaSqlService - Added downlevel support for multi-version installs

### PR DESCRIPTION
**Pull request by FriedrichWeinmann**
## Type of Change

 - [ ] Bug fix (non-breaking change, fixes #<enter issue number>)
 - [x] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [x] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 
### Purpose
Computers with multiple instances of multiple versions would only retrieve services from the latest namespace.
However, this might miss services of older versions that were installed after later versions of SQL Server.
Now all accessible instances of all versions are respected, but only the latest version of a service is returned.
In most scenarios, this change will not affect the output at all.

### CODE REVIEW

**Comment by potatoqualitee** [comment]
Mr. Fred, this test's got some failures

**Comment by FriedrichWeinmann** [comment]
Ms. Chrissy, those tests are as green as the grass on the other side!

**Comment by FriedrichWeinmann** [comment]
Or maybe not so after all. Should hit refresh before replying ^^

**Comment by potatoqualitee** [comment]
wow that last one time tf out at 60 minutes cuz of another command. Green should be good thoooooooo, I think you fixed it :wizard:

**Comment by potatoqualitee** [comment]
hey @FriedrichWeinmann did you do anything that would impact Get-DbaComputerCertificate? It's only failing on your branch.

**Comment by FriedrichWeinmann** [comment]
Until just now, I hadn't. And nothing in this failing test uses the *-DbaSqlService suite of commands.
I've added some additional awesomeness to them now though, as I was checking them out :sunglasses:
(Mostly made sure I ironed out some of the consistent user experience issues. Check out what I did with scriptblock arguments though)

**Comment by potatoqualitee** [comment]
🤔 i cant see it? Thank you for this PR! I know you worked hard on it.

**Pull request merged**
