### PR TITLE
Bug/remove dba agent job step/sql credential missing

### PR DESCRIPTION
**Pull request by marioanton**
## Type of Change

 - [x] Bug fix (non-breaking change, fixes #<enter issue number>)
 - [ ] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [x] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
Fixing a privileges problem
### Approach
Passing credentials when inherited creds not enough.
### Commands to test
Remove-DbaAgentJobStep
### Screenshots
https://github.com/sqlcollaborative/dbatools/issues/3830

### CODE REVIEW

**Comment by potatoqualitee** [comment]
excellent, thank you! will wait for tests to pass 👍

**Comment by marioanton** [comment]
Erm. i think i cut off master branch instead development so more changes are coming in since you changed the PR destination branch to be merged in.

Let me know whether that is fine or i shall redo it.

**Comment by potatoqualitee** [comment]
Thank you for your contribution 🎆 🍰 

Yes, we branch off of development (forgot to mention in previous PR, my apologies), but I fixed it and tests pass 👍

**Comment by potatoqualitee** [comment]
Your code is now in the PowerShell Gallery 😁

**Pull request merged**
