### PR TITLE
Go Version of Restore-DbaBackup work

### PR DESCRIPTION
**Pull request by Stuart-Moore**
Fixes # 

Changes proposed in this pull request:
Implements the following abilities for Restore-DbaBackup:
PointInTime restore
Obtain files from directory, Ola style directory, user generated file objects and xp_DirTree
Rename Logical Files (copes with filegroups and any number of files)
Variable CaPiTilisation should be correct now

How to test this code: 
- [ ] 
- [ ] 

Has been tested on minimum requirements:
- [ ]  Powershell 3
- [ ]  Windows 7
- [ ]  SQL Server 2000

Has been tested on maximum requirements:
- [ ]  SQL Server vNext
- [ ]  Windows 10
- [ ]  Azure Database

Tests for tester:
- [ ] Working/useful help content, including link to command on dbatools web site
- [ ] All examples work as advertised
- [ ] Does not contain template content
- [ ] Does not contain excessive/unnecessary amounts of comments
- [ ] Works remotely
- [ ] Works locally
- [ ] Works on lower versions or throws error specifying version not supported
- [ ] Works with named instances
- [ ] Works with clustered instances
- [ ] Handles offline/read only databases
- [ ] Supports multiple servers (at the command line or piped from Get-SqlRegisteredServerName)
- [ ] No un-handled errors which stop the command working with multiple servers

### CODE REVIEW

**Comment by Stuart-Moore** [comment]
Appveyor is complaining about some Pester tests I added to the Tests folder. 
They happily pass locally, so guessing they'll need fixing for Appveyor. 
Want me to remove them for the PR?

**Comment by ctrlbold** [comment]
I'm currently in the middle of a huge overhaul. It will complain for the next few days, unfortunately. It's likely not your own commands.

There were a couple issues with the PR, however -- each of your PRs have been directly to master, and so I edit them to point to development. They should be PRd into development, always.

Also, the number of files is very high. It will take a lot longer for whoever is testing to change them. We prefer them in smaller batches, though I understand sometimes that isn't possible -- I'm about to modify about 50 commands myself.

**Comment by Stuart-Moore** [comment]
:(  Sorry about that, trying to do PRs while packing for a trip. 

Want me to split them as seperate PRs and resubmit? Problem is they all hang together eventually. But could submit all the 'hidden' stuff, and then the public one last so if something doesn't make it, end users won't notice?

**Comment by ctrlbold** [comment]
No problem! I appreciate your work. It looks like there were a few unrelated changes somehow. I believe this may have been caused by not syncing the branch prior to the PR? Looks like it would be best to close PR and redo with only the required changes.

I fear that a really large PR will hold up the process for you to go forward. i would divide into workable chunks if that's possible.

Thanks for your patience while we work all of this out!

**Comment by Stuart-Moore** [comment]
closing to resubmit smaller requests.

**Pull request closed without merging**
