### PR TITLE
Find-DbaStoredProcedure - Split logic modified

### LINKED ISSUE #8036: Find-DbaStoredProcedure - CR Line Ending Output On StoredProcedureFullText Property
### Verified issue does not already exist?

Yes

### What error did you receive?

Error wasn't received. Due to how the split is happening on typical Windows installations, there is an "orphan" `CR` character.

https://github.com/sqlcollaborative/dbatools/blob/27bc0adb3357fd5933dd2c285970039a7fe3895c/functions/Find-DbaStoredProcedure.ps1#L144

Maybe we can take some of the philosophy from this [issue ](https://github.com/sqlcollaborative/dbatools/issues/7689) with  `$eol = [System.Environment]::NewLine`.

### Steps to Reproduce

```powershell
Find-DbaStoredProcedure Server -Database db -Pattern select
```

### Are you running the latest release?

Yes

### Other details or mentions

I noticed the issue when I tried to mix `CRLF` with the `CR` within SQL Server Management Studio. I did a `Find-DbaStoredProcedure | Select-Object -ExpandProperty StoredProcedureFullText | Set-Clipboard` and copied into SSMS. Then I added a `USE` and `GO` declaration at the top. When I ran the entire script, I received the below error.

```sql
Msg 102, Level 15, State 1, Line 1
Incorrect syntax near 'GO'.
```

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe)

### PowerShell Host Version

```powershell
[32;1mName                           Value[0m
[32;1m----                           -----[0m
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### SQL Server Edition and Build number

```sql
Microsoft SQL Server 2014 (SP3) (KB4022619) - 12.0.6024.0 (X64) 
	Sep  7 2018 01:37:51 
	Copyright (c) Microsoft Corporation
	Enterprise Edition: Core-based Licensing (64-bit) on Windows NT 6.3 <X64> (Build 9600: )
```

### .NET Framework Version

```powershell
.NET 6.0.0-rtm.21522.10
```

### PR DESCRIPTION
**Pull request by mattcargile**
## Type of Change

 - [ ] Bug fix (non-breaking change, fixes # )
 - [ ] New feature (non-breaking change, adds functionality, fixes #  )
 - [x] Breaking change (effects multiple commands or functionality, fixes #8036  )
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1`)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Unit test is included
 - [ ] Documentation
 - [ ] Build system

### Purpose

Avoiding `` `r`` output from `StoredProcedureFullText` by outputting as blob of text. Not sure how stored procedure text will be output from SQL Server across platforms. Normalize line endings on `StoredProcedureTextFound` to `[System.Environment]::NewLine`.

### Breaking Changes
Previously output from `StoredProcedureFullText` was a `String[]` ( NOTE: I think it was technically an arraylist ). Now it will return a `string`. Previously output from `StoredProcedureTextFound` was always joined with a hardcodded `` `n``. Now it will be joined with the client's environment new line.

### Approach

Removed `.Split` by `` `n`` from `StoredProcedureFullText`. Added `.Split()` to derivation of `$spTextFound`. Deciding to split on `` `n``, `` `r``, and `` `r`n`` because `Get-Content` behavior on PowerShell 7.2.1 is the same. Not sure if the team agrees. Approach for `StoredProcedureTextFound` is self explanatory _i think_.
### Commands to test

`Find-DbaStoredProcedure`

### CODE REVIEW

**Comment by andreasjordan** [comment]
Tests say:
```
Describe : dbatools style
Context  : indentation
Name     : It Find-DbaStoredProcedure.ps1 has no trailing spaces (line(s) 146)
Result   : Failed
Message  : Expected 0, but got 1.
```

**Comment by mattcargile** [comment]
Oops. Fixed. Bad habit of mine to add the trailing spaces.

Also I finally got the Pester tests working for the first time. Here is my output. Not sure if this should be another Issue.

```powershell
      [-] Should find a specific StoredProcedure named cp_dbatoolsci_sysadmin 5ms
        Expected 'cp_dbatoolsci_sysadmin', but got @('sp_Blitz', 'sp_BlitzFirst', 'sp_QuickieStore', 'cp_dbatoolsci_sysadmin').
        34:             $results.Name | Should Be "cp_dbatoolsci_sysadmin"
        at <ScriptBlock>, C:\git_personal\dbatools\tests\Find-DbaStoredProcedure.Tests.ps1: line 34
```
Looks like this could be fixed with an edit this line of code? I have tool procs in my `master` database so my output is an array.

https://github.com/mattcargile/dbatools/blob/84e469c70734c696e436feeb9e0713a790c23fa9/tests/Find-DbaStoredProcedure.Tests.ps1#L32

**Comment by andreasjordan** [comment]
> Also where did you see that trailing space issue? Was that from the appveyor output?
Yes.

**Comment by andreasjordan** [comment]
About the test:

```
$results = Find-DbaStoredProcedure -SqlInstance $script:instance2 -Pattern dbatools* -IncludeSystemDatabases
```
`-Pattern` is a regex that is matched against every row of the definition. So it should be changed from `dbatools*` to `cp_dbatoolsci_sysadmin` to only find the specific procedure.

Can you try that?

**Comment by mattcargile** [comment]
All green on the Integration Tests for this one proc. 

I was thinking about trying to keep the asterisk in the function call. Then using use an `-in` clause to make sure it included this procedure. Doesn't this change kind of change the intent of the test a little with this recent commit?

https://github.com/sqlcollaborative/dbatools/blob/31af4729245f8073ddec3f8453b20ef16543c9b6/tests/Find-DbaStoredProcedure.Tests.ps1#L32

**Comment by andreasjordan** [comment]
> All green on the Integration Tests for this one proc.
> 
> I was thinking about trying to keep the asterisk in the function call. Then using use an `-in` clause to make sure it included this procedure. Doesn't this change kind of change the intent of the test a little with this recent commit?

The asterix is not a wildcard! "dbatools*" is used a regex - so it says "the string 'dbatool'", because "s*" is the "s" 0 to x times. So I really don't understand what the author of that line wanted to test.

**Comment by mattcargile** [comment]
Oh! Of course! I see what you mean. I assume the previous author was assuming behavior similar to the operator `-like`. 

What do you think about these recent changes to the tests to use `Should Contain`? It would correct the other tests if they found multiple items on the same pattern.

**Comment by mattcargile** [comment]
Also, please feel free to critique my commit formatting and the like. I had read there was some commit pattern you were using to create docs or change logs now? I didn't see it in the `Contributing.md`.

I did try to make my commit in the summary/wrapped detail style. I didn't quite perfectly wrap my lines though at 72 characters.

Lastly, my commits are kind of messy and overlapping at this point. Is it still reasonable to rebase locally and do a force push with a cleaner commit message or does that mess things up?

**Comment by potatoqualitee** [comment]
I squash them all in the end, Matt, no problem! Will merge once approved ✅

**Review by andreasjordan — APPROVED** [review]
Looks good to me.

**Comment by potatoqualitee** [comment]
sweet as heck, thank you both!

**Pull request merged**
