### PR TITLE
Test-DbaConnection - added -SkipPSRemoting / fixed getting Port

### LINKED ISSUE #4678: Test-DBAConnectivity - Check connection to database
Just wondering if it would be worthwhile giving this function the ability to check connection to a specific database. I.E.

`Test-DBAConnection "localhost" -database "db1"`

Then just another member in the output _DBConnectSuccess_ 

At the moment i do this manually by running `Invoke-SQLCmd2` against the database and catching the error, would be nice to have this all rolled into one.

### LINKED ISSUE #6148: Test-DbaConnection - PSRemoting
### Summary of new feature

When running "Test-DbaConnection -SQLinstance <server>", it checks if PSremoting is accessible (PSRemotingAccessible).  
We often connect to SQL servers, that are either in another domain or not accessible for PSRemoting, and we know this from the beginning.  
But it seems there isnt an option, to disable the PSRemotingAccessible check, so the cmdlet takes a long time, just to time out.  

**Measure command:**  
To a server with PSRemotingAccessible working:  
Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 0
Milliseconds      : 534
Ticks             : 5340054
TotalDays         : 6,18061805555556E-06
TotalHours        : 0,000148334833333333
TotalMinutes      : 0,00890009
TotalSeconds      : 0,5340054
TotalMilliseconds : 534,0054  

To a server with PSRemotingAccessible NOT working:  
Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 43
Milliseconds      : 205
Ticks             : 432051498
TotalDays         : 0,000500059604166667
TotalHours        : 0,0120014305
TotalMinutes      : 0,72008583
TotalSeconds      : 43,2051498
TotalMilliseconds : 43205,1498  

### Proposed technical details (if applicable)

Provide an optional parameter like "-SkipPSRemoting", that skips the PSRemotingAccessible check.
Command could look like: "Test-DbaConnection -SqlInstance $SourceServer -SqlCredential $SourceLogin -SkipPSRemoting"  

### Latest version of dbatools as of writing

Version: 1.0.58

### LINKED ISSUE #6157: [Bug] Test-DBAConnection ignoring -SQLCredential
#### PowerShell version:

Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      5.1.18362.145                                                                           
PSEdition                      Desktop                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   10.0.18362.145                                                                          
CLRVersion                     4.0.30319.42000                                                                         
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1                                                                                 

#### dbatools Module version:

Name    : dbatools
Path    : C:\Users\dsolodow\OneDrive - Gaylor Electric, 
          Inc\Documents\WindowsPowerShell\Modules\dbatools\1.0.61\dbatools.psd1
Version : 1.0.61

Name    : dbatools
Path    : C:\Users\dsolodow\OneDrive - Gaylor Electric, 
          Inc\Documents\WindowsPowerShell\Modules\dbatools\1.0.46\dbatools.psd1
Version : 1.0.46

#### SQL Server: 

```sql

Column1                                                                                                                                                                 
-------                                                                                                                                                                 
Microsoft SQL Server 2017 (RTM-CU17) (KB4515579) - 14.0.3238.1 (X64) ...                                                                                                
```

#### Host used

- [X] powershell.exe
- [ ] ISE
- [X] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [X] Still buggy in powershell.exe

#### Errors Received

```
PSMessageDetails      : 
Exception             : System.Exception: Login failed for user 'GAYLOR\dsolodow'. ---> System.Data.SqlClient.SqlException: Login failed for user 'GAYLOR\dsolodow'.
                           at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, 
                        SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, 
                        SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean 
                        applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)
                           at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object 
                        poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
                           at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions 
                        options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
                           at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal 
                        oldConnection)
                           at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, 
                        DbConnectionInternal oldConnection)
                           at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean 
                        allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
                           at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions 
                        userOptions, DbConnectionInternal& connection)
                           at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, 
                        DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
                           at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory 
                        connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
                           at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
                           at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
                           at System.Data.SqlClient.SqlConnection.Open()
                           at CallSite.Target(Closure , CallSite , Object )
                           --- End of inner exception stack trace ---
TargetObject          : TCP:sqlserver\Instance
CategoryInfo          : ConnectionError: (TCP:sqlserver\Instance:String) [], Exception
FullyQualifiedErrorId : dbatools_Get-DbaTcpPort
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Stop-Function, C:\Users\dsolodow\OneDrive - Gaylor Electric, Inc\Documents\WindowsPowerShell\Modules\dbatools\1.0.61\allcommands.ps1: line 
                        81747
                        at Get-DbaTcpPort<Process>, C:\Users\dsolodow\OneDrive - Gaylor Electric, 
                        Inc\Documents\WindowsPowerShell\Modules\dbatools\1.0.61\allcommands.ps1: line 34806
                        at Test-DbaConnection<Process>, C:\Users\dsolodow\OneDrive - Gaylor Electric, 
                        Inc\Documents\WindowsPowerShell\Modules\dbatools\1.0.61\allcommands.ps1: line 68319
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}

```

#### Steps to Reproduce

$admin = get-credential
Test-DbaConnection -SqlInstance sqlserver\instance -SqlCredential $admin

#### Expected Behavior

Successful connection test

#### Actual Behavior

TcpPort reported "Login failed for user" and gave domain\username of the running user rather than the username in $admin
If I launched a PowerShell console as the user for $admin, the test-dbaconnection worked as expected.
Oddly, this worked fine:

```powershell
Invoke-dbaquery -sqlinstance sqlserver\instance -SqlCredential $admin -query "select @@version"
```

### PR DESCRIPTION
**Pull request by andreasjordan**
## Type of Change

 - [x] Bug fix (non-breaking change, fixes #6157  )
 - [x] New feature (non-breaking change, adds functionality, fixes #6148 )
 - [ ] Breaking change (effects multiple commands or functionality, fixes # )
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 
image

### CODE REVIEW

**Comment by potatoqualitee** [comment]
Thank you! DatabaseIsAccessible should be `$false` and Status `Unknown` for that last one.

**Comment by andreasjordan** [comment]
I thought it this way: DatabaseIsAccessible and Status are $null, because there is no database "unknown" in the instance. A not-NULL value would indicate, that the database can be found in the SMO.
And Status is of type [Microsoft.SqlServer.Management.Smo.DatabaseStatus](https://docs.microsoft.com/de-de/dotnet/api/microsoft.sqlserver.management.smo.databasestatus?view=sql-smo-160) which has no "Unknown".

A new commit with a refresh on .Databases is on its way to ensure that SMO is up to date when using it.

**Comment by potatoqualitee** [comment]
If we're comparing null, the following may be equally useful? `if (-not (Get-DbaDatabase -SqlInstance..)`

**Comment by potatoqualitee** [comment]
Looks good, thank you!

**Pull request merged**
