### PR TITLE
Use new command Save-DbaCommunitySoftware

### PR DESCRIPTION
**Pull request by andreasjordan**
Reduce code by using the new command, does not change functionality.

### CODE REVIEW

**Comment by andreasjordan** [comment]
@potatoqualitee Please have a look at the test.

**Comment by potatoqualitee** [comment]
my simple test saves the day!

```
[16ms] C:/github/dbatools❯ $results = Install-DbaDarlingData
WARNING: [18:48:13][Install-DbaDarlingData] Failed to update local cached copy | Cannot
 find path 'C:\github\dbatools\DarlingData-master' because it does not exist.
```

**Comment by potatoqualitee** [comment]
no, that default is `C:\Users\ctrlb\AppData\Roaming\PowerShell\dbatools`. C:\github\dbatools is $pwd.

```
 at Stop-Function, C:\github\dbatools\internal\functions\flowcon
                        trol\Stop-Function.ps1: line 260
                        at Install-DbaDarlingData<Begin>,
                        C:\github\dbatools\functions\Install-DbaDarlingData.ps1: line
                        124
```

**Comment by andreasjordan** [comment]
The initial line number in Save-DbaCommunitySoftware is still missing.

**Comment by potatoqualitee** [comment]
I did not run Save-DbaCommunitySoftware and it is not in the exceptions output

**Comment by andreasjordan** [comment]
The message "Failed to update local cached copy" is from the catch block after calling Save-DbaCommunitySoftware inside of Install-DbaDarlingData. So Save-DbaCommunitySoftware is definitly called and raises the error "Cannot find path 'C:\github\dbatools\DarlingData-master' because it does not exist." The question is: Where is this path build and where is it used?

**Comment by potatoqualitee** [comment]
Found it!

```
System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Save-DbaCommunitySoftware<Process>,
                        C:\github\dbatools\functions\Save-DbaCommunitySoftware.ps1:
                        line 196
                        at Install-DbaDarlingData<Begin>,
                        C:\github\dbatools\functions\Install-DbaDarlingData.ps1: line
                        122
                        at <ScriptBlock>, <No file>: line 1
```

btw, i just ran this from my own command line. you'll find install-dbadarlingdata is broken in yours as well.

**Comment by andreasjordan** [comment]
Ok, fails on my 5.1, but works on 7.1.3 (which is the current default in VSCode):
image

**Comment by andreasjordan** [comment]
Thanks, I found it.

**Comment by andreasjordan** [comment]
Now all bugs are fixed...

**Comment by potatoqualitee** [comment]
I'm constantly surprised by how many differences there are in 7.x vs 5.1 :/

**Pull request merged**
