### PR TITLE
Fix Test-DbaValidLogin -Detailed (#2217)

### PR DESCRIPTION
**Pull request by joshcorr**
## Type of Change

 - [ X] Bug fix (non-breaking change, fixes #2217 )
 - [ ] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ X] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ X] Pester test is included
 - [ ] Nunit test is included
 - [ X] Documentation
 - [ ] Build system
 

### Purpose
 
- To remove all references in Test-DbaValidLogin to the -Detailed parameter in favor of Select-DefaultView (As requested in Issue #2217)
- To update the documentation and examples reflecting the change. 
- To provide a basic parameter UnitTest for this cmdlet.
### Approach

- Looked at the work already done on Test-DbaTempDbConfiguration
- Analyzed how Select-DefaultView works
- Wrote a Pester test to validate the Parameters I had changed.

### Commands to test

Example 2 shows the updated syntax for returning all properties from the cmdlet.

Test-DbaValidLogin -SqlInstance Dev01 -FilterBy GroupsOnly | Select-Object -Property *

### CODE REVIEW

**Comment by potatoqualitee** [comment]
heyyyy, thanks so much @joshcorr ! I'll take a closer look and merge asap.

**Comment by potatoqualitee** [comment]
And a test!! our lucky day 💃

**Comment by joshcorr** [comment]
@potatoqualitee Thanks! I was super nervous about getting my first pull request right.

**Comment by potatoqualitee** [comment]
You did it so well 💞 right branch, includes test, nice headline, good info, everything. Thanks again! Your code will be published to master shortly.

**Pull request merged**
