### PR TITLE
Get-DbaADObject, enhancements

### PR DESCRIPTION
**Pull request by niphlod**
Changes proposed in this pull request:
- can use a different set of credentials that are used to connect to AD
- can use different formats for ADObj

This will ultimately enable better flexibility for "harder" cmdlets, like the *spn* ones.

### CODE REVIEW

**Comment by niphlod** [comment]
hold on this a few hours, I spotted a bug

**Comment by niphlod** [comment]
ok, now it's better and more complete. 
@ctrlbold , @wsmelton , @ConstantineK and @FriedrichWeinmann , could you please review this ?
I hope the wording and the code are clearer in the latest commit but alas, AD is cumbersome at best for not-so-technical users. 
Thanks to the nitty-gritty details of my env at least it's now far more complete and intelligent than before.

**Comment by ConstantineK** [comment]
Would a useful test be running the examples @niphlod or is there anything more we should try to verify?

**Comment by niphlod** [comment]
Not that I'm aware of. If you all guys have intricate ad setups, throw at
it anything you can find.

Il 11 apr 2017 01:26, "Constantine" <notifications@github.com> ha scritto:

Would a useful test be running the examples @niphlod
<https://github.com/niphlod> or is there anything more we should try to
verify?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/sqlcollaborative/dbatools/pull/1027#issuecomment-293107116>,
or mute the thread

**Comment by niphlod** [comment]
BTW, really, if the precedent version worked, the only culprit I see in this one is the `$Credential` passing (in my intricated env, it works). 
Every other change is just on the proper filter, which relies on the underlying implementation of `System.DirectoryServices.AccountManagement` so it should be totally safe.

**Comment by ConstantineK** [comment]
Assigned to myself to test this later today if possible.
Looks good!

**Comment by ctrlbold** [comment]
Thanks @ConstantineK and @niphlod !

**Pull request merged**
