### PR TITLE
Install-DbaMaintenanceSolution Carry on even if 1 server fails

### PR DESCRIPTION
**Pull request by MikeyBronowski**
## Type of Change

 - [x] Bug fix (non-breaking change, fixes # )
 - [ ] New feature (non-breaking change, adds functionality, fixes # )
 - [ ] Breaking change (effects multiple commands or functionality, fixes # )
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
 
The output should be like that:
Warning for the first instance and success for the other one.

```
WARNING: [16:05:14][Install-DbaMaintenanceSolution] The Maintenance Solution already exists in Mikey on localhost,1433. Use -ReplaceExisting to automatically drop and recreate.

ComputerName InstanceName SqlInstance     Results
------------ ------------ -----------     -------
localhost    MSSQLSERVER  localhost,1433  Success
```

Currently, it stops executing after the first server that has a solution throws a warning.

### Commands to test

```powershell
# install the solution on one SQL first
Install-DbaMaintenanceSolution -SqlInstance sql1 -Database Mikey

# execute the command with the SQL that has the solution already
Install-DbaMaintenanceSolution -SqlInstance sql1, sql2 -Database Mikey
```

### CODE REVIEW

**Comment by andreasjordan** [comment]
What about just adding `-Continue` to the `Stop-Function` call? That should result in the same output if -EnableException is $false and still fail the command if -EnableException is $true.

**Comment by MikeyBronowski** [comment]
> What about just adding `-Continue` to the `Stop-Function` call? That should result in the same output if -EnableException is $false and still fail the command if -EnableException is $true.

Did not know that. Good call. I will change it

**Comment by potatoqualitee** [comment]
Will wait for @MikeyBronowski's fixes 💯  Thank you for the review, @andreasjordan

**Comment by MikeyBronowski** [comment]
I thought I've pushed the changes. Let me check 🤔

**Comment by potatoqualitee** [comment]
Oh, sorry @MikeyBronowski! I followed the order of comments. Is it ready to merge?

**Comment by MikeyBronowski** [comment]
> Oh, sorry @MikeyBronowski! I followed the order of comments. Is it ready to merge?

That's totally my fault :) I was out of order and commented after the commits. Should be good to merge. Thank you Chrissy for your patience :)

**Comment by potatoqualitee** [comment]
Thanks again, Mikey. Do the tests work for you locally? They are failing on appveyor.

**Comment by andreasjordan** [comment]
The test ist not correct.

 ```
      It "Continues the installation on other servers " {
            $results2 = Install-DbaMaintenanceSolution -SqlInstance $script:instance2, $script:instance3 -Database tempdb
            $sproc = Get-DbaDbModule -SqlInstance 'localhost,14333' -Database tempdb | where {$_.Name -eq "CommandExecute"}
            $sproc | Should -Not -BeNullOrEmpty
```

The installation is done on `$script:instance2` and `$script:instance3`, but the test is running against `localhost,14333`.

I think you want it to fail for `$script:instance2` but to work for `$script:instance3`. 
So how do you let it fail for the first one? Then you would have to test for the second one.

**Comment by andreasjordan** [comment]
Ok, I found how you fail on the first one (by creating the table).

**Comment by andreasjordan** [comment]
So probably just change line 33 from 
```
$sproc = Get-DbaDbModule -SqlInstance 'localhost,14333' -Database tempdb | where {$_.Name -eq "CommandExecute"}
```
to
```
$sproc = Get-DbaDbModule -SqlInstance $script:instance3 -Database tempdb | where {$_.Name -eq "CommandExecute"}
```

**Comment by MikeyBronowski** [comment]
Duh.... what a stupid thing... I will fix it. Thanks for looking into this. I thought the tests passed, but maybe because of my setup they are ok locally.

**Comment by MikeyBronowski** [comment]
@potatoqualitee not sure what I need to do now as the checks have been cancelled?

**Comment by MikeyBronowski** [comment]
> @potatoqualitee not sure what I need to do now as the checks have been cancelled?

I think I have sorted it out. It needed the branch refresh. The one error in the log does not seem to be related to the command I have changed.

**Comment by potatoqualitee** [comment]
Looks good! Thanks so much, will release shortly 💯

**Pull request merged**
