### PR TITLE
Get-DbaDbBackupHistory - Fix trying to run Get-DbaDbBackupHistory with empty listener

### LINKED ISSUE #6610: [Bug] Get-DbaDbBackupHistory - Not working on availabitity groups without listener because of obsolete code
I think this code is obsolete:

Line 311 to 332:
```
            if (($server.AvailabilityGroups.count -gt 0) -and ($agCheck -ne $True)) {
                $adbs = $databases | Where-Object Name -In $server.AvailabilityGroups.AvailabilityDatabases.Name
                $adbs = $adbs | Where-Object Name -NotIn $ProcessedAgDatabases
                ForEach ($adb in $adbs) {
                    Write-Message -Level Verbose -Message "Fetching history from replicas for db $($adb.name)"
                    if ($adb.GetType().name -ne 'Database') {
                        $adb = Get-DbaDatabase -SqlInstance $server -Database $adb.name
                    }
                    $AvailabilityGroupBase = $adb.parent.AvailabilityGroups[$adb.AvailabilityGroupName]
                    $null = $PSBoundParameters.Remove('SqlInstance')
                    $null = $PSBoundParameters.Remove('Database')
                    $AgLoopResults = Get-DbaDbBackupHistory -SqlInstance $AvailabilityGroupBase.AvailabilityGroupListeners.name -database $adb.Name @PSBoundParameters
                    $AvailabilityGroupName = $AvailabilityGroupBase.name
                    Foreach ($agr in $AgLoopResults) {
                        $agr.AvailabilityGroupName = $AvailabilityGroupName
                    }
                    # Results already in the right format, drop straight to output
                    $AgLoopResults
                    # Remove database from collection as it is now done with
                    $databases = $databases | Where-Object Name -ne $adb.name
                }
            }
```

Because the test for availability groups is already done here:
Line 229 to 268:
```
            $AgResults = @()
            $ProcessedAgDatabases = @()
            if (($server.AvailabilityGroups.count -gt 0) -and ($agCheck -ne $True)) {
                $agShortInstance = $instance.FullName.split('.')[0]
                if ($agShortInstance -in ($server.AvailabilityGroups.AvailabilityGroupListeners).Name) {
                    # We have a listener passed in, just query the dbs specified or all in the AG
                    $null = $PSBoundParameters.Remove('SqlInstance')
                    $null = $PSBoundParameters.Remove('IncludeCopyOnly')
                    $null = $PsBoundParameters.Remove('AgCheck')
                    Write-Message -Level Verbose -Message "Fetching history from replicas on $($AvailabilityGroupBase.AvailabilityReplicas.name)"
                    $AvailabilityGroupBase = ($server.AvailabilityGroups | Where-Object { $_.AvailabilityGroupListeners.name -eq $agShortInstance })
                    $AgLoopResults = Get-DbaDbBackupHistory -SqlInstance $AvailabilityGroupBase.AvailabilityReplicas.name @PSBoundParameters -AgCheck -IncludeCopyOnly
                    $AvailabilityGroupName = $AvailabilityGroupBase.name
                    Foreach ($agr in $AgLoopResults) {
                        $agr.AvailabilityGroupName = $AvailabilityGroupName
                    }
                    if ($Last) {
                        Write-Message -Level Verbose -Message "Filtering Ag backups for Last"
                        $AgResults = $AgLoopResults | Select-DbaBackupInformation -ServerName $AvailabilityGroupName
                    } elseif ($LastFull) {
                        Foreach ($AgDb in ( $AgLoopResults.Database | Select-Object -Unique)) {
                            $AgResults += $AgLoopResults | Where-Object { $_.Database -eq $AgDb } | Sort-Object -Property FirstLsn | Select-Object -Last 1
                        }
                    } elseif ($LastDiff) {
                        Foreach ($AgDb in ( $AgLoopResults.Database | Select-Object -Unique)) {
                            $AgResults += $AgLoopResults | Where-Object { $_.Database -eq $AgDb } | Sort-Object -Property FirstLsn | Select-Object -Last 1
                        }
                    } elseif ($LastLog) {
                        Foreach ($AgDb in ( $AgLoopResults.Database | Select-Object -Unique)) {
                            $AgResults += $AgLoopResults | Where-Object { $_.Database -eq $AgDb } | Sort-Object -Property FirstLsn | Select-Object -Last 1
                        }
                    } else {
                        $AgResults += $AgLoopResults
                    }
                    # Results are already in the correct format so drop to output
                    $agresults
                    # We're done at this point so exit function
                    return
                }
            }
```

In this part there is the needed test for the listener, so this works correctly.

I don't see the additional need for the code in line 311 to 332. I have deleted the lines in my environment and it works well.

### PR DESCRIPTION
**Pull request by andreasjordan**
The recursive call of Get-DbaDbBackupHistory when trying to get
history from replicas has done this via the listener of that
availability group without testing for existance of a listener.

I added a test for existance of a listener to skip the recursive
call if non is found.

In my opinion this is the smallest possible change to solve
the issue #6607.

## Type of Change

 - [x] Bug fix (non-breaking change, fixes #6610 and #6607  )
 - [ ] New feature (non-breaking change, adds functionality, fixes # )
 - [ ] Breaking change (effects multiple commands or functionality, fixes # )
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system

### CODE REVIEW

**Comment by andreasjordan** [comment]
@Stuart-Moore : I changed your code to work with Availability Groups without listener. Can you please review the changes - maybe I have overlooked something.

**Comment by potatoqualitee** [comment]
Thanks so much, Andreas! I'll wait for @Stuart-Moore's blessing and ping him on Twitter.

**Comment by Stuart-Moore** [comment]
Looks good to me 👍

**Comment by potatoqualitee** [comment]
sweet, thank you, Stuart!

**Pull request merged**
