### PR TITLE
Move Add databases to Add-DbaAgDatabase

### PR DESCRIPTION
**Pull request by ijeb**
## Type of Change

 - [ ] Bug fix (non-breaking change, fixes #<enter issue number>)
 - [x] New feature (non-breaking change, adds functionality) #4610
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
Use the same process/code for adding a database to an existing availability group.

### Commands to test
New-DbaAvailabilityGroup -Primary sqlserver-0 -Secondary sqlserver-1 -Name ag-1 -ClusterType Wsfc -SeedingMode Automatic -Database db1 -Confirm:$false
New-DbaAvailabilityGroup -Primary sqlserver-0 -Secondary sqlserver-1 -Name ag-1 -ClusterType Wsfc -SeedingMode Manual -SharedPath '\\sqlserver-0\Share' -Database db1

### CODE REVIEW

**Comment by potatoqualitee** [comment]
hey thanks :D i think add-dbaagedatabase is missing from this pr

**Comment by ijeb** [comment]
> hey thanks :D i think add-dbaagedatabase is missing from this pr

I tried to put two commits in one PR, but it didn't work ...

**Comment by ijeb** [comment]
Added second commit

**Comment by potatoqualitee** [comment]
looks like it worked this time 👍  looking forward to seeing the test outcome

**Comment by potatoqualitee** [comment]
I added the 3 params to the unit tests to ensure we get a pass, tests are running now 👍 I do have two questions about the design

1. I saw a commented out `.SeedingMode =`, was that a question for me? Looks like it should be set or were you questioning if it should have been set when the replica joined and not at the db level? That could make sense.
2. There is a condition where there would be no output. Was that intentional?

thx

**Comment by ijeb** [comment]
1 Parameter SeedingMode
My intention is:
If not specified, the setting from the availability group replica will be used (this is the case when called from New-DbaAvailabilityGroup).
If the SeedingMode is specified the function will update the ag replica setting (and use it). I can’t update the property and don’t know why this won’t work). Can’t find any example how to do it either.
2 No. I see it now and have to look at it.

**Comment by potatoqualitee** [comment]
ah ha.. mmm

So the way i'd usually check is this `Get-DbaAgReplica -SqlInstance sql2016c | Get-Member` then look to see if SeedingMode is a `get;set;`

image

In this case it is, but I saw there are version restrictions. Are you using 2016 or above? It's also possible it can only be set at create? (I'm not sure, I generally just try stuff until it works)

**Comment by ijeb** [comment]
It's 2017. The erros is The property 'SeedingMode' cannot be found on this object. Verify that the property exists and can be set.

**Comment by potatoqualitee** [comment]
It is completely by accident that i may have figured this out? it has to be one replica at a time.

image

I didn't even really know that about PS

**Comment by ijeb** [comment]
Wow thanks, that makes sense. Now the function that at least update the property SeedingMode.

**Comment by potatoqualitee** [comment]
awesome! tests pass, thank you, i will merge and delete Test-DbaAvailabilityGroup

**Pull request merged**
