### PR TITLE
New-DbadbMaskingConfig, fix shouldprocess (do MaskingConfig)

### PR DESCRIPTION
**Pull request by niphlod**
## Type of Change

 - [x] Bug fix (non-breaking change, fixes #<enter issue number>)
 - [ ] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
New-* doesn't always require nagging user for shouldprocess....

### Approach
Tag as appropriate per PSSA rules

### CODE REVIEW

**Comment by potatoqualitee** [comment]
if you're still up, needs whatif/confirm help! same for the other one i assume

**Comment by potatoqualitee** [comment]
fixed help 👍

**Comment by niphlod** [comment]
sry, totally forgot ^_^'''

**Comment by potatoqualitee** [comment]
np fixed in prerelease!

**Pull request merged**
