### PR TITLE
Check for SMO and DMO XPs Enabled on an instance

### LINKED ISSUE #448: Need to add SMO / DMO Disabled check to Connect-SqlServer
Is this a *feature* OR *bug*:
Kind of a bug? 

**Additional comments**
If sp_configure 'SMO and DMO XPs', 0;  then SSMS bails and doesn't even try to connect. People may think that since we're command line, we can bypass a lot of the GUI stuff and thus they still won't need SMO. We should check and bail too.

image

### PR DESCRIPTION
**Pull request by shaneis**
Many thanks to @ConstantineK for the help with this one. Git and I had a few...words...to say about each other.

Fixes #448 

Changes proposed in this pull request:
 - Added configuration check for 'SMO and DMO XPs enabled' and errors out if found.
 - 
 - 

How to test this code: 
- [ ] Attempt to connect to an instance with 'SMO and DMO XPs enabled' set to 1.
- [ ] Attempt to connect to an instance with 'SMO and DMO XPs enabled' set to 0.

Has been tested on minimum requirements:
- [ ]  Powershell 3
- [ ]  Windows 7
- [ ]  SQL Server 2000

Has been tested on maximum requirements:
- [ ]  SQL Server vNext
- [ ]  Windows 10
- [ ]  Azure Database

Tests for tester:
- [ ] Working/useful help content, including link to command on dbatools web site
- [ ] All examples work as advertised
- [ ] Does not contain template content
- [ ] Does not contain excessive/unnecessary amounts of comments
- [ ] Works remotely
- [ ] Works locally
- [ ] Works on lower versions or throws error specifying version not supported
- [ ] Works with named instances
- [ ] Works with clustered instances
- [ ] Handles offline/read only databases
- [ ] Supports multiple servers (at the command line or piped from Get-SqlRegisteredServerName)
- [ ] No un-handled errors which stop the command working with multiple servers

### CODE REVIEW

**Comment by wsmelton** [comment]
If we state something has to be changed (sp_configure setting) we should offer the command in PowerShell to do it ;)

> Enable the option 'SMO and DMO XPs' on your instance using sp_configure to continue.

Compared to:

> Enable the option 'SMO and DMO XPs' on your instance with `Set-DbaSpConfigure -SqlServer MyInstance -Name 'SMO and DMO XPs' -Value 1`

**Comment by shaneis** [comment]
@wsmelton Good idea actually. I like it a lot better.
If nobody has any objections with this, I'll aim to have a commit Wednesday. 
Busy tomorrow and all that jazz

**Comment by ctrlbold** [comment]
@wsmelton, @shaneis  - Ultimately, I realized that it was usnig SMO to check for SMO -- same goes for `Set-DbaSpConfigure -SqlServer MyInstance -Name 'SMO and DMO XPs' -Value 1` - that command uses SMO as well. And I had to comment it out with a note. Please revisit using pure T-SQL instead.

**Comment by wsmelton** [comment]
I'm not sure I follow, please revisit what? 

The setting 'SMO and DMO XPs' in no way prevents you from hitting an instance utilizing SMO itself. This setting is strictly around the use of **extended procedures** that utilize SMO, which is why SSMS will bark if it is found disabled (or set to zero).

image

So are we saying just because SSMS gets it's jollies using extended stored procedures with SMO that we should not allow dbatools to function at all?

**Comment by ctrlbold** [comment]
This isn't about SSMS, but rather not having to check within every command to see if we can use SMO XPs when we need it.

To my knowledge, we use a several SMO XP's -- any command that uses Test-SqlPath uses it, Find-DbaOrphanedFile and so on. While it's possible to make an index of commands that use xps, either explicitly or implicitly, I don't know if anyone can commit lifelong time or interest to maintain the index and do the research as to what implicitly uses the XPs.

**Comment by ctrlbold** [comment]
okay, just did some testing. thank you for bringing this up @wsmelton 

I was able to perform an entire migration with the XPs being disabled on both sides, so we can skip the check in its entirety for connect-sqlserver. i was also able to execute find-dbaorphanedfile with success, so i actually have no idea which XPs are SMO specific XPs and Microsoft does not provide an index on the first page of google search.

**Pull request merged**
