### PR TITLE
Fixed Test-DbaWindowsLogin so it copes with Computer accounts

### LINKED ISSUE #3792: Make Test-DbaWindowsLogin parse computer accounts properly
---
name: Make Test-DbaWindowsLogin parse computer accounts properly :bomb:
about: Currently doesn't parse domain computer accounts, so makes my dbachecks reports look ugly against SCCM and othe systems

---

### Summary of new feature

This shouldn't happen:
image

### Proposed technical details (if applicable)

See PR

### Latest version of dbatools as of writing

* Minty fresh pull of dev

### PR DESCRIPTION
**Pull request by Stuart-Moore**
## Type of Change

 - [x] Bug fix (non-breaking change, fixes #3792 )
 - [x] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [x] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
Implements fix for #3792

Lots of apps use the AD computer account to connect (SCCM, CRM, etc) and Test-DbaWindowsLogin doesn't parse them properly

### Approach
If the account isn't matched as user, check if it's in computer name format ',*`$' and then lookup as a computer

### Screenshots
Before/After:
image

### CODE REVIEW

**Comment by niphlod** [comment]
looks good. Only thing that comes to mind are MSA and gMSAs, which have a similar format (did something on those on *spn* commands). 
Did you try with those too ? 
Unfortunately I'm still on an unsupported AD version to test those properly :-(

**Comment by wsmelton** [comment]
The only difference in format of the computer account and MSA/gMSA is that before the `$` it has the same restrictions of any AD username (which means it can't contain any of these `" / \ [ ] : ; | = , + * ? < >`). So basically just `-` or `_` in the name.

I don't see how it is handled here being an issue on either. If you wanted to take it as an MSA or gMSA though we would have to look up the property that shows it as one.

**Comment by niphlod** [comment]
No problem then

Il dom 15 lug 2018, 05:13 Shawn Melton <notifications@github.com> ha
scritto:

**Comment by potatoqualitee** [comment]
cool, so merge? 🎉

**Comment by niphlod** [comment]
Yeah, mine was just a sidenote on MSAs that unfortunately I'm unable to
test. Everything is completely fine

Il dom 15 lug 2018, 17:17 Chrissy LeMaire <notifications@github.com> ha
scritto:

**Comment by potatoqualitee** [comment]
thank you all!

**Pull request merged**
