### PR TITLE
Fixes PSUseBOMForUnicodeEncodedFile ScriptAnalyzer rule

### PR DESCRIPTION
**Pull request by maddhatter**
## Type of Change

 - [x] Bug fix (non-breaking change, fixes #<enter issue number>)
 - [ ] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [x] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
 
Fix files that violate `ScriptAnalyzer`'s  `PSUseBOMForUnicodeEncodedFile` rule.

### Approach

Re-save files in VS Code as "UTF-8 with BOM"

### CODE REVIEW

**Comment by niphlod** [comment]
good and bad, frankly having half of files with the BOM and half without isn't smarty........ like the check. 
If for some reason within the code or the docs there's something out of "normal chars" (e.g. happened with @ClaudioESSilva signature, for some accented letters), the check is triggered.
The solution by PSSCriptAnalyzer is including the BOM, mine would be to hunt down the "special character" and replace it with something not outside the range of normal chars.

**Comment by wsmelton** [comment]
@maddhatter This fix is irrelevant because we do not check for this rule with PSSA.

However, it is also a bug in that check for PSSA and it is documented in their repository. There are files that this check won't warn even though the file is only saved as UTF-8 and not UTF-8 w/ BOM. So it is an unstable check in my opinion.

**Comment by maddhatter** [comment]
I don't have a strong opinion either way, I just was going to submit a couple ScriptAnalyzer PRs from the Bill of Health post while I had some downtime during meetings, etc (multitasking, ftw).

I ran `.\tests\manual.pester.ps1 -Path .\functions\Add-DbaComputerCertificate.ps1 -ScriptAnalyzer` since it was the very first file in the Bill of Health list, and it returned that `PSUseBOMForUnicodeEncodedFile` rule for that file.

**Comment by wsmelton** [comment]
Slack discussion with @niphlod about some of this and from the standpoint of PSSA rules we do not have any that are showing errors, which would be the ones we really needed to fix.

The only thing being thrown when the manual test is run are warnings and informational rules. So I'm going to go ahead and close this PR out.

**Pull request closed without merging**
