### PR TITLE
Copy-DbaDatabase - Fill *NetBios with FullComputerName

### LINKED ISSUE #6600: Copy-DbaDatabase -DetachAttach switch is using \\SqlSERVER\M$\MSSql... without domain name causing access issue
I found an issue here with the -detachAttach switch. It doesn't take into consideration the domain name of the server when accessing the directories. Eg. \\server\serverFolder\user_dbdata\data instead of \\server.domain.com\serverFolder\user_dbdata\data

Causing this error: 
image

DetachAttach methos doesn;t allow using SharedPath instead File copies are performed over administrative shares (\\server\x$\mssql

### PR DESCRIPTION
**Pull request by andreasjordan**
## Type of Change

 - [x] Bug fix (non-breaking change, fixes #6600 )
 - [ ] New feature (non-breaking change, adds functionality, fixes # )
 - [ ] Breaking change (effects multiple commands or functionality, fixes # )
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
Use ComputerName with domain in UNC path while copying with -DetachAttach.

### Approach
Use `Resolve-DbaNetworkName`.

### Problems
* I don't know which of DNSHostEntry, FQDN or FullComputerName would be the best to use.
* I don't know if this has side affects in other network setups.
* The variable $sourceNetBios and $destNetBios now contain more information than just the NETBIOS name and thus should be changed in the code.

Generally I have a problem understanding the concept of when to use just the computer name and when to use the full name including the domain. Some commands do it one way, some the other way - I havn't seen a general concept.

So I will open this just as a draft and hope for help.

### CODE REVIEW

**Comment by potatoqualitee** [comment]
@niphlod knows best but I think it is FullComputerName

**Comment by niphlod** [comment]
yeah, I concur with myself ;-) https://github.com/sqlcollaborative/dbatools/issues/6600#issuecomment-848227095

**Comment by andreasjordan** [comment]
OK, then FullComputerName. But the question is: Shall we "fix" this?

**Comment by niphlod** [comment]
theoretically, yes. using netbios is a nice shortcut, but doesn't cover all cases.
Whenever is needed to get the underlying server running the instance, Resolve- should be used and FullComputerName holds the most accurate representation of the server name, in DNS terms, which is what the SMB "path" needs. 
I'd hope sooner or later MS fixes that, but, alas, nothing has been done to tell MSSQL that its running on a server joined to a domain, and with a particular dns entry.

**Comment by andreasjordan** [comment]
I close this as I have found a nice workaround (see https://github.com/sqlcollaborative/dbatools/issues/6600#issuecomment-848890799) that will help the user.

**Comment by niphlod** [comment]
ahum, I'd leave this up: asking users to look for a workaround when netbios doesn't work isn't "sane defaults"

**Comment by potatoqualitee** [comment]
I would like to revisit, per Simone

**Comment by andreasjordan** [comment]
This is related: #7427.

**Comment by potatoqualitee** [comment]
@ClaudioESSilva i just saw an old branch where you were working on something similar. can you take a look and give feedback?

**Comment by andreasjordan** [comment]
I would like to use the new internal command `Resolve-DbaComputerName` as introduced here: #7468.

**Comment by potatoqualitee** [comment]
Would again like @niphlod or @wsmelton's approval 👍🏼  It works in both Windows and Linux on docker, pretty cool!

**Review by niphlod — APPROVED** [review]

**Comment by potatoqualitee** [comment]
🥳

**Pull request merged**
