### PR TITLE
Tweaks to the DbaTimeline 19/03/2019

### PR DESCRIPTION
**Pull request by marcingminski**
## Type of Change

 - [x] Bug fix (non-breaking change, fixes #<enter issue number>)
 - [x] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
 
There are two improvements in this PR:

1. Cosmetic change to how JavaScript is handling backslashes. For named instances the backslash will currently not be shown on the timeline: 
`[SQL-TEST-1SQL2016] ContosoRetailDW` 
and after the tweak: 
`[SQL-TEST-1\SQL2016] ContosoRetailDW`

2. New switch `-NoRowLabels` to hide row labels and to maximise timeline area: `ConvertTo-DbaTimeline -NoRowLabels`

Please note that the job details are still available in the tooltip

### Approach

1. The backslash is now being correctly escaped (JS needs two backslashes to show one):
`"[" + $($_.SqlInstance -replace "\\", "\\\") + "] "`
2. The `NoRowLabels` switch is being used to dynamically build JS array as per the Google Docs: https://developers.google.com/chart/interactive/docs/gallery/timeline : 
```
        var options = {
            timeline: {
                rowLabelStyle: { },
                barLabelStyle: { },
                showRowLabels: $(if($NoRowLabels){'false'} else {'true'})
            },
            hAxis: {
                format: 'dd/MM HH:mm',
            },
```
### Commands to test

```
Get-DbaAgentJobHistory -SqlInstance sql-test-1\sql2016,sql-test-1\sql2017 -ExcludeJobSteps | ConvertTo-DbaTimeline -NoRowLabels | Out-File C:\temp\DbaAgentJobHistory1.html -Encoding ascii
Get-DbaAgentJobHistory -SqlInstance sql-test-1\sql2016 -ExcludeJobSteps | ConvertTo-DbaTimeline | Out-File C:\temp\DbaAgentJobHistory2.html -Encoding ascii


Get-DbaBackupHistory -SqlInstance sql-test-1\sql2016,sql-test-1\sql2017 | ConvertTo-DbaTimeline | Out-File C:\temp\DbaAgentJobHistory3.html -Encoding ascii
Get-DbaBackupHistory -SqlInstance sql-test-1\sql2016 | ConvertTo-DbaTimeline | Out-File C:\temp\DbaAgentJobHistory4.html -Encoding ascii
```
### Screenshots

Before the backslash escape tweak:
image

After the backslash escape tweak:
image

NoRowLabels option:
image

### CODE REVIEW

**Comment by marcingminski** [comment]
@potatoqualitee this is on top of your previous PR (you beat me to it, we worked on it in parallel this evening) updated with small cosmetic change and additional functionality

**Comment by potatoqualitee** [comment]
thanks so much 👍  sorry bout working in parallel, i'm eager to close issues as the Project has gamified it and my brain is cooperating so I jumped on the train ;)

These changes are fabulous! thank you so very nych

**Comment by marcingminski** [comment]
Done. FIngers crossed. How can I (or should I?) update https://docs.dbatools.io/#ConvertTo-DbaTimeline to add new parameter?

**Comment by potatoqualitee** [comment]
sorry i forgot to highlight, ExcludeRowLabel is singular ,not plural

**Comment by potatoqualitee** [comment]
docs will auto update once i publish to the gallery 😁

**Comment by marcingminski** [comment]
hmmm, `showRowLabels {}` is the exact name Google uses in their code so thought it would make sense to keep it consistent? I can change it to singular though.

**Comment by potatoqualitee** [comment]
PowerShell naming conventions favor singular, even when plural can occur. Like smo is $server.Databases but we do Database. That way it keeps things consistent. There are times that we pluralize but it's rare and has another meaning 👍

**Comment by marcingminski** [comment]
Done. Learnt something new about PS today. Thank you! I like to keep database entities singular too!

**Comment by potatoqualitee** [comment]
:banandance: will merge and publish 💯

**Pull request merged**
