### PR TITLE
Update Test-DbaMaxDop.ps1

### LINKED ISSUE #6341: Update MaxDOP calculation formula in Test-DbaMaxDop
### Summary of new feature

It appears that the formula used to calculate recommended MaxDOP in Test-DbaMaxDop is not aligned with the last review of KB2806535.
Actually, for SQL2016 or higher version, MaxDOP should be set up to 16 if multiple NUMA nodes are detected (instead of 8).
The formula is correct for older versions.

### Proposed technical details (if applicable)

Details about MaxDOP recommended values are available at: https://support.microsoft.com/en-us/help/2806535/recommendations-and-guidelines-for-the-max-degree-of-parallelism-confi

Updating the calculation formula requires only an IF condition in the actual script; I'll provide a PR to update it.

### Latest version of dbatools as of writing

1.0.88

### PR DESCRIPTION
**Pull request by OmegaMadLab**
Update to MaxDOP calculation on Test-DbaMaxDop

Update to MaxDOP formula for SQL2016+, as per last review of KB2806535

## Type of Change

 - [ ] Bug fix (non-breaking change, fixes # )
 - [X] New feature (non-breaking change, adds functionality, fixes #6341)
 - [ ] Breaking change (effects multiple commands or functionality, fixes # )
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
This PR updates the formula used for calculation of recommended MaxDOP, as per last review of KB2806535 (https://support.microsoft.com/en-us/help/2806535/recommendations-and-guidelines-for-the-max-degree-of-parallelism-confi).
Actually, for SQL2016+ the MaxDOP value can go up to 16, if multiple NUMA nodes are detected.

### Approach
Simply added an IF condition, checking for instance version, if more than a single NUMA node is detected

### CODE REVIEW

**Comment by potatoqualitee** [comment]
Hey @OmegaMadLab ! Thanks so much for the PR, my apologies for the delayed review. I'll take a look today.

**Comment by potatoqualitee** [comment]
This looks great - thank you for providing the reasoning and link 💯

**Comment by OmegaMadLab** [comment]
It was a pleasure! I appreciate so much the module and the work the team is doing! I hope this one will be the first of my contributions!

**Comment by potatoqualitee** [comment]
Looking forward to it! Your changes are now in the PowerShell Gallery 🎉

**Pull request merged**
