### PR TITLE
Use CONVERT and InvariantCulture with .ToString

### LINKED ISSUE #6452: [Bug] Backup-DbaDatabase | Conversion failed
#### PowerShell version:
```powershell

Name                           Value
----                           -----
PSVersion                      5.1.17763.1007
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.1007
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1


#### dbatools Module version:

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.104\dbatools.psd1
Version : 1.0.104
```

```powershell

LCID             Name             DisplayName
----             ----             -----------
1035             fi-FI            Finnish (Finland)
```

#### SQL Server:

```sql
Microsoft SQL Server 2017 (RTM-CU17) (KB4515579) - 14.0.3238.1 (X64)   Sep 13 2019 15:49:57   Copyright (C) 2017 Microsoft Corporation  Developer Edition (64-bit) on Windows 10 Enterprise 10.0 <X64> (Build 17763: ) (Hypervisor) 
```

```sql
us_english
```

### Report

I am afraid this dbatools backup related issue #5749 (and its related issues: #5751 #5748 #5744 #5742 #5308 #5024) might still exist as I am still getting same symptoms with latest dbatools on my box (having Finnish locale).

I checked the [related PR](https://github.com/sqlcollaborative/dbatools/pull/5753)  that tries to fix that issue and noticed that in Get-DbaBackupHistory it still has one place (line number 660) that is missing the CONVERT fix that was applied elsewhere in that PR, so I believe this missing convert might be still causing different issues with many backup related commands.

For example Backup-DbaDatabase warns me about backup failure (although it seemed to do it):
```
WARNING: [16.14.05][Backup-DbaDatabase] Backup Failed | Conversion failed when converting date and/or time from character string.
```

And that Get-DbaDbBackupHistory fails with an unhandled exception:
```
Exception calling "ExecuteWithResults" with "1" argument(s): "An exception occurred while executing a Transact-SQL statement or batch."
At C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.104\allcommands.ps1:22515 char:13
+             $results = $server.ConnectionContext.ExecuteWithResults($ ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ExecutionFailureException
```

#### Host used

- [x] powershell.exe
- [ ] ISE
- [ ] VS Code
- [ ] Other (please specify)

#### Errors Received

```


PSMessageDetails      :
Exception             : System.Management.Automation.MethodInvocationException: Exception calling "ExecuteWithResults"
                        with "1" argument(s): "An exception occurred while executing a Transact-SQL statement or batch.
                        " ---> Microsoft.SqlServer.Management.Common.ExecutionFailureException: An exception occurred w
                        hile executing a Transact-SQL statement or batch. ---> System.Data.SqlClient.SqlException: Conv
                        ersion failed when converting date and/or time from character string.
                           at Microsoft.SqlServer.Management.Common.ConnectionManager.ExecuteTSql(ExecuteTSqlAction act
                        ion, Object execObject, DataSet fillDataSet, Boolean catchException)
                           at Microsoft.SqlServer.Management.Common.ServerConnection.ExecuteWithResults(String sqlComma
                        nd, Boolean retry)
                           --- End of inner exception stack trace ---
                           at Microsoft.SqlServer.Management.Common.ServerConnection.ExecuteWithResults(String sqlComma
                        nd, Boolean retry)
                           at CallSite.Target(Closure , CallSite , Object , Object )
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.ExceptionHandlingOps.ConvertToMethodInvocationException(Exce
                        ption exception, Type typeToThrow, String methodName, Int32 numArgs, MemberInfo memberInfo)
                           at CallSite.Target(Closure , CallSite , Object , Object )
                           at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 a
                        rg1)
                           at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedF
                        rame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedF
                        rame frame)
TargetObject          :
CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
FullyQualifiedErrorId : ExecutionFailureException
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Get-DbaDbBackupHistory<Process>, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.104
                        \allcommands.ps1: line 22515
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}
```

### LINKED ISSUE #6909: [Bug] .ToString("yyyy-MM-dd HH:mm:ss") is not "culture safe" and ":" can be converted to "."
I open this issue to discuss a general solution for converting datetimes into strings.

We found this here: https://github.com/sqlcollaborative/dbatools/issues/6452

I used VSCode and searched the code for "yyyy-MM-ddTHH:mm:ss" and found this in:
* Get-DbaDbBackupHistory
* Get-DbaDbMailHistory
* Get-DbaDbMailLog
* Get-DbaDbRestoreHistory

I used VSCode and searched the code for "yyyy-MM-dd HH:mm:ss" and found this in:
* Export-DbaExecutionPlan
* Get-DbaExecutionPlan
* Get-DbaRandomizedValue
* Invoke-DbaDbDataMasking

@niphlod came up with `.ToString("yyyy-MM-ddTHH:mm:ss", [System.Globalization.CultureInfo]::InvariantCulture)`.

Are there other ideas?

### PR DESCRIPTION
**Pull request by andreasjordan**
## Type of Change

 - [x] Bug fix (non-breaking change, fixes #6909, fixes #6452 )
 - [ ] New feature (non-breaking change, adds functionality, fixes # )
 - [ ] Breaking change (effects multiple commands or functionality, fixes # )
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system

### CODE REVIEW

**Comment by andreasjordan** [comment]
Coding is finished, will do tests tomorrow.

**Comment by potatoqualitee** [comment]
sweet as heck, thanks @andreasjordan !

**Comment by andreasjordan** [comment]
Ok, did some tests, looked good.

**Review by niphlod — APPROVED** [review]

**Comment by potatoqualitee** [comment]
Thank you both 🙇 🏆 !

**Pull request merged**
