### PR TITLE
Issue6402 copy dba database supportdbs

### LINKED ISSUE #6402: [Bug] - SSISDB not included in support DBs
#### PowerShell version:

                                                                                                                                 
PSVersion                      5.1.14393.3471                                                                                                                            
PSEdition                      Desktop                                                                                                                                   
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                   
BuildVersion                   10.0.14393.3471                                                                                                                           
CLRVersion                     4.0.30319.42000                                                                                                                           
WSManStackVersion              3.0                                                                                                                                       
PSRemotingProtocolVersion      2.3                                                                                                                                       
SerializationVersion           1.1.0.1                                                                                                                                   

#### dbatools Module version:

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.101\dbatools.psd1
Version : 1.0.101

#### SQL Server: 

```sql
Microsoft SQL Server 2017 (RTM) - 14.0.1000.169 (X64)   Aug 22 2017 17:04:49   Copyright (C) 2017 Microsoft Corporation  Standard Edition (64-bit) on Windows Server 2016 Datacenter 10.0 <X64> (Build 14393: ) (Hypervisor) 
```

#### Host used

- [x] powershell.exe
- [X] ISE
- [ ] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can du licate the issue wit  powershell.exe

- [X] Still buggy in powershell.exe

#### Expected Behavior
Not migrate SSISDB

#### Actual Behavior

Migrated SSISDB, causing issues with all my pre-staged SSIS packages.
Based on documentation in both copy-DbaDatabase and Start-DbaMigration, that shouldn't happen. 

#### Fix
on dbatools/functions/Copy-DbaDatabase.ps1

Line 933: $SupportDBs = "ReportServer", "ReportServerTempDB", "distribution"
Should read: $SupportDBs = "ReportServer", "ReportServerTempDB", "distribution", "SSISDB"

### PR DESCRIPTION
**Pull request by MikeyBronowski**
## Type of Change

 - [x] Bug fix (non-breaking change, fixes #6402 )

### Purpose
Documentation says SSISDB is not included in the process by default, but it was not excluded in the code.

### Approach
Added database to the list and updated example to match the code.

### CODE REVIEW

**Comment by wsmelton** [comment]
Would you like to take a stab at updating the test to cover this change? 🥺

**Comment by MikeyBronowski** [comment]
Good point.
Will take a look tomorrow.

**Comment by MikeyBronowski** [comment]
@wsmelton I've added the test. Hope it's fine.

**Comment by potatoqualitee** [comment]
looks fab 👍 Thank you both!

**Pull request merged**
