### PR TITLE
Here is a small change that reruns failed jobs 

### PR DESCRIPTION
**Pull request by andrewn2000**
## Type of Change

 - [ ] Bug fix (non-breaking change, fixes #<enter issue number>)
 - [X] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
While reviewing Find-DbaAgentJob, it lists all the jobs, but doesn't do anything with them.  I had a couple of failures on multiple servers.  I needed this switch to rerun all the jobs.

### Approach
It's clean and easy.  Just use a switch and check if its turned on.  If so, just start the job.  I imagine you can add additional functionality, but I wanted it quick and simple.

My other DBAs were asking for this functionality as this past weekend I ended up doing these manually through SSMS, and although I was working with a list, it was quite painful.  And this isn't the first time we're doing something like this as we always seem to have SAN issues running out of space or not being available.  Then we'll spend sometimes the next couple of hours or days rerunning jobs.  This is going to save us *TONS* of time because we're doing 125+ SQL servers

### Commands to test
Get-DbaRegisteredServer -SqlInstance ServerCMS1 -Group DEV | Find-DbaAgentJob  -IsFailed -Verbose -RestartJob

### Screenshots

`PS C:\windows> Get-DbaRegisteredServer -SqlInstance ServerCMS1 -Group DEV | Find-DbaAgentJob  -IsFailed -Verbose -RestartJob`

VERBOSE: [Find-DbaAgentJob][14:33:26] Running Scan on: CALV-SQLDEV2
VERBOSE: [Find-DbaAgentJob][14:33:27] Connecting to CALV-SQLDEV2
VERBOSE: [Find-DbaAgentJob][14:33:28] Checking for failed jobs.
VERBOSE: [Find-DbaAgentJob][14:33:28] Running Scan on: CALV-SQLDEV3
VERBOSE: [Find-DbaAgentJob][14:33:28] Connecting to CALV-SQLDEV3
VERBOSE: [Find-DbaAgentJob][14:33:30] Checking for failed jobs.

ComputerName    : CALV-SQLDEV3
InstanceName    : MSSQLSERVER
SqlInstance     : CALV-SQLDEV3
JobName         : DatabaseBackup - SYSTEM_DATABASES - FULL
LastRunDate     : 9/27/2017 2:32:41 PM
LastRunOutcome  : Failed
IsEnabled       : False
CreateDate      : 
HasSchedule     : True
OperatorToEmail : DBA
Category        : Database Maintenance
OwnerLoginName  : sa

**VERBOSE: [Find-DbaAgentJob][14:33:30] Attempt to Restart** 
VERBOSE: [Find-DbaAgentJob][14:33:30] Running Scan on: CALV-SQLDEV4
VERBOSE: [Find-DbaAgentJob][14:33:30] Connecting to CALV-SQLDEV4
VERBOSE: [Find-DbaAgentJob][14:33:31] Checking for failed jobs.
VERBOSE: [Find-DbaAgentJob][14:33:31] Running Scan on: CALV-SQLDEV5
VERBOSE: [Find-DbaAgentJob][14:33:31] Connecting to CALV-SQLDEV5
VERBOSE: [Find-DbaAgentJob][14:33:32] Checking for failed jobs.
ComputerName    : CALV-SQLDEV5
InstanceName    : MSSQLSERVER
SqlInstance     : CALV-SQLDEV5
JobName         : DatabaseBackup - USER_DATABASES - FULL
LastRunDate     : 9/27/2017 2:32:43 PM
LastRunOutcome  : Failed
IsEnabled       : True
CreateDate      : 
HasSchedule     : True
OperatorToEmail : DBA
Category        : Database Maintenance
OwnerLoginName  : sa

**VERBOSE: [Find-DbaAgentJob][14:33:32] Attempt to Restart**

### CODE REVIEW

**Comment by potatoqualitee** [comment]
Very nice! 💃 ! Will merge once I create a test, thank youuuuuu

**Comment by niphlod** [comment]
Find- cannot restart....

**Comment by potatoqualitee** [comment]
You make a good point, @niphlod. We should pipe the results to Start-DbaAgentJob instead. We don't have Start-DbaAgentJob yet, however.

Until Start-DbaAgentJob is created, I will accept this PR then update the command and Andrew once the new command has been merged 🌻

**Comment by niphlod** [comment]
🆗 👌 🙆‍♂️ 🙆 👍

**Comment by andrewn2000** [comment]
Chrissy, 

Thanks for doing that so quickly as my DBAs really wanted me to start
developing more....guess I'd better get used to using GitHub!   

Thanks for also sending CK over to help.  It was like having a personal
training to help me on that. 

The presentation went well.  I should have the recording up by the end
of this week. 

Although I just realized that its pretty basic compared to all your
other videos and I should update them.
I've been asked to speak at the local user group, but didn't want to
rehash this again.  Maybe I'll learn get some good ideas from the
precon. 

See you then! 

Andy 

On 2017-09-28 09:09, Chrissy LeMaire wrote:

> Merged #2347 [1]. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3].

  

Links:
------
[1] https://github.com/sqlcollaborative/dbatools/pull/2347
[2]
https://github.com/sqlcollaborative/dbatools/pull/2347#event-1270117484
[3]

**Pull request merged**
