### PR TITLE
Moving code block to always fire

### LINKED ISSUE #2551: IgnoreLogBackups does not completely ignore.
- [X] Verified running latest release of dbatools?
- [X] Verified errors are not related to permissions?
- [X] Can duplicate in new/fresh PowerShell.exe session?

 - Operating System (Name|Version): Windows 2012
 - PowerShell Version: 3
 - SQL Server (Edition|Version): SQL 2014

## Steps to Reproduce
Have database with log backups.
Delete most recent Differential backup so that command will fail.
Run Test-DBALastBackup with -IgnoreLogBackups and without -CopyFile.
See that while log backups were not restored they are shown in the output.

### PR DESCRIPTION
**Pull request by josh-simar**
Code block for checking IgnoreLogBackup should always fire for this instead of only firing if doing Copy. This makes output from this command better as even when running IgnoreLogBackup it is outputting logs in the result.

## Type of Change

 - [X] Bug fix (non-breaking change, fixes #2551)
 - [ ] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
Allow check code to always fire as it should not be dependent on the code it is embedded in currently.

### Approach
Moved code to outside if block but right above as if block does use output.

### CODE REVIEW

**Comment by wsmelton** [comment]
@gbargsley can you do the same on the current version of the command in PSGallery/master and show those?

**Comment by josh-simar** [comment]
Sorry all, royally screwed this up.
Let me get some screenshots and some better outputs to explain better. Give me a few minutes.

**Comment by josh-simar** [comment]
With current code this is the output of script:
image

With the new code this is the output of script:
image

Here is my test script for this (please substitute your own source, destination, and database as needed.

`Import-Module dbaTools

$TestResult = Test-DbaLastBackup -SqlInstance $YourInstance -Destination $MyInstance -Database $YourDatabase -IgnoreLogBackup

$msg = ""
$msg2 = ""

foreach ($BackupFile in $TestResult.BackupFiles)
{
    $msg += "$BackupFile`n"
}

foreach ($BackupDate in $TestResult.BackupDate)
{
    $msg2 += "$BackupDate`n"
}

Write-Host $msg
Write-Host $msg2

`

**Comment by josh-simar** [comment]
No missing files are required to do these tests.

**Comment by Stuart-Moore** [comment]
@gbargsley  - 1 & 2 are what I'd expect from the restore stack with a missing file. Test-DbaLastBackup relies on SQL backup history, which doesn't do well with missing files (we trust it, but not so much we don't test for a missing file, as we don't want to restore something you didn't ask for!)

Or are you actually wanting a IgnoreDiffBackup switch? As that's potentially how I read what you're testing there.

**Comment by potatoqualitee** [comment]
Sup, yall?

**Comment by potatoqualitee** [comment]
hey guys, can we get some movement here? @josh-simar do you need any additional information from anyone?

**Comment by potatoqualitee** [comment]
Closing this PR for now - please resubmit and request a review from garry if it's still valid. Thanks much and sorry!

**Pull request closed without merging**
