### PR TITLE
Add version 11.0.6251 to build file

### PR DESCRIPTION
**Pull request by LowlyDBA**
## Type of Change

 - [x] Bug fix (non-breaking change, fixes #<enter issue number>)
 - [ ] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
Adding version 11.0.6251 to the build list

### Approach
Adds a ref in the JSON file

### Commands to test
N/A

### Screenshots
N/A

### CODE REVIEW

**Comment by niphlod** [comment]
This one is good!

Il 28 set 2017 10:26 PM, "John McCall" <notifications@github.com> ha
scritto:

**Comment by potatoqualitee** [comment]
awesome, thank you @LowlyDBA! The data is good, I just had to clean up the UNICODE characters that somehow got inserted.

**Comment by potatoqualitee** [comment]
Will merge once tests pass 👍

**Comment by potatoqualitee** [comment]
heck yah, all passed!

**Pull request merged**
