### PR TITLE
Copy-DbaDatase Managed instance ready, and Azure blob support for sharedpath

### PR DESCRIPTION
**Pull request by Stuart-Moore**
## Type of Change

 - [ ] Bug fix (non-breaking change, fixes #<enter issue number>)
 - [x] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [x] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
Copy-DbaDatabase now supports using Azure blob storage as the shared path, and the target being an Azure Managed instance

Blob storage option also gives an option for people who want to migrate securely between domains/forests without any trust. Yes, there's some latency, but not as much as spinning up an insecure intermediate box and getting the Sec officer to sign off on it ;)

### Commands to test
```
$results = Copy-DbaDatabase -Source localhost -Database  mitest -DestinationSqlCredential $cred -Destination dbatoolsmi.cus19c972e4513d6.database.windows.net -SharedPath  https://twitchd
ba.blob.core.windows.net/sql -NewName c3ptest -BackupRestore 
```

### CODE REVIEW

**Comment by potatoqualitee** [comment]
:bananadance:!!!!

**Comment by Stuart-Moore** [comment]
Just realised I've not added examples, will do that and then merge

**Comment by Stuart-Moore** [comment]
Different box and the formatting works 🤦‍♂️ more time formatting than coding 🤷‍♂️

**Comment by potatoqualitee** [comment]
quick note to @Stuart-Moore and @wsmelton  - when merging, please use squash and merge. This will reduce the number of individual commits to the repo.

image

There are two exceptions (that apply primarily to me and Shawn).

1. When there is a first time contributor - squashing their commits makes their contribution not count towards the contributors list.
2. When I merge to master, I cannot use squash and merge or there are junkloads of conflicts. I don't get it but w/e.

ty 🙇

**Comment by potatoqualitee** [comment]
also, about the contributors thing, i wrote to githbu about it but they say it's by design so not much hope there

**Pull request merged**
