### PR TITLE
added integration test to CopyDbaAgentProxy

### PR DESCRIPTION
**Pull request by gbargsley**
## Type of Change

 - [ ] Bug fix (non-breaking change, fixes #<enter issue number>)
 - [ ] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [X] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
 
Added integration test to the Copy-DbaAgentProxy test
### Approach

Integration test request for help

### CODE REVIEW

**Comment by potatoqualitee** [comment]
YESSSSSSSSSSSSSSSSSSSSS! Thank you, Garry!! awesome 💃

**Comment by gbargsley** [comment]
Failed :(

**Comment by gbargsley** [comment]
I cannot test locally since I only have one instance.  I am looking for the bits to install a 2016 instance.  And our security is so tight I cannot get docker to work.

If anyone can tell why this failed I can update the PR.

**Comment by potatoqualitee** [comment]
when i tested your code, it failed on the second batch of deletes. Maybe try naming it $server2 instead? shouldn't have to but this is what I got:

` The specified @proxy_name ('dbatoolsci_agentproxy') does not exist.`

` Cannot drop the credential 'dbatoolsci_credential', because it does not exist or you do not have permission.`

but my setup is slightly different. may need to login to htat server to see what's up. try to do it w/o $sql = "DROP CREDENTIAL dbatoolsci_credential"
        $server.Query($sql)?

maybe it's not copying the credential?

**Comment by gbargsley** [comment]
You have to execute the sql.  Did not have $server.Query on the credential create on Instance3.

**Comment by gbargsley** [comment]
Double green....

**Comment by potatoqualitee** [comment]
boooooooooooom! 🎉

**Comment by potatoqualitee** [comment]
thank you 💃

**Pull request merged**
