### PR TITLE
Update Invoke-ManagedComputerCommand.ps1

### PR DESCRIPTION
**Pull request by pkotov87**
User must pass permissions

## Type of Change

 - [ ] Bug fix (non-breaking change, fixes #<enter issue number>)
 - [ ] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [x] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system

### CODE REVIEW

**Comment by pkotov87** [comment]
test

**Comment by pkotov87** [comment]
test

**Comment by potatoqualitee** [comment]
aw why'd you close it? that was a legit change? 🎉

**Comment by pkotov87** [comment]
That was misunderstanding from my side.

**Comment by potatoqualitee** [comment]
fantastic 💯  will merge after tests complete. did this solve a local issue for you?

**Comment by potatoqualitee** [comment]
code checks out and tests pass 🎉

**Pull request merged**
