### PR TITLE
Install-DbaMaintenanceSolution

### PR DESCRIPTION
**Pull request by cviorel**
Download and Install SQL Server Maintenance Solution created by Ola Hallengren

## Type of Change

 - [ ] Bug fix (non-breaking change, fixes #<enter issue number>)
 - [ ] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Pester test is included

### CODE REVIEW

**Comment by potatoqualitee** [comment]
Thanks so much @cviorel! I shall accept and patch. It'll pretty much just need a rename and I'll add the required help from another command 👍 Hope to see more from you!

**Comment by niphlod** [comment]
reminder: as discussed in the channel, before merging, it'd be good to have it match other install-* cmdlets and having a param to just install the base procedures instead of the whole solution, as there will be many that tuned ola's default jobs to match each specific need.

**Comment by cviorel** [comment]
@niphlod, that's a good point, I will add this logic to the script.
Thanks!

**Comment by potatoqualitee** [comment]
@cviorel - please add the following validated parameter set which allows the user to pass more than one solution

```
[ValidateSet('Backup', 'IntegrityCheck','IndexOptimize')]
[string[]]$Solution,
```

then
```
if (!$Solution) { 
   $Solution = 'Backup', 'IntegrityCheck','IndexOptimize'
}
```
then `foreach ($part in $solution) { if $part -eq 'Backup' ..... }`

Merci! 🍺

**Comment by potatoqualitee** [comment]
Gonna merge and create tests! Thanks so much!

**Pull request merged**
