### PR TITLE
Update to Test-DbaTempDbConfiguration

### LINKED ISSUE #2165: Test-DbaTempDbConfiguration suggestion for change
## Feature Request

 Simply answer the question: What problem or scenario would you like to solve with dbatools?

I'm currently working on setting up a pester test for our SQL servers. In this I use Test-DbaTempDbConfiguration to figure out if we are following best practies. I have som cases where it has been decided to use fewer tempdb files than is best practies. Since the command returns a string as output when it's OK and a PScustomobject when its not its hard to write a good pester test. 

Suggestion is that also make the output on success a PSCustomObject that follow the same standard as the error output. The string that is the output today can be moved to the notes.

This way I can work on the pscustombject and check IsBestpractises, Recomended or currentsettings to see if I follow our setup on the sql server.

### PR DESCRIPTION
**Pull request by wsmelton**
## Type of Change

 - [x] Address #2217 
 - [ ] New feature (non-breaking change, adds functionality)
 - [x] Breaking change fixes #2165 
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Pester test is included

### Purpose
To bring command up to the standard of other commands and output object no matter what, not just an output if IsBestPractice returns all true. As well have default output, adjusted to just require SELECT * to get that notes property.

### Approach
- Removed detailed parameter
- Updated help
- changed servername to instance on foreach
- added -MinimumVersion 9 to connect command, dropped version check
- updated ExecuteQueryWithResults to use Query() method
- Changed IsBestpractice to IsBestPractice
- Changed T-SQL to get file info for tempdb to use Get-DbaDatabaseFile
- Changed write-verbose to write-message
- Added Silent parameter to param block and help
- changed output to have basic properties, use select * to see the notes property
- removed code from end block so it outputs full object

### Screenshots

image

image

Previous version of the command only output those that were false for the `IsBestpractice`

image

### CODE REVIEW

**Comment by potatoqualitee** [comment]
ouuu this is nice, i'll merge and write a test once tests have passed

**Comment by wsmelton** [comment]
I was contemplating the test part while I was writing up the PR. Based on the other "tests" files for the Test commands there would be some mocking required for this one?

**Comment by potatoqualitee** [comment]
I suppose, though I think there could be integration tests with real testing as well 👍

**Comment by potatoqualitee** [comment]
added test :monkeydance:

**Pull request merged**
