### PR TITLE
Set-DbaPowerPlan - Implement a workaround for server 2019

### LINKED ISSUE #6505: [Bug] Set-DbaPowerPlan fails on WS2019
<!--
🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
The core team may close bug reports that do not follow our provided template.

The information we ask for helps to better troubleshoot the report. We release frequently and often, this information helps to resolve the issue more efficiently.
-->

<!--
dbatools 1.0 has been released as of June 20, 2019
Please ensure you are on this version before submitting an issue
-->

### Environmental information

```
#### PowerShell version:
Name                           Value                                                                                                                                                                                                                                       
----                           -----                                                                                                                                                                                                                                       
PSVersion                      5.1.17763.1007                                                                                                                                                                                                                              
PSEdition                      Desktop                                                                                                                                                                                                                                     
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                                                                                     
BuildVersion                   10.0.17763.1007                                                                                                                                                                                                                             
CLRVersion                     4.0.30319.42000                                                                                                                                                                                                                             
WSManStackVersion              3.0                                                                                                                                                                                                                                         
PSRemotingProtocolVersion      2.3                                                                                                                                                                                                                                         
SerializationVersion           1.1.0.1                                                                                                                                                                                                                                     

#### dbatools Module version:
Name    : dbatools
Path    : C:\Users\a-bent\Documents\WindowsPowerShell\Modules\dbatools\1.0.107\dbatools.psd1
Version : 1.0.107

```

```powershell
LCID             Name             DisplayName
----             ----             -----------
5129             en-NZ            English (New Zealand)
```

### Report

On Windows Server 2019, the Set-DbaPowerPlan command fails as it appears the 'Activate' Cim Method for Win32_PowerPlan appears to be broken.

This seems to be widely reported in other community projects:

- [ComputerManagementDsc Issue #155](https://github.com/dsccommunity/ComputerManagementDsc/issues/155)
- [Ansible Issue #43827](https://github.com/ansible/ansible/issues/43827)

Like other projects, it looks like the only option is to use the Windows APIs via `powercfg.exe` command.

#### Host used

- [x] powershell.exe
- [ ] ISE
- [ ] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [ ] Still buggy in powershell.exe

#### Errors Received

```
writeErrorStream      : True
PSMessageDetails      : 
Exception             : System.Exception: Couldn't set the requested Power Plan 'High Performance' on sqlserver.
TargetObject          : sqlserver
CategoryInfo          : ConnectionError: (sqlserver:PSObject) [Write-Error], Exception
FullyQualifiedErrorId : dbatools_Set-DbaPowerPlanInternal,Stop-Function
ErrorDetails          : Couldn't set the requested Power Plan 'High Performance' on sqlserver.
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Stop-Function, C:\Users\username\Documents\WindowsPowerShell\Modules\dbatools\1.0.107\allcommands.ps1: line 82910
                        at Set-DbaPowerPlanInternal, C:\Users\username\Documents\WindowsPowerShell\Modules\dbatools\1.0.107\allcommands.ps1: line 65811
                        at Set-DbaPowerPlan<Process>, C:\Users\username\Documents\WindowsPowerShell\Modules\dbatools\1.0.107\allcommands.ps1: line 65849
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {0, 1}
```

#### Steps to Reproduce

Run the Set-DbaPowerPlan command on a fresh deployment of Windows Server 2019

```powershell
Set-DbaPowerPlan -ComputerName sqlserver
```

#### Expected Behavior

Windows Power Plan to be set to 'High Performance'

#### Actual Behavior

Error thrown and Power Plan failed to update.

### PR DESCRIPTION
**Pull request by andreasjordan**
Because the activate method for powerplans is broken
on windows server 2019, we now use the windows tool powercfg
as a fallback.

## Type of Change

 - [x] Bug fix (non-breaking change, fixes #6505 )
 - [ ] New feature (non-breaking change, adds functionality, fixes # )
 - [ ] Breaking change (effects multiple commands or functionality, fixes # )
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
I want to use Set-DbaPowerPlan on windows server 2019

### Approach
I used the windows tool powercfg as a fallback just for setting the plan. Everything else (like getting the plans and even the GUID of the desired plan) is still working well on 2019.

### Alternative Approach
It would also be possible to use the windows DLL (have a look at https://github.com/sqlcollaborative/dbatools/issues/6505#issuecomment-663997294), but that would need more lines of code.

### Some info to better understand the code

A try-catch around Invoke-CimMethod doesn't work, so -ErrorAction SilentlyContinue is used.

```
PS C:\Users\Administrator> $cimInstance                            

Caption        : 
Description    : Favors performance, but may use more energy.
ElementName    : High performance
InstanceID     : Microsoft:PowerPlan\{8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c}
IsActive       : False
PSComputerName : SRV3
```

### CODE REVIEW

**Comment by wsmelton** [comment]
If this is broken in the set command wouldn't the get command require updating as well?

We can't supply a message that it might be because of 2019. We should include checking the OS version so we know it needs the call to the API.

**Comment by andreasjordan** [comment]
As I said: Only the activate method is broken.
Get-DbaPowerPlan just works fine, Test-DbaPowerPlan as well.

Ok, checking for the version would be better. Do we have already code for that?

**Comment by wsmelton** [comment]
I'm not all that fond of calling the utilities in Windows Server because they can change and become broken at any time. 

Any reason we can't just use the same method DSC module uses, it seems pretty simply and not that much extra coding?

https://github.com/dsccommunity/ComputerManagementDsc/blob/49beec359c838bf107a6cc932dcb572ec22954cd/source/Modules/ComputerManagementDsc.Common/ComputerManagementDsc.Common.psm1#L532-L576

**Comment by wsmelton** [comment]
On checking OS version, think just calling the `Get-DbaOperatingSystem` would be sufficient to grab that value.

**Comment by andreasjordan** [comment]
Ok, the DSC-Code is smaller than the Anible-Code I already found.
I will try to implement this later today.

**Comment by andreasjordan** [comment]
@wsmelton I need your expertise on using Get-DbaOperatingSystem.
```
PS C:\Users\Administrator> Get-DbaOperatingSystem -ComputerName SRV3


ComputerName       : SRV3.Company.Pri
Manufacturer       : Microsoft Corporation
Organization       : Virtual Engine
Architecture       : 64-bit
Version            : 10.0.17763
OSVersion          : Microsoft Windows Server 2019 Standard Evaluation
LastBootTime       : 2020-07-27 07:57:56.309
LocalDateTime      : 2020-07-27 09:32:20.180
PowerShellVersion  : 5.1
TimeZone           : (UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna
TotalVisibleMemory : 2.74 GB
ActivePowerPlan    : Balanced
LanguageNative     : English (United States)




PS C:\Users\Administrator> Get-DbaOperatingSystem -ComputerName SRV2


ComputerName       : SRV2.Company.Pri
Manufacturer       : Microsoft Corporation
Organization       : Virtual Engine
Architecture       : 64-bit
Version            : 10.0.14393
OSVersion          : Microsoft Windows Server 2016 Standard Evaluation
LastBootTime       : 2020-07-27 07:57:56.608
LocalDateTime      : 2020-07-27 09:32:43.038
PowerShellVersion  : 5.1
TimeZone           : (UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna
TotalVisibleMemory : 1.51 GB
ActivePowerPlan    : High performance
LanguageNative     : English (United States)
```

Should I test for "2019" in OSVersion or should I test Version against a (currently unknown) first version of windows server 2019?

**Comment by andreasjordan** [comment]
Or should we use the new set-method on all systems? Then I do not need to get the OSVersion.

**Comment by wsmelton** [comment]
17763 is Server 2019 1809 build, higher than that will be the semi-annual builds (1903, 1909)

**Comment by andreasjordan** [comment]
@wsmelton Without testing for OSVersion now, because this is maybe also needed for other versions like Server 2012 R2 core or Nano Server (as mentioned in the comments of the DSC code).

**Comment by wsmelton** [comment]
Have not heard of anyone having issue with our current code on 2012 R2.

**Comment by andreasjordan** [comment]
So I should implement the Get-DbaOperatingSystem? And then use the dll only on 17763 or higher?

**Comment by andreasjordan** [comment]
Does anyone know, why the AppVeyor-Test (Invoke-DbaDbClone Integration Tests) is failing?

**Comment by wsmelton** [comment]
@andreasjordan that test fails often and can just be ignored if your PR does not touch it.

**Pull request merged**
