### PR TITLE
Fix example connect dbainstance

### PR DESCRIPTION
**Pull request by Splaxi**
## Type of Change

 - [X] Documentation
 

### Purpose
Update example documentation based on my automated example testing script

### CODE REVIEW

**Comment by wsmelton** [comment]
@splaxi for pure doc updates it is easier for us to review just putting them in one PR instead of creating multiple.

**Comment by Splaxi** [comment]
Sorry - I will try and remember that for next time.

My personal process is a bit more iterative per command / function on my end, based on the scripts and tools I run. Which makes it easier to keep as single branches.

**Comment by wsmelton** [comment]
In our situation current commit in each PR is firing off our full suite of test in Appveyor. Mind you not a deal breaker, just a bit of overkill for documentation updates.

Still appreciate the PRs though 😉

**Comment by wsmelton** [comment]
You do have something off on your branching though because a handful of commits are showing up in all your PRs.

**Pull request merged**
