### PR TITLE
Invoke-DbaAdvancedRestore, fixes #2878

### LINKED ISSUE #2878: Restore-DbaDatabase Progress bar no longer works
### General Troubleshooting steps

- [X] Verified running latest release of dbatools?
- [X] Verified errors are not related to permissions?
- [X] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - Operating System (Name|Version): Windows Server 2016
 - PowerShell Version: 5.1.14393.1532
 - SQL Server (Edition|Version): Target 2016 13.0.4422

## Steps to Reproduce
`Restore-DbaDatabase -Path \\server1\BackupTest\Backups\ -SqlInstance server1 -useDestinationDefaultDirectories`

image
Progress stays at 0% until it's finished and it just closes. Restore works fine, just doesn't report progress.

## Additional Info
Tested with latest dev version too (0.9.128) and still have the issue

### PR DESCRIPTION
**Pull request by niphlod**
## Type of Change
 - [x] Bug fix (non-breaking change, fixes #2878)
 - [ ] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [x] Pester test is included
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 
### Purpose
Adding back proper progress info about restore.

Plus a small touch on tests to be able to run even when you don't have a 2008R2 instance (remember the old karma, "everyone should be able to run tests in their own environment"). We'd need to rewrite that piece that now is skipped making sure -StandbyDirectory and -Continue are working even if the instance is not a 2008R2. For the time being, instead of failing, the test is skipped when conditions are not met.

Hopefully it'll go better than https://github.com/sqlcollaborative/dbatools/pull/2963 .

### CODE REVIEW

**Comment by potatoqualitee** [comment]
fantastic! thank you @niphlod - @Stuart-Moore or @Zhunya would you guys be able to test?

**Comment by Stuart-Moore** [comment]
Doesn't seem to like Get-DbaBackupHistory pipeline:
image

Running the Restore-DbaDatabase.Tests.ps1 locally all the pipe tests fail
image
image

image


No idea why they've passed on Appveyor.

**Comment by niphlod** [comment]
I'll take a look in a few hours

Il 25 gen 2018 5:41 PM, "Stuart Moore" <notifications@github.com> ha
scritto:

**Comment by niphlod** [comment]
aha, gotcha! @Stuart-Moore : it seems you're pulling from the "old" attempt, which is branched to niphlod:progress/Invoke-DbaAdvancedRestore. This one is on niphlod:progress**info**/Invoke-DbaAdvancedRestore. Thank god for the screenshots ^_^

**Comment by Stuart-Moore** [comment]
Doh. Good spot.
Will pull in the morning and take a look then.

**Comment by Stuart-Moore** [comment]
Yes, all works. Or at least as well as SMO restores will let it!

The restore is truthful, but if going across versions there's a  lag after the full restore as the upgrade runs, this bit doesn't get reported back. Just for future reference if anyone complains ;)

**Pull request merged**
