### PR TITLE
refine modules

### PR DESCRIPTION
**Pull request by RichieBzzzt**
publish-dbadacpac - 
   output deployoptions and sqlcommandvariablevalues
   fixing replace bug where server name has a '-' in the name
   fix newline bug
export-dacpac
   add check if database doesn't exist.

### CODE REVIEW

**Comment by potatoqualitee** [comment]
hey richie! unfortunately, the branch was stale when you committed to it and there are conflicts. can you revisit the changes?

**Comment by RichieBzzzt** [comment]
Hello!

I've resolved and merged (858ff65). Dunno why it is showing as still having conflicts though?

**Comment by potatoqualitee** [comment]
I think it's because it had to be done before the commit and not after (im surprised it allowed it to commit!) I just fixed it, I hope. Lemme see if these two files are valid!

**Comment by potatoqualitee** [comment]
bon, it's a merge!

**Comment by RichieBzzzt** [comment]
Excellent many thanks!

**Pull request merged**
