### PR TITLE
Fixing Invoke() methods in DB and Server objects

### LINKED ISSUE #2174: Invoke() method of Server and Database objects throws error
## Bug Report
Invoke() method of server and database objects throws error because of the unneeded else in the code of the script method.
### General Troubleshooting steps

- [x] Verified running latest release of dbatools?
- [x] Verified errors are not related to permissions?
- [x] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
Windows    : 6.1.7601.65536
PowerShell : 5.1.14409.1012
CLR        : 4.0.30319.42000
SMO        : 13.0.0.0
DomainUser : True
RunAsAdmin : False
SqlServerVersion   : 13.0.4001

## Steps to Reproduce
 - [ ] Attach any screenshots (if possible/allowed)
 - [ ] Attach logs generated by dbatools (`Get-DbatoolsLog`)
 - [x] Attach output from PowerShell console (if possible/allowed)
```powershell
$server = Connect-DbaSqlServer -SqlInstance 'myinstance'
$server.invoke('select 1')
```
outputs
```
Exception calling "Invoke" with "1" argument(s): "The term 'else' is not recognized as the name of a cmdlet, function,
script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is
correct and try again."
At line:1 char:1
+ $server.invoke('select 1')
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ScriptMethodRuntimeException
```

### PR DESCRIPTION
**Pull request by nvarscar**
## Type of Change

 - [x] Bug fix (non-breaking change, fixes #2174)
 - [ ] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Pester test is included

### Purpose
Fix issue with the Invoke method

### Approach
Remove unneeded else from the code

### Commands to test
```powershell
$server = Connect-DbaSqlServer -SqlInstance 'myinstance'
$server.invoke('select 1')
```

### CODE REVIEW

**Comment by wsmelton** [comment]
I'll confirm the error goes away, but it still does not execute any code....

image

**Comment by nvarscar** [comment]
Invoke() utilizes ExecuteNonQuery method, which does not return any results.

**Comment by wsmelton** [comment]
Ok. But have to ask why was it called `Invoke()` when we have `Query()`. Why didn't we just call it `NonQuery()`? Or have `Invoke()` and `InvokeResults()`?

@potatoqualitee or @FriedrichWeinmann ?

**Comment by FriedrichWeinmann** [comment]
@wsmelton actually, the naming was an arbitrary whim of mine, seemed - and still seems - appropriate to me. I ran it across Chrissy and she was like "sounds fine" and thus I pushed it. Have no strong feelings either way where the naming is concerned, removing the current name now would be a breaking change, but I could give it a new name and alias the old one.

**Comment by potatoqualitee** [comment]
Lemme know how you guys are going forward with this. @FriedrichWeinmann - do we merge then you alias? Could I also have ExecuteScalar while you're at it? ;D

**Comment by FriedrichWeinmann** [comment]
I can add any alias you want. Decide what the actual name should be and what aliases you want, then file me an issue for them @potatoqualitee  .
Same for `ExecuteScalar` (feel very free to combine both in the same issue)

**Pull request merged**
