### PR TITLE
Backup-DbaDatabase - Support prefix backups

### LINKED ISSUE #5275: Backup-DbaDatabase enhancement - prefix backups
Prefix backups with increment numbers. This can improves the read speed in certain environments.

### PR DESCRIPTION
**Pull request by Stuart-Moore**
## Type of Change

 - [ ] Bug fix (non-breaking change, fixes # )
 - [x] New feature (non-breaking change, adds functionality, fixes #5275 
 - [ ] Breaking change (effects multiple commands or functionality, fixes # )
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [x] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Approach
Added IncrementPrefix switch

Used the fact that string*null = empty string to save an if else loop in a foreach

### CODE REVIEW

**Comment by potatoqualitee** [comment]
this is a very cool feature, thank you! unsure if the test is at fault or the code but it is failing in both cases. Hope you have a wonderful new year, thanks for all of your work over the years 🤩

**Comment by Stuart-Moore** [comment]
added in returning a warning when the user manages to specify 0 databases for backup as mentiond in #6288 (test included)

**Comment by Stuart-Moore** [comment]
Test failures don't appear to be down to my code changes, so good to go if you want to give it a review @potatoqualitee

**Comment by potatoqualitee** [comment]
excellent, thanks stuart!

**Pull request merged**
