### PR TITLE
Set-DbatoolsConfig -Register & Find-DbaInstance Domain Discovery

### PR DESCRIPTION
**Pull request by FriedrichWeinmann**
## Type of Change
 - [ ] Bug fix (non-breaking change, fixes #<enter issue number>)
 - [X] New feature (non-breaking change, adds functionality)
 - [ ] Breaking change (effects multiple commands or functionality)
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 
### Changes

- Set-DbatoolsConfig now has a `-Register` parameter to allow instant per-user persistence of settings. This parameter is only applied when a setting has already been initialized and a user actually provided a value.
- Find-DbaInstance now has a new discovery type: `DomainServer` which will scan all enabled windows servers in the domain. Previous domain discovery was SPN based and required SPNs to be correctly set in order to work.

### CODE REVIEW

**Comment by potatoqualitee** [comment]
lol wickedinc, t hanks man!

**Comment by FriedrichWeinmann** [comment]
Just remembered:
For the Discovery types, I renamed the previous SPN-based Domain discoverytype to `DomainSPN` but left the old `Domain` in there as an Alias to `DomainSPN` (no breaking change thinking).
I think it might be better to use `Domain` as alias for `DomainServer` instead.
Want me to go ahead and update that before merging?

**Comment by wsmelton** [comment]
We can allow breaking changes now as this will not hit development until 1.0 is released...

**Comment by potatoqualitee** [comment]
@FriedrichWeinmann  - if you'd like to introduce breaking changes, now is the time! we have about 7-10 days left before I ask that things slow down in preparation.

**Pull request merged**
