### PR TITLE
Fix New-DBADirectory

### LINKED ISSUE #7161: New-DBADirectory does not work on multiple servers, and returns "directory already exists" when it does not
#### Host used

- [X] powershell.exe
- [X] ISE
- [ ] VS Code
- [ ] Other (please specify)

#### Errors Received

```
writeErrorStream      : True
PSMessageDetails      :
Exception             : System.Exception: C:\diagnostics already exists
TargetObject          : EC2AMAZ-XXXX
CategoryInfo          : NotSpecified: (EC2AMAZ-XXXX:PSObject) [Write-Error], Exception
FullyQualifiedErrorId : dbatools_New-DbaDirectory,Stop-Function
ErrorDetails          : C:\diagnostics already exists
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Stop-Function, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.137\allcommands.ps1:
                        line 87353
                        at New-DbaDirectory, C:\Program
                        Files\WindowsPowerShell\Modules\dbatools\1.0.137\allcommands.ps1: line 56196
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {0, 1}

From ISE below:
![image](https://user-images.githubusercontent.com/59977920/108711429-5c4ed300-74e3-11eb-92fe-177631d752b0.png)

```

#### Steps to Reproduce

Provide a list of steps to reproduce and any code required. Sanitize code if needed.
$Server1 = '10.95.XX.XXX'
$RSServer = '10.95.XX.XXX'
New-DbaDirectory -SqlInstance $Server1,$RSServer -Path "C:\diagnostics" -Verbose

#### Expected Behavior

What did you expect to happen?
Create the C:\Diagnostics folder on both $Server1 and $RSServer machines

#### Actual Behavior

What happened?
Errors thrown that the folder already exists.  Confirmed the folder does not exist.
Does not create the folder on the 2nd server.  only 1st server gets used if the above error is fixed.

### Environmental information

🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
Please provide the output of the below script

```powershell
PowerShell Version        : 5.1.17763.1490
dbatools latest installed : 1.0.137
Culture of OS             : en-US
```

#### SQL Server:

```sql
Microsoft SQL Server 2019 (RTM-CU8-GDR) (KB4583459) - 15.0.4083.2 (X64)   Nov  2 2020 18:35:09   Copyright (C) 2019 Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2019 Datacenter 10.0 <X64> (Build 17763: ) (Hypervisor) 
```

```sql
us_english
```
2021-02-22_07h55_35

### PR DESCRIPTION
**Pull request by GLoeffler14**
## Type of Change

 - [x] Bug fix (non-breaking change, fixes #7161 )
 - [ ] New feature (non-breaking change, adds functionality, fixes # )
 - [ ] Breaking change (effects multiple commands or functionality, fixes # )
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
Fix bug to allow creating folders on more than 1 server.

### Approach
iterates across all servers passed to the -sqlinstance parameter

### Commands to test
 $server1 = '10.95.XX.XXX'
 $server2 = '10.95.XX.XXX'
New-DbaDirectory -SqlInstance $server1,$server2 -Path "C:\diagnostics" -Verbose

### CODE REVIEW

**Comment by andreasjordan** [comment]
Hi, thanks for the pull request. I updated the text so that the issue is linked correctly.
And one more thing: All variables (except parameters) start with a lowercases - so it should be "$server" instead of "$Server".

**Comment by GLoeffler14** [comment]
> Hi, thanks for the pull request. I updated the text so that the issue is linked correctly.
> And one more thing: All variables (except parameters) start with a lowercases - so it should be "$server" instead of "$Server".

I'm new to PR creations, so thanks for the guidance on how to properly format them.

**Comment by andreasjordan** [comment]
No problem. I was in your position just some months ago.

**Comment by GLoeffler14** [comment]
Is there something I need to do regarding the failed AppVeyor build check on this PR?

**Comment by andreasjordan** [comment]
> Is there something I need to do regarding the failed AppVeyor build check on this PR?

Not really, sometimes they fail. But you can change $Server to $server and commit this - then there will be another test run.

**Comment by GLoeffler14** [comment]
> > Is there something I need to do regarding the failed AppVeyor build check on this PR?
> 
> Not really, sometimes they fail. But you can change $Server to $server and commit this - then there will be another test run.

I just changed and committed the changes.

**Comment by andreasjordan** [comment]
Hi @GLoeffler14 ,

that change solves the issue, thanks for that. I have only one more thing: The parameter "-SqlCredential $SqlCredential" is not needed anymore, because with $server we already have a connection to the instance under the account of $SqlCredential. So this parameter would not be used - and I think we should not have code in there that is not beeing used.

**Review by andreasjordan — APPROVED** [review]
Looks great, thanks a lot.

**Comment by andreasjordan** [comment]
Hi @GLoeffler14 , for your info: @potatoqualitee (Chrissy LeMaire) will have a look, too - and then probably merge it into the next version.

**Comment by potatoqualitee** [comment]
Thank you for the approval @andreasjordan, good to see you. And thank you so much for the fix @GLoeffler14 🥳

**Pull request merged**
