### PR TITLE
Invoke-DbatoolsFormatter / allcommands.ps1 issue - fixes #5800

### LINKED ISSUE #5800: [Bug] Invoke-DbatoolsFormatter behaves strangely in allcommands.ps1
### Environmental information

(AppVeyor CI default worker; vs 2015 & 2017 images both tested)
```
Name                           Value                                           
----                           -----                                           
PSVersion                      5.1.14409.1012                                  
PSEdition                      Desktop                                         
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                         
BuildVersion                   10.0.14409.1012                                 
CLRVersion                     4.0.30319.42000                                 
WSManStackVersion              3.0                                             
PSRemotingProtocolVersion      2.3                                             
SerializationVersion           1.1.0.1
```

### Report

It looks like the `allcommands.ps1` copy of Invoke-DbatoolsFormatter is broken, not having the same regexes as appear in the function `Invoke-DbatoolsFormatter.ps1`.

```
        $CBHRex = [regex]'(?smi)\s+<#[^#]*#>'
        $CBHStartRex = [regex]'(?<spaces>[ ]+)<#'
        $CBHEndRex = [regex]'(?<spaces>[ ]*)#>'
        $OSEOL = "`n"
```

vs in allcommands.ps1
```
        $CBHRex = [regex]'(?smi)\s+'
        $CBHStartRex = [regex]'(?<spaces>[ ]+)'
        $OSEOL = "`n"
```

My guess is that `<#..#>` is getting swallowed by some post-processor.  A bit ironic that it was intended to solve a bug ... https://github.com/sqlcollaborative/dbatools/issues/4373

#### Host used

- [x] powershell.exe
- [ ] ISE
- [ ] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [ ] Still buggy in powershell.exe

#### Errors Received

```console
You cannot call a method on a null-valued expression.
At C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.0\allcommands.ps1:44709 char:21
+ ...                  $newCBH = $CBHEndRex.Replace($CBH, "$startSpaces#>")
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 
```

#### Steps to Reproduce

appveyor.yml
```yaml
image: Visual Studio 2015

platform:
  - x86
  - x64

install:
  # Show initial state
  - powershell -c "$PSVersionTable"
  - echo %PATH%
  - echo %PSModulePath%
  - choco install PSScriptAnalyzer dbatools

build: false  # Not a C# project, build stuff at the test step instead.

test_script:
  - ps: echo "echo foo" > foo.ps1

        cat foo.ps1

        Invoke-DbatoolsFormatter foo.ps1

  - "set DBATOOLS=C:\\Program Files\\WindowsPowerShell\\Modules\\dbatools\\1.0.0"
  - ps: echo "echo foo" > foo.ps1

        cat foo.ps1

        . "$env:DBATOOLS\internal\functions\flowcontrol\Stop-Function.ps1"

        . "$env:DBATOOLS\internal\functions\flowcontrol\Test-FunctionInterrupt.ps1"

        . "$env:DBATOOLS\functions\Invoke-DbatoolsFormatter.ps1"

        Invoke-DbatoolsFormatter foo.ps1
```

#### Expected Behavior

choco package should work

#### Actual Behavior

it didnt, and the source appears to be the 1.0 zip file at https://github.com/sqlcollaborative/dbatools/archive/1.0.0.zip

### PR DESCRIPTION
**Pull request by potatoqualitee**
fixes #5800

### CODE REVIEW

**Comment by potatoqualitee** [comment]
@niphlod can i get your approval?

**Comment by potatoqualitee** [comment]
tested it vs dev and also passed tests so I'm gonna merge 👍

**Comment by niphlod** [comment]
Not sure why it was needed but it's a perfectly functional rewrite

Il mar 25 giu 2019, 11:52 Chrissy LeMaire <notifications@github.com> ha
scritto:

**Comment by potatoqualitee** [comment]
it was needed for our helper divider that autogens dbatools-Help.xml and allcommands.ps1, HelpOut

**Comment by niphlod** [comment]
ok no probl

**Pull request merged**
